apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: unified-healthcare-saas

resources:
  - namespace.yaml
  - imagepolicy.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - encryption.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - backup-scripts.yaml
  - backup-cronjob.yaml
