apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare

resources:
  - ../../base

replicas:
  - name: core
    count: 4

patches:
  - target:
      kind: ConfigMap
      name: core-config
    path: config-patch.yaml
  - target:
      kind: Deployment
      name: core
    path: resources-patch.yaml
