/// Typed client for healthcare.nursing.v1.NursingService.
///
/// Covers the RPCs a ward tablet needs and no more: the worklist a nurse works
/// through, charting an observation, the medication round, and recording an
/// administration. The rest of the service is a desktop or an administrator's
/// concern.
///
/// Every procedure path is the canonical one from the proto package, so this
/// shell and the web shell call literally the same endpoint (Gate A9).
library;

import 'package:protobuf/well_known_types/google/protobuf/timestamp.pb.dart';

import '../gen/healthcare/nursing/v1/nursing.pb.dart';
import 'connect_client.dart';

/// Wire timestamp from a Dart instant.
///
/// Always UTC. A ward tablet's time zone is a display concern (see
/// `src/time/display.dart`); what goes on the wire is an instant, and a device
/// that sent a local time would put an observation an hour out twice a year.
Timestamp timestampOf(DateTime at) => Timestamp.fromDateTime(at.toUtc());

class NursingClient {
  NursingClient(this._connect);

  final ConnectClient _connect;

  static const _service = '/healthcare.nursing.v1.NursingService';

  /// The work outstanding for one encounter, or for one nurse.
  Future<GetWorklistResponse> getWorklist({
    String encounterId = '',
    String assignedTo = '',
    bool pendingOnly = true,
    int pageSize = 50,
  }) {
    return _connect.unary(
      procedure: '$_service/GetWorklist',
      request: GetWorklistRequest(
        encounterId: encounterId,
        assignedTo: assignedTo,
        pendingOnly: pendingOnly,
        pageSize: pageSize,
      ),
      parse: GetWorklistResponse.fromBuffer,
    );
  }

  /// Marks a task done, with what was done.
  ///
  /// `evidence` is not decoration: a task closed with no record of what
  /// happened is indistinguishable from one closed to clear the list.
  Future<CompleteTaskResponse> completeTask({
    required String taskId,
    required String evidence,
    required String idempotencyKey,
  }) {
    return _connect.unary(
      procedure: '$_service/CompleteTask',
      request: CompleteTaskRequest(taskId: taskId, evidence: evidence),
      parse: CompleteTaskResponse.fromBuffer,
      idempotencyKey: idempotencyKey,
    );
  }

  /// Records an observation on the flowsheet.
  ///
  /// [observedAt] is when the reading was taken, which on a ward is routinely
  /// not when it is typed in. The server decides whether that gap makes it a
  /// late entry; the client's job is to send the truth and to have asked for a
  /// reason when it knows the entry is late.
  Future<ChartObservationResponse> chartObservation({
    required String patientId,
    required String encounterId,
    required Coding code,
    required DateTime observedAt,
    required EntrySource source,
    Quantity? value,
    String textValue = '',
    String deviceId = '',
    String lateEntryReason = '',
    required String idempotencyKey,
  }) {
    final request = ChartObservationRequest(
      patientId: patientId,
      encounterId: encounterId,
      code: code,
      observedAt: timestampOf(observedAt),
      source: source,
      textValue: textValue,
      deviceId: deviceId,
      lateEntryReason: lateEntryReason,
    );
    if (value != null) request.value = value;

    return _connect.unary(
      procedure: '$_service/ChartObservation',
      request: request,
      parse: ChartObservationResponse.fromBuffer,
      idempotencyKey: idempotencyKey,
    );
  }

  /// The doses due in a window, with the policy that governs giving them.
  ///
  /// The policy comes back with the doses rather than being fetched separately
  /// or cached: whether a barcode scan is required is a per-deployment decision
  /// that a tablet must not answer from a stale copy.
  Future<GetMedicationRoundResponse> getMedicationRound({
    required String encounterId,
    required String patientId,
    required String facilityId,
    required DateTime from,
    required DateTime to,
  }) {
    return _connect.unary(
      procedure: '$_service/GetMedicationRound',
      request: GetMedicationRoundRequest(
        encounterId: encounterId,
        patientId: patientId,
        facilityId: facilityId,
        from: timestampOf(from),
        to: timestampOf(to),
      ),
      parse: GetMedicationRoundResponse.fromBuffer,
    );
  }

  /// Records an administration.
  ///
  /// [idempotencyKey] is generated by the caller before the request goes out,
  /// so a retry after a lost response is deduplicated by the server rather than
  /// producing a second dose in the record. [offline] tells the server this was
  /// captured on a device that could not reach it at the time, which is a
  /// different fact from when it arrived.
  Future<AdministerResponse> administer({
    required String orderId,
    required String facilityId,
    required DateTime scheduledAt,
    required DateTime givenAt,
    required AdministrationOutcome outcome,
    required String idempotencyKey,
    Quantity? givenDose,
    String route = '',
    String site = '',
    String reason = '',
    Verification? verification,
    String overrideReason = '',
    String witnessedBy = '',
    bool offline = false,
  }) {
    final request = AdministerRequest(
      orderId: orderId,
      facilityId: facilityId,
      scheduledAt: timestampOf(scheduledAt),
      givenAt: timestampOf(givenAt),
      outcome: outcome,
      route: route,
      site: site,
      reason: reason,
      overrideReason: overrideReason,
      witnessedBy: witnessedBy,
      idempotencyKey: idempotencyKey,
      offline: offline,
    );
    if (givenDose != null) request.givenDose = givenDose;
    if (verification != null) request.verification = verification;

    return _connect.unary(
      procedure: '$_service/Administer',
      request: request,
      parse: AdministerResponse.fromBuffer,
      idempotencyKey: idempotencyKey,
    );
  }
}
