// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bloodbank.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const concludeReaction = `-- name: ConcludeReaction :execrows
UPDATE bloodbank.reaction
SET state = 'concluded', classification = $1,
    conclusion = $2, concluded_at = $3,
    concluded_by = $4, unit_returned = $5
WHERE tenant_id = $6 AND reaction_id = $7
  AND state = 'open'
`

type ConcludeReactionParams struct {
	Classification string
	Conclusion     string
	ConcludedAt    pgtype.Timestamptz
	ConcludedBy    string
	UnitReturned   bool
	TenantID       uuid.UUID
	ReactionID     uuid.UUID
}

func (q *Queries) ConcludeReaction(ctx context.Context, arg ConcludeReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, concludeReaction,
		arg.Classification,
		arg.Conclusion,
		arg.ConcludedAt,
		arg.ConcludedBy,
		arg.UnitReturned,
		arg.TenantID,
		arg.ReactionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDiscarded = `-- name: CountDiscarded :one
SELECT count(*) FROM bloodbank.component
WHERE tenant_id = $1
  AND status = 'discarded'
  AND created_at >= $2 AND created_at < $3
`

type CountDiscardedParams struct {
	TenantID    uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

func (q *Queries) CountDiscarded(ctx context.Context, arg CountDiscardedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDiscarded, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReservationsInPeriod = `-- name: CountReservationsInPeriod :one
SELECT count(*) FROM bloodbank.reservation
WHERE tenant_id = $1
  AND reserved_at >= $2 AND reserved_at < $3
`

type CountReservationsInPeriodParams struct {
	TenantID    uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

func (q *Queries) CountReservationsInPeriod(ctx context.Context, arg CountReservationsInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReservationsInPeriod, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCollection = `-- name: GetCollection :one
SELECT collection_id, tenant_id, donor_id, screening_id, donation_number, kind, volume_ml, abo, rhd, collected_at, collected_by, adverse_event, adverse_note FROM bloodbank.collection
WHERE tenant_id = $1 AND collection_id = $2
`

type GetCollectionParams struct {
	TenantID     uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (BloodbankCollection, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.TenantID, arg.CollectionID)
	var i BloodbankCollection
	err := row.Scan(
		&i.CollectionID,
		&i.TenantID,
		&i.DonorID,
		&i.ScreeningID,
		&i.DonationNumber,
		&i.Kind,
		&i.VolumeMl,
		&i.Abo,
		&i.Rhd,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.AdverseEvent,
		&i.AdverseNote,
	)
	return i, err
}

const getComponent = `-- name: GetComponent :one
SELECT component_id, tenant_id, unit_number, collection_id, donor_id, source, component_class, abo, rhd, status, discard_reason, volume_ml, attributes, location, collected_at, expires_at, created_at, created_by, version FROM bloodbank.component
WHERE tenant_id = $1 AND component_id = $2
`

type GetComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) GetComponent(ctx context.Context, arg GetComponentParams) (BloodbankComponent, error) {
	row := q.db.QueryRow(ctx, getComponent, arg.TenantID, arg.ComponentID)
	var i BloodbankComponent
	err := row.Scan(
		&i.ComponentID,
		&i.TenantID,
		&i.UnitNumber,
		&i.CollectionID,
		&i.DonorID,
		&i.Source,
		&i.ComponentClass,
		&i.Abo,
		&i.Rhd,
		&i.Status,
		&i.DiscardReason,
		&i.VolumeMl,
		&i.Attributes,
		&i.Location,
		&i.CollectedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getComponentByNumber = `-- name: GetComponentByNumber :one
SELECT component_id, tenant_id, unit_number, collection_id, donor_id, source, component_class, abo, rhd, status, discard_reason, volume_ml, attributes, location, collected_at, expires_at, created_at, created_by, version FROM bloodbank.component
WHERE tenant_id = $1 AND unit_number = $2
`

type GetComponentByNumberParams struct {
	TenantID   uuid.UUID
	UnitNumber string
}

func (q *Queries) GetComponentByNumber(ctx context.Context, arg GetComponentByNumberParams) (BloodbankComponent, error) {
	row := q.db.QueryRow(ctx, getComponentByNumber, arg.TenantID, arg.UnitNumber)
	var i BloodbankComponent
	err := row.Scan(
		&i.ComponentID,
		&i.TenantID,
		&i.UnitNumber,
		&i.CollectionID,
		&i.DonorID,
		&i.Source,
		&i.ComponentClass,
		&i.Abo,
		&i.Rhd,
		&i.Status,
		&i.DiscardReason,
		&i.VolumeMl,
		&i.Attributes,
		&i.Location,
		&i.CollectedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getCurrentPatientSample = `-- name: GetCurrentPatientSample :one
SELECT sample_id, tenant_id, patient_id, sample_number, abo, rhd, antibody_screen_positive, antibody_note, second_check, collected_at, collected_by, expires_at, tested_at, tested_by FROM bloodbank.patient_sample
WHERE tenant_id = $1 AND patient_id = $2
  AND expires_at > $3
ORDER BY collected_at DESC
LIMIT 1
`

type GetCurrentPatientSampleParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	AsOf      pgtype.Timestamptz
}

// The sample a crossmatch runs against: the patient's latest that has not
// expired. Latest rather than any, because a corrected group is on the newest
// tube.
func (q *Queries) GetCurrentPatientSample(ctx context.Context, arg GetCurrentPatientSampleParams) (BloodbankPatientSample, error) {
	row := q.db.QueryRow(ctx, getCurrentPatientSample, arg.TenantID, arg.PatientID, arg.AsOf)
	var i BloodbankPatientSample
	err := row.Scan(
		&i.SampleID,
		&i.TenantID,
		&i.PatientID,
		&i.SampleNumber,
		&i.Abo,
		&i.Rhd,
		&i.AntibodyScreenPositive,
		&i.AntibodyNote,
		&i.SecondCheck,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.ExpiresAt,
		&i.TestedAt,
		&i.TestedBy,
	)
	return i, err
}

const getDonor = `-- name: GetDonor :one
SELECT donor_id, tenant_id, donor_number, patient_id, display_name, birth_date, contact_phone, abo, rhd, deferral, deferral_code, deferral_note, deferred_at, deferred_by, deferred_until, registered_at, registered_by, version FROM bloodbank.donor WHERE tenant_id = $1 AND donor_id = $2
`

type GetDonorParams struct {
	TenantID uuid.UUID
	DonorID  uuid.UUID
}

func (q *Queries) GetDonor(ctx context.Context, arg GetDonorParams) (BloodbankDonor, error) {
	row := q.db.QueryRow(ctx, getDonor, arg.TenantID, arg.DonorID)
	var i BloodbankDonor
	err := row.Scan(
		&i.DonorID,
		&i.TenantID,
		&i.DonorNumber,
		&i.PatientID,
		&i.DisplayName,
		&i.BirthDate,
		&i.ContactPhone,
		&i.Abo,
		&i.Rhd,
		&i.Deferral,
		&i.DeferralCode,
		&i.DeferralNote,
		&i.DeferredAt,
		&i.DeferredBy,
		&i.DeferredUntil,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.Version,
	)
	return i, err
}

const getDonorByNumber = `-- name: GetDonorByNumber :one
SELECT donor_id, tenant_id, donor_number, patient_id, display_name, birth_date, contact_phone, abo, rhd, deferral, deferral_code, deferral_note, deferred_at, deferred_by, deferred_until, registered_at, registered_by, version FROM bloodbank.donor WHERE tenant_id = $1 AND donor_number = $2
`

type GetDonorByNumberParams struct {
	TenantID    uuid.UUID
	DonorNumber string
}

func (q *Queries) GetDonorByNumber(ctx context.Context, arg GetDonorByNumberParams) (BloodbankDonor, error) {
	row := q.db.QueryRow(ctx, getDonorByNumber, arg.TenantID, arg.DonorNumber)
	var i BloodbankDonor
	err := row.Scan(
		&i.DonorID,
		&i.TenantID,
		&i.DonorNumber,
		&i.PatientID,
		&i.DisplayName,
		&i.BirthDate,
		&i.ContactPhone,
		&i.Abo,
		&i.Rhd,
		&i.Deferral,
		&i.DeferralCode,
		&i.DeferralNote,
		&i.DeferredAt,
		&i.DeferredBy,
		&i.DeferredUntil,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.Version,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT issue_id, tenant_id, component_id, reservation_id, patient_id, request_id, destination, emergency, emergency_authoriser, emergency_reason, reconciled, reconciled_at, reconciled_by, reconcile_note, issued_at, issued_by, issued_to, checked_by FROM bloodbank.issue WHERE tenant_id = $1 AND issue_id = $2
`

type GetIssueParams struct {
	TenantID uuid.UUID
	IssueID  uuid.UUID
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (BloodbankIssue, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.TenantID, arg.IssueID)
	var i BloodbankIssue
	err := row.Scan(
		&i.IssueID,
		&i.TenantID,
		&i.ComponentID,
		&i.ReservationID,
		&i.PatientID,
		&i.RequestID,
		&i.Destination,
		&i.Emergency,
		&i.EmergencyAuthoriser,
		&i.EmergencyReason,
		&i.Reconciled,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.ReconcileNote,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.IssuedTo,
		&i.CheckedBy,
	)
	return i, err
}

const getIssueForComponent = `-- name: GetIssueForComponent :one
SELECT issue_id, tenant_id, component_id, reservation_id, patient_id, request_id, destination, emergency, emergency_authoriser, emergency_reason, reconciled, reconciled_at, reconciled_by, reconcile_note, issued_at, issued_by, issued_to, checked_by FROM bloodbank.issue
WHERE tenant_id = $1 AND component_id = $2
ORDER BY issued_at DESC
LIMIT 1
`

type GetIssueForComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) GetIssueForComponent(ctx context.Context, arg GetIssueForComponentParams) (BloodbankIssue, error) {
	row := q.db.QueryRow(ctx, getIssueForComponent, arg.TenantID, arg.ComponentID)
	var i BloodbankIssue
	err := row.Scan(
		&i.IssueID,
		&i.TenantID,
		&i.ComponentID,
		&i.ReservationID,
		&i.PatientID,
		&i.RequestID,
		&i.Destination,
		&i.Emergency,
		&i.EmergencyAuthoriser,
		&i.EmergencyReason,
		&i.Reconciled,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.ReconcileNote,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.IssuedTo,
		&i.CheckedBy,
	)
	return i, err
}

const getPatientSample = `-- name: GetPatientSample :one
SELECT sample_id, tenant_id, patient_id, sample_number, abo, rhd, antibody_screen_positive, antibody_note, second_check, collected_at, collected_by, expires_at, tested_at, tested_by FROM bloodbank.patient_sample
WHERE tenant_id = $1 AND sample_id = $2
`

type GetPatientSampleParams struct {
	TenantID uuid.UUID
	SampleID uuid.UUID
}

func (q *Queries) GetPatientSample(ctx context.Context, arg GetPatientSampleParams) (BloodbankPatientSample, error) {
	row := q.db.QueryRow(ctx, getPatientSample, arg.TenantID, arg.SampleID)
	var i BloodbankPatientSample
	err := row.Scan(
		&i.SampleID,
		&i.TenantID,
		&i.PatientID,
		&i.SampleNumber,
		&i.Abo,
		&i.Rhd,
		&i.AntibodyScreenPositive,
		&i.AntibodyNote,
		&i.SecondCheck,
		&i.CollectedAt,
		&i.CollectedBy,
		&i.ExpiresAt,
		&i.TestedAt,
		&i.TestedBy,
	)
	return i, err
}

const getReaction = `-- name: GetReaction :one
SELECT reaction_id, tenant_id, episode_id, component_id, patient_id, severity, features, note, reported_at, reported_by, state, classification, conclusion, concluded_at, concluded_by, unit_returned FROM bloodbank.reaction WHERE tenant_id = $1 AND reaction_id = $2
`

type GetReactionParams struct {
	TenantID   uuid.UUID
	ReactionID uuid.UUID
}

func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (BloodbankReaction, error) {
	row := q.db.QueryRow(ctx, getReaction, arg.TenantID, arg.ReactionID)
	var i BloodbankReaction
	err := row.Scan(
		&i.ReactionID,
		&i.TenantID,
		&i.EpisodeID,
		&i.ComponentID,
		&i.PatientID,
		&i.Severity,
		&i.Features,
		&i.Note,
		&i.ReportedAt,
		&i.ReportedBy,
		&i.State,
		&i.Classification,
		&i.Conclusion,
		&i.ConcludedAt,
		&i.ConcludedBy,
		&i.UnitReturned,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
SELECT request_id, tenant_id, patient_id, encounter_id, facility_id, component_class, quantity, indication, urgency, requirements, required_by, status, requested_by, requested_at, version FROM bloodbank.request WHERE tenant_id = $1 AND request_id = $2
`

type GetRequestParams struct {
	TenantID  uuid.UUID
	RequestID uuid.UUID
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (BloodbankRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, arg.TenantID, arg.RequestID)
	var i BloodbankRequest
	err := row.Scan(
		&i.RequestID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.FacilityID,
		&i.ComponentClass,
		&i.Quantity,
		&i.Indication,
		&i.Urgency,
		&i.Requirements,
		&i.RequiredBy,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Version,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT reservation_id, tenant_id, component_id, request_id, patient_id, sample_id, crossmatched, crossmatch_note, status, expires_at, reserved_at, reserved_by, released_reason FROM bloodbank.reservation
WHERE tenant_id = $1 AND reservation_id = $2
`

type GetReservationParams struct {
	TenantID      uuid.UUID
	ReservationID uuid.UUID
}

func (q *Queries) GetReservation(ctx context.Context, arg GetReservationParams) (BloodbankReservation, error) {
	row := q.db.QueryRow(ctx, getReservation, arg.TenantID, arg.ReservationID)
	var i BloodbankReservation
	err := row.Scan(
		&i.ReservationID,
		&i.TenantID,
		&i.ComponentID,
		&i.RequestID,
		&i.PatientID,
		&i.SampleID,
		&i.Crossmatched,
		&i.CrossmatchNote,
		&i.Status,
		&i.ExpiresAt,
		&i.ReservedAt,
		&i.ReservedBy,
		&i.ReleasedReason,
	)
	return i, err
}

const getScreening = `-- name: GetScreening :one
SELECT screening_id, tenant_id, donor_id, answers, measurements, consented, consent_note, accepted, deferral, deferral_code, screened_at, screened_by FROM bloodbank.screening
WHERE tenant_id = $1 AND screening_id = $2
`

type GetScreeningParams struct {
	TenantID    uuid.UUID
	ScreeningID uuid.UUID
}

func (q *Queries) GetScreening(ctx context.Context, arg GetScreeningParams) (BloodbankScreening, error) {
	row := q.db.QueryRow(ctx, getScreening, arg.TenantID, arg.ScreeningID)
	var i BloodbankScreening
	err := row.Scan(
		&i.ScreeningID,
		&i.TenantID,
		&i.DonorID,
		&i.Answers,
		&i.Measurements,
		&i.Consented,
		&i.ConsentNote,
		&i.Accepted,
		&i.Deferral,
		&i.DeferralCode,
		&i.ScreenedAt,
		&i.ScreenedBy,
	)
	return i, err
}

const getTransfusionEpisode = `-- name: GetTransfusionEpisode :one
SELECT episode_id, tenant_id, component_id, issue_id, patient_id, encounter_id, status, started_at, started_by, ended_at, volume_given_ml, stop_reason, checked_by, checked_with FROM bloodbank.episode WHERE tenant_id = $1 AND episode_id = $2
`

type GetTransfusionEpisodeParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) GetTransfusionEpisode(ctx context.Context, arg GetTransfusionEpisodeParams) (BloodbankEpisode, error) {
	row := q.db.QueryRow(ctx, getTransfusionEpisode, arg.TenantID, arg.EpisodeID)
	var i BloodbankEpisode
	err := row.Scan(
		&i.EpisodeID,
		&i.TenantID,
		&i.ComponentID,
		&i.IssueID,
		&i.PatientID,
		&i.EncounterID,
		&i.Status,
		&i.StartedAt,
		&i.StartedBy,
		&i.EndedAt,
		&i.VolumeGivenMl,
		&i.StopReason,
		&i.CheckedBy,
		&i.CheckedWith,
	)
	return i, err
}

const insertBloodBankObservation = `-- name: InsertBloodBankObservation :exec
INSERT INTO bloodbank.observation (
    observation_id, tenant_id, episode_id, timing, values, note,
    observed_at, observed_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
`

type InsertBloodBankObservationParams struct {
	ObservationID uuid.UUID
	TenantID      uuid.UUID
	EpisodeID     uuid.UUID
	Timing        string
	Values        []byte
	Note          string
	ObservedAt    pgtype.Timestamptz
	ObservedBy    string
}

func (q *Queries) InsertBloodBankObservation(ctx context.Context, arg InsertBloodBankObservationParams) error {
	_, err := q.db.Exec(ctx, insertBloodBankObservation,
		arg.ObservationID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Timing,
		arg.Values,
		arg.Note,
		arg.ObservedAt,
		arg.ObservedBy,
	)
	return err
}

const insertCollection = `-- name: InsertCollection :exec
INSERT INTO bloodbank.collection (
    collection_id, tenant_id, donor_id, screening_id, donation_number, kind,
    volume_ml, abo, rhd, collected_at, collected_by, adverse_event, adverse_note
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13
)
`

type InsertCollectionParams struct {
	CollectionID   uuid.UUID
	TenantID       uuid.UUID
	DonorID        uuid.UUID
	ScreeningID    uuid.UUID
	DonationNumber string
	Kind           string
	VolumeMl       int32
	Abo            *string
	Rhd            *string
	CollectedAt    pgtype.Timestamptz
	CollectedBy    string
	AdverseEvent   bool
	AdverseNote    string
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) error {
	_, err := q.db.Exec(ctx, insertCollection,
		arg.CollectionID,
		arg.TenantID,
		arg.DonorID,
		arg.ScreeningID,
		arg.DonationNumber,
		arg.Kind,
		arg.VolumeMl,
		arg.Abo,
		arg.Rhd,
		arg.CollectedAt,
		arg.CollectedBy,
		arg.AdverseEvent,
		arg.AdverseNote,
	)
	return err
}

const insertComponent = `-- name: InsertComponent :exec
INSERT INTO bloodbank.component (
    component_id, tenant_id, unit_number, collection_id, donor_id, source,
    component_class, abo, rhd, status, volume_ml, attributes, location,
    collected_at, expires_at, created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17
)
`

type InsertComponentParams struct {
	ComponentID    uuid.UUID
	TenantID       uuid.UUID
	UnitNumber     string
	CollectionID   uuid.UUID
	DonorID        pgtype.UUID
	Source         string
	ComponentClass string
	Abo            string
	Rhd            string
	Status         string
	VolumeMl       int32
	Attributes     []string
	Location       string
	CollectedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	CreatedBy      string
}

func (q *Queries) InsertComponent(ctx context.Context, arg InsertComponentParams) error {
	_, err := q.db.Exec(ctx, insertComponent,
		arg.ComponentID,
		arg.TenantID,
		arg.UnitNumber,
		arg.CollectionID,
		arg.DonorID,
		arg.Source,
		arg.ComponentClass,
		arg.Abo,
		arg.Rhd,
		arg.Status,
		arg.VolumeMl,
		arg.Attributes,
		arg.Location,
		arg.CollectedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertDonor = `-- name: InsertDonor :exec

INSERT INTO bloodbank.donor (
    donor_id, tenant_id, donor_number, patient_id, display_name, birth_date,
    contact_phone, abo, rhd, registered_at, registered_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type InsertDonorParams struct {
	DonorID      uuid.UUID
	TenantID     uuid.UUID
	DonorNumber  string
	PatientID    pgtype.UUID
	DisplayName  string
	BirthDate    pgtype.Date
	ContactPhone string
	Abo          *string
	Rhd          *string
	RegisteredAt pgtype.Timestamptz
	RegisteredBy string
}

// Blood bank and transfusion medicine (SRS-BLD-001 … 017).
func (q *Queries) InsertDonor(ctx context.Context, arg InsertDonorParams) error {
	_, err := q.db.Exec(ctx, insertDonor,
		arg.DonorID,
		arg.TenantID,
		arg.DonorNumber,
		arg.PatientID,
		arg.DisplayName,
		arg.BirthDate,
		arg.ContactPhone,
		arg.Abo,
		arg.Rhd,
		arg.RegisteredAt,
		arg.RegisteredBy,
	)
	return err
}

const insertIssue = `-- name: InsertIssue :exec
INSERT INTO bloodbank.issue (
    issue_id, tenant_id, component_id, reservation_id, patient_id, request_id,
    destination, emergency, emergency_authoriser, emergency_reason,
    issued_at, issued_by, issued_to, checked_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
`

type InsertIssueParams struct {
	IssueID             uuid.UUID
	TenantID            uuid.UUID
	ComponentID         uuid.UUID
	ReservationID       pgtype.UUID
	PatientID           uuid.UUID
	RequestID           pgtype.UUID
	Destination         string
	Emergency           bool
	EmergencyAuthoriser string
	EmergencyReason     string
	IssuedAt            pgtype.Timestamptz
	IssuedBy            string
	IssuedTo            string
	CheckedBy           string
}

func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) error {
	_, err := q.db.Exec(ctx, insertIssue,
		arg.IssueID,
		arg.TenantID,
		arg.ComponentID,
		arg.ReservationID,
		arg.PatientID,
		arg.RequestID,
		arg.Destination,
		arg.Emergency,
		arg.EmergencyAuthoriser,
		arg.EmergencyReason,
		arg.IssuedAt,
		arg.IssuedBy,
		arg.IssuedTo,
		arg.CheckedBy,
	)
	return err
}

const insertPatientSample = `-- name: InsertPatientSample :exec
INSERT INTO bloodbank.patient_sample (
    sample_id, tenant_id, patient_id, sample_number, abo, rhd,
    antibody_screen_positive, antibody_note, second_check,
    collected_at, collected_by, expires_at, tested_at, tested_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14
)
`

type InsertPatientSampleParams struct {
	SampleID               uuid.UUID
	TenantID               uuid.UUID
	PatientID              uuid.UUID
	SampleNumber           string
	Abo                    string
	Rhd                    string
	AntibodyScreenPositive bool
	AntibodyNote           string
	SecondCheck            bool
	CollectedAt            pgtype.Timestamptz
	CollectedBy            string
	ExpiresAt              pgtype.Timestamptz
	TestedAt               pgtype.Timestamptz
	TestedBy               string
}

func (q *Queries) InsertPatientSample(ctx context.Context, arg InsertPatientSampleParams) error {
	_, err := q.db.Exec(ctx, insertPatientSample,
		arg.SampleID,
		arg.TenantID,
		arg.PatientID,
		arg.SampleNumber,
		arg.Abo,
		arg.Rhd,
		arg.AntibodyScreenPositive,
		arg.AntibodyNote,
		arg.SecondCheck,
		arg.CollectedAt,
		arg.CollectedBy,
		arg.ExpiresAt,
		arg.TestedAt,
		arg.TestedBy,
	)
	return err
}

const insertReaction = `-- name: InsertReaction :exec
INSERT INTO bloodbank.reaction (
    reaction_id, tenant_id, episode_id, component_id, patient_id, severity,
    features, note, reported_at, reported_by, state
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type InsertReactionParams struct {
	ReactionID  uuid.UUID
	TenantID    uuid.UUID
	EpisodeID   pgtype.UUID
	ComponentID uuid.UUID
	PatientID   uuid.UUID
	Severity    string
	Features    []string
	Note        string
	ReportedAt  pgtype.Timestamptz
	ReportedBy  string
	State       string
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) error {
	_, err := q.db.Exec(ctx, insertReaction,
		arg.ReactionID,
		arg.TenantID,
		arg.EpisodeID,
		arg.ComponentID,
		arg.PatientID,
		arg.Severity,
		arg.Features,
		arg.Note,
		arg.ReportedAt,
		arg.ReportedBy,
		arg.State,
	)
	return err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO bloodbank.request (
    request_id, tenant_id, patient_id, encounter_id, facility_id,
    component_class, quantity, indication, urgency, requirements, required_by,
    status, requested_by, requested_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14
)
`

type InsertRequestParams struct {
	RequestID      uuid.UUID
	TenantID       uuid.UUID
	PatientID      uuid.UUID
	EncounterID    pgtype.UUID
	FacilityID     string
	ComponentClass string
	Quantity       int32
	Indication     string
	Urgency        string
	Requirements   []string
	RequiredBy     pgtype.Timestamptz
	Status         string
	RequestedBy    string
	RequestedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.Exec(ctx, insertRequest,
		arg.RequestID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.FacilityID,
		arg.ComponentClass,
		arg.Quantity,
		arg.Indication,
		arg.Urgency,
		arg.Requirements,
		arg.RequiredBy,
		arg.Status,
		arg.RequestedBy,
		arg.RequestedAt,
	)
	return err
}

const insertReservation = `-- name: InsertReservation :exec
INSERT INTO bloodbank.reservation (
    reservation_id, tenant_id, component_id, request_id, patient_id, sample_id,
    crossmatched, crossmatch_note, status, expires_at, reserved_at, reserved_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
`

type InsertReservationParams struct {
	ReservationID  uuid.UUID
	TenantID       uuid.UUID
	ComponentID    uuid.UUID
	RequestID      pgtype.UUID
	PatientID      uuid.UUID
	SampleID       pgtype.UUID
	Crossmatched   bool
	CrossmatchNote string
	Status         string
	ExpiresAt      pgtype.Timestamptz
	ReservedAt     pgtype.Timestamptz
	ReservedBy     string
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) error {
	_, err := q.db.Exec(ctx, insertReservation,
		arg.ReservationID,
		arg.TenantID,
		arg.ComponentID,
		arg.RequestID,
		arg.PatientID,
		arg.SampleID,
		arg.Crossmatched,
		arg.CrossmatchNote,
		arg.Status,
		arg.ExpiresAt,
		arg.ReservedAt,
		arg.ReservedBy,
	)
	return err
}

const insertScreening = `-- name: InsertScreening :exec
INSERT INTO bloodbank.screening (
    screening_id, tenant_id, donor_id, answers, measurements, consented,
    consent_note, accepted, deferral, deferral_code, screened_at, screened_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12
)
`

type InsertScreeningParams struct {
	ScreeningID  uuid.UUID
	TenantID     uuid.UUID
	DonorID      uuid.UUID
	Answers      []byte
	Measurements []byte
	Consented    bool
	ConsentNote  string
	Accepted     bool
	Deferral     *string
	DeferralCode string
	ScreenedAt   pgtype.Timestamptz
	ScreenedBy   string
}

func (q *Queries) InsertScreening(ctx context.Context, arg InsertScreeningParams) error {
	_, err := q.db.Exec(ctx, insertScreening,
		arg.ScreeningID,
		arg.TenantID,
		arg.DonorID,
		arg.Answers,
		arg.Measurements,
		arg.Consented,
		arg.ConsentNote,
		arg.Accepted,
		arg.Deferral,
		arg.DeferralCode,
		arg.ScreenedAt,
		arg.ScreenedBy,
	)
	return err
}

const insertTestResult = `-- name: InsertTestResult :exec
INSERT INTO bloodbank.test_result (
    test_id, tenant_id, collection_id, code, display, reactive, value, method,
    tested_at, tested_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
`

type InsertTestResultParams struct {
	TestID       uuid.UUID
	TenantID     uuid.UUID
	CollectionID uuid.UUID
	Code         string
	Display      string
	Reactive     bool
	Value        string
	Method       string
	TestedAt     pgtype.Timestamptz
	TestedBy     string
}

func (q *Queries) InsertTestResult(ctx context.Context, arg InsertTestResultParams) error {
	_, err := q.db.Exec(ctx, insertTestResult,
		arg.TestID,
		arg.TenantID,
		arg.CollectionID,
		arg.Code,
		arg.Display,
		arg.Reactive,
		arg.Value,
		arg.Method,
		arg.TestedAt,
		arg.TestedBy,
	)
	return err
}

const insertTransfusionEpisode = `-- name: InsertTransfusionEpisode :exec
INSERT INTO bloodbank.episode (
    episode_id, tenant_id, component_id, issue_id, patient_id, encounter_id,
    status, started_at, started_by, volume_given_ml, checked_by, checked_with
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
`

type InsertTransfusionEpisodeParams struct {
	EpisodeID     uuid.UUID
	TenantID      uuid.UUID
	ComponentID   uuid.UUID
	IssueID       pgtype.UUID
	PatientID     uuid.UUID
	EncounterID   pgtype.UUID
	Status        string
	StartedAt     pgtype.Timestamptz
	StartedBy     string
	VolumeGivenMl int32
	CheckedBy     string
	CheckedWith   string
}

func (q *Queries) InsertTransfusionEpisode(ctx context.Context, arg InsertTransfusionEpisodeParams) error {
	_, err := q.db.Exec(ctx, insertTransfusionEpisode,
		arg.EpisodeID,
		arg.TenantID,
		arg.ComponentID,
		arg.IssueID,
		arg.PatientID,
		arg.EncounterID,
		arg.Status,
		arg.StartedAt,
		arg.StartedBy,
		arg.VolumeGivenMl,
		arg.CheckedBy,
		arg.CheckedWith,
	)
	return err
}

const listAllocatableComponents = `-- name: ListAllocatableComponents :many
SELECT component_id, tenant_id, unit_number, collection_id, donor_id, source, component_class, abo, rhd, status, discard_reason, volume_ml, attributes, location, collected_at, expires_at, created_at, created_by, version FROM bloodbank.component
WHERE tenant_id = $1
  AND component_class = $2
  AND status = 'available'
  AND expires_at > $3
ORDER BY expires_at
LIMIT $4
`

type ListAllocatableComponentsParams struct {
	TenantID       uuid.UUID
	ComponentClass string
	AsOf           pgtype.Timestamptz
	RowLimit       int32
}

// The allocation search. Soonest to expire first, so the bank issues the unit
// that would otherwise be wasted. Compatibility is the domain's to decide, so
// this narrows by component and status and hands back candidates.
func (q *Queries) ListAllocatableComponents(ctx context.Context, arg ListAllocatableComponentsParams) ([]BloodbankComponent, error) {
	rows, err := q.db.Query(ctx, listAllocatableComponents,
		arg.TenantID,
		arg.ComponentClass,
		arg.AsOf,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankComponent{}
	for rows.Next() {
		var i BloodbankComponent
		if err := rows.Scan(
			&i.ComponentID,
			&i.TenantID,
			&i.UnitNumber,
			&i.CollectionID,
			&i.DonorID,
			&i.Source,
			&i.ComponentClass,
			&i.Abo,
			&i.Rhd,
			&i.Status,
			&i.DiscardReason,
			&i.VolumeMl,
			&i.Attributes,
			&i.Location,
			&i.CollectedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBloodBankObservations = `-- name: ListBloodBankObservations :many
SELECT observation_id, tenant_id, episode_id, timing, values, note, observed_at, observed_by FROM bloodbank.observation
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY observed_at
`

type ListBloodBankObservationsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListBloodBankObservations(ctx context.Context, arg ListBloodBankObservationsParams) ([]BloodbankObservation, error) {
	rows, err := q.db.Query(ctx, listBloodBankObservations, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankObservation{}
	for rows.Next() {
		var i BloodbankObservation
		if err := rows.Scan(
			&i.ObservationID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Timing,
			&i.Values,
			&i.Note,
			&i.ObservedAt,
			&i.ObservedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsForCollection = `-- name: ListComponentsForCollection :many
SELECT component_id, tenant_id, unit_number, collection_id, donor_id, source, component_class, abo, rhd, status, discard_reason, volume_ml, attributes, location, collected_at, expires_at, created_at, created_by, version FROM bloodbank.component
WHERE tenant_id = $1 AND collection_id = $2
ORDER BY created_at
`

type ListComponentsForCollectionParams struct {
	TenantID     uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) ListComponentsForCollection(ctx context.Context, arg ListComponentsForCollectionParams) ([]BloodbankComponent, error) {
	rows, err := q.db.Query(ctx, listComponentsForCollection, arg.TenantID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankComponent{}
	for rows.Next() {
		var i BloodbankComponent
		if err := rows.Scan(
			&i.ComponentID,
			&i.TenantID,
			&i.UnitNumber,
			&i.CollectionID,
			&i.DonorID,
			&i.Source,
			&i.ComponentClass,
			&i.Abo,
			&i.Rhd,
			&i.Status,
			&i.DiscardReason,
			&i.VolumeMl,
			&i.Attributes,
			&i.Location,
			&i.CollectedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeferredDonors = `-- name: ListDeferredDonors :many
SELECT donor_id, tenant_id, donor_number, patient_id, display_name, birth_date, contact_phone, abo, rhd, deferral, deferral_code, deferral_note, deferred_at, deferred_by, deferred_until, registered_at, registered_by, version FROM bloodbank.donor
WHERE tenant_id = $1
  AND deferral IS NOT NULL
  AND (deferred_until IS NULL OR deferred_until > $2)
ORDER BY deferred_at DESC
LIMIT $3
`

type ListDeferredDonorsParams struct {
	TenantID uuid.UUID
	AsOf     pgtype.Timestamptz
	RowLimit int32
}

// The deferred list a screening desk reads. A permanent deferral has no end
// date and is always current; a temporary one is current until its date.
func (q *Queries) ListDeferredDonors(ctx context.Context, arg ListDeferredDonorsParams) ([]BloodbankDonor, error) {
	rows, err := q.db.Query(ctx, listDeferredDonors, arg.TenantID, arg.AsOf, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankDonor{}
	for rows.Next() {
		var i BloodbankDonor
		if err := rows.Scan(
			&i.DonorID,
			&i.TenantID,
			&i.DonorNumber,
			&i.PatientID,
			&i.DisplayName,
			&i.BirthDate,
			&i.ContactPhone,
			&i.Abo,
			&i.Rhd,
			&i.Deferral,
			&i.DeferralCode,
			&i.DeferralNote,
			&i.DeferredAt,
			&i.DeferredBy,
			&i.DeferredUntil,
			&i.RegisteredAt,
			&i.RegisteredBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonorRecipients = `-- name: ListDonorRecipients :many
SELECT e.patient_id, e.episode_id, e.started_at,
       c.component_id, c.unit_number
FROM bloodbank.episode e
JOIN bloodbank.component c
  ON c.component_id = e.component_id AND c.tenant_id = e.tenant_id
JOIN bloodbank.collection col
  ON col.collection_id = c.collection_id AND col.tenant_id = c.tenant_id
WHERE e.tenant_id = $1 AND col.donor_id = $2
ORDER BY e.started_at DESC
LIMIT $3
`

type ListDonorRecipientsParams struct {
	TenantID uuid.UUID
	DonorID  uuid.UUID
	RowLimit int32
}

type ListDonorRecipientsRow struct {
	PatientID   uuid.UUID
	EpisodeID   uuid.UUID
	StartedAt   pgtype.Timestamptz
	ComponentID uuid.UUID
	UnitNumber  string
}

// The other direction a look-back runs: from a donor to every patient who
// received their blood. Deliberately thin — identifiers and times, no
// clinical detail — because a look-back list is read outside the care team.
func (q *Queries) ListDonorRecipients(ctx context.Context, arg ListDonorRecipientsParams) ([]ListDonorRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listDonorRecipients, arg.TenantID, arg.DonorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDonorRecipientsRow{}
	for rows.Next() {
		var i ListDonorRecipientsRow
		if err := rows.Scan(
			&i.PatientID,
			&i.EpisodeID,
			&i.StartedAt,
			&i.ComponentID,
			&i.UnitNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonorScreenings = `-- name: ListDonorScreenings :many
SELECT screening_id, tenant_id, donor_id, answers, measurements, consented, consent_note, accepted, deferral, deferral_code, screened_at, screened_by FROM bloodbank.screening
WHERE tenant_id = $1 AND donor_id = $2
ORDER BY screened_at DESC
LIMIT $3
`

type ListDonorScreeningsParams struct {
	TenantID uuid.UUID
	DonorID  uuid.UUID
	RowLimit int32
}

func (q *Queries) ListDonorScreenings(ctx context.Context, arg ListDonorScreeningsParams) ([]BloodbankScreening, error) {
	rows, err := q.db.Query(ctx, listDonorScreenings, arg.TenantID, arg.DonorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankScreening{}
	for rows.Next() {
		var i BloodbankScreening
		if err := rows.Scan(
			&i.ScreeningID,
			&i.TenantID,
			&i.DonorID,
			&i.Answers,
			&i.Measurements,
			&i.Consented,
			&i.ConsentNote,
			&i.Accepted,
			&i.Deferral,
			&i.DeferralCode,
			&i.ScreenedAt,
			&i.ScreenedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesForComponent = `-- name: ListEpisodesForComponent :many
SELECT episode_id, tenant_id, component_id, issue_id, patient_id, encounter_id, status, started_at, started_by, ended_at, volume_given_ml, stop_reason, checked_by, checked_with FROM bloodbank.episode
WHERE tenant_id = $1 AND component_id = $2
ORDER BY started_at
`

type ListEpisodesForComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) ListEpisodesForComponent(ctx context.Context, arg ListEpisodesForComponentParams) ([]BloodbankEpisode, error) {
	rows, err := q.db.Query(ctx, listEpisodesForComponent, arg.TenantID, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankEpisode{}
	for rows.Next() {
		var i BloodbankEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.ComponentID,
			&i.IssueID,
			&i.PatientID,
			&i.EncounterID,
			&i.Status,
			&i.StartedAt,
			&i.StartedBy,
			&i.EndedAt,
			&i.VolumeGivenMl,
			&i.StopReason,
			&i.CheckedBy,
			&i.CheckedWith,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesInPeriod = `-- name: ListEpisodesInPeriod :many
SELECT episode_id, tenant_id, component_id, issue_id, patient_id, encounter_id, status, started_at, started_by, ended_at, volume_given_ml, stop_reason, checked_by, checked_with FROM bloodbank.episode
WHERE tenant_id = $1
  AND started_at >= $2 AND started_at < $3
ORDER BY started_at
LIMIT $4
`

type ListEpisodesInPeriodParams struct {
	TenantID    uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	RowLimit    int32
}

func (q *Queries) ListEpisodesInPeriod(ctx context.Context, arg ListEpisodesInPeriodParams) ([]BloodbankEpisode, error) {
	rows, err := q.db.Query(ctx, listEpisodesInPeriod,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankEpisode{}
	for rows.Next() {
		var i BloodbankEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.ComponentID,
			&i.IssueID,
			&i.PatientID,
			&i.EncounterID,
			&i.Status,
			&i.StartedAt,
			&i.StartedBy,
			&i.EndedAt,
			&i.VolumeGivenMl,
			&i.StopReason,
			&i.CheckedBy,
			&i.CheckedWith,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventory = `-- name: ListInventory :many
SELECT component_id, tenant_id, unit_number, collection_id, donor_id, source, component_class, abo, rhd, status, discard_reason, volume_ml, attributes, location, collected_at, expires_at, created_at, created_by, version FROM bloodbank.component
WHERE tenant_id = $1
  AND status IN ('quarantined', 'available', 'reserved')
ORDER BY component_class, abo, rhd, expires_at
LIMIT $2
`

type ListInventoryParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

// The whole inventory for the stock report, including the states that are not
// allocatable: a bank short because everything is reserved has a different
// problem from one short because nothing has been tested.
func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]BloodbankComponent, error) {
	rows, err := q.db.Query(ctx, listInventory, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankComponent{}
	for rows.Next() {
		var i BloodbankComponent
		if err := rows.Scan(
			&i.ComponentID,
			&i.TenantID,
			&i.UnitNumber,
			&i.CollectionID,
			&i.DonorID,
			&i.Source,
			&i.ComponentClass,
			&i.Abo,
			&i.Rhd,
			&i.Status,
			&i.DiscardReason,
			&i.VolumeMl,
			&i.Attributes,
			&i.Location,
			&i.CollectedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForComponent = `-- name: ListIssuesForComponent :many
SELECT issue_id, tenant_id, component_id, reservation_id, patient_id, request_id, destination, emergency, emergency_authoriser, emergency_reason, reconciled, reconciled_at, reconciled_by, reconcile_note, issued_at, issued_by, issued_to, checked_by FROM bloodbank.issue
WHERE tenant_id = $1 AND component_id = $2
ORDER BY issued_at
`

type ListIssuesForComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) ListIssuesForComponent(ctx context.Context, arg ListIssuesForComponentParams) ([]BloodbankIssue, error) {
	rows, err := q.db.Query(ctx, listIssuesForComponent, arg.TenantID, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankIssue{}
	for rows.Next() {
		var i BloodbankIssue
		if err := rows.Scan(
			&i.IssueID,
			&i.TenantID,
			&i.ComponentID,
			&i.ReservationID,
			&i.PatientID,
			&i.RequestID,
			&i.Destination,
			&i.Emergency,
			&i.EmergencyAuthoriser,
			&i.EmergencyReason,
			&i.Reconciled,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.ReconcileNote,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.IssuedTo,
			&i.CheckedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesInPeriod = `-- name: ListIssuesInPeriod :many
SELECT issue_id, tenant_id, component_id, reservation_id, patient_id, request_id, destination, emergency, emergency_authoriser, emergency_reason, reconciled, reconciled_at, reconciled_by, reconcile_note, issued_at, issued_by, issued_to, checked_by FROM bloodbank.issue
WHERE tenant_id = $1
  AND issued_at >= $2 AND issued_at < $3
ORDER BY issued_at
LIMIT $4
`

type ListIssuesInPeriodParams struct {
	TenantID    uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	RowLimit    int32
}

func (q *Queries) ListIssuesInPeriod(ctx context.Context, arg ListIssuesInPeriodParams) ([]BloodbankIssue, error) {
	rows, err := q.db.Query(ctx, listIssuesInPeriod,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankIssue{}
	for rows.Next() {
		var i BloodbankIssue
		if err := rows.Scan(
			&i.IssueID,
			&i.TenantID,
			&i.ComponentID,
			&i.ReservationID,
			&i.PatientID,
			&i.RequestID,
			&i.Destination,
			&i.Emergency,
			&i.EmergencyAuthoriser,
			&i.EmergencyReason,
			&i.Reconciled,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.ReconcileNote,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.IssuedTo,
			&i.CheckedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLapsedReservations = `-- name: ListLapsedReservations :many
SELECT reservation_id, tenant_id, component_id, request_id, patient_id, sample_id, crossmatched, crossmatch_note, status, expires_at, reserved_at, reserved_by, released_reason FROM bloodbank.reservation
WHERE tenant_id = $1 AND status = 'held' AND expires_at <= $2
ORDER BY expires_at
LIMIT $3
`

type ListLapsedReservationsParams struct {
	TenantID uuid.UUID
	AsOf     pgtype.Timestamptz
	RowLimit int32
}

// Reservations past their window, for the sweep that returns held blood to the
// shelf. Blood held for a patient who did not need it is blood the next
// patient could not have.
func (q *Queries) ListLapsedReservations(ctx context.Context, arg ListLapsedReservationsParams) ([]BloodbankReservation, error) {
	rows, err := q.db.Query(ctx, listLapsedReservations, arg.TenantID, arg.AsOf, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReservation{}
	for rows.Next() {
		var i BloodbankReservation
		if err := rows.Scan(
			&i.ReservationID,
			&i.TenantID,
			&i.ComponentID,
			&i.RequestID,
			&i.PatientID,
			&i.SampleID,
			&i.Crossmatched,
			&i.CrossmatchNote,
			&i.Status,
			&i.ExpiresAt,
			&i.ReservedAt,
			&i.ReservedBy,
			&i.ReleasedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenReactions = `-- name: ListOpenReactions :many
SELECT reaction_id, tenant_id, episode_id, component_id, patient_id, severity, features, note, reported_at, reported_by, state, classification, conclusion, concluded_at, concluded_by, unit_returned FROM bloodbank.reaction
WHERE tenant_id = $1 AND state = 'open'
ORDER BY reported_at
LIMIT $2
`

type ListOpenReactionsParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

func (q *Queries) ListOpenReactions(ctx context.Context, arg ListOpenReactionsParams) ([]BloodbankReaction, error) {
	rows, err := q.db.Query(ctx, listOpenReactions, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReaction{}
	for rows.Next() {
		var i BloodbankReaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.TenantID,
			&i.EpisodeID,
			&i.ComponentID,
			&i.PatientID,
			&i.Severity,
			&i.Features,
			&i.Note,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.State,
			&i.Classification,
			&i.Conclusion,
			&i.ConcludedAt,
			&i.ConcludedBy,
			&i.UnitReturned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRequests = `-- name: ListOpenRequests :many
SELECT request_id, tenant_id, patient_id, encounter_id, facility_id, component_class, quantity, indication, urgency, requirements, required_by, status, requested_by, requested_at, version FROM bloodbank.request
WHERE tenant_id = $1
  AND status = 'open'
  AND ($2::text = '' OR facility_id = $2)
ORDER BY CASE urgency
             WHEN 'emergency' THEN 0
             WHEN 'urgent' THEN 1
             ELSE 2
         END,
         required_by NULLS LAST,
         requested_at
LIMIT $3
`

type ListOpenRequestsParams struct {
	TenantID   uuid.UUID
	FacilityID string
	RowLimit   int32
}

// The blood bank's worklist. Emergency before urgent before routine, then
// soonest needed; a request with no required-by time sorts last rather than
// hiding.
func (q *Queries) ListOpenRequests(ctx context.Context, arg ListOpenRequestsParams) ([]BloodbankRequest, error) {
	rows, err := q.db.Query(ctx, listOpenRequests, arg.TenantID, arg.FacilityID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankRequest{}
	for rows.Next() {
		var i BloodbankRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.FacilityID,
			&i.ComponentClass,
			&i.Quantity,
			&i.Indication,
			&i.Urgency,
			&i.Requirements,
			&i.RequiredBy,
			&i.Status,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientEpisodes = `-- name: ListPatientEpisodes :many
SELECT episode_id, tenant_id, component_id, issue_id, patient_id, encounter_id, status, started_at, started_by, ended_at, volume_given_ml, stop_reason, checked_by, checked_with FROM bloodbank.episode
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListPatientEpisodesParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	RowLimit  int32
}

// The patient's transfusion history, which is what "longitudinally visible"
// means: every episode, across admissions, most recent first.
func (q *Queries) ListPatientEpisodes(ctx context.Context, arg ListPatientEpisodesParams) ([]BloodbankEpisode, error) {
	rows, err := q.db.Query(ctx, listPatientEpisodes, arg.TenantID, arg.PatientID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankEpisode{}
	for rows.Next() {
		var i BloodbankEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.ComponentID,
			&i.IssueID,
			&i.PatientID,
			&i.EncounterID,
			&i.Status,
			&i.StartedAt,
			&i.StartedBy,
			&i.EndedAt,
			&i.VolumeGivenMl,
			&i.StopReason,
			&i.CheckedBy,
			&i.CheckedWith,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientRequests = `-- name: ListPatientRequests :many
SELECT request_id, tenant_id, patient_id, encounter_id, facility_id, component_class, quantity, indication, urgency, requirements, required_by, status, requested_by, requested_at, version FROM bloodbank.request
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY requested_at DESC
LIMIT $3
`

type ListPatientRequestsParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	RowLimit  int32
}

func (q *Queries) ListPatientRequests(ctx context.Context, arg ListPatientRequestsParams) ([]BloodbankRequest, error) {
	rows, err := q.db.Query(ctx, listPatientRequests, arg.TenantID, arg.PatientID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankRequest{}
	for rows.Next() {
		var i BloodbankRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.FacilityID,
			&i.ComponentClass,
			&i.Quantity,
			&i.Indication,
			&i.Urgency,
			&i.Requirements,
			&i.RequiredBy,
			&i.Status,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientReservations = `-- name: ListPatientReservations :many
SELECT reservation_id, tenant_id, component_id, request_id, patient_id, sample_id, crossmatched, crossmatch_note, status, expires_at, reserved_at, reserved_by, released_reason FROM bloodbank.reservation
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY reserved_at DESC
LIMIT $3
`

type ListPatientReservationsParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	RowLimit  int32
}

func (q *Queries) ListPatientReservations(ctx context.Context, arg ListPatientReservationsParams) ([]BloodbankReservation, error) {
	rows, err := q.db.Query(ctx, listPatientReservations, arg.TenantID, arg.PatientID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReservation{}
	for rows.Next() {
		var i BloodbankReservation
		if err := rows.Scan(
			&i.ReservationID,
			&i.TenantID,
			&i.ComponentID,
			&i.RequestID,
			&i.PatientID,
			&i.SampleID,
			&i.Crossmatched,
			&i.CrossmatchNote,
			&i.Status,
			&i.ExpiresAt,
			&i.ReservedAt,
			&i.ReservedBy,
			&i.ReleasedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForComponent = `-- name: ListReactionsForComponent :many
SELECT reaction_id, tenant_id, episode_id, component_id, patient_id, severity, features, note, reported_at, reported_by, state, classification, conclusion, concluded_at, concluded_by, unit_returned FROM bloodbank.reaction
WHERE tenant_id = $1 AND component_id = $2
ORDER BY reported_at
`

type ListReactionsForComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) ListReactionsForComponent(ctx context.Context, arg ListReactionsForComponentParams) ([]BloodbankReaction, error) {
	rows, err := q.db.Query(ctx, listReactionsForComponent, arg.TenantID, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReaction{}
	for rows.Next() {
		var i BloodbankReaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.TenantID,
			&i.EpisodeID,
			&i.ComponentID,
			&i.PatientID,
			&i.Severity,
			&i.Features,
			&i.Note,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.State,
			&i.Classification,
			&i.Conclusion,
			&i.ConcludedAt,
			&i.ConcludedBy,
			&i.UnitReturned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsInPeriod = `-- name: ListReactionsInPeriod :many
SELECT reaction_id, tenant_id, episode_id, component_id, patient_id, severity, features, note, reported_at, reported_by, state, classification, conclusion, concluded_at, concluded_by, unit_returned FROM bloodbank.reaction
WHERE tenant_id = $1
  AND reported_at >= $2 AND reported_at < $3
ORDER BY reported_at
LIMIT $4
`

type ListReactionsInPeriodParams struct {
	TenantID    uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	RowLimit    int32
}

func (q *Queries) ListReactionsInPeriod(ctx context.Context, arg ListReactionsInPeriodParams) ([]BloodbankReaction, error) {
	rows, err := q.db.Query(ctx, listReactionsInPeriod,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReaction{}
	for rows.Next() {
		var i BloodbankReaction
		if err := rows.Scan(
			&i.ReactionID,
			&i.TenantID,
			&i.EpisodeID,
			&i.ComponentID,
			&i.PatientID,
			&i.Severity,
			&i.Features,
			&i.Note,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.State,
			&i.Classification,
			&i.Conclusion,
			&i.ConcludedAt,
			&i.ConcludedBy,
			&i.UnitReturned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsForComponent = `-- name: ListReservationsForComponent :many
SELECT reservation_id, tenant_id, component_id, request_id, patient_id, sample_id, crossmatched, crossmatch_note, status, expires_at, reserved_at, reserved_by, released_reason FROM bloodbank.reservation
WHERE tenant_id = $1 AND component_id = $2
ORDER BY reserved_at
`

type ListReservationsForComponentParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

func (q *Queries) ListReservationsForComponent(ctx context.Context, arg ListReservationsForComponentParams) ([]BloodbankReservation, error) {
	rows, err := q.db.Query(ctx, listReservationsForComponent, arg.TenantID, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankReservation{}
	for rows.Next() {
		var i BloodbankReservation
		if err := rows.Scan(
			&i.ReservationID,
			&i.TenantID,
			&i.ComponentID,
			&i.RequestID,
			&i.PatientID,
			&i.SampleID,
			&i.Crossmatched,
			&i.CrossmatchNote,
			&i.Status,
			&i.ExpiresAt,
			&i.ReservedAt,
			&i.ReservedBy,
			&i.ReleasedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingComponents = `-- name: ListSiblingComponents :many
SELECT sibling.component_id, sibling.tenant_id, sibling.unit_number, sibling.collection_id, sibling.donor_id, sibling.source, sibling.component_class, sibling.abo, sibling.rhd, sibling.status, sibling.discard_reason, sibling.volume_ml, sibling.attributes, sibling.location, sibling.collected_at, sibling.expires_at, sibling.created_at, sibling.created_by, sibling.version FROM bloodbank.component sibling
JOIN bloodbank.component origin
  ON origin.collection_id = sibling.collection_id
 AND origin.tenant_id = sibling.tenant_id
WHERE sibling.tenant_id = $1
  AND origin.component_id = $2
  AND sibling.component_id <> $2
ORDER BY sibling.created_at
`

type ListSiblingComponentsParams struct {
	TenantID    uuid.UUID
	ComponentID uuid.UUID
}

// The direction a look-back runs: from one component to every sibling made
// from the same donation. A reactive test result arriving late, or a reaction,
// means every other component from that collection has to be found.
func (q *Queries) ListSiblingComponents(ctx context.Context, arg ListSiblingComponentsParams) ([]BloodbankComponent, error) {
	rows, err := q.db.Query(ctx, listSiblingComponents, arg.TenantID, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankComponent{}
	for rows.Next() {
		var i BloodbankComponent
		if err := rows.Scan(
			&i.ComponentID,
			&i.TenantID,
			&i.UnitNumber,
			&i.CollectionID,
			&i.DonorID,
			&i.Source,
			&i.ComponentClass,
			&i.Abo,
			&i.Rhd,
			&i.Status,
			&i.DiscardReason,
			&i.VolumeMl,
			&i.Attributes,
			&i.Location,
			&i.CollectedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockThresholds = `-- name: ListStockThresholds :many
SELECT threshold_id, tenant_id, facility_id, component_class, abo, rhd, minimum, set_by, set_at FROM bloodbank.stock_threshold
WHERE tenant_id = $1
  AND ($2::text = '' OR facility_id = $2)
ORDER BY component_class, abo, rhd
`

type ListStockThresholdsParams struct {
	TenantID   uuid.UUID
	FacilityID string
}

func (q *Queries) ListStockThresholds(ctx context.Context, arg ListStockThresholdsParams) ([]BloodbankStockThreshold, error) {
	rows, err := q.db.Query(ctx, listStockThresholds, arg.TenantID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankStockThreshold{}
	for rows.Next() {
		var i BloodbankStockThreshold
		if err := rows.Scan(
			&i.ThresholdID,
			&i.TenantID,
			&i.FacilityID,
			&i.ComponentClass,
			&i.Abo,
			&i.Rhd,
			&i.Minimum,
			&i.SetBy,
			&i.SetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestResults = `-- name: ListTestResults :many
SELECT test_id, tenant_id, collection_id, code, display, reactive, value, method, tested_at, tested_by FROM bloodbank.test_result
WHERE tenant_id = $1 AND collection_id = $2
ORDER BY tested_at
`

type ListTestResultsParams struct {
	TenantID     uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) ListTestResults(ctx context.Context, arg ListTestResultsParams) ([]BloodbankTestResult, error) {
	rows, err := q.db.Query(ctx, listTestResults, arg.TenantID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankTestResult{}
	for rows.Next() {
		var i BloodbankTestResult
		if err := rows.Scan(
			&i.TestID,
			&i.TenantID,
			&i.CollectionID,
			&i.Code,
			&i.Display,
			&i.Reactive,
			&i.Value,
			&i.Method,
			&i.TestedAt,
			&i.TestedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreconciledIssues = `-- name: ListUnreconciledIssues :many
SELECT issue_id, tenant_id, component_id, reservation_id, patient_id, request_id, destination, emergency, emergency_authoriser, emergency_reason, reconciled, reconciled_at, reconciled_by, reconcile_note, issued_at, issued_by, issued_to, checked_by FROM bloodbank.issue
WHERE tenant_id = $1 AND emergency AND NOT reconciled
ORDER BY issued_at
LIMIT $2
`

type ListUnreconciledIssuesParams struct {
	TenantID uuid.UUID
	RowLimit int32
}

// The outstanding reconciliation list: SRS-BLD-016's "later reconciled" is
// read against this.
func (q *Queries) ListUnreconciledIssues(ctx context.Context, arg ListUnreconciledIssuesParams) ([]BloodbankIssue, error) {
	rows, err := q.db.Query(ctx, listUnreconciledIssues, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BloodbankIssue{}
	for rows.Next() {
		var i BloodbankIssue
		if err := rows.Scan(
			&i.IssueID,
			&i.TenantID,
			&i.ComponentID,
			&i.ReservationID,
			&i.PatientID,
			&i.RequestID,
			&i.Destination,
			&i.Emergency,
			&i.EmergencyAuthoriser,
			&i.EmergencyReason,
			&i.Reconciled,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.ReconcileNote,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.IssuedTo,
			&i.CheckedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileIssue = `-- name: ReconcileIssue :execrows
UPDATE bloodbank.issue
SET reconciled = true, reconciled_at = $1,
    reconciled_by = $2, reconcile_note = $3
WHERE tenant_id = $4 AND issue_id = $5
  AND emergency AND NOT reconciled
`

type ReconcileIssueParams struct {
	ReconciledAt  pgtype.Timestamptz
	ReconciledBy  string
	ReconcileNote string
	TenantID      uuid.UUID
	IssueID       uuid.UUID
}

func (q *Queries) ReconcileIssue(ctx context.Context, arg ReconcileIssueParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileIssue,
		arg.ReconciledAt,
		arg.ReconciledBy,
		arg.ReconcileNote,
		arg.TenantID,
		arg.IssueID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComponentStatus = `-- name: UpdateComponentStatus :execrows
UPDATE bloodbank.component
SET status = $1, discard_reason = $2,
    location = $3, version = version + 1
WHERE tenant_id = $4 AND component_id = $5
  AND version = $6
`

type UpdateComponentStatusParams struct {
	Status          string
	DiscardReason   string
	Location        string
	TenantID        uuid.UUID
	ComponentID     uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateComponentStatus(ctx context.Context, arg UpdateComponentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComponentStatus,
		arg.Status,
		arg.DiscardReason,
		arg.Location,
		arg.TenantID,
		arg.ComponentID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDonorDeferral = `-- name: UpdateDonorDeferral :execrows
UPDATE bloodbank.donor
SET deferral = $1, deferral_code = $2,
    deferral_note = $3, deferred_at = $4,
    deferred_by = $5, deferred_until = $6,
    abo = $7, rhd = $8,
    version = version + 1
WHERE tenant_id = $9 AND donor_id = $10
  AND version = $11
`

type UpdateDonorDeferralParams struct {
	Deferral        *string
	DeferralCode    string
	DeferralNote    string
	DeferredAt      pgtype.Timestamptz
	DeferredBy      string
	DeferredUntil   pgtype.Timestamptz
	Abo             *string
	Rhd             *string
	TenantID        uuid.UUID
	DonorID         uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateDonorDeferral(ctx context.Context, arg UpdateDonorDeferralParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDonorDeferral,
		arg.Deferral,
		arg.DeferralCode,
		arg.DeferralNote,
		arg.DeferredAt,
		arg.DeferredBy,
		arg.DeferredUntil,
		arg.Abo,
		arg.Rhd,
		arg.TenantID,
		arg.DonorID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRequestStatus = `-- name: UpdateRequestStatus :execrows
UPDATE bloodbank.request
SET status = $1, version = version + 1
WHERE tenant_id = $2 AND request_id = $3
  AND version = $4
`

type UpdateRequestStatusParams struct {
	Status          string
	TenantID        uuid.UUID
	RequestID       uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequestStatus,
		arg.Status,
		arg.TenantID,
		arg.RequestID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :execrows
UPDATE bloodbank.reservation
SET status = $1, released_reason = $2
WHERE tenant_id = $3 AND reservation_id = $4
  AND status = 'held'
`

type UpdateReservationStatusParams struct {
	Status         string
	ReleasedReason string
	TenantID       uuid.UUID
	ReservationID  uuid.UUID
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReservationStatus,
		arg.Status,
		arg.ReleasedReason,
		arg.TenantID,
		arg.ReservationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransfusionEpisode = `-- name: UpdateTransfusionEpisode :execrows
UPDATE bloodbank.episode
SET status = $1, ended_at = $2,
    volume_given_ml = $3, stop_reason = $4
WHERE tenant_id = $5 AND episode_id = $6
`

type UpdateTransfusionEpisodeParams struct {
	Status        string
	EndedAt       pgtype.Timestamptz
	VolumeGivenMl int32
	StopReason    string
	TenantID      uuid.UUID
	EpisodeID     uuid.UUID
}

func (q *Queries) UpdateTransfusionEpisode(ctx context.Context, arg UpdateTransfusionEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransfusionEpisode,
		arg.Status,
		arg.EndedAt,
		arg.VolumeGivenMl,
		arg.StopReason,
		arg.TenantID,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStockThreshold = `-- name: UpsertStockThreshold :exec
INSERT INTO bloodbank.stock_threshold (
    threshold_id, tenant_id, facility_id, component_class, abo, rhd,
    minimum, set_by, set_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (tenant_id, facility_id, component_class, abo, rhd) DO UPDATE
SET minimum = EXCLUDED.minimum,
    set_by = EXCLUDED.set_by,
    set_at = EXCLUDED.set_at
`

type UpsertStockThresholdParams struct {
	ThresholdID    uuid.UUID
	TenantID       uuid.UUID
	FacilityID     string
	ComponentClass string
	Abo            string
	Rhd            string
	Minimum        int32
	SetBy          string
	SetAt          pgtype.Timestamptz
}

func (q *Queries) UpsertStockThreshold(ctx context.Context, arg UpsertStockThresholdParams) error {
	_, err := q.db.Exec(ctx, upsertStockThreshold,
		arg.ThresholdID,
		arg.TenantID,
		arg.FacilityID,
		arg.ComponentClass,
		arg.Abo,
		arg.Rhd,
		arg.Minimum,
		arg.SetBy,
		arg.SetAt,
	)
	return err
}
