// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: empi.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeDuplicateCandidate = `-- name: CloseDuplicateCandidate :execrows
UPDATE empi.duplicate_candidate
SET status = $1, reviewed_by = $2,
    reviewed_at = $3, resolution = $4
WHERE tenant_id = $5 AND candidate_id = $6 AND status = 'open'
`

type CloseDuplicateCandidateParams struct {
	Status      string
	ReviewedBy  string
	ReviewedAt  pgtype.Timestamptz
	Resolution  string
	TenantID    uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) CloseDuplicateCandidate(ctx context.Context, arg CloseDuplicateCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeDuplicateCandidate,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.Resolution,
		arg.TenantID,
		arg.CandidateID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLaterMergesIntoSurvivor = `-- name: CountLaterMergesIntoSurvivor :one
SELECT count(*)
FROM empi.merge_journal
WHERE tenant_id = $1
  AND survivor_id = $2
  AND NOT undone
  AND performed_at > $3
`

type CountLaterMergesIntoSurvivorParams struct {
	TenantID   uuid.UUID
	SurvivorID uuid.UUID
	After      pgtype.Timestamptz
}

// Whether another merge into this survivor came after the one being reversed.
//
// Reversing an earlier merge while a later one stands would restore
// identifiers the later merge has already moved again, and the second merge's
// journal would then describe a state that no longer exists.
func (q *Queries) CountLaterMergesIntoSurvivor(ctx context.Context, arg CountLaterMergesIntoSurvivorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLaterMergesIntoSurvivor, arg.TenantID, arg.SurvivorID, arg.After)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findDuplicateCandidateByPair = `-- name: FindDuplicateCandidateByPair :one
SELECT candidate_id, tenant_id, patient_a_id, patient_b_id, score, outcome,
       status, detected_by, detected_at, reviewed_by, reviewed_at, resolution
FROM empi.duplicate_candidate
WHERE tenant_id = $1 AND patient_a_id = $2 AND patient_b_id = $3
`

type FindDuplicateCandidateByPairParams struct {
	TenantID   uuid.UUID
	PatientAID uuid.UUID
	PatientBID uuid.UUID
}

func (q *Queries) FindDuplicateCandidateByPair(ctx context.Context, arg FindDuplicateCandidateByPairParams) (EmpiDuplicateCandidate, error) {
	row := q.db.QueryRow(ctx, findDuplicateCandidateByPair, arg.TenantID, arg.PatientAID, arg.PatientBID)
	var i EmpiDuplicateCandidate
	err := row.Scan(
		&i.CandidateID,
		&i.TenantID,
		&i.PatientAID,
		&i.PatientBID,
		&i.Score,
		&i.Outcome,
		&i.Status,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Resolution,
	)
	return i, err
}

const findIdentifierHolder = `-- name: FindIdentifierHolder :one
SELECT patient_id
FROM empi.patient_identifier
WHERE tenant_id = $1
  AND identifier_type = $2
  AND system = $3
  AND value = $4
  AND status = 'active'
`

type FindIdentifierHolderParams struct {
	TenantID       uuid.UUID
	IdentifierType string
	System         string
	Value          string
}

// Who currently holds this identifier value, if anybody.
//
// Used before linking, so a conflict is reported as "already linked to another
// patient" rather than as a unique-violation SQLSTATE the transport would have
// to guess at.
func (q *Queries) FindIdentifierHolder(ctx context.Context, arg FindIdentifierHolderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findIdentifierHolder,
		arg.TenantID,
		arg.IdentifierType,
		arg.System,
		arg.Value,
	)
	var patient_id uuid.UUID
	err := row.Scan(&patient_id)
	return patient_id, err
}

const findPatientByIdentifier = `-- name: FindPatientByIdentifier :many
SELECT p.patient_id, p.tenant_id, p.registered_facility_id, p.status,
       p.family_name, p.given_names, p.name_prefix, p.name_suffix,
       p.birth_date, p.birth_date_precision, p.sex, p.phones, p.emails, p.addresses,
       p.merged_into_patient_id,
       p.deceased_date, p.deceased_precision, p.deceased_source,
       p.deceased_recorded_at, p.deceased_recorded_by,
       p.created_at, p.updated_at, p.version
FROM empi.patient p
JOIN empi.patient_identifier i
  ON i.tenant_id = p.tenant_id AND i.patient_id = p.patient_id
WHERE p.tenant_id = $1
  AND i.identifier_type = $2
  AND i.system = $3
  AND i.value = $4
  AND i.status <> 'revoked'
ORDER BY p.updated_at DESC
LIMIT $5
`

type FindPatientByIdentifierParams struct {
	TenantID       uuid.UUID
	IdentifierType string
	System         string
	Value          string
	PageLimit      int32
}

// Resolves an identifier a patient quoted.
//
// Excludes revoked values and nothing else: a superseded MRN is on a discharge
// summary printed last week, and a clerk typing it in has to reach this
// patient. A revoked one belongs to somebody else and must not resolve.
func (q *Queries) FindPatientByIdentifier(ctx context.Context, arg FindPatientByIdentifierParams) ([]EmpiPatient, error) {
	rows, err := q.db.Query(ctx, findPatientByIdentifier,
		arg.TenantID,
		arg.IdentifierType,
		arg.System,
		arg.Value,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiPatient{}
	for rows.Next() {
		var i EmpiPatient
		if err := rows.Scan(
			&i.PatientID,
			&i.TenantID,
			&i.RegisteredFacilityID,
			&i.Status,
			&i.FamilyName,
			&i.GivenNames,
			&i.NamePrefix,
			&i.NameSuffix,
			&i.BirthDate,
			&i.BirthDatePrecision,
			&i.Sex,
			&i.Phones,
			&i.Emails,
			&i.Addresses,
			&i.MergedIntoPatientID,
			&i.DeceasedDate,
			&i.DeceasedPrecision,
			&i.DeceasedSource,
			&i.DeceasedRecordedAt,
			&i.DeceasedRecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDemographicPolicy = `-- name: GetDemographicPolicy :one
SELECT policy_id, tenant_id, jurisdiction, facility_id,
       required_fields, allow_unidentified, created_at, updated_at
FROM empi.demographic_policy
WHERE tenant_id = $1
  AND jurisdiction = $2
  AND (facility_id IS NULL OR facility_id = $3)
ORDER BY facility_id NULLS LAST
LIMIT 1
`

type GetDemographicPolicyParams struct {
	TenantID     uuid.UUID
	Jurisdiction string
	FacilityID   pgtype.UUID
}

// The minimum set in force, facility first then jurisdiction (SRS-EMPI-001).
//
// ORDER BY on the facility column puts the specific row first, so one query
// answers both scopes rather than the application making two round trips and
// choosing between them.
func (q *Queries) GetDemographicPolicy(ctx context.Context, arg GetDemographicPolicyParams) (EmpiDemographicPolicy, error) {
	row := q.db.QueryRow(ctx, getDemographicPolicy, arg.TenantID, arg.Jurisdiction, arg.FacilityID)
	var i EmpiDemographicPolicy
	err := row.Scan(
		&i.PolicyID,
		&i.TenantID,
		&i.Jurisdiction,
		&i.FacilityID,
		&i.RequiredFields,
		&i.AllowUnidentified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDuplicateCandidate = `-- name: GetDuplicateCandidate :one
SELECT candidate_id, tenant_id, patient_a_id, patient_b_id, score, outcome,
       status, detected_by, detected_at, reviewed_by, reviewed_at, resolution
FROM empi.duplicate_candidate
WHERE tenant_id = $1 AND candidate_id = $2
`

type GetDuplicateCandidateParams struct {
	TenantID    uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) GetDuplicateCandidate(ctx context.Context, arg GetDuplicateCandidateParams) (EmpiDuplicateCandidate, error) {
	row := q.db.QueryRow(ctx, getDuplicateCandidate, arg.TenantID, arg.CandidateID)
	var i EmpiDuplicateCandidate
	err := row.Scan(
		&i.CandidateID,
		&i.TenantID,
		&i.PatientAID,
		&i.PatientBID,
		&i.Score,
		&i.Outcome,
		&i.Status,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Resolution,
	)
	return i, err
}

const getMatchConfig = `-- name: GetMatchConfig :one
SELECT tenant_id, weights, review_threshold, probable_threshold, updated_at, updated_by
FROM empi.match_config
WHERE tenant_id = $1
`

func (q *Queries) GetMatchConfig(ctx context.Context, tenantID uuid.UUID) (EmpiMatchConfig, error) {
	row := q.db.QueryRow(ctx, getMatchConfig, tenantID)
	var i EmpiMatchConfig
	err := row.Scan(
		&i.TenantID,
		&i.Weights,
		&i.ReviewThreshold,
		&i.ProbableThreshold,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getMergeRecord = `-- name: GetMergeRecord :one
SELECT merge_id, tenant_id, survivor_id, merged_id, merged_previous_status,
       reason, performed_by, performed_at, moved_identifiers, carried_deceased,
       undone, undone_by, undone_at, undo_reason
FROM empi.merge_journal
WHERE tenant_id = $1 AND merge_id = $2
`

type GetMergeRecordParams struct {
	TenantID uuid.UUID
	MergeID  uuid.UUID
}

func (q *Queries) GetMergeRecord(ctx context.Context, arg GetMergeRecordParams) (EmpiMergeJournal, error) {
	row := q.db.QueryRow(ctx, getMergeRecord, arg.TenantID, arg.MergeID)
	var i EmpiMergeJournal
	err := row.Scan(
		&i.MergeID,
		&i.TenantID,
		&i.SurvivorID,
		&i.MergedID,
		&i.MergedPreviousStatus,
		&i.Reason,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.MovedIdentifiers,
		&i.CarriedDeceased,
		&i.Undone,
		&i.UndoneBy,
		&i.UndoneAt,
		&i.UndoReason,
	)
	return i, err
}

const getPatient = `-- name: GetPatient :one
SELECT patient_id, tenant_id, registered_facility_id, status,
       family_name, given_names, name_prefix, name_suffix,
       birth_date, birth_date_precision, sex, phones, emails, addresses,
       merged_into_patient_id,
       deceased_date, deceased_precision, deceased_source,
       deceased_recorded_at, deceased_recorded_by,
       created_at, updated_at, version
FROM empi.patient
WHERE tenant_id = $1 AND patient_id = $2
`

type GetPatientParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
}

func (q *Queries) GetPatient(ctx context.Context, arg GetPatientParams) (EmpiPatient, error) {
	row := q.db.QueryRow(ctx, getPatient, arg.TenantID, arg.PatientID)
	var i EmpiPatient
	err := row.Scan(
		&i.PatientID,
		&i.TenantID,
		&i.RegisteredFacilityID,
		&i.Status,
		&i.FamilyName,
		&i.GivenNames,
		&i.NamePrefix,
		&i.NameSuffix,
		&i.BirthDate,
		&i.BirthDatePrecision,
		&i.Sex,
		&i.Phones,
		&i.Emails,
		&i.Addresses,
		&i.MergedIntoPatientID,
		&i.DeceasedDate,
		&i.DeceasedPrecision,
		&i.DeceasedSource,
		&i.DeceasedRecordedAt,
		&i.DeceasedRecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getStandingMergeForLoser = `-- name: GetStandingMergeForLoser :one
SELECT merge_id, tenant_id, survivor_id, merged_id, merged_previous_status,
       reason, performed_by, performed_at, moved_identifiers, carried_deceased,
       undone, undone_by, undone_at, undo_reason
FROM empi.merge_journal
WHERE tenant_id = $1 AND merged_id = $2 AND NOT undone
`

type GetStandingMergeForLoserParams struct {
	TenantID uuid.UUID
	MergedID uuid.UUID
}

// The merge that currently holds this record down, if any.
func (q *Queries) GetStandingMergeForLoser(ctx context.Context, arg GetStandingMergeForLoserParams) (EmpiMergeJournal, error) {
	row := q.db.QueryRow(ctx, getStandingMergeForLoser, arg.TenantID, arg.MergedID)
	var i EmpiMergeJournal
	err := row.Scan(
		&i.MergeID,
		&i.TenantID,
		&i.SurvivorID,
		&i.MergedID,
		&i.MergedPreviousStatus,
		&i.Reason,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.MovedIdentifiers,
		&i.CarriedDeceased,
		&i.Undone,
		&i.UndoneBy,
		&i.UndoneAt,
		&i.UndoReason,
	)
	return i, err
}

const insertMergeRecord = `-- name: InsertMergeRecord :exec

INSERT INTO empi.merge_journal (
    merge_id, tenant_id, survivor_id, merged_id, merged_previous_status,
    reason, performed_by, performed_at, moved_identifiers, carried_deceased
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
`

type InsertMergeRecordParams struct {
	MergeID              uuid.UUID
	TenantID             uuid.UUID
	SurvivorID           uuid.UUID
	MergedID             uuid.UUID
	MergedPreviousStatus string
	Reason               string
	PerformedBy          string
	PerformedAt          pgtype.Timestamptz
	MovedIdentifiers     []byte
	CarriedDeceased      bool
}

// Merge journal and duplicate review (SRS-EMPI-004/005/006).
func (q *Queries) InsertMergeRecord(ctx context.Context, arg InsertMergeRecordParams) error {
	_, err := q.db.Exec(ctx, insertMergeRecord,
		arg.MergeID,
		arg.TenantID,
		arg.SurvivorID,
		arg.MergedID,
		arg.MergedPreviousStatus,
		arg.Reason,
		arg.PerformedBy,
		arg.PerformedAt,
		arg.MovedIdentifiers,
		arg.CarriedDeceased,
	)
	return err
}

const insertPatient = `-- name: InsertPatient :exec

INSERT INTO empi.patient (
    patient_id, tenant_id, registered_facility_id, status,
    family_name, given_names, name_prefix, name_suffix,
    birth_date, birth_date_precision, sex,
    phones, emails, addresses,
    created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9::date, $10, $11,
    $12, $13, $14,
    $15, $16, 1
)
`

type InsertPatientParams struct {
	PatientID            uuid.UUID
	TenantID             uuid.UUID
	RegisteredFacilityID uuid.UUID
	Status               string
	FamilyName           string
	GivenNames           []string
	NamePrefix           string
	NameSuffix           string
	BirthDate            pgtype.Date
	BirthDatePrecision   string
	Sex                  string
	Phones               []byte
	Emails               []byte
	Addresses            []byte
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

// Enterprise master patient index (SRS-EMPI).
//
// Every statement here leads with tenant_id. That is not a convention: a query
// that filters on patient_id alone would return another tenant's patient to a
// caller who guessed a UUID, and the repository cannot even be called without
// a verified tenant scope (FIT-03). The predicate is the second half of that.
func (q *Queries) InsertPatient(ctx context.Context, arg InsertPatientParams) error {
	_, err := q.db.Exec(ctx, insertPatient,
		arg.PatientID,
		arg.TenantID,
		arg.RegisteredFacilityID,
		arg.Status,
		arg.FamilyName,
		arg.GivenNames,
		arg.NamePrefix,
		arg.NameSuffix,
		arg.BirthDate,
		arg.BirthDatePrecision,
		arg.Sex,
		arg.Phones,
		arg.Emails,
		arg.Addresses,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPatientIdentifier = `-- name: InsertPatientIdentifier :exec
INSERT INTO empi.patient_identifier (
    identifier_id, tenant_id, patient_id, identifier_type, system, value,
    assigning_authority, status, source, is_primary, linked_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertPatientIdentifierParams struct {
	IdentifierID       uuid.UUID
	TenantID           uuid.UUID
	PatientID          uuid.UUID
	IdentifierType     string
	System             string
	Value              string
	AssigningAuthority string
	Status             string
	Source             string
	IsPrimary          bool
	LinkedAt           pgtype.Timestamptz
}

// Relies on patient_identifier_active_value_key to refuse a value already held
// by another patient. Checking first and inserting second is a race two
// concurrent registrations both win (SRS-EMPI-016).
func (q *Queries) InsertPatientIdentifier(ctx context.Context, arg InsertPatientIdentifierParams) error {
	_, err := q.db.Exec(ctx, insertPatientIdentifier,
		arg.IdentifierID,
		arg.TenantID,
		arg.PatientID,
		arg.IdentifierType,
		arg.System,
		arg.Value,
		arg.AssigningAuthority,
		arg.Status,
		arg.Source,
		arg.IsPrimary,
		arg.LinkedAt,
	)
	return err
}

const listIdentifiersForPatients = `-- name: ListIdentifiersForPatients :many
SELECT identifier_id, tenant_id, patient_id, identifier_type, system, value,
       assigning_authority, status, source, is_primary,
       linked_at, unlinked_at, superseded_by_id, reason
FROM empi.patient_identifier
WHERE tenant_id = $1 AND patient_id = ANY($2::uuid[])
ORDER BY patient_id, is_primary DESC, linked_at
`

type ListIdentifiersForPatientsParams struct {
	TenantID   uuid.UUID
	PatientIds []uuid.UUID
}

// Batch load for a search result. One query per patient would make a page of
// twenty candidates twenty-one round trips.
func (q *Queries) ListIdentifiersForPatients(ctx context.Context, arg ListIdentifiersForPatientsParams) ([]EmpiPatientIdentifier, error) {
	rows, err := q.db.Query(ctx, listIdentifiersForPatients, arg.TenantID, arg.PatientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiPatientIdentifier{}
	for rows.Next() {
		var i EmpiPatientIdentifier
		if err := rows.Scan(
			&i.IdentifierID,
			&i.TenantID,
			&i.PatientID,
			&i.IdentifierType,
			&i.System,
			&i.Value,
			&i.AssigningAuthority,
			&i.Status,
			&i.Source,
			&i.IsPrimary,
			&i.LinkedAt,
			&i.UnlinkedAt,
			&i.SupersededByID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDuplicateCandidates = `-- name: ListOpenDuplicateCandidates :many
SELECT candidate_id, tenant_id, patient_a_id, patient_b_id, score, outcome,
       status, detected_by, detected_at, reviewed_by, reviewed_at, resolution
FROM empi.duplicate_candidate
WHERE tenant_id = $1 AND status = 'open'
ORDER BY score DESC, detected_at, candidate_id
LIMIT $2
`

type ListOpenDuplicateCandidatesParams struct {
	TenantID  uuid.UUID
	PageLimit int32
}

// The review worklist, strongest first: that is the pair most likely to be one
// person, and the one whose being wrong costs the most.
func (q *Queries) ListOpenDuplicateCandidates(ctx context.Context, arg ListOpenDuplicateCandidatesParams) ([]EmpiDuplicateCandidate, error) {
	rows, err := q.db.Query(ctx, listOpenDuplicateCandidates, arg.TenantID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiDuplicateCandidate{}
	for rows.Next() {
		var i EmpiDuplicateCandidate
		if err := rows.Scan(
			&i.CandidateID,
			&i.TenantID,
			&i.PatientAID,
			&i.PatientBID,
			&i.Score,
			&i.Outcome,
			&i.Status,
			&i.DetectedBy,
			&i.DetectedAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientIdentifiers = `-- name: ListPatientIdentifiers :many
SELECT identifier_id, tenant_id, patient_id, identifier_type, system, value,
       assigning_authority, status, source, is_primary,
       linked_at, unlinked_at, superseded_by_id, reason
FROM empi.patient_identifier
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY is_primary DESC, linked_at, identifier_id
`

type ListPatientIdentifiersParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
}

func (q *Queries) ListPatientIdentifiers(ctx context.Context, arg ListPatientIdentifiersParams) ([]EmpiPatientIdentifier, error) {
	rows, err := q.db.Query(ctx, listPatientIdentifiers, arg.TenantID, arg.PatientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiPatientIdentifier{}
	for rows.Next() {
		var i EmpiPatientIdentifier
		if err := rows.Scan(
			&i.IdentifierID,
			&i.TenantID,
			&i.PatientID,
			&i.IdentifierType,
			&i.System,
			&i.Value,
			&i.AssigningAuthority,
			&i.Status,
			&i.Source,
			&i.IsPrimary,
			&i.LinkedAt,
			&i.UnlinkedAt,
			&i.SupersededByID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsByName = `-- name: ListPatientsByName :many
SELECT patient_id, tenant_id, registered_facility_id, status,
       family_name, given_names, name_prefix, name_suffix,
       birth_date, birth_date_precision, sex, phones, emails, addresses,
       merged_into_patient_id,
       deceased_date, deceased_precision, deceased_source,
       deceased_recorded_at, deceased_recorded_by,
       created_at, updated_at, version
FROM empi.patient
WHERE tenant_id = $1
  AND status <> 'merged'
  AND lower(family_name) LIKE lower($2::text) || '%'
  AND (lower(family_name), patient_id) > (lower($3::text), $4::uuid)
ORDER BY lower(family_name), patient_id
LIMIT $5
`

type ListPatientsByNameParams struct {
	TenantID     uuid.UUID
	FamilyPrefix string
	AfterFamily  string
	AfterID      uuid.UUID
	PageLimit    int32
}

// Plain name search for the registration desk, cursor-paginated.
//
// Keyset on (lower(family_name), patient_id) rather than OFFSET: a clerk
// paging through results while registrations are happening would otherwise see
// rows shift under them.
func (q *Queries) ListPatientsByName(ctx context.Context, arg ListPatientsByNameParams) ([]EmpiPatient, error) {
	rows, err := q.db.Query(ctx, listPatientsByName,
		arg.TenantID,
		arg.FamilyPrefix,
		arg.AfterFamily,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiPatient{}
	for rows.Next() {
		var i EmpiPatient
		if err := rows.Scan(
			&i.PatientID,
			&i.TenantID,
			&i.RegisteredFacilityID,
			&i.Status,
			&i.FamilyName,
			&i.GivenNames,
			&i.NamePrefix,
			&i.NameSuffix,
			&i.BirthDate,
			&i.BirthDatePrecision,
			&i.Sex,
			&i.Phones,
			&i.Emails,
			&i.Addresses,
			&i.MergedIntoPatientID,
			&i.DeceasedDate,
			&i.DeceasedPrecision,
			&i.DeceasedSource,
			&i.DeceasedRecordedAt,
			&i.DeceasedRecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMergeUndone = `-- name: MarkMergeUndone :execrows
UPDATE empi.merge_journal
SET undone = true, undone_by = $1, undone_at = $2, undo_reason = $3
WHERE tenant_id = $4 AND merge_id = $5 AND NOT undone
`

type MarkMergeUndoneParams struct {
	UndoneBy   string
	UndoneAt   pgtype.Timestamptz
	UndoReason string
	TenantID   uuid.UUID
	MergeID    uuid.UUID
}

func (q *Queries) MarkMergeUndone(ctx context.Context, arg MarkMergeUndoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMergeUndone,
		arg.UndoneBy,
		arg.UndoneAt,
		arg.UndoReason,
		arg.TenantID,
		arg.MergeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveIdentifierToPatient = `-- name: MoveIdentifierToPatient :execrows
UPDATE empi.patient_identifier
SET patient_id = $1,
    status = $2,
    is_primary = $3,
    reason = $4,
    -- Both arms are cast: without them PostgreSQL infers the parameter's type
    -- from the comparison above and decides unlinked_at is text.
    unlinked_at = CASE WHEN $2::text = 'active'
                       THEN NULL::timestamptz
                       ELSE $5::timestamptz END
WHERE tenant_id = $6 AND identifier_id = $7
`

type MoveIdentifierToPatientParams struct {
	PatientID    uuid.UUID
	Status       string
	IsPrimary    bool
	Reason       string
	UnlinkedAt   pgtype.Timestamptz
	TenantID     uuid.UUID
	IdentifierID uuid.UUID
}

// Re-points one identifier at another patient.
//
// Used by a merge to move the losing record's identifiers to the survivor, and
// by an unmerge to put them back. The status travels with the move: a merged
// MRN arrives superseded so the survivor's own stays the one on the wristband,
// and an unmerge restores whatever the journal says it was.
func (q *Queries) MoveIdentifierToPatient(ctx context.Context, arg MoveIdentifierToPatientParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveIdentifierToPatient,
		arg.PatientID,
		arg.Status,
		arg.IsPrimary,
		arg.Reason,
		arg.UnlinkedAt,
		arg.TenantID,
		arg.IdentifierID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchPatientCandidates = `-- name: SearchPatientCandidates :many
SELECT patient_id, tenant_id, registered_facility_id, status,
       family_name, given_names, name_prefix, name_suffix,
       birth_date, birth_date_precision, sex, phones, emails, addresses,
       merged_into_patient_id,
       deceased_date, deceased_precision, deceased_source,
       deceased_recorded_at, deceased_recorded_by,
       created_at, updated_at, version
FROM empi.patient
WHERE tenant_id = $1
  -- A merged record is not a candidate: its survivor is the one to match
  -- against, and offering both would invite a second merge of the same pair.
  AND status <> 'merged'
  AND patient_id <> COALESCE($2::uuid,
                             '00000000-0000-0000-0000-000000000000'::uuid)
  AND (
        ($3::date IS NOT NULL AND birth_date = $3::date)
     OR ($4::text IS NOT NULL
         AND lower(family_name) LIKE $4::text || '%')
     OR ($5::text IS NOT NULL
         AND phones @> jsonb_build_array(jsonb_build_object('value', $5::text)))
  )
ORDER BY updated_at DESC, patient_id
LIMIT $6
`

type SearchPatientCandidatesParams struct {
	TenantID         uuid.UUID
	ExcludePatientID pgtype.UUID
	BirthDate        pgtype.Date
	FamilyPrefix     *string
	Phone            *string
	PageLimit        int32
}

// The blocking query for duplicate detection (SRS-EMPI-003, SRS-EMPI-004).
//
// Scoring every patient in the tenant against a new registration is O(tenant)
// per registration and unusable by the second week. This narrows to records
// that share at least one strong, indexable signal — a birth date, a surname
// prefix, a phone number — and the matcher scores only those.
//
// Blocking is allowed to miss: a duplicate whose surname, birth date and phone
// all differ is not findable by any index, and the merge workflow exists for
// what search does not catch.
func (q *Queries) SearchPatientCandidates(ctx context.Context, arg SearchPatientCandidatesParams) ([]EmpiPatient, error) {
	rows, err := q.db.Query(ctx, searchPatientCandidates,
		arg.TenantID,
		arg.ExcludePatientID,
		arg.BirthDate,
		arg.FamilyPrefix,
		arg.Phone,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmpiPatient{}
	for rows.Next() {
		var i EmpiPatient
		if err := rows.Scan(
			&i.PatientID,
			&i.TenantID,
			&i.RegisteredFacilityID,
			&i.Status,
			&i.FamilyName,
			&i.GivenNames,
			&i.NamePrefix,
			&i.NameSuffix,
			&i.BirthDate,
			&i.BirthDatePrecision,
			&i.Sex,
			&i.Phones,
			&i.Emails,
			&i.Addresses,
			&i.MergedIntoPatientID,
			&i.DeceasedDate,
			&i.DeceasedPrecision,
			&i.DeceasedSource,
			&i.DeceasedRecordedAt,
			&i.DeceasedRecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPatientDeceased = `-- name: SetPatientDeceased :execrows
UPDATE empi.patient
SET deceased_date = $1::date,
    deceased_precision = $2,
    deceased_source = $3,
    deceased_recorded_at = $4::timestamptz,
    deceased_recorded_by = $5,
    updated_at = $6,
    version = version + 1
WHERE tenant_id = $7 AND patient_id = $8
`

type SetPatientDeceasedParams struct {
	DeceasedDate       pgtype.Date
	DeceasedPrecision  string
	DeceasedSource     string
	DeceasedRecordedAt pgtype.Timestamptz
	DeceasedRecordedBy string
	UpdatedAt          pgtype.Timestamptz
	TenantID           uuid.UUID
	PatientID          uuid.UUID
}

func (q *Queries) SetPatientDeceased(ctx context.Context, arg SetPatientDeceasedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPatientDeceased,
		arg.DeceasedDate,
		arg.DeceasedPrecision,
		arg.DeceasedSource,
		arg.DeceasedRecordedAt,
		arg.DeceasedRecordedBy,
		arg.UpdatedAt,
		arg.TenantID,
		arg.PatientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPatientMergedInto = `-- name: SetPatientMergedInto :execrows
UPDATE empi.patient
SET status = $1,
    merged_into_patient_id = $2::uuid,
    updated_at = $3,
    version = version + 1
WHERE tenant_id = $4
  AND patient_id = $5
  AND version = $6
`

type SetPatientMergedIntoParams struct {
	Status              string
	MergedIntoPatientID pgtype.UUID
	UpdatedAt           pgtype.Timestamptz
	TenantID            uuid.UUID
	PatientID           uuid.UUID
	ExpectedVersion     int64
}

func (q *Queries) SetPatientMergedInto(ctx context.Context, arg SetPatientMergedIntoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPatientMergedInto,
		arg.Status,
		arg.MergedIntoPatientID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.PatientID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPatientStatus = `-- name: SetPatientStatus :execrows
UPDATE empi.patient
SET status = $1, updated_at = $2, version = version + 1
WHERE tenant_id = $3
  AND patient_id = $4
  AND version = $5
`

type SetPatientStatusParams struct {
	Status          string
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	PatientID       uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) SetPatientStatus(ctx context.Context, arg SetPatientStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPatientStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.PatientID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePatientDemographics = `-- name: UpdatePatientDemographics :execrows
UPDATE empi.patient
SET family_name = $1,
    given_names = $2,
    name_prefix = $3,
    name_suffix = $4,
    birth_date = $5::date,
    birth_date_precision = $6,
    sex = $7,
    phones = $8,
    emails = $9,
    addresses = $10,
    updated_at = $11,
    version = version + 1
WHERE tenant_id = $12
  AND patient_id = $13
  AND version = $14
  -- Correcting the losing side of a merge writes to a record nobody reads.
  AND status <> 'merged'
`

type UpdatePatientDemographicsParams struct {
	FamilyName         string
	GivenNames         []string
	NamePrefix         string
	NameSuffix         string
	BirthDate          pgtype.Date
	BirthDatePrecision string
	Sex                string
	Phones             []byte
	Emails             []byte
	Addresses          []byte
	UpdatedAt          pgtype.Timestamptz
	TenantID           uuid.UUID
	PatientID          uuid.UUID
	ExpectedVersion    int64
}

// Optimistic concurrency. Two clerks correcting one record at the same
// registration desk is routine, and last-write-wins silently discards one of
// their corrections.
func (q *Queries) UpdatePatientDemographics(ctx context.Context, arg UpdatePatientDemographicsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePatientDemographics,
		arg.FamilyName,
		arg.GivenNames,
		arg.NamePrefix,
		arg.NameSuffix,
		arg.BirthDate,
		arg.BirthDatePrecision,
		arg.Sex,
		arg.Phones,
		arg.Emails,
		arg.Addresses,
		arg.UpdatedAt,
		arg.TenantID,
		arg.PatientID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDemographicPolicy = `-- name: UpsertDemographicPolicy :exec
INSERT INTO empi.demographic_policy (
    policy_id, tenant_id, jurisdiction, facility_id,
    required_fields, allow_unidentified, created_at, updated_at
) VALUES (
    $1, $2, $3, $4::uuid,
    $5, $6, $7, $8
)
ON CONFLICT (tenant_id, jurisdiction,
             COALESCE(facility_id, '00000000-0000-0000-0000-000000000000'::uuid))
DO UPDATE SET
    required_fields = EXCLUDED.required_fields,
    allow_unidentified = EXCLUDED.allow_unidentified,
    updated_at = EXCLUDED.updated_at
`

type UpsertDemographicPolicyParams struct {
	PolicyID          uuid.UUID
	TenantID          uuid.UUID
	Jurisdiction      string
	FacilityID        pgtype.UUID
	RequiredFields    []string
	AllowUnidentified bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpsertDemographicPolicy(ctx context.Context, arg UpsertDemographicPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertDemographicPolicy,
		arg.PolicyID,
		arg.TenantID,
		arg.Jurisdiction,
		arg.FacilityID,
		arg.RequiredFields,
		arg.AllowUnidentified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertDuplicateCandidate = `-- name: UpsertDuplicateCandidate :exec
INSERT INTO empi.duplicate_candidate (
    candidate_id, tenant_id, patient_a_id, patient_b_id,
    score, outcome, status, detected_by, detected_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, 'open', $7, $8
)
ON CONFLICT (tenant_id, patient_a_id, patient_b_id) DO NOTHING
`

type UpsertDuplicateCandidateParams struct {
	CandidateID uuid.UUID
	TenantID    uuid.UUID
	PatientAID  uuid.UUID
	PatientBID  uuid.UUID
	Score       pgtype.Numeric
	Outcome     string
	DetectedBy  string
	DetectedAt  pgtype.Timestamptz
}

// Queues a pair for review, or leaves an existing decision alone.
//
// DO NOTHING rather than DO UPDATE on purpose: re-detecting a pair that was
// already dismissed must not reopen it. A decision already taken is not a new
// question, and reopening it would put the same pair in front of HIM every
// time either record is touched.
func (q *Queries) UpsertDuplicateCandidate(ctx context.Context, arg UpsertDuplicateCandidateParams) error {
	_, err := q.db.Exec(ctx, upsertDuplicateCandidate,
		arg.CandidateID,
		arg.TenantID,
		arg.PatientAID,
		arg.PatientBID,
		arg.Score,
		arg.Outcome,
		arg.DetectedBy,
		arg.DetectedAt,
	)
	return err
}

const upsertMatchConfig = `-- name: UpsertMatchConfig :exec
INSERT INTO empi.match_config (
    tenant_id, weights, review_threshold, probable_threshold, updated_at, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (tenant_id) DO UPDATE SET
    weights = EXCLUDED.weights,
    review_threshold = EXCLUDED.review_threshold,
    probable_threshold = EXCLUDED.probable_threshold,
    updated_at = EXCLUDED.updated_at,
    updated_by = EXCLUDED.updated_by
`

type UpsertMatchConfigParams struct {
	TenantID          uuid.UUID
	Weights           []byte
	ReviewThreshold   pgtype.Numeric
	ProbableThreshold pgtype.Numeric
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         string
}

func (q *Queries) UpsertMatchConfig(ctx context.Context, arg UpsertMatchConfigParams) error {
	_, err := q.db.Exec(ctx, upsertMatchConfig,
		arg.TenantID,
		arg.Weights,
		arg.ReviewThreshold,
		arg.ProbableThreshold,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
