// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: encounter.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const endCareTeamMember = `-- name: EndCareTeamMember :execrows
UPDATE encounter.care_team_member
SET effective_until = $1
WHERE tenant_id = $2
  AND care_team_id = $3
  AND effective_until IS NULL
  AND $1::timestamptz > effective_from
`

type EndCareTeamMemberParams struct {
	EffectiveUntil pgtype.Timestamptz
	TenantID       uuid.UUID
	CareTeamID     uuid.UUID
}

// Closes an involvement rather than deleting it: whether this clinician was
// looking after the patient last Tuesday is a question an investigation asks.
func (q *Queries) EndCareTeamMember(ctx context.Context, arg EndCareTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, endCareTeamMember, arg.EffectiveUntil, arg.TenantID, arg.CareTeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEncounter = `-- name: GetEncounter :one
SELECT encounter_id, tenant_id, facility_id, org_unit_id, patient_id, class,
       visit_type, attending_provider_id, appointment_id, episode_id, referral_id,
       reason, status, started_at, ended_at, closed_at,
       created_by, created_at, updated_at, version
FROM encounter.encounter
WHERE tenant_id = $1 AND encounter_id = $2
`

type GetEncounterParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

func (q *Queries) GetEncounter(ctx context.Context, arg GetEncounterParams) (EncounterEncounter, error) {
	row := q.db.QueryRow(ctx, getEncounter, arg.TenantID, arg.EncounterID)
	var i EncounterEncounter
	err := row.Scan(
		&i.EncounterID,
		&i.TenantID,
		&i.FacilityID,
		&i.OrgUnitID,
		&i.PatientID,
		&i.Class,
		&i.VisitType,
		&i.AttendingProviderID,
		&i.AppointmentID,
		&i.EpisodeID,
		&i.ReferralID,
		&i.Reason,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT episode_id, tenant_id, patient_id, facility_id, episode_type, label,
       care_manager_id, status, started_at, ended_at, created_by,
       created_at, updated_at, version
FROM encounter.episode
WHERE tenant_id = $1 AND episode_id = $2
`

type GetEpisodeParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) GetEpisode(ctx context.Context, arg GetEpisodeParams) (EncounterEpisode, error) {
	row := q.db.QueryRow(ctx, getEpisode, arg.TenantID, arg.EpisodeID)
	var i EncounterEpisode
	err := row.Scan(
		&i.EpisodeID,
		&i.TenantID,
		&i.PatientID,
		&i.FacilityID,
		&i.EpisodeType,
		&i.Label,
		&i.CareManagerID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertCareTeamMember = `-- name: InsertCareTeamMember :exec
INSERT INTO encounter.care_team_member (
    care_team_id, tenant_id, encounter_id, subject_id, role,
    effective_from, effective_until, assigned_by, assigned_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7::timestamptz,
    $8, $9
)
`

type InsertCareTeamMemberParams struct {
	CareTeamID     uuid.UUID
	TenantID       uuid.UUID
	EncounterID    uuid.UUID
	SubjectID      string
	Role           string
	EffectiveFrom  pgtype.Timestamptz
	EffectiveUntil pgtype.Timestamptz
	AssignedBy     string
	AssignedAt     pgtype.Timestamptz
}

func (q *Queries) InsertCareTeamMember(ctx context.Context, arg InsertCareTeamMemberParams) error {
	_, err := q.db.Exec(ctx, insertCareTeamMember,
		arg.CareTeamID,
		arg.TenantID,
		arg.EncounterID,
		arg.SubjectID,
		arg.Role,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.AssignedBy,
		arg.AssignedAt,
	)
	return err
}

const insertClosureOverride = `-- name: InsertClosureOverride :exec
INSERT INTO encounter.closure_override (
    override_id, tenant_id, encounter_id, missing_items, reason,
    overridden_by, overridden_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
`

type InsertClosureOverrideParams struct {
	OverrideID   uuid.UUID
	TenantID     uuid.UUID
	EncounterID  uuid.UUID
	MissingItems []string
	Reason       string
	OverriddenBy string
	OverriddenAt pgtype.Timestamptz
}

func (q *Queries) InsertClosureOverride(ctx context.Context, arg InsertClosureOverrideParams) error {
	_, err := q.db.Exec(ctx, insertClosureOverride,
		arg.OverrideID,
		arg.TenantID,
		arg.EncounterID,
		arg.MissingItems,
		arg.Reason,
		arg.OverriddenBy,
		arg.OverriddenAt,
	)
	return err
}

const insertDiagnosis = `-- name: InsertDiagnosis :exec
INSERT INTO encounter.encounter_diagnosis (
    diagnosis_id, tenant_id, encounter_id, patient_id, code_system,
    code_version, code, code_display, certainty, rank, note, onset_at,
    superseded_by_id, retracted_reason, recorded_by, recorded_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12::timestamptz, NULL, '', $13, $14
)
`

type InsertDiagnosisParams struct {
	DiagnosisID uuid.UUID
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	PatientID   uuid.UUID
	CodeSystem  string
	CodeVersion string
	Code        string
	CodeDisplay string
	Certainty   string
	Rank        string
	Note        string
	OnsetAt     pgtype.Timestamptz
	RecordedBy  string
	RecordedAt  pgtype.Timestamptz
}

func (q *Queries) InsertDiagnosis(ctx context.Context, arg InsertDiagnosisParams) error {
	_, err := q.db.Exec(ctx, insertDiagnosis,
		arg.DiagnosisID,
		arg.TenantID,
		arg.EncounterID,
		arg.PatientID,
		arg.CodeSystem,
		arg.CodeVersion,
		arg.Code,
		arg.CodeDisplay,
		arg.Certainty,
		arg.Rank,
		arg.Note,
		arg.OnsetAt,
		arg.RecordedBy,
		arg.RecordedAt,
	)
	return err
}

const insertEncounter = `-- name: InsertEncounter :exec
INSERT INTO encounter.encounter (
    encounter_id, tenant_id, facility_id, org_unit_id, patient_id, class,
    visit_type, attending_provider_id, appointment_id, episode_id, referral_id,
    reason, status, started_at, ended_at, closed_at,
    created_by, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4::uuid,
    $5, $6, $7, $8,
    $9::uuid, $10::uuid,
    $11, $12, $13,
    $14::timestamptz, $15::timestamptz,
    $16::timestamptz,
    $17, $18, $19, 1
)
`

type InsertEncounterParams struct {
	EncounterID         uuid.UUID
	TenantID            uuid.UUID
	FacilityID          uuid.UUID
	OrgUnitID           pgtype.UUID
	PatientID           uuid.UUID
	Class               string
	VisitType           string
	AttendingProviderID string
	AppointmentID       pgtype.UUID
	EpisodeID           pgtype.UUID
	ReferralID          string
	Reason              string
	Status              string
	StartedAt           pgtype.Timestamptz
	EndedAt             pgtype.Timestamptz
	ClosedAt            pgtype.Timestamptz
	CreatedBy           string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertEncounter(ctx context.Context, arg InsertEncounterParams) error {
	_, err := q.db.Exec(ctx, insertEncounter,
		arg.EncounterID,
		arg.TenantID,
		arg.FacilityID,
		arg.OrgUnitID,
		arg.PatientID,
		arg.Class,
		arg.VisitType,
		arg.AttendingProviderID,
		arg.AppointmentID,
		arg.EpisodeID,
		arg.ReferralID,
		arg.Reason,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.ClosedAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertEncounterStatusHistory = `-- name: InsertEncounterStatusHistory :exec
INSERT INTO encounter.encounter_status_history (
    history_id, tenant_id, encounter_id, from_status, to_status,
    changed_at, changed_by, reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
`

type InsertEncounterStatusHistoryParams struct {
	HistoryID   uuid.UUID
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	FromStatus  string
	ToStatus    string
	ChangedAt   pgtype.Timestamptz
	ChangedBy   string
	Reason      string
}

func (q *Queries) InsertEncounterStatusHistory(ctx context.Context, arg InsertEncounterStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertEncounterStatusHistory,
		arg.HistoryID,
		arg.TenantID,
		arg.EncounterID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedAt,
		arg.ChangedBy,
		arg.Reason,
	)
	return err
}

const insertEpisode = `-- name: InsertEpisode :exec

INSERT INTO encounter.episode (
    episode_id, tenant_id, patient_id, facility_id, episode_type, label,
    care_manager_id, status, started_at, ended_at, created_by,
    created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10::timestamptz,
    $11, $12, $13, 1
)
`

type InsertEpisodeParams struct {
	EpisodeID     uuid.UUID
	TenantID      uuid.UUID
	PatientID     uuid.UUID
	FacilityID    uuid.UUID
	EpisodeType   string
	Label         string
	CareManagerID string
	Status        string
	StartedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
	CreatedBy     string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Encounters, episodes, care teams and diagnoses (SRS-ENC).
func (q *Queries) InsertEpisode(ctx context.Context, arg InsertEpisodeParams) error {
	_, err := q.db.Exec(ctx, insertEpisode,
		arg.EpisodeID,
		arg.TenantID,
		arg.PatientID,
		arg.FacilityID,
		arg.EpisodeType,
		arg.Label,
		arg.CareManagerID,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVisitSummary = `-- name: InsertVisitSummary :exec
INSERT INTO encounter.visit_summary (
    summary_id, tenant_id, encounter_id, patient_id, version, supersedes_id,
    amendment_reason, encounter_class, started_at, ended_at, diagnoses,
    care_team, narrative, generated_by, generated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6::uuid, $7, $8,
    $9::timestamptz, $10::timestamptz,
    $11, $12, $13, $14, $15
)
`

type InsertVisitSummaryParams struct {
	SummaryID       uuid.UUID
	TenantID        uuid.UUID
	EncounterID     uuid.UUID
	PatientID       uuid.UUID
	Version         int32
	SupersedesID    pgtype.UUID
	AmendmentReason string
	EncounterClass  string
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	Diagnoses       []byte
	CareTeam        []string
	Narrative       string
	GeneratedBy     string
	GeneratedAt     pgtype.Timestamptz
}

func (q *Queries) InsertVisitSummary(ctx context.Context, arg InsertVisitSummaryParams) error {
	_, err := q.db.Exec(ctx, insertVisitSummary,
		arg.SummaryID,
		arg.TenantID,
		arg.EncounterID,
		arg.PatientID,
		arg.Version,
		arg.SupersedesID,
		arg.AmendmentReason,
		arg.EncounterClass,
		arg.StartedAt,
		arg.EndedAt,
		arg.Diagnoses,
		arg.CareTeam,
		arg.Narrative,
		arg.GeneratedBy,
		arg.GeneratedAt,
	)
	return err
}

const isOnCareTeamAt = `-- name: IsOnCareTeamAt :one
SELECT EXISTS (
    SELECT 1
    FROM encounter.care_team_member
    WHERE tenant_id = $1
      AND encounter_id = $2
      AND subject_id = $3
      AND effective_from <= $4::timestamptz
      AND (effective_until IS NULL OR effective_until > $4::timestamptz)
) AS on_team
`

type IsOnCareTeamAtParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	SubjectID   string
	At          pgtype.Timestamptz
}

// The authorization question, answered as of a time (SRS-ENC-005).
func (q *Queries) IsOnCareTeamAt(ctx context.Context, arg IsOnCareTeamAtParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOnCareTeamAt,
		arg.TenantID,
		arg.EncounterID,
		arg.SubjectID,
		arg.At,
	)
	var on_team bool
	err := row.Scan(&on_team)
	return on_team, err
}

const listCareTeam = `-- name: ListCareTeam :many
SELECT care_team_id, tenant_id, encounter_id, subject_id, role,
       effective_from, effective_until, assigned_by, assigned_at
FROM encounter.care_team_member
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY effective_from, care_team_id
`

type ListCareTeamParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

func (q *Queries) ListCareTeam(ctx context.Context, arg ListCareTeamParams) ([]EncounterCareTeamMember, error) {
	rows, err := q.db.Query(ctx, listCareTeam, arg.TenantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterCareTeamMember{}
	for rows.Next() {
		var i EncounterCareTeamMember
		if err := rows.Scan(
			&i.CareTeamID,
			&i.TenantID,
			&i.EncounterID,
			&i.SubjectID,
			&i.Role,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosureOverrides = `-- name: ListClosureOverrides :many
SELECT override_id, tenant_id, encounter_id, missing_items, reason,
       overridden_by, overridden_at
FROM encounter.closure_override
WHERE tenant_id = $1
  AND ($2::uuid IS NULL
       OR encounter_id = $2::uuid)
ORDER BY overridden_at DESC, override_id
LIMIT $3
`

type ListClosureOverridesParams struct {
	TenantID    uuid.UUID
	EncounterID pgtype.UUID
	PageLimit   int32
}

func (q *Queries) ListClosureOverrides(ctx context.Context, arg ListClosureOverridesParams) ([]EncounterClosureOverride, error) {
	rows, err := q.db.Query(ctx, listClosureOverrides, arg.TenantID, arg.EncounterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterClosureOverride{}
	for rows.Next() {
		var i EncounterClosureOverride
		if err := rows.Scan(
			&i.OverrideID,
			&i.TenantID,
			&i.EncounterID,
			&i.MissingItems,
			&i.Reason,
			&i.OverriddenBy,
			&i.OverriddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosurePolicy = `-- name: ListClosurePolicy :many
SELECT encounter_class, required_items, allow_override, facility_id
FROM encounter.closure_policy
WHERE tenant_id = $1
  AND (facility_id IS NULL OR facility_id = $2::uuid)
ORDER BY (facility_id IS NULL), encounter_class
`

type ListClosurePolicyParams struct {
	TenantID   uuid.UUID
	FacilityID pgtype.UUID
}

type ListClosurePolicyRow struct {
	EncounterClass string
	RequiredItems  []string
	AllowOverride  bool
	FacilityID     pgtype.UUID
}

// Facility-specific rows first, so the resolver takes the first it sees for
// each class.
func (q *Queries) ListClosurePolicy(ctx context.Context, arg ListClosurePolicyParams) ([]ListClosurePolicyRow, error) {
	rows, err := q.db.Query(ctx, listClosurePolicy, arg.TenantID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClosurePolicyRow{}
	for rows.Next() {
		var i ListClosurePolicyRow
		if err := rows.Scan(
			&i.EncounterClass,
			&i.RequiredItems,
			&i.AllowOverride,
			&i.FacilityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiagnosesForEncounter = `-- name: ListDiagnosesForEncounter :many
SELECT diagnosis_id, tenant_id, encounter_id, patient_id, code_system,
       code_version, code, code_display, certainty, rank, note, onset_at,
       superseded_by_id, retracted_reason, recorded_by, recorded_at
FROM encounter.encounter_diagnosis
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY recorded_at, diagnosis_id
`

type ListDiagnosesForEncounterParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

func (q *Queries) ListDiagnosesForEncounter(ctx context.Context, arg ListDiagnosesForEncounterParams) ([]EncounterEncounterDiagnosis, error) {
	rows, err := q.db.Query(ctx, listDiagnosesForEncounter, arg.TenantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterEncounterDiagnosis{}
	for rows.Next() {
		var i EncounterEncounterDiagnosis
		if err := rows.Scan(
			&i.DiagnosisID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.CodeSystem,
			&i.CodeVersion,
			&i.Code,
			&i.CodeDisplay,
			&i.Certainty,
			&i.Rank,
			&i.Note,
			&i.OnsetAt,
			&i.SupersededByID,
			&i.RetractedReason,
			&i.RecordedBy,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounterStatusHistory = `-- name: ListEncounterStatusHistory :many
SELECT from_status, to_status, changed_at, changed_by, reason
FROM encounter.encounter_status_history
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY changed_at, history_id
`

type ListEncounterStatusHistoryParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

type ListEncounterStatusHistoryRow struct {
	FromStatus string
	ToStatus   string
	ChangedAt  pgtype.Timestamptz
	ChangedBy  string
	Reason     string
}

func (q *Queries) ListEncounterStatusHistory(ctx context.Context, arg ListEncounterStatusHistoryParams) ([]ListEncounterStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listEncounterStatusHistory, arg.TenantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEncounterStatusHistoryRow{}
	for rows.Next() {
		var i ListEncounterStatusHistoryRow
		if err := rows.Scan(
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPatient = `-- name: ListEncountersForPatient :many
SELECT encounter_id, tenant_id, facility_id, org_unit_id, patient_id, class,
       visit_type, attending_provider_id, appointment_id, episode_id, referral_id,
       reason, status, started_at, ended_at, closed_at,
       created_by, created_at, updated_at, version
FROM encounter.encounter
WHERE tenant_id = $1
  AND patient_id = $2
  AND ($3::uuid IS NULL OR episode_id = $3::uuid)
  AND ($4::text = '' OR class = $4::text)
  AND ($5::boolean = true OR status <> 'entered_in_error')
ORDER BY COALESCE(started_at, created_at) DESC, encounter_id
LIMIT $6
`

type ListEncountersForPatientParams struct {
	TenantID         uuid.UUID
	PatientID        uuid.UUID
	EpisodeID        pgtype.UUID
	ClassFilter      string
	IncludeRetracted bool
	PageLimit        int32
}

// The patient's chronology, newest first, which is how a chart is read.
func (q *Queries) ListEncountersForPatient(ctx context.Context, arg ListEncountersForPatientParams) ([]EncounterEncounter, error) {
	rows, err := q.db.Query(ctx, listEncountersForPatient,
		arg.TenantID,
		arg.PatientID,
		arg.EpisodeID,
		arg.ClassFilter,
		arg.IncludeRetracted,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterEncounter{}
	for rows.Next() {
		var i EncounterEncounter
		if err := rows.Scan(
			&i.EncounterID,
			&i.TenantID,
			&i.FacilityID,
			&i.OrgUnitID,
			&i.PatientID,
			&i.Class,
			&i.VisitType,
			&i.AttendingProviderID,
			&i.AppointmentID,
			&i.EpisodeID,
			&i.ReferralID,
			&i.Reason,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.ClosedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesForPatient = `-- name: ListEpisodesForPatient :many
SELECT episode_id, tenant_id, patient_id, facility_id, episode_type, label,
       care_manager_id, status, started_at, ended_at, created_by,
       created_at, updated_at, version
FROM encounter.episode
WHERE tenant_id = $1
  AND patient_id = $2
  AND ($3::boolean = false OR status IN ('active', 'on_hold'))
ORDER BY started_at DESC, episode_id
LIMIT $4
`

type ListEpisodesForPatientParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	OpenOnly  bool
	PageLimit int32
}

func (q *Queries) ListEpisodesForPatient(ctx context.Context, arg ListEpisodesForPatientParams) ([]EncounterEpisode, error) {
	rows, err := q.db.Query(ctx, listEpisodesForPatient,
		arg.TenantID,
		arg.PatientID,
		arg.OpenOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterEpisode{}
	for rows.Next() {
		var i EncounterEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.PatientID,
			&i.FacilityID,
			&i.EpisodeType,
			&i.Label,
			&i.CareManagerID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveDiagnosesForPatient = `-- name: ListLiveDiagnosesForPatient :many
SELECT diagnosis_id, tenant_id, encounter_id, patient_id, code_system,
       code_version, code, code_display, certainty, rank, note, onset_at,
       superseded_by_id, retracted_reason, recorded_by, recorded_at
FROM encounter.encounter_diagnosis
WHERE tenant_id = $1
  AND patient_id = $2
  AND superseded_by_id IS NULL
  AND retracted_reason = ''
ORDER BY recorded_at DESC, diagnosis_id
LIMIT $3
`

type ListLiveDiagnosesForPatientParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	PageLimit int32
}

// What a problem list and a discharge summary both read.
func (q *Queries) ListLiveDiagnosesForPatient(ctx context.Context, arg ListLiveDiagnosesForPatientParams) ([]EncounterEncounterDiagnosis, error) {
	rows, err := q.db.Query(ctx, listLiveDiagnosesForPatient, arg.TenantID, arg.PatientID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterEncounterDiagnosis{}
	for rows.Next() {
		var i EncounterEncounterDiagnosis
		if err := rows.Scan(
			&i.DiagnosisID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.CodeSystem,
			&i.CodeVersion,
			&i.Code,
			&i.CodeDisplay,
			&i.Certainty,
			&i.Rank,
			&i.Note,
			&i.OnsetAt,
			&i.SupersededByID,
			&i.RetractedReason,
			&i.RecordedBy,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenEncounters = `-- name: ListOpenEncounters :many
SELECT encounter_id, tenant_id, facility_id, org_unit_id, patient_id, class,
       visit_type, attending_provider_id, appointment_id, episode_id, referral_id,
       reason, status, started_at, ended_at, closed_at,
       created_by, created_at, updated_at, version
FROM encounter.encounter
WHERE tenant_id = $1
  AND facility_id = $2
  AND status IN ('planned', 'in_progress', 'on_leave')
  AND ($3::text = '' OR class = $3::text)
ORDER BY COALESCE(started_at, created_at), encounter_id
LIMIT $4
`

type ListOpenEncountersParams struct {
	TenantID    uuid.UUID
	FacilityID  uuid.UUID
	ClassFilter string
	PageLimit   int32
}

// The ward round: who is here now.
func (q *Queries) ListOpenEncounters(ctx context.Context, arg ListOpenEncountersParams) ([]EncounterEncounter, error) {
	rows, err := q.db.Query(ctx, listOpenEncounters,
		arg.TenantID,
		arg.FacilityID,
		arg.ClassFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterEncounter{}
	for rows.Next() {
		var i EncounterEncounter
		if err := rows.Scan(
			&i.EncounterID,
			&i.TenantID,
			&i.FacilityID,
			&i.OrgUnitID,
			&i.PatientID,
			&i.Class,
			&i.VisitType,
			&i.AttendingProviderID,
			&i.AppointmentID,
			&i.EpisodeID,
			&i.ReferralID,
			&i.Reason,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.ClosedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitSummaries = `-- name: ListVisitSummaries :many
SELECT summary_id, tenant_id, encounter_id, patient_id, version, supersedes_id,
       amendment_reason, encounter_class, started_at, ended_at, diagnoses,
       care_team, narrative, generated_by, generated_at
FROM encounter.visit_summary
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY version DESC
`

type ListVisitSummariesParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

// Every version, newest first. The superseded ones stay readable: somebody
// acted on them.
func (q *Queries) ListVisitSummaries(ctx context.Context, arg ListVisitSummariesParams) ([]EncounterVisitSummary, error) {
	rows, err := q.db.Query(ctx, listVisitSummaries, arg.TenantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EncounterVisitSummary{}
	for rows.Next() {
		var i EncounterVisitSummary
		if err := rows.Scan(
			&i.SummaryID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.Version,
			&i.SupersedesID,
			&i.AmendmentReason,
			&i.EncounterClass,
			&i.StartedAt,
			&i.EndedAt,
			&i.Diagnoses,
			&i.CareTeam,
			&i.Narrative,
			&i.GeneratedBy,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retractDiagnosis = `-- name: RetractDiagnosis :execrows
UPDATE encounter.encounter_diagnosis
SET retracted_reason = $1
WHERE tenant_id = $2
  AND diagnosis_id = $3
  AND superseded_by_id IS NULL
  AND retracted_reason = ''
`

type RetractDiagnosisParams struct {
	RetractedReason string
	TenantID        uuid.UUID
	DiagnosisID     uuid.UUID
}

func (q *Queries) RetractDiagnosis(ctx context.Context, arg RetractDiagnosisParams) (int64, error) {
	result, err := q.db.Exec(ctx, retractDiagnosis, arg.RetractedReason, arg.TenantID, arg.DiagnosisID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEncounterState = `-- name: SetEncounterState :execrows
UPDATE encounter.encounter
SET status = $1,
    started_at = $2::timestamptz,
    ended_at = $3::timestamptz,
    closed_at = $4::timestamptz,
    attending_provider_id = $5,
    updated_at = $6,
    version = version + 1
WHERE tenant_id = $7
  AND encounter_id = $8
  AND version = $9
`

type SetEncounterStateParams struct {
	Status              string
	StartedAt           pgtype.Timestamptz
	EndedAt             pgtype.Timestamptz
	ClosedAt            pgtype.Timestamptz
	AttendingProviderID string
	UpdatedAt           pgtype.Timestamptz
	TenantID            uuid.UUID
	EncounterID         uuid.UUID
	ExpectedVersion     int64
}

// Writes a status change under optimistic concurrency (SRS-ENC-006).
//
// The times move with the status because they always change together: an
// encounter becomes in_progress exactly when it starts. Two statements would be
// two chances to commit half of it.
func (q *Queries) SetEncounterState(ctx context.Context, arg SetEncounterStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEncounterState,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.ClosedAt,
		arg.AttendingProviderID,
		arg.UpdatedAt,
		arg.TenantID,
		arg.EncounterID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEpisodeStatus = `-- name: SetEpisodeStatus :execrows
UPDATE encounter.episode
SET status = $1,
    ended_at = $2::timestamptz,
    updated_at = $3,
    version = version + 1
WHERE tenant_id = $4
  AND episode_id = $5
  AND version = $6
`

type SetEpisodeStatusParams struct {
	Status          string
	EndedAt         pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	EpisodeID       uuid.UUID
	ExpectedVersion int64
}

// Guarded on the version read, so two clinicians closing a course of care at
// once do not both believe they did it.
func (q *Queries) SetEpisodeStatus(ctx context.Context, arg SetEpisodeStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEpisodeStatus,
		arg.Status,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.EpisodeID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeDiagnosis = `-- name: SupersedeDiagnosis :execrows
UPDATE encounter.encounter_diagnosis
SET superseded_by_id = $1
WHERE tenant_id = $2
  AND diagnosis_id = $3
  AND superseded_by_id IS NULL
  AND retracted_reason = ''
`

type SupersedeDiagnosisParams struct {
	SupersededByID pgtype.UUID
	TenantID       uuid.UUID
	DiagnosisID    uuid.UUID
}

// A change of mind is a new row that supersedes the old one, never an edit.
//
// Guarded on still being live, so two clinicians revising the same diagnosis at
// once produce one chain rather than a fork nobody can read.
func (q *Queries) SupersedeDiagnosis(ctx context.Context, arg SupersedeDiagnosisParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeDiagnosis, arg.SupersededByID, arg.TenantID, arg.DiagnosisID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertClosurePolicy = `-- name: UpsertClosurePolicy :exec
INSERT INTO encounter.closure_policy (
    policy_id, tenant_id, facility_id, encounter_class, required_items,
    allow_override, created_at, updated_at
) VALUES (
    $1, $2, $3::uuid, $4,
    $5, $6, $7, $8
)
ON CONFLICT (tenant_id,
             COALESCE(facility_id, '00000000-0000-0000-0000-000000000000'::uuid),
             encounter_class)
DO UPDATE SET required_items = EXCLUDED.required_items,
              allow_override = EXCLUDED.allow_override,
              updated_at = EXCLUDED.updated_at
`

type UpsertClosurePolicyParams struct {
	PolicyID       uuid.UUID
	TenantID       uuid.UUID
	FacilityID     pgtype.UUID
	EncounterClass string
	RequiredItems  []string
	AllowOverride  bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertClosurePolicy(ctx context.Context, arg UpsertClosurePolicyParams) error {
	_, err := q.db.Exec(ctx, upsertClosurePolicy,
		arg.PolicyID,
		arg.TenantID,
		arg.FacilityID,
		arg.EncounterClass,
		arg.RequiredItems,
		arg.AllowOverride,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
