// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: icu.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideIcuObservation = `-- name: DecideIcuObservation :execrows
UPDATE icu.observation
SET validation = $1,
    validated_by = $2,
    validated_at = $3,
    validation_note = $4
WHERE tenant_id = $5
  AND observation_id = $6
  AND validation = 'pending'
`

type DecideIcuObservationParams struct {
	Validation     string
	ValidatedBy    string
	ValidatedAt    pgtype.Timestamptz
	ValidationNote string
	TenantID       uuid.UUID
	ObservationID  uuid.UUID
}

// Confirming or rejecting a device reading. The reading itself is never
// changed: a rejected artefact that vanished would leave a gap in the trend
// and no sign that anybody looked.
func (q *Queries) DecideIcuObservation(ctx context.Context, arg DecideIcuObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideIcuObservation,
		arg.Validation,
		arg.ValidatedBy,
		arg.ValidatedAt,
		arg.ValidationNote,
		arg.TenantID,
		arg.ObservationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIcuEpisode = `-- name: GetIcuEpisode :one
SELECT episode_id, tenant_id, encounter_id, patient_id, facility_id, unit_id, bed_id, source, transferred_from, responsible_team, responsible_clinician, status, admitted_at, ready_at, discharged_at, outcome, outcome_note, created_by, created_at, updated_at, version FROM icu.episode
WHERE tenant_id = $1 AND episode_id = $2
`

type GetIcuEpisodeParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) GetIcuEpisode(ctx context.Context, arg GetIcuEpisodeParams) (IcuEpisode, error) {
	row := q.db.QueryRow(ctx, getIcuEpisode, arg.TenantID, arg.EpisodeID)
	var i IcuEpisode
	err := row.Scan(
		&i.EpisodeID,
		&i.TenantID,
		&i.EncounterID,
		&i.PatientID,
		&i.FacilityID,
		&i.UnitID,
		&i.BedID,
		&i.Source,
		&i.TransferredFrom,
		&i.ResponsibleTeam,
		&i.ResponsibleClinician,
		&i.Status,
		&i.AdmittedAt,
		&i.ReadyAt,
		&i.DischargedAt,
		&i.Outcome,
		&i.OutcomeNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getIcuInfusion = `-- name: GetIcuInfusion :one
SELECT infusion_id, tenant_id, episode_id, prescription_id, drug_code, drug_display, concentration_amount, concentration_unit, concentration_volume, dose_unit, weight_kg, started_at, started_by, stopped_at, stopped_by FROM icu.infusion
WHERE tenant_id = $1 AND infusion_id = $2
`

type GetIcuInfusionParams struct {
	TenantID   uuid.UUID
	InfusionID uuid.UUID
}

func (q *Queries) GetIcuInfusion(ctx context.Context, arg GetIcuInfusionParams) (IcuInfusion, error) {
	row := q.db.QueryRow(ctx, getIcuInfusion, arg.TenantID, arg.InfusionID)
	var i IcuInfusion
	err := row.Scan(
		&i.InfusionID,
		&i.TenantID,
		&i.EpisodeID,
		&i.PrescriptionID,
		&i.DrugCode,
		&i.DrugDisplay,
		&i.ConcentrationAmount,
		&i.ConcentrationUnit,
		&i.ConcentrationVolume,
		&i.DoseUnit,
		&i.WeightKg,
		&i.StartedAt,
		&i.StartedBy,
		&i.StoppedAt,
		&i.StoppedBy,
	)
	return i, err
}

const getIcuObservation = `-- name: GetIcuObservation :one
SELECT observation_id, tenant_id, episode_id, code_system, code, display, dimension, value, unit, raw_value, raw_unit, normalised, source, validation, device_id, device_model, device_channel, device_measured_at, device_quality, observed_at, recorded_at, recorded_by, validated_by, validated_at, validation_note FROM icu.observation
WHERE tenant_id = $1 AND observation_id = $2
`

type GetIcuObservationParams struct {
	TenantID      uuid.UUID
	ObservationID uuid.UUID
}

func (q *Queries) GetIcuObservation(ctx context.Context, arg GetIcuObservationParams) (IcuObservation, error) {
	row := q.db.QueryRow(ctx, getIcuObservation, arg.TenantID, arg.ObservationID)
	var i IcuObservation
	err := row.Scan(
		&i.ObservationID,
		&i.TenantID,
		&i.EpisodeID,
		&i.CodeSystem,
		&i.Code,
		&i.Display,
		&i.Dimension,
		&i.Value,
		&i.Unit,
		&i.RawValue,
		&i.RawUnit,
		&i.Normalised,
		&i.Source,
		&i.Validation,
		&i.DeviceID,
		&i.DeviceModel,
		&i.DeviceChannel,
		&i.DeviceMeasuredAt,
		&i.DeviceQuality,
		&i.ObservedAt,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.ValidatedBy,
		&i.ValidatedAt,
		&i.ValidationNote,
	)
	return i, err
}

const insertIcuAssessment = `-- name: InsertIcuAssessment :exec
INSERT INTO icu.assessment (
    assessment_id, tenant_id, episode_id, kind, scale, score,
    findings, note, performed_at, performed_by, next_due_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6::integer, $7, $8,
    $9, $10, $11
)
`

type InsertIcuAssessmentParams struct {
	AssessmentID uuid.UUID
	TenantID     uuid.UUID
	EpisodeID    uuid.UUID
	Kind         string
	Scale        string
	Score        *int32
	Findings     []byte
	Note         string
	PerformedAt  pgtype.Timestamptz
	PerformedBy  string
	NextDueAt    pgtype.Timestamptz
}

func (q *Queries) InsertIcuAssessment(ctx context.Context, arg InsertIcuAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertIcuAssessment,
		arg.AssessmentID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Kind,
		arg.Scale,
		arg.Score,
		arg.Findings,
		arg.Note,
		arg.PerformedAt,
		arg.PerformedBy,
		arg.NextDueAt,
	)
	return err
}

const insertIcuBalanceEntry = `-- name: InsertIcuBalanceEntry :exec
INSERT INTO icu.balance_entry (
    entry_id, tenant_id, episode_id, direction, route, volume_ml,
    occurred_at, recorded_at, recorded_by, corrects, correction_reason
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10::uuid, $11
)
`

type InsertIcuBalanceEntryParams struct {
	EntryID          uuid.UUID
	TenantID         uuid.UUID
	EpisodeID        uuid.UUID
	Direction        string
	Route            string
	VolumeMl         float64
	OccurredAt       pgtype.Timestamptz
	RecordedAt       pgtype.Timestamptz
	RecordedBy       string
	Corrects         pgtype.UUID
	CorrectionReason string
}

func (q *Queries) InsertIcuBalanceEntry(ctx context.Context, arg InsertIcuBalanceEntryParams) error {
	_, err := q.db.Exec(ctx, insertIcuBalanceEntry,
		arg.EntryID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Direction,
		arg.Route,
		arg.VolumeMl,
		arg.OccurredAt,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.Corrects,
		arg.CorrectionReason,
	)
	return err
}

const insertIcuBundlePerformance = `-- name: InsertIcuBundlePerformance :exec
INSERT INTO icu.bundle_performance (
    performance_id, tenant_id, episode_id, kind, label, version,
    performed_at, performed_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
`

type InsertIcuBundlePerformanceParams struct {
	PerformanceID uuid.UUID
	TenantID      uuid.UUID
	EpisodeID     uuid.UUID
	Kind          string
	Label         string
	Version       string
	PerformedAt   pgtype.Timestamptz
	PerformedBy   string
}

func (q *Queries) InsertIcuBundlePerformance(ctx context.Context, arg InsertIcuBundlePerformanceParams) error {
	_, err := q.db.Exec(ctx, insertIcuBundlePerformance,
		arg.PerformanceID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Kind,
		arg.Label,
		arg.Version,
		arg.PerformedAt,
		arg.PerformedBy,
	)
	return err
}

const insertIcuBundleResult = `-- name: InsertIcuBundleResult :exec
INSERT INTO icu.bundle_result (performance_id, code, state, reason)
VALUES ($1, $2, $3, $4)
`

type InsertIcuBundleResultParams struct {
	PerformanceID uuid.UUID
	Code          string
	State         string
	Reason        string
}

func (q *Queries) InsertIcuBundleResult(ctx context.Context, arg InsertIcuBundleResultParams) error {
	_, err := q.db.Exec(ctx, insertIcuBundleResult,
		arg.PerformanceID,
		arg.Code,
		arg.State,
		arg.Reason,
	)
	return err
}

const insertIcuDevice = `-- name: InsertIcuDevice :exec
INSERT INTO icu.invasive_device (
    device_id, tenant_id, episode_id, kind, site, lumens,
    inserted_at, inserted_by, review_every_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
`

type InsertIcuDeviceParams struct {
	DeviceID           uuid.UUID
	TenantID           uuid.UUID
	EpisodeID          uuid.UUID
	Kind               string
	Site               string
	Lumens             int32
	InsertedAt         pgtype.Timestamptz
	InsertedBy         string
	ReviewEverySeconds int64
}

func (q *Queries) InsertIcuDevice(ctx context.Context, arg InsertIcuDeviceParams) error {
	_, err := q.db.Exec(ctx, insertIcuDevice,
		arg.DeviceID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Kind,
		arg.Site,
		arg.Lumens,
		arg.InsertedAt,
		arg.InsertedBy,
		arg.ReviewEverySeconds,
	)
	return err
}

const insertIcuEpisode = `-- name: InsertIcuEpisode :exec

INSERT INTO icu.episode (
    episode_id, tenant_id, encounter_id, patient_id, facility_id,
    unit_id, bed_id, source, transferred_from,
    responsible_team, responsible_clinician, status, admitted_at,
    created_by, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9::uuid,
    $10, $11, $12, $13,
    $14, $15, $16, 1
)
`

type InsertIcuEpisodeParams struct {
	EpisodeID            uuid.UUID
	TenantID             uuid.UUID
	EncounterID          uuid.UUID
	PatientID            uuid.UUID
	FacilityID           string
	UnitID               string
	BedID                string
	Source               string
	TransferredFrom      pgtype.UUID
	ResponsibleTeam      string
	ResponsibleClinician string
	Status               string
	AdmittedAt           pgtype.Timestamptz
	CreatedBy            string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

// Critical care (SRS-ICU).
func (q *Queries) InsertIcuEpisode(ctx context.Context, arg InsertIcuEpisodeParams) error {
	_, err := q.db.Exec(ctx, insertIcuEpisode,
		arg.EpisodeID,
		arg.TenantID,
		arg.EncounterID,
		arg.PatientID,
		arg.FacilityID,
		arg.UnitID,
		arg.BedID,
		arg.Source,
		arg.TransferredFrom,
		arg.ResponsibleTeam,
		arg.ResponsibleClinician,
		arg.Status,
		arg.AdmittedAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertIcuGoal = `-- name: InsertIcuGoal :exec
INSERT INTO icu.goal (
    goal_id, tenant_id, episode_id, round_id, domain, text,
    owner_role, owner_id, status, target_at, created_by, created_at
) VALUES (
    $1, $2, $3, $4::uuid,
    $5, $6, $7, $8, $9,
    $10::timestamptz, $11, $12
)
`

type InsertIcuGoalParams struct {
	GoalID    uuid.UUID
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	RoundID   pgtype.UUID
	Domain    string
	Text      string
	OwnerRole string
	OwnerID   string
	Status    string
	TargetAt  pgtype.Timestamptz
	CreatedBy string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertIcuGoal(ctx context.Context, arg InsertIcuGoalParams) error {
	_, err := q.db.Exec(ctx, insertIcuGoal,
		arg.GoalID,
		arg.TenantID,
		arg.EpisodeID,
		arg.RoundID,
		arg.Domain,
		arg.Text,
		arg.OwnerRole,
		arg.OwnerID,
		arg.Status,
		arg.TargetAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertIcuGoalsOfCare = `-- name: InsertIcuGoalsOfCare :exec
INSERT INTO icu.goals_of_care (
    goals_of_care_id, tenant_id, episode_id, intent, limitations, cpr_status,
    discussed_with, rationale, authorised_by, authorised_role,
    recorded_at, recorded_by, review_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13::timestamptz
)
`

type InsertIcuGoalsOfCareParams struct {
	GoalsOfCareID  uuid.UUID
	TenantID       uuid.UUID
	EpisodeID      uuid.UUID
	Intent         string
	Limitations    []string
	CprStatus      string
	DiscussedWith  string
	Rationale      string
	AuthorisedBy   string
	AuthorisedRole string
	RecordedAt     pgtype.Timestamptz
	RecordedBy     string
	ReviewBy       pgtype.Timestamptz
}

func (q *Queries) InsertIcuGoalsOfCare(ctx context.Context, arg InsertIcuGoalsOfCareParams) error {
	_, err := q.db.Exec(ctx, insertIcuGoalsOfCare,
		arg.GoalsOfCareID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Intent,
		arg.Limitations,
		arg.CprStatus,
		arg.DiscussedWith,
		arg.Rationale,
		arg.AuthorisedBy,
		arg.AuthorisedRole,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.ReviewBy,
	)
	return err
}

const insertIcuInfusion = `-- name: InsertIcuInfusion :exec
INSERT INTO icu.infusion (
    infusion_id, tenant_id, episode_id, prescription_id,
    drug_code, drug_display,
    concentration_amount, concentration_unit, concentration_volume,
    dose_unit, weight_kg, started_at, started_by
) VALUES (
    $1, $2, $3, $4::uuid,
    $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13
)
`

type InsertIcuInfusionParams struct {
	InfusionID          uuid.UUID
	TenantID            uuid.UUID
	EpisodeID           uuid.UUID
	PrescriptionID      pgtype.UUID
	DrugCode            string
	DrugDisplay         string
	ConcentrationAmount float64
	ConcentrationUnit   string
	ConcentrationVolume float64
	DoseUnit            string
	WeightKg            float64
	StartedAt           pgtype.Timestamptz
	StartedBy           string
}

func (q *Queries) InsertIcuInfusion(ctx context.Context, arg InsertIcuInfusionParams) error {
	_, err := q.db.Exec(ctx, insertIcuInfusion,
		arg.InfusionID,
		arg.TenantID,
		arg.EpisodeID,
		arg.PrescriptionID,
		arg.DrugCode,
		arg.DrugDisplay,
		arg.ConcentrationAmount,
		arg.ConcentrationUnit,
		arg.ConcentrationVolume,
		arg.DoseUnit,
		arg.WeightKg,
		arg.StartedAt,
		arg.StartedBy,
	)
	return err
}

const insertIcuObservation = `-- name: InsertIcuObservation :exec
INSERT INTO icu.observation (
    observation_id, tenant_id, episode_id,
    code_system, code, display, dimension,
    value, unit, raw_value, raw_unit, normalised,
    source, validation,
    device_id, device_model, device_channel, device_measured_at, device_quality,
    observed_at, recorded_at, recorded_by
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14,
    $15, $16, $17,
    $18::timestamptz, $19,
    $20, $21, $22
)
`

type InsertIcuObservationParams struct {
	ObservationID    uuid.UUID
	TenantID         uuid.UUID
	EpisodeID        uuid.UUID
	CodeSystem       string
	Code             string
	Display          string
	Dimension        string
	Value            float64
	Unit             string
	RawValue         float64
	RawUnit          string
	Normalised       bool
	Source           string
	Validation       string
	DeviceID         string
	DeviceModel      string
	DeviceChannel    string
	DeviceMeasuredAt pgtype.Timestamptz
	DeviceQuality    string
	ObservedAt       pgtype.Timestamptz
	RecordedAt       pgtype.Timestamptz
	RecordedBy       string
}

func (q *Queries) InsertIcuObservation(ctx context.Context, arg InsertIcuObservationParams) error {
	_, err := q.db.Exec(ctx, insertIcuObservation,
		arg.ObservationID,
		arg.TenantID,
		arg.EpisodeID,
		arg.CodeSystem,
		arg.Code,
		arg.Display,
		arg.Dimension,
		arg.Value,
		arg.Unit,
		arg.RawValue,
		arg.RawUnit,
		arg.Normalised,
		arg.Source,
		arg.Validation,
		arg.DeviceID,
		arg.DeviceModel,
		arg.DeviceChannel,
		arg.DeviceMeasuredAt,
		arg.DeviceQuality,
		arg.ObservedAt,
		arg.RecordedAt,
		arg.RecordedBy,
	)
	return err
}

const insertIcuRound = `-- name: InsertIcuRound :exec
INSERT INTO icu.round (
    round_id, tenant_id, episode_id, attendance, summary,
    performed_at, performed_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
`

type InsertIcuRoundParams struct {
	RoundID     uuid.UUID
	TenantID    uuid.UUID
	EpisodeID   uuid.UUID
	Attendance  []string
	Summary     string
	PerformedAt pgtype.Timestamptz
	PerformedBy string
}

func (q *Queries) InsertIcuRound(ctx context.Context, arg InsertIcuRoundParams) error {
	_, err := q.db.Exec(ctx, insertIcuRound,
		arg.RoundID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Attendance,
		arg.Summary,
		arg.PerformedAt,
		arg.PerformedBy,
	)
	return err
}

const insertIcuScore = `-- name: InsertIcuScore :exec
INSERT INTO icu.score (
    score_id, tenant_id, episode_id, name, formula_version,
    total, missing, calculated_at, calculated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertIcuScoreParams struct {
	ScoreID        uuid.UUID
	TenantID       uuid.UUID
	EpisodeID      uuid.UUID
	Name           string
	FormulaVersion string
	Total          int32
	Missing        []string
	CalculatedAt   pgtype.Timestamptz
	CalculatedBy   string
}

func (q *Queries) InsertIcuScore(ctx context.Context, arg InsertIcuScoreParams) error {
	_, err := q.db.Exec(ctx, insertIcuScore,
		arg.ScoreID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Name,
		arg.FormulaVersion,
		arg.Total,
		arg.Missing,
		arg.CalculatedAt,
		arg.CalculatedBy,
	)
	return err
}

const insertIcuScoreInput = `-- name: InsertIcuScoreInput :exec
INSERT INTO icu.score_input (
    score_id, code, observation_id, value, unit, observed_at, points
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertIcuScoreInputParams struct {
	ScoreID       uuid.UUID
	Code          string
	ObservationID uuid.UUID
	Value         float64
	Unit          string
	ObservedAt    pgtype.Timestamptz
	Points        int32
}

func (q *Queries) InsertIcuScoreInput(ctx context.Context, arg InsertIcuScoreInputParams) error {
	_, err := q.db.Exec(ctx, insertIcuScoreInput,
		arg.ScoreID,
		arg.Code,
		arg.ObservationID,
		arg.Value,
		arg.Unit,
		arg.ObservedAt,
		arg.Points,
	)
	return err
}

const insertIcuSupport = `-- name: InsertIcuSupport :exec
INSERT INTO icu.support (
    support_id, tenant_id, episode_id, kind, label, modality,
    started_at, started_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
`

type InsertIcuSupportParams struct {
	SupportID uuid.UUID
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Kind      string
	Label     string
	Modality  string
	StartedAt pgtype.Timestamptz
	StartedBy string
}

func (q *Queries) InsertIcuSupport(ctx context.Context, arg InsertIcuSupportParams) error {
	_, err := q.db.Exec(ctx, insertIcuSupport,
		arg.SupportID,
		arg.TenantID,
		arg.EpisodeID,
		arg.Kind,
		arg.Label,
		arg.Modality,
		arg.StartedAt,
		arg.StartedBy,
	)
	return err
}

const insertIcuTitration = `-- name: InsertIcuTitration :exec
INSERT INTO icu.titration (
    titration_id, tenant_id, infusion_id, rate, rate_unit, dose,
    effective_at, recorded_at, recorded_by, device_id, reason
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertIcuTitrationParams struct {
	TitrationID uuid.UUID
	TenantID    uuid.UUID
	InfusionID  uuid.UUID
	Rate        float64
	RateUnit    string
	Dose        float64
	EffectiveAt pgtype.Timestamptz
	RecordedAt  pgtype.Timestamptz
	RecordedBy  string
	DeviceID    string
	Reason      string
}

func (q *Queries) InsertIcuTitration(ctx context.Context, arg InsertIcuTitrationParams) error {
	_, err := q.db.Exec(ctx, insertIcuTitration,
		arg.TitrationID,
		arg.TenantID,
		arg.InfusionID,
		arg.Rate,
		arg.RateUnit,
		arg.Dose,
		arg.EffectiveAt,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.DeviceID,
		arg.Reason,
	)
	return err
}

const insertIcuVentSetting = `-- name: InsertIcuVentSetting :exec
INSERT INTO icu.vent_setting (
    setting_id, tenant_id, episode_id, support_id, mode,
    parameters, measured, units, device_id,
    effective_at, recorded_at, recorded_by, change_reason
) VALUES (
    $1, $2, $3, $4::uuid, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
`

type InsertIcuVentSettingParams struct {
	SettingID    uuid.UUID
	TenantID     uuid.UUID
	EpisodeID    uuid.UUID
	SupportID    pgtype.UUID
	Mode         string
	Parameters   []byte
	Measured     []byte
	Units        []byte
	DeviceID     string
	EffectiveAt  pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
	RecordedBy   string
	ChangeReason string
}

func (q *Queries) InsertIcuVentSetting(ctx context.Context, arg InsertIcuVentSettingParams) error {
	_, err := q.db.Exec(ctx, insertIcuVentSetting,
		arg.SettingID,
		arg.TenantID,
		arg.EpisodeID,
		arg.SupportID,
		arg.Mode,
		arg.Parameters,
		arg.Measured,
		arg.Units,
		arg.DeviceID,
		arg.EffectiveAt,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.ChangeReason,
	)
	return err
}

const listIcuAssessments = `-- name: ListIcuAssessments :many
SELECT assessment_id, tenant_id, episode_id, kind, scale, score, findings, note, performed_at, performed_by, next_due_at FROM icu.assessment
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type ListIcuAssessmentsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Limit     int32
}

func (q *Queries) ListIcuAssessments(ctx context.Context, arg ListIcuAssessmentsParams) ([]IcuAssessment, error) {
	rows, err := q.db.Query(ctx, listIcuAssessments, arg.TenantID, arg.EpisodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuAssessment{}
	for rows.Next() {
		var i IcuAssessment
		if err := rows.Scan(
			&i.AssessmentID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Kind,
			&i.Scale,
			&i.Score,
			&i.Findings,
			&i.Note,
			&i.PerformedAt,
			&i.PerformedBy,
			&i.NextDueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuBalanceEntries = `-- name: ListIcuBalanceEntries :many
SELECT entry_id, tenant_id, episode_id, direction, route, volume_ml, occurred_at, recorded_at, recorded_by, superseded_by, corrects, correction_reason FROM icu.balance_entry
WHERE tenant_id = $1
  AND episode_id = $2
  AND occurred_at >= $3
  AND occurred_at < $4
ORDER BY occurred_at
`

type ListIcuBalanceEntriesParams struct {
	TenantID    uuid.UUID
	EpisodeID   uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
}

func (q *Queries) ListIcuBalanceEntries(ctx context.Context, arg ListIcuBalanceEntriesParams) ([]IcuBalanceEntry, error) {
	rows, err := q.db.Query(ctx, listIcuBalanceEntries,
		arg.TenantID,
		arg.EpisodeID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuBalanceEntry{}
	for rows.Next() {
		var i IcuBalanceEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Direction,
			&i.Route,
			&i.VolumeMl,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.SupersededBy,
			&i.Corrects,
			&i.CorrectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuBundlePerformances = `-- name: ListIcuBundlePerformances :many
SELECT performance_id, tenant_id, episode_id, kind, label, version, performed_at, performed_by FROM icu.bundle_performance
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type ListIcuBundlePerformancesParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Limit     int32
}

func (q *Queries) ListIcuBundlePerformances(ctx context.Context, arg ListIcuBundlePerformancesParams) ([]IcuBundlePerformance, error) {
	rows, err := q.db.Query(ctx, listIcuBundlePerformances, arg.TenantID, arg.EpisodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuBundlePerformance{}
	for rows.Next() {
		var i IcuBundlePerformance
		if err := rows.Scan(
			&i.PerformanceID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Kind,
			&i.Label,
			&i.Version,
			&i.PerformedAt,
			&i.PerformedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuBundleResults = `-- name: ListIcuBundleResults :many
SELECT performance_id, code, state, reason FROM icu.bundle_result
WHERE performance_id = $1
ORDER BY code
`

func (q *Queries) ListIcuBundleResults(ctx context.Context, performanceID uuid.UUID) ([]IcuBundleResult, error) {
	rows, err := q.db.Query(ctx, listIcuBundleResults, performanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuBundleResult{}
	for rows.Next() {
		var i IcuBundleResult
		if err := rows.Scan(
			&i.PerformanceID,
			&i.Code,
			&i.State,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuDevices = `-- name: ListIcuDevices :many
SELECT device_id, tenant_id, episode_id, kind, site, lumens, inserted_at, inserted_by, removed_at, removed_by, removal_reason, review_every_seconds, last_reviewed_at, last_reviewed_by FROM icu.invasive_device
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY inserted_at
`

type ListIcuDevicesParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuDevices(ctx context.Context, arg ListIcuDevicesParams) ([]IcuInvasiveDevice, error) {
	rows, err := q.db.Query(ctx, listIcuDevices, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuInvasiveDevice{}
	for rows.Next() {
		var i IcuInvasiveDevice
		if err := rows.Scan(
			&i.DeviceID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Kind,
			&i.Site,
			&i.Lumens,
			&i.InsertedAt,
			&i.InsertedBy,
			&i.RemovedAt,
			&i.RemovedBy,
			&i.RemovalReason,
			&i.ReviewEverySeconds,
			&i.LastReviewedAt,
			&i.LastReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuDevicesInPeriod = `-- name: ListIcuDevicesInPeriod :many
SELECT d.device_id, d.tenant_id, d.episode_id, d.kind, d.site, d.lumens, d.inserted_at, d.inserted_by, d.removed_at, d.removed_by, d.removal_reason, d.review_every_seconds, d.last_reviewed_at, d.last_reviewed_by FROM icu.invasive_device d
JOIN icu.episode e ON e.episode_id = d.episode_id AND e.tenant_id = d.tenant_id
WHERE d.tenant_id = $1
  AND ($2::text = '' OR e.unit_id = $2)
  AND d.inserted_at < $3
  AND (d.removed_at IS NULL OR d.removed_at >= $4)
ORDER BY d.inserted_at
`

type ListIcuDevicesInPeriodParams struct {
	TenantID    uuid.UUID
	UnitID      string
	PeriodEnd   pgtype.Timestamptz
	PeriodStart pgtype.Timestamptz
}

// Device days (SRS-ICU-017), across a unit rather than one patient.
func (q *Queries) ListIcuDevicesInPeriod(ctx context.Context, arg ListIcuDevicesInPeriodParams) ([]IcuInvasiveDevice, error) {
	rows, err := q.db.Query(ctx, listIcuDevicesInPeriod,
		arg.TenantID,
		arg.UnitID,
		arg.PeriodEnd,
		arg.PeriodStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuInvasiveDevice{}
	for rows.Next() {
		var i IcuInvasiveDevice
		if err := rows.Scan(
			&i.DeviceID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Kind,
			&i.Site,
			&i.Lumens,
			&i.InsertedAt,
			&i.InsertedBy,
			&i.RemovedAt,
			&i.RemovedBy,
			&i.RemovalReason,
			&i.ReviewEverySeconds,
			&i.LastReviewedAt,
			&i.LastReviewedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuEpisodesForEncounter = `-- name: ListIcuEpisodesForEncounter :many
SELECT episode_id, tenant_id, encounter_id, patient_id, facility_id, unit_id, bed_id, source, transferred_from, responsible_team, responsible_clinician, status, admitted_at, ready_at, discharged_at, outcome, outcome_note, created_by, created_at, updated_at, version FROM icu.episode
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY admitted_at
`

type ListIcuEpisodesForEncounterParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
}

func (q *Queries) ListIcuEpisodesForEncounter(ctx context.Context, arg ListIcuEpisodesForEncounterParams) ([]IcuEpisode, error) {
	rows, err := q.db.Query(ctx, listIcuEpisodesForEncounter, arg.TenantID, arg.EncounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuEpisode{}
	for rows.Next() {
		var i IcuEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.FacilityID,
			&i.UnitID,
			&i.BedID,
			&i.Source,
			&i.TransferredFrom,
			&i.ResponsibleTeam,
			&i.ResponsibleClinician,
			&i.Status,
			&i.AdmittedAt,
			&i.ReadyAt,
			&i.DischargedAt,
			&i.Outcome,
			&i.OutcomeNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuEpisodesInPeriod = `-- name: ListIcuEpisodesInPeriod :many
SELECT episode_id, tenant_id, encounter_id, patient_id, facility_id, unit_id, bed_id, source, transferred_from, responsible_team, responsible_clinician, status, admitted_at, ready_at, discharged_at, outcome, outcome_note, created_by, created_at, updated_at, version FROM icu.episode
WHERE tenant_id = $1
  AND ($2::text = '' OR unit_id = $2)
  AND admitted_at < $3
  AND (discharged_at IS NULL OR discharged_at >= $4)
ORDER BY admitted_at
`

type ListIcuEpisodesInPeriodParams struct {
	TenantID    uuid.UUID
	UnitID      string
	PeriodEnd   pgtype.Timestamptz
	PeriodStart pgtype.Timestamptz
}

// Closed and open episodes overlapping a window, for occupancy and length of
// stay (SRS-ICU-017).
func (q *Queries) ListIcuEpisodesInPeriod(ctx context.Context, arg ListIcuEpisodesInPeriodParams) ([]IcuEpisode, error) {
	rows, err := q.db.Query(ctx, listIcuEpisodesInPeriod,
		arg.TenantID,
		arg.UnitID,
		arg.PeriodEnd,
		arg.PeriodStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuEpisode{}
	for rows.Next() {
		var i IcuEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.FacilityID,
			&i.UnitID,
			&i.BedID,
			&i.Source,
			&i.TransferredFrom,
			&i.ResponsibleTeam,
			&i.ResponsibleClinician,
			&i.Status,
			&i.AdmittedAt,
			&i.ReadyAt,
			&i.DischargedAt,
			&i.Outcome,
			&i.OutcomeNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuGoals = `-- name: ListIcuGoals :many
SELECT goal_id, tenant_id, episode_id, round_id, domain, text, owner_role, owner_id, status, target_at, resolved_at, resolved_by, outcome, created_by, created_at FROM icu.goal
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY created_at
`

type ListIcuGoalsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuGoals(ctx context.Context, arg ListIcuGoalsParams) ([]IcuGoal, error) {
	rows, err := q.db.Query(ctx, listIcuGoals, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuGoal{}
	for rows.Next() {
		var i IcuGoal
		if err := rows.Scan(
			&i.GoalID,
			&i.TenantID,
			&i.EpisodeID,
			&i.RoundID,
			&i.Domain,
			&i.Text,
			&i.OwnerRole,
			&i.OwnerID,
			&i.Status,
			&i.TargetAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Outcome,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuGoalsOfCare = `-- name: ListIcuGoalsOfCare :many
SELECT goals_of_care_id, tenant_id, episode_id, intent, limitations, cpr_status, discussed_with, rationale, authorised_by, authorised_role, recorded_at, recorded_by, superseded_by, superseded_at, review_by FROM icu.goals_of_care
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY recorded_at
`

type ListIcuGoalsOfCareParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuGoalsOfCare(ctx context.Context, arg ListIcuGoalsOfCareParams) ([]IcuGoalsOfCare, error) {
	rows, err := q.db.Query(ctx, listIcuGoalsOfCare, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuGoalsOfCare{}
	for rows.Next() {
		var i IcuGoalsOfCare
		if err := rows.Scan(
			&i.GoalsOfCareID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Intent,
			&i.Limitations,
			&i.CprStatus,
			&i.DiscussedWith,
			&i.Rationale,
			&i.AuthorisedBy,
			&i.AuthorisedRole,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.SupersededBy,
			&i.SupersededAt,
			&i.ReviewBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuInfusions = `-- name: ListIcuInfusions :many
SELECT infusion_id, tenant_id, episode_id, prescription_id, drug_code, drug_display, concentration_amount, concentration_unit, concentration_volume, dose_unit, weight_kg, started_at, started_by, stopped_at, stopped_by FROM icu.infusion
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY started_at
`

type ListIcuInfusionsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuInfusions(ctx context.Context, arg ListIcuInfusionsParams) ([]IcuInfusion, error) {
	rows, err := q.db.Query(ctx, listIcuInfusions, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuInfusion{}
	for rows.Next() {
		var i IcuInfusion
		if err := rows.Scan(
			&i.InfusionID,
			&i.TenantID,
			&i.EpisodeID,
			&i.PrescriptionID,
			&i.DrugCode,
			&i.DrugDisplay,
			&i.ConcentrationAmount,
			&i.ConcentrationUnit,
			&i.ConcentrationVolume,
			&i.DoseUnit,
			&i.WeightKg,
			&i.StartedAt,
			&i.StartedBy,
			&i.StoppedAt,
			&i.StoppedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuObservations = `-- name: ListIcuObservations :many
SELECT observation_id, tenant_id, episode_id, code_system, code, display, dimension, value, unit, raw_value, raw_unit, normalised, source, validation, device_id, device_model, device_channel, device_measured_at, device_quality, observed_at, recorded_at, recorded_by, validated_by, validated_at, validation_note FROM icu.observation
WHERE tenant_id = $1
  AND episode_id = $2
  AND ($3::timestamptz IS NULL OR observed_at >= $3)
ORDER BY observed_at DESC
LIMIT $4
`

type ListIcuObservationsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Since     pgtype.Timestamptz
	RowLimit  int32
}

func (q *Queries) ListIcuObservations(ctx context.Context, arg ListIcuObservationsParams) ([]IcuObservation, error) {
	rows, err := q.db.Query(ctx, listIcuObservations,
		arg.TenantID,
		arg.EpisodeID,
		arg.Since,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuObservation{}
	for rows.Next() {
		var i IcuObservation
		if err := rows.Scan(
			&i.ObservationID,
			&i.TenantID,
			&i.EpisodeID,
			&i.CodeSystem,
			&i.Code,
			&i.Display,
			&i.Dimension,
			&i.Value,
			&i.Unit,
			&i.RawValue,
			&i.RawUnit,
			&i.Normalised,
			&i.Source,
			&i.Validation,
			&i.DeviceID,
			&i.DeviceModel,
			&i.DeviceChannel,
			&i.DeviceMeasuredAt,
			&i.DeviceQuality,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.ValidatedBy,
			&i.ValidatedAt,
			&i.ValidationNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuRounds = `-- name: ListIcuRounds :many
SELECT round_id, tenant_id, episode_id, attendance, summary, performed_at, performed_by FROM icu.round
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type ListIcuRoundsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Limit     int32
}

func (q *Queries) ListIcuRounds(ctx context.Context, arg ListIcuRoundsParams) ([]IcuRound, error) {
	rows, err := q.db.Query(ctx, listIcuRounds, arg.TenantID, arg.EpisodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuRound{}
	for rows.Next() {
		var i IcuRound
		if err := rows.Scan(
			&i.RoundID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Attendance,
			&i.Summary,
			&i.PerformedAt,
			&i.PerformedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuScoreInputs = `-- name: ListIcuScoreInputs :many
SELECT score_id, code, observation_id, value, unit, observed_at, points FROM icu.score_input
WHERE score_id = $1
ORDER BY code
`

func (q *Queries) ListIcuScoreInputs(ctx context.Context, scoreID uuid.UUID) ([]IcuScoreInput, error) {
	rows, err := q.db.Query(ctx, listIcuScoreInputs, scoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuScoreInput{}
	for rows.Next() {
		var i IcuScoreInput
		if err := rows.Scan(
			&i.ScoreID,
			&i.Code,
			&i.ObservationID,
			&i.Value,
			&i.Unit,
			&i.ObservedAt,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuScores = `-- name: ListIcuScores :many
SELECT score_id, tenant_id, episode_id, name, formula_version, total, missing, calculated_at, calculated_by FROM icu.score
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY calculated_at DESC
LIMIT $3
`

type ListIcuScoresParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	Limit     int32
}

func (q *Queries) ListIcuScores(ctx context.Context, arg ListIcuScoresParams) ([]IcuScore, error) {
	rows, err := q.db.Query(ctx, listIcuScores, arg.TenantID, arg.EpisodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuScore{}
	for rows.Next() {
		var i IcuScore
		if err := rows.Scan(
			&i.ScoreID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Name,
			&i.FormulaVersion,
			&i.Total,
			&i.Missing,
			&i.CalculatedAt,
			&i.CalculatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuSupport = `-- name: ListIcuSupport :many
SELECT support_id, tenant_id, episode_id, kind, label, modality, started_at, started_by, stopped_at, stopped_by, stop_note FROM icu.support
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY started_at
`

type ListIcuSupportParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuSupport(ctx context.Context, arg ListIcuSupportParams) ([]IcuSupport, error) {
	rows, err := q.db.Query(ctx, listIcuSupport, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuSupport{}
	for rows.Next() {
		var i IcuSupport
		if err := rows.Scan(
			&i.SupportID,
			&i.TenantID,
			&i.EpisodeID,
			&i.Kind,
			&i.Label,
			&i.Modality,
			&i.StartedAt,
			&i.StartedBy,
			&i.StoppedAt,
			&i.StoppedBy,
			&i.StopNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuTitrations = `-- name: ListIcuTitrations :many
SELECT titration_id, tenant_id, infusion_id, rate, rate_unit, dose, effective_at, recorded_at, recorded_by, device_id, reason FROM icu.titration
WHERE tenant_id = $1 AND infusion_id = $2
ORDER BY effective_at
`

type ListIcuTitrationsParams struct {
	TenantID   uuid.UUID
	InfusionID uuid.UUID
}

func (q *Queries) ListIcuTitrations(ctx context.Context, arg ListIcuTitrationsParams) ([]IcuTitration, error) {
	rows, err := q.db.Query(ctx, listIcuTitrations, arg.TenantID, arg.InfusionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuTitration{}
	for rows.Next() {
		var i IcuTitration
		if err := rows.Scan(
			&i.TitrationID,
			&i.TenantID,
			&i.InfusionID,
			&i.Rate,
			&i.RateUnit,
			&i.Dose,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.DeviceID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIcuVentSettings = `-- name: ListIcuVentSettings :many
SELECT setting_id, tenant_id, episode_id, support_id, mode, parameters, measured, units, device_id, effective_at, recorded_at, recorded_by, change_reason FROM icu.vent_setting
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY effective_at
`

type ListIcuVentSettingsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListIcuVentSettings(ctx context.Context, arg ListIcuVentSettingsParams) ([]IcuVentSetting, error) {
	rows, err := q.db.Query(ctx, listIcuVentSettings, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuVentSetting{}
	for rows.Next() {
		var i IcuVentSetting
		if err := rows.Scan(
			&i.SettingID,
			&i.TenantID,
			&i.EpisodeID,
			&i.SupportID,
			&i.Mode,
			&i.Parameters,
			&i.Measured,
			&i.Units,
			&i.DeviceID,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.ChangeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIcuEpisodes = `-- name: ListOpenIcuEpisodes :many
SELECT episode_id, tenant_id, encounter_id, patient_id, facility_id, unit_id, bed_id, source, transferred_from, responsible_team, responsible_clinician, status, admitted_at, ready_at, discharged_at, outcome, outcome_note, created_by, created_at, updated_at, version FROM icu.episode
WHERE tenant_id = $1
  AND ($2::text = '' OR unit_id = $2)
  AND status <> 'closed'
ORDER BY bed_id
LIMIT $3
`

type ListOpenIcuEpisodesParams struct {
	TenantID uuid.UUID
	UnitID   string
	RowLimit int32
}

// The unit as it stands, which is what the dashboard is.
func (q *Queries) ListOpenIcuEpisodes(ctx context.Context, arg ListOpenIcuEpisodesParams) ([]IcuEpisode, error) {
	rows, err := q.db.Query(ctx, listOpenIcuEpisodes, arg.TenantID, arg.UnitID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuEpisode{}
	for rows.Next() {
		var i IcuEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.EncounterID,
			&i.PatientID,
			&i.FacilityID,
			&i.UnitID,
			&i.BedID,
			&i.Source,
			&i.TransferredFrom,
			&i.ResponsibleTeam,
			&i.ResponsibleClinician,
			&i.Status,
			&i.AdmittedAt,
			&i.ReadyAt,
			&i.DischargedAt,
			&i.Outcome,
			&i.OutcomeNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingIcuObservations = `-- name: ListPendingIcuObservations :many
SELECT observation_id, tenant_id, episode_id, code_system, code, display, dimension, value, unit, raw_value, raw_unit, normalised, source, validation, device_id, device_model, device_channel, device_measured_at, device_quality, observed_at, recorded_at, recorded_by, validated_by, validated_at, validation_note FROM icu.observation
WHERE tenant_id = $1
  AND episode_id = $2
  AND validation = 'pending'
ORDER BY observed_at
LIMIT $3
`

type ListPendingIcuObservationsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
	RowLimit  int32
}

// The nurse's validation worklist.
func (q *Queries) ListPendingIcuObservations(ctx context.Context, arg ListPendingIcuObservationsParams) ([]IcuObservation, error) {
	rows, err := q.db.Query(ctx, listPendingIcuObservations, arg.TenantID, arg.EpisodeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IcuObservation{}
	for rows.Next() {
		var i IcuObservation
		if err := rows.Scan(
			&i.ObservationID,
			&i.TenantID,
			&i.EpisodeID,
			&i.CodeSystem,
			&i.Code,
			&i.Display,
			&i.Dimension,
			&i.Value,
			&i.Unit,
			&i.RawValue,
			&i.RawUnit,
			&i.Normalised,
			&i.Source,
			&i.Validation,
			&i.DeviceID,
			&i.DeviceModel,
			&i.DeviceChannel,
			&i.DeviceMeasuredAt,
			&i.DeviceQuality,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.ValidatedBy,
			&i.ValidatedAt,
			&i.ValidationNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIcuDevice = `-- name: RemoveIcuDevice :execrows
UPDATE icu.invasive_device
SET removed_at = $1, removed_by = $2,
    removal_reason = $3
WHERE tenant_id = $4
  AND device_id = $5
  AND removed_at IS NULL
`

type RemoveIcuDeviceParams struct {
	RemovedAt     pgtype.Timestamptz
	RemovedBy     string
	RemovalReason string
	TenantID      uuid.UUID
	DeviceID      uuid.UUID
}

func (q *Queries) RemoveIcuDevice(ctx context.Context, arg RemoveIcuDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeIcuDevice,
		arg.RemovedAt,
		arg.RemovedBy,
		arg.RemovalReason,
		arg.TenantID,
		arg.DeviceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveIcuGoal = `-- name: ResolveIcuGoal :execrows
UPDATE icu.goal
SET status = $1, outcome = $2,
    resolved_by = $3, resolved_at = $4
WHERE tenant_id = $5
  AND goal_id = $6
  AND status = 'open'
`

type ResolveIcuGoalParams struct {
	Status     string
	Outcome    string
	ResolvedBy string
	ResolvedAt pgtype.Timestamptz
	TenantID   uuid.UUID
	GoalID     uuid.UUID
}

func (q *Queries) ResolveIcuGoal(ctx context.Context, arg ResolveIcuGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveIcuGoal,
		arg.Status,
		arg.Outcome,
		arg.ResolvedBy,
		arg.ResolvedAt,
		arg.TenantID,
		arg.GoalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewIcuDevice = `-- name: ReviewIcuDevice :execrows
UPDATE icu.invasive_device
SET last_reviewed_at = $1, last_reviewed_by = $2
WHERE tenant_id = $3
  AND device_id = $4
  AND removed_at IS NULL
`

type ReviewIcuDeviceParams struct {
	LastReviewedAt pgtype.Timestamptz
	LastReviewedBy string
	TenantID       uuid.UUID
	DeviceID       uuid.UUID
}

func (q *Queries) ReviewIcuDevice(ctx context.Context, arg ReviewIcuDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewIcuDevice,
		arg.LastReviewedAt,
		arg.LastReviewedBy,
		arg.TenantID,
		arg.DeviceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopIcuInfusion = `-- name: StopIcuInfusion :execrows
UPDATE icu.infusion
SET stopped_at = $1, stopped_by = $2
WHERE tenant_id = $3
  AND infusion_id = $4
  AND stopped_at IS NULL
`

type StopIcuInfusionParams struct {
	StoppedAt  pgtype.Timestamptz
	StoppedBy  string
	TenantID   uuid.UUID
	InfusionID uuid.UUID
}

func (q *Queries) StopIcuInfusion(ctx context.Context, arg StopIcuInfusionParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopIcuInfusion,
		arg.StoppedAt,
		arg.StoppedBy,
		arg.TenantID,
		arg.InfusionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopIcuSupport = `-- name: StopIcuSupport :execrows
UPDATE icu.support
SET stopped_at = $1, stopped_by = $2, stop_note = $3
WHERE tenant_id = $4
  AND support_id = $5
  AND stopped_at IS NULL
`

type StopIcuSupportParams struct {
	StoppedAt pgtype.Timestamptz
	StoppedBy string
	StopNote  string
	TenantID  uuid.UUID
	SupportID uuid.UUID
}

func (q *Queries) StopIcuSupport(ctx context.Context, arg StopIcuSupportParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopIcuSupport,
		arg.StoppedAt,
		arg.StoppedBy,
		arg.StopNote,
		arg.TenantID,
		arg.SupportID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeIcuBalanceEntry = `-- name: SupersedeIcuBalanceEntry :execrows
UPDATE icu.balance_entry
SET superseded_by = $1
WHERE tenant_id = $2
  AND entry_id = $3
  AND superseded_by IS NULL
`

type SupersedeIcuBalanceEntryParams struct {
	SupersededBy pgtype.UUID
	TenantID     uuid.UUID
	EntryID      uuid.UUID
}

// A correction supersedes rather than overwrites. Refuses an entry already
// superseded, so two corrections of the same entry do not both count.
func (q *Queries) SupersedeIcuBalanceEntry(ctx context.Context, arg SupersedeIcuBalanceEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeIcuBalanceEntry, arg.SupersededBy, arg.TenantID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeIcuGoalsOfCare = `-- name: SupersedeIcuGoalsOfCare :execrows
UPDATE icu.goals_of_care
SET superseded_by = $1, superseded_at = $2
WHERE tenant_id = $3
  AND episode_id = $4
  AND superseded_by IS NULL
`

type SupersedeIcuGoalsOfCareParams struct {
	SupersededBy pgtype.UUID
	SupersededAt pgtype.Timestamptz
	TenantID     uuid.UUID
	EpisodeID    uuid.UUID
}

// Refuses one already superseded, so two replacements of the same ceiling do
// not both claim to have replaced it.
func (q *Queries) SupersedeIcuGoalsOfCare(ctx context.Context, arg SupersedeIcuGoalsOfCareParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeIcuGoalsOfCare,
		arg.SupersededBy,
		arg.SupersededAt,
		arg.TenantID,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIcuEpisode = `-- name: UpdateIcuEpisode :execrows
UPDATE icu.episode
SET bed_id = $1,
    responsible_team = $2,
    responsible_clinician = $3,
    status = $4,
    ready_at = $5::timestamptz,
    discharged_at = $6::timestamptz,
    outcome = $7,
    outcome_note = $8,
    updated_at = $9,
    version = version + 1
WHERE tenant_id = $10
  AND episode_id = $11
  AND version = $12
`

type UpdateIcuEpisodeParams struct {
	BedID                string
	ResponsibleTeam      string
	ResponsibleClinician string
	Status               string
	ReadyAt              pgtype.Timestamptz
	DischargedAt         pgtype.Timestamptz
	Outcome              string
	OutcomeNote          string
	UpdatedAt            pgtype.Timestamptz
	TenantID             uuid.UUID
	EpisodeID            uuid.UUID
	ExpectedVersion      int64
}

// Guarded on the version, so two clinicians discharging at once do not both win.
func (q *Queries) UpdateIcuEpisode(ctx context.Context, arg UpdateIcuEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIcuEpisode,
		arg.BedID,
		arg.ResponsibleTeam,
		arg.ResponsibleClinician,
		arg.Status,
		arg.ReadyAt,
		arg.DischargedAt,
		arg.Outcome,
		arg.OutcomeNote,
		arg.UpdatedAt,
		arg.TenantID,
		arg.EpisodeID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
