// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: medication.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeReconciliation = `-- name: CompleteReconciliation :execrows
UPDATE medication.reconciliation r
SET completed_by = $1,
    completed_at = $2,
    updated_at = $3,
    version = $4
WHERE r.tenant_id = $5
  AND r.reconciliation_id = $6
  AND r.version = $7
  AND r.completed_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM medication.reconciliation_item i
      WHERE i.tenant_id = r.tenant_id
        AND i.reconciliation_id = r.reconciliation_id
        AND i.disposition = 'pending')
`

type CompleteReconciliationParams struct {
	CompletedBy      string
	CompletedAt      pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	TenantID         uuid.UUID
	ReconciliationID uuid.UUID
	ExpectedVersion  int64
}

// Guarded on nothing being left pending, so the acceptance criterion holds even
// against a caller that skipped the domain — two clinicians working the same
// list cannot complete it between each other's decisions.
func (q *Queries) CompleteReconciliation(ctx context.Context, arg CompleteReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeReconciliation,
		arg.CompletedBy,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.Version,
		arg.TenantID,
		arg.ReconciliationID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDoseSegments = `-- name: DeleteDoseSegments :exec
DELETE FROM medication.dose_segment
WHERE tenant_id = $1 AND prescription_id = $2
`

type DeleteDoseSegmentsParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

// Segments are rewritten as a set when a prescription is re-versioned, because
// a taper is one instruction: leaving an old step behind would put a dose on the
// chart that no current version of the prescription asks for.
func (q *Queries) DeleteDoseSegments(ctx context.Context, arg DeleteDoseSegmentsParams) error {
	_, err := q.db.Exec(ctx, deleteDoseSegments, arg.TenantID, arg.PrescriptionID)
	return err
}

const getMedicationPolicy = `-- name: GetMedicationPolicy :one
SELECT tenant_id, max_overridable, verification_required, verification_classes, structured_dose_classes, updated_by, updated_at FROM medication.policy WHERE tenant_id = $1
`

func (q *Queries) GetMedicationPolicy(ctx context.Context, tenantID uuid.UUID) (MedicationPolicy, error) {
	row := q.db.QueryRow(ctx, getMedicationPolicy, tenantID)
	var i MedicationPolicy
	err := row.Scan(
		&i.TenantID,
		&i.MaxOverridable,
		&i.VerificationRequired,
		&i.VerificationClasses,
		&i.StructuredDoseClasses,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrescription = `-- name: GetPrescription :one
SELECT prescription_id, tenant_id, order_id, order_number, patient_id, encounter_id, facility_id, prescriber_id, entered_by_id, ingredient_system, ingredient_code, ingredient_display, ingredient_version, product_system, product_code, product_display, route, starts_at, stop_kind, stop_at, stop_doses, stop_text, indication, indication_system, indication_code, indication_display, instructions, prn, prn_indication, prn_min_interval, prn_max_doses, prn_max_total_value, prn_max_total_unit, prn_period, therapy_status, effective_stop, verified_by, verified_at, verification_note, formulary_status, formulary_scope, formulary_scope_id, formulary_restriction, formulary_approval_path, screened_at, created_at, updated_at, version FROM medication.prescription
WHERE tenant_id = $1 AND prescription_id = $2
`

type GetPrescriptionParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

func (q *Queries) GetPrescription(ctx context.Context, arg GetPrescriptionParams) (MedicationPrescription, error) {
	row := q.db.QueryRow(ctx, getPrescription, arg.TenantID, arg.PrescriptionID)
	var i MedicationPrescription
	err := row.Scan(
		&i.PrescriptionID,
		&i.TenantID,
		&i.OrderID,
		&i.OrderNumber,
		&i.PatientID,
		&i.EncounterID,
		&i.FacilityID,
		&i.PrescriberID,
		&i.EnteredByID,
		&i.IngredientSystem,
		&i.IngredientCode,
		&i.IngredientDisplay,
		&i.IngredientVersion,
		&i.ProductSystem,
		&i.ProductCode,
		&i.ProductDisplay,
		&i.Route,
		&i.StartsAt,
		&i.StopKind,
		&i.StopAt,
		&i.StopDoses,
		&i.StopText,
		&i.Indication,
		&i.IndicationSystem,
		&i.IndicationCode,
		&i.IndicationDisplay,
		&i.Instructions,
		&i.Prn,
		&i.PrnIndication,
		&i.PrnMinInterval,
		&i.PrnMaxDoses,
		&i.PrnMaxTotalValue,
		&i.PrnMaxTotalUnit,
		&i.PrnPeriod,
		&i.TherapyStatus,
		&i.EffectiveStop,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationNote,
		&i.FormularyStatus,
		&i.FormularyScope,
		&i.FormularyScopeID,
		&i.FormularyRestriction,
		&i.FormularyApprovalPath,
		&i.ScreenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getPrescriptionByOrder = `-- name: GetPrescriptionByOrder :one
SELECT prescription_id, tenant_id, order_id, order_number, patient_id, encounter_id, facility_id, prescriber_id, entered_by_id, ingredient_system, ingredient_code, ingredient_display, ingredient_version, product_system, product_code, product_display, route, starts_at, stop_kind, stop_at, stop_doses, stop_text, indication, indication_system, indication_code, indication_display, instructions, prn, prn_indication, prn_min_interval, prn_max_doses, prn_max_total_value, prn_max_total_unit, prn_period, therapy_status, effective_stop, verified_by, verified_at, verification_note, formulary_status, formulary_scope, formulary_scope_id, formulary_restriction, formulary_approval_path, screened_at, created_at, updated_at, version FROM medication.prescription
WHERE tenant_id = $1 AND order_id = $2
`

type GetPrescriptionByOrderParams struct {
	TenantID uuid.UUID
	OrderID  uuid.UUID
}

func (q *Queries) GetPrescriptionByOrder(ctx context.Context, arg GetPrescriptionByOrderParams) (MedicationPrescription, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByOrder, arg.TenantID, arg.OrderID)
	var i MedicationPrescription
	err := row.Scan(
		&i.PrescriptionID,
		&i.TenantID,
		&i.OrderID,
		&i.OrderNumber,
		&i.PatientID,
		&i.EncounterID,
		&i.FacilityID,
		&i.PrescriberID,
		&i.EnteredByID,
		&i.IngredientSystem,
		&i.IngredientCode,
		&i.IngredientDisplay,
		&i.IngredientVersion,
		&i.ProductSystem,
		&i.ProductCode,
		&i.ProductDisplay,
		&i.Route,
		&i.StartsAt,
		&i.StopKind,
		&i.StopAt,
		&i.StopDoses,
		&i.StopText,
		&i.Indication,
		&i.IndicationSystem,
		&i.IndicationCode,
		&i.IndicationDisplay,
		&i.Instructions,
		&i.Prn,
		&i.PrnIndication,
		&i.PrnMinInterval,
		&i.PrnMaxDoses,
		&i.PrnMaxTotalValue,
		&i.PrnMaxTotalUnit,
		&i.PrnPeriod,
		&i.TherapyStatus,
		&i.EffectiveStop,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationNote,
		&i.FormularyStatus,
		&i.FormularyScope,
		&i.FormularyScopeID,
		&i.FormularyRestriction,
		&i.FormularyApprovalPath,
		&i.ScreenedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getReconciliation = `-- name: GetReconciliation :one
SELECT reconciliation_id, tenant_id, patient_id, encounter_id, event, started_by, started_at, completed_by, completed_at, updated_at, version FROM medication.reconciliation
WHERE tenant_id = $1 AND reconciliation_id = $2
`

type GetReconciliationParams struct {
	TenantID         uuid.UUID
	ReconciliationID uuid.UUID
}

func (q *Queries) GetReconciliation(ctx context.Context, arg GetReconciliationParams) (MedicationReconciliation, error) {
	row := q.db.QueryRow(ctx, getReconciliation, arg.TenantID, arg.ReconciliationID)
	var i MedicationReconciliation
	err := row.Scan(
		&i.ReconciliationID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Event,
		&i.StartedBy,
		&i.StartedAt,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSubstitution = `-- name: GetSubstitution :one
SELECT substitution_id, tenant_id, prescription_id, prescribed_system, prescribed_code, prescribed_display, dispensed_system, dispensed_code, dispensed_display, kind, status, reason, proposed_by, proposed_at, authorized_by, authorized_at, dispensed_at FROM medication.substitution
WHERE tenant_id = $1 AND substitution_id = $2
`

type GetSubstitutionParams struct {
	TenantID       uuid.UUID
	SubstitutionID uuid.UUID
}

func (q *Queries) GetSubstitution(ctx context.Context, arg GetSubstitutionParams) (MedicationSubstitution, error) {
	row := q.db.QueryRow(ctx, getSubstitution, arg.TenantID, arg.SubstitutionID)
	var i MedicationSubstitution
	err := row.Scan(
		&i.SubstitutionID,
		&i.TenantID,
		&i.PrescriptionID,
		&i.PrescribedSystem,
		&i.PrescribedCode,
		&i.PrescribedDisplay,
		&i.DispensedSystem,
		&i.DispensedCode,
		&i.DispensedDisplay,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.AuthorizedBy,
		&i.AuthorizedAt,
		&i.DispensedAt,
	)
	return i, err
}

const getTerminologyMapping = `-- name: GetTerminologyMapping :one
SELECT tenant_id, medication_system, medication_code, medication_display, ingredients, classes, moiety_system, moiety_code, moiety_display, map_version, updated_by, updated_at FROM medication.terminology_map
WHERE tenant_id = $1
  AND medication_system = $2
  AND medication_code = $3
`

type GetTerminologyMappingParams struct {
	TenantID         uuid.UUID
	MedicationSystem string
	MedicationCode   string
}

func (q *Queries) GetTerminologyMapping(ctx context.Context, arg GetTerminologyMappingParams) (MedicationTerminologyMap, error) {
	row := q.db.QueryRow(ctx, getTerminologyMapping, arg.TenantID, arg.MedicationSystem, arg.MedicationCode)
	var i MedicationTerminologyMap
	err := row.Scan(
		&i.TenantID,
		&i.MedicationSystem,
		&i.MedicationCode,
		&i.MedicationDisplay,
		&i.Ingredients,
		&i.Classes,
		&i.MoietySystem,
		&i.MoietyCode,
		&i.MoietyDisplay,
		&i.MapVersion,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDoseSegment = `-- name: InsertDoseSegment :exec
INSERT INTO medication.dose_segment (
    tenant_id, prescription_id, sequence,
    dose_value, dose_unit, free_text_dose,
    frequency_text, interval_period, times_of_day, days_of_week, prn, dose_duration,
    starts_at, ends_at, note, version
) VALUES (
    $1, $2, $3,
    $4::numeric, $5, $6,
    $7, $8::interval,
    $9::integer[], $10::integer[], $11,
    $12::interval,
    $13, $14::timestamptz, $15, $16
)
`

type InsertDoseSegmentParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
	Sequence       int32
	DoseValue      pgtype.Numeric
	DoseUnit       string
	FreeTextDose   string
	FrequencyText  string
	IntervalPeriod pgtype.Interval
	TimesOfDay     []int32
	DaysOfWeek     []int32
	Prn            bool
	DoseDuration   pgtype.Interval
	StartsAt       pgtype.Timestamptz
	EndsAt         pgtype.Timestamptz
	Note           string
	Version        int64
}

func (q *Queries) InsertDoseSegment(ctx context.Context, arg InsertDoseSegmentParams) error {
	_, err := q.db.Exec(ctx, insertDoseSegment,
		arg.TenantID,
		arg.PrescriptionID,
		arg.Sequence,
		arg.DoseValue,
		arg.DoseUnit,
		arg.FreeTextDose,
		arg.FrequencyText,
		arg.IntervalPeriod,
		arg.TimesOfDay,
		arg.DaysOfWeek,
		arg.Prn,
		arg.DoseDuration,
		arg.StartsAt,
		arg.EndsAt,
		arg.Note,
		arg.Version,
	)
	return err
}

const insertPrescription = `-- name: InsertPrescription :exec

INSERT INTO medication.prescription (
    prescription_id, tenant_id, order_id, order_number,
    patient_id, encounter_id, facility_id, prescriber_id, entered_by_id,
    ingredient_system, ingredient_code, ingredient_display, ingredient_version,
    product_system, product_code, product_display,
    route, starts_at, stop_kind, stop_at, stop_doses, stop_text,
    indication, indication_system, indication_code, indication_display, instructions,
    prn, prn_indication, prn_min_interval, prn_max_doses,
    prn_max_total_value, prn_max_total_unit, prn_period,
    therapy_status, effective_stop,
    verified_by, verified_at, verification_note,
    formulary_status, formulary_scope, formulary_scope_id,
    formulary_restriction, formulary_approval_path,
    screened_at, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19, $20::timestamptz,
    $21, $22,
    $23, $24, $25, $26, $27,
    $28, $29, $30::interval, $31,
    $32::numeric, $33,
    $34::interval,
    $35, $36::timestamptz,
    $37, $38::timestamptz, $39,
    $40, $41, $42,
    $43, $44,
    $45::timestamptz, $46, $47, $48
)
`

type InsertPrescriptionParams struct {
	PrescriptionID        uuid.UUID
	TenantID              uuid.UUID
	OrderID               uuid.UUID
	OrderNumber           string
	PatientID             uuid.UUID
	EncounterID           uuid.UUID
	FacilityID            uuid.UUID
	PrescriberID          string
	EnteredByID           string
	IngredientSystem      string
	IngredientCode        string
	IngredientDisplay     string
	IngredientVersion     string
	ProductSystem         string
	ProductCode           string
	ProductDisplay        string
	Route                 string
	StartsAt              pgtype.Timestamptz
	StopKind              string
	StopAt                pgtype.Timestamptz
	StopDoses             int32
	StopText              string
	Indication            string
	IndicationSystem      string
	IndicationCode        string
	IndicationDisplay     string
	Instructions          string
	Prn                   bool
	PrnIndication         string
	PrnMinInterval        pgtype.Interval
	PrnMaxDoses           int32
	PrnMaxTotalValue      pgtype.Numeric
	PrnMaxTotalUnit       string
	PrnPeriod             pgtype.Interval
	TherapyStatus         string
	EffectiveStop         pgtype.Timestamptz
	VerifiedBy            string
	VerifiedAt            pgtype.Timestamptz
	VerificationNote      string
	FormularyStatus       string
	FormularyScope        string
	FormularyScopeID      string
	FormularyRestriction  string
	FormularyApprovalPath string
	ScreenedAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
}

// Medication management (SRS-MED).
//
// Every statement is scoped by tenant_id in its WHERE clause as well as by the
// caller's verified TenantScope, so a missing scope is a query that returns
// nothing rather than a query that returns somebody else's prescriptions.
//
// The writes that change a therapy are guarded on the prescription's version,
// which is how two clinicians holding the same drug at once resolve to one
// ledger entry rather than two.
// Written fully formed, including its therapy status: a prescription that
// reached the table as a draft and was then updated would be visible to a
// concurrent reader in a state the prescriber never intended.
func (q *Queries) InsertPrescription(ctx context.Context, arg InsertPrescriptionParams) error {
	_, err := q.db.Exec(ctx, insertPrescription,
		arg.PrescriptionID,
		arg.TenantID,
		arg.OrderID,
		arg.OrderNumber,
		arg.PatientID,
		arg.EncounterID,
		arg.FacilityID,
		arg.PrescriberID,
		arg.EnteredByID,
		arg.IngredientSystem,
		arg.IngredientCode,
		arg.IngredientDisplay,
		arg.IngredientVersion,
		arg.ProductSystem,
		arg.ProductCode,
		arg.ProductDisplay,
		arg.Route,
		arg.StartsAt,
		arg.StopKind,
		arg.StopAt,
		arg.StopDoses,
		arg.StopText,
		arg.Indication,
		arg.IndicationSystem,
		arg.IndicationCode,
		arg.IndicationDisplay,
		arg.Instructions,
		arg.Prn,
		arg.PrnIndication,
		arg.PrnMinInterval,
		arg.PrnMaxDoses,
		arg.PrnMaxTotalValue,
		arg.PrnMaxTotalUnit,
		arg.PrnPeriod,
		arg.TherapyStatus,
		arg.EffectiveStop,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.VerificationNote,
		arg.FormularyStatus,
		arg.FormularyScope,
		arg.FormularyScopeID,
		arg.FormularyRestriction,
		arg.FormularyApprovalPath,
		arg.ScreenedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}

const insertReconciliation = `-- name: InsertReconciliation :exec
INSERT INTO medication.reconciliation (
    reconciliation_id, tenant_id, patient_id, encounter_id, event,
    started_by, started_at, completed_by, completed_at, updated_at, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, '', NULL, $8, $9
)
`

type InsertReconciliationParams struct {
	ReconciliationID uuid.UUID
	TenantID         uuid.UUID
	PatientID        uuid.UUID
	EncounterID      uuid.UUID
	Event            string
	StartedBy        string
	StartedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
}

func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertReconciliation,
		arg.ReconciliationID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Event,
		arg.StartedBy,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}

const insertReconciliationItem = `-- name: InsertReconciliationItem :exec
INSERT INTO medication.reconciliation_item (
    tenant_id, reconciliation_id, sequence,
    medication_system, medication_code, medication_display,
    dose_text, route, source, disposition, rationale,
    resulting_prescription_id, decided_by, decided_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12::uuid, $13,
    $14::timestamptz
)
`

type InsertReconciliationItemParams struct {
	TenantID                uuid.UUID
	ReconciliationID        uuid.UUID
	Sequence                int32
	MedicationSystem        string
	MedicationCode          string
	MedicationDisplay       string
	DoseText                string
	Route                   string
	Source                  string
	Disposition             string
	Rationale               string
	ResultingPrescriptionID pgtype.UUID
	DecidedBy               string
	DecidedAt               pgtype.Timestamptz
}

func (q *Queries) InsertReconciliationItem(ctx context.Context, arg InsertReconciliationItemParams) error {
	_, err := q.db.Exec(ctx, insertReconciliationItem,
		arg.TenantID,
		arg.ReconciliationID,
		arg.Sequence,
		arg.MedicationSystem,
		arg.MedicationCode,
		arg.MedicationDisplay,
		arg.DoseText,
		arg.Route,
		arg.Source,
		arg.Disposition,
		arg.Rationale,
		arg.ResultingPrescriptionID,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	return err
}

const insertSafetyFinding = `-- name: InsertSafetyFinding :exec
INSERT INTO medication.safety_finding (
    finding_id, tenant_id, prescription_id, kind, severity,
    rule_id, rule_version, summary, subjects, inputs,
    override_by, override_at, override_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12::timestamptz, $13
)
`

type InsertSafetyFindingParams struct {
	FindingID      uuid.UUID
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
	Kind           string
	Severity       string
	RuleID         string
	RuleVersion    string
	Summary        string
	Subjects       []byte
	Inputs         []byte
	OverrideBy     string
	OverrideAt     pgtype.Timestamptz
	OverrideReason string
}

func (q *Queries) InsertSafetyFinding(ctx context.Context, arg InsertSafetyFindingParams) error {
	_, err := q.db.Exec(ctx, insertSafetyFinding,
		arg.FindingID,
		arg.TenantID,
		arg.PrescriptionID,
		arg.Kind,
		arg.Severity,
		arg.RuleID,
		arg.RuleVersion,
		arg.Summary,
		arg.Subjects,
		arg.Inputs,
		arg.OverrideBy,
		arg.OverrideAt,
		arg.OverrideReason,
	)
	return err
}

const insertSubstitution = `-- name: InsertSubstitution :exec
INSERT INTO medication.substitution (
    substitution_id, tenant_id, prescription_id,
    prescribed_system, prescribed_code, prescribed_display,
    dispensed_system, dispensed_code, dispensed_display,
    kind, status, reason, proposed_by, proposed_at,
    authorized_by, authorized_at, dispensed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14,
    '', NULL, NULL
)
`

type InsertSubstitutionParams struct {
	SubstitutionID    uuid.UUID
	TenantID          uuid.UUID
	PrescriptionID    uuid.UUID
	PrescribedSystem  string
	PrescribedCode    string
	PrescribedDisplay string
	DispensedSystem   string
	DispensedCode     string
	DispensedDisplay  string
	Kind              string
	Status            string
	Reason            string
	ProposedBy        string
	ProposedAt        pgtype.Timestamptz
}

func (q *Queries) InsertSubstitution(ctx context.Context, arg InsertSubstitutionParams) error {
	_, err := q.db.Exec(ctx, insertSubstitution,
		arg.SubstitutionID,
		arg.TenantID,
		arg.PrescriptionID,
		arg.PrescribedSystem,
		arg.PrescribedCode,
		arg.PrescribedDisplay,
		arg.DispensedSystem,
		arg.DispensedCode,
		arg.DispensedDisplay,
		arg.Kind,
		arg.Status,
		arg.Reason,
		arg.ProposedBy,
		arg.ProposedAt,
	)
	return err
}

const insertTherapyChange = `-- name: InsertTherapyChange :exec
INSERT INTO medication.therapy_change (
    change_id, tenant_id, prescription_id,
    from_status, to_status, effective_at, recorded_at, changed_by, reason
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8, $9
)
`

type InsertTherapyChangeParams struct {
	ChangeID       uuid.UUID
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
	FromStatus     string
	ToStatus       string
	EffectiveAt    pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
	ChangedBy      string
	Reason         string
}

func (q *Queries) InsertTherapyChange(ctx context.Context, arg InsertTherapyChangeParams) error {
	_, err := q.db.Exec(ctx, insertTherapyChange,
		arg.ChangeID,
		arg.TenantID,
		arg.PrescriptionID,
		arg.FromStatus,
		arg.ToStatus,
		arg.EffectiveAt,
		arg.RecordedAt,
		arg.ChangedBy,
		arg.Reason,
	)
	return err
}

const latestTerminologyMapVersion = `-- name: LatestTerminologyMapVersion :one
SELECT map_version FROM medication.terminology_map
WHERE tenant_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

// The edition in force, so an allergy finding can name the version of the map
// that produced it. The most recently updated row wins: the map is published as
// a set, and a tenant midway through an import is a tenant whose findings should
// name the version they were actually screened against.
func (q *Queries) LatestTerminologyMapVersion(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, latestTerminologyMapVersion, tenantID)
	var map_version string
	err := row.Scan(&map_version)
	return map_version, err
}

const listActiveInteractionRules = `-- name: ListActiveInteractionRules :many
SELECT tenant_id, rule_id, version, left_system, left_code, left_display, right_system, right_code, right_display, severity, advice, management, active, updated_by, updated_at FROM medication.interaction_rule
WHERE tenant_id = $1 AND active
ORDER BY rule_id, version
`

func (q *Queries) ListActiveInteractionRules(ctx context.Context, tenantID uuid.UUID) ([]MedicationInteractionRule, error) {
	rows, err := q.db.Query(ctx, listActiveInteractionRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationInteractionRule{}
	for rows.Next() {
		var i MedicationInteractionRule
		if err := rows.Scan(
			&i.TenantID,
			&i.RuleID,
			&i.Version,
			&i.LeftSystem,
			&i.LeftCode,
			&i.LeftDisplay,
			&i.RightSystem,
			&i.RightCode,
			&i.RightDisplay,
			&i.Severity,
			&i.Advice,
			&i.Management,
			&i.Active,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoseSegments = `-- name: ListDoseSegments :many
SELECT tenant_id, prescription_id, sequence, dose_value, dose_unit, free_text_dose, frequency_text, interval_period, times_of_day, days_of_week, prn, dose_duration, starts_at, ends_at, note, version FROM medication.dose_segment
WHERE tenant_id = $1 AND prescription_id = $2
ORDER BY sequence
`

type ListDoseSegmentsParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

func (q *Queries) ListDoseSegments(ctx context.Context, arg ListDoseSegmentsParams) ([]MedicationDoseSegment, error) {
	rows, err := q.db.Query(ctx, listDoseSegments, arg.TenantID, arg.PrescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationDoseSegment{}
	for rows.Next() {
		var i MedicationDoseSegment
		if err := rows.Scan(
			&i.TenantID,
			&i.PrescriptionID,
			&i.Sequence,
			&i.DoseValue,
			&i.DoseUnit,
			&i.FreeTextDose,
			&i.FrequencyText,
			&i.IntervalPeriod,
			&i.TimesOfDay,
			&i.DaysOfWeek,
			&i.Prn,
			&i.DoseDuration,
			&i.StartsAt,
			&i.EndsAt,
			&i.Note,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormularyEntries = `-- name: ListFormularyEntries :many
SELECT tenant_id, medication_system, medication_code, medication_display, scope, scope_id, status, restriction, approval_path, updated_by, updated_at FROM medication.formulary_entry
WHERE tenant_id = $1
ORDER BY medication_system, medication_code, scope, scope_id
`

func (q *Queries) ListFormularyEntries(ctx context.Context, tenantID uuid.UUID) ([]MedicationFormularyEntry, error) {
	rows, err := q.db.Query(ctx, listFormularyEntries, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationFormularyEntry{}
	for rows.Next() {
		var i MedicationFormularyEntry
		if err := rows.Scan(
			&i.TenantID,
			&i.MedicationSystem,
			&i.MedicationCode,
			&i.MedicationDisplay,
			&i.Scope,
			&i.ScopeID,
			&i.Status,
			&i.Restriction,
			&i.ApprovalPath,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePrescriptionsForPatient = `-- name: ListLivePrescriptionsForPatient :many
SELECT prescription_id, tenant_id, order_id, order_number, patient_id, encounter_id, facility_id, prescriber_id, entered_by_id, ingredient_system, ingredient_code, ingredient_display, ingredient_version, product_system, product_code, product_display, route, starts_at, stop_kind, stop_at, stop_doses, stop_text, indication, indication_system, indication_code, indication_display, instructions, prn, prn_indication, prn_min_interval, prn_max_doses, prn_max_total_value, prn_max_total_unit, prn_period, therapy_status, effective_stop, verified_by, verified_at, verification_note, formulary_status, formulary_scope, formulary_scope_id, formulary_restriction, formulary_approval_path, screened_at, created_at, updated_at, version FROM medication.prescription
WHERE tenant_id = $1
  AND patient_id = $2
  AND therapy_status IN ('active', 'held')
ORDER BY starts_at DESC
LIMIT $3
`

type ListLivePrescriptionsForPatientParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	RowLimit  int32
}

// What the interaction and duplicate-therapy screens read (SRS-MED-003). Held
// medications are included: a drug paused for a procedure is still in the
// patient, and an interaction with it is still an interaction.
func (q *Queries) ListLivePrescriptionsForPatient(ctx context.Context, arg ListLivePrescriptionsForPatientParams) ([]MedicationPrescription, error) {
	rows, err := q.db.Query(ctx, listLivePrescriptionsForPatient, arg.TenantID, arg.PatientID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationPrescription{}
	for rows.Next() {
		var i MedicationPrescription
		if err := rows.Scan(
			&i.PrescriptionID,
			&i.TenantID,
			&i.OrderID,
			&i.OrderNumber,
			&i.PatientID,
			&i.EncounterID,
			&i.FacilityID,
			&i.PrescriberID,
			&i.EnteredByID,
			&i.IngredientSystem,
			&i.IngredientCode,
			&i.IngredientDisplay,
			&i.IngredientVersion,
			&i.ProductSystem,
			&i.ProductCode,
			&i.ProductDisplay,
			&i.Route,
			&i.StartsAt,
			&i.StopKind,
			&i.StopAt,
			&i.StopDoses,
			&i.StopText,
			&i.Indication,
			&i.IndicationSystem,
			&i.IndicationCode,
			&i.IndicationDisplay,
			&i.Instructions,
			&i.Prn,
			&i.PrnIndication,
			&i.PrnMinInterval,
			&i.PrnMaxDoses,
			&i.PrnMaxTotalValue,
			&i.PrnMaxTotalUnit,
			&i.PrnPeriod,
			&i.TherapyStatus,
			&i.EffectiveStop,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNote,
			&i.FormularyStatus,
			&i.FormularyScope,
			&i.FormularyScopeID,
			&i.FormularyRestriction,
			&i.FormularyApprovalPath,
			&i.ScreenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionSafetyFindings = `-- name: ListPrescriptionSafetyFindings :many
SELECT finding_id, tenant_id, prescription_id, kind, severity, rule_id, rule_version, summary, subjects, inputs, override_by, override_at, override_reason FROM medication.safety_finding
WHERE tenant_id = $1 AND prescription_id = $2
ORDER BY finding_id
`

type ListPrescriptionSafetyFindingsParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

func (q *Queries) ListPrescriptionSafetyFindings(ctx context.Context, arg ListPrescriptionSafetyFindingsParams) ([]MedicationSafetyFinding, error) {
	rows, err := q.db.Query(ctx, listPrescriptionSafetyFindings, arg.TenantID, arg.PrescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationSafetyFinding{}
	for rows.Next() {
		var i MedicationSafetyFinding
		if err := rows.Scan(
			&i.FindingID,
			&i.TenantID,
			&i.PrescriptionID,
			&i.Kind,
			&i.Severity,
			&i.RuleID,
			&i.RuleVersion,
			&i.Summary,
			&i.Subjects,
			&i.Inputs,
			&i.OverrideBy,
			&i.OverrideAt,
			&i.OverrideReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsAwaitingVerification = `-- name: ListPrescriptionsAwaitingVerification :many
SELECT prescription_id, tenant_id, order_id, order_number, patient_id, encounter_id, facility_id, prescriber_id, entered_by_id, ingredient_system, ingredient_code, ingredient_display, ingredient_version, product_system, product_code, product_display, route, starts_at, stop_kind, stop_at, stop_doses, stop_text, indication, indication_system, indication_code, indication_display, instructions, prn, prn_indication, prn_min_interval, prn_max_doses, prn_max_total_value, prn_max_total_unit, prn_period, therapy_status, effective_stop, verified_by, verified_at, verification_note, formulary_status, formulary_scope, formulary_scope_id, formulary_restriction, formulary_approval_path, screened_at, created_at, updated_at, version FROM medication.prescription
WHERE tenant_id = $1
  AND facility_id = $2
  AND therapy_status = 'active'
  AND verified_by = ''
ORDER BY created_at
LIMIT $3
`

type ListPrescriptionsAwaitingVerificationParams struct {
	TenantID   uuid.UUID
	FacilityID uuid.UUID
	RowLimit   int32
}

// The pharmacy worklist (SRS-MED-006).
func (q *Queries) ListPrescriptionsAwaitingVerification(ctx context.Context, arg ListPrescriptionsAwaitingVerificationParams) ([]MedicationPrescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsAwaitingVerification, arg.TenantID, arg.FacilityID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationPrescription{}
	for rows.Next() {
		var i MedicationPrescription
		if err := rows.Scan(
			&i.PrescriptionID,
			&i.TenantID,
			&i.OrderID,
			&i.OrderNumber,
			&i.PatientID,
			&i.EncounterID,
			&i.FacilityID,
			&i.PrescriberID,
			&i.EnteredByID,
			&i.IngredientSystem,
			&i.IngredientCode,
			&i.IngredientDisplay,
			&i.IngredientVersion,
			&i.ProductSystem,
			&i.ProductCode,
			&i.ProductDisplay,
			&i.Route,
			&i.StartsAt,
			&i.StopKind,
			&i.StopAt,
			&i.StopDoses,
			&i.StopText,
			&i.Indication,
			&i.IndicationSystem,
			&i.IndicationCode,
			&i.IndicationDisplay,
			&i.Instructions,
			&i.Prn,
			&i.PrnIndication,
			&i.PrnMinInterval,
			&i.PrnMaxDoses,
			&i.PrnMaxTotalValue,
			&i.PrnMaxTotalUnit,
			&i.PrnPeriod,
			&i.TherapyStatus,
			&i.EffectiveStop,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNote,
			&i.FormularyStatus,
			&i.FormularyScope,
			&i.FormularyScopeID,
			&i.FormularyRestriction,
			&i.FormularyApprovalPath,
			&i.ScreenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsForEncounter = `-- name: ListPrescriptionsForEncounter :many
SELECT prescription_id, tenant_id, order_id, order_number, patient_id, encounter_id, facility_id, prescriber_id, entered_by_id, ingredient_system, ingredient_code, ingredient_display, ingredient_version, product_system, product_code, product_display, route, starts_at, stop_kind, stop_at, stop_doses, stop_text, indication, indication_system, indication_code, indication_display, instructions, prn, prn_indication, prn_min_interval, prn_max_doses, prn_max_total_value, prn_max_total_unit, prn_period, therapy_status, effective_stop, verified_by, verified_at, verification_note, formulary_status, formulary_scope, formulary_scope_id, formulary_restriction, formulary_approval_path, screened_at, created_at, updated_at, version FROM medication.prescription
WHERE tenant_id = $1
  AND encounter_id = $2
  AND (NOT $3::boolean OR therapy_status IN ('active', 'held'))
ORDER BY starts_at DESC
LIMIT $4
`

type ListPrescriptionsForEncounterParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	LiveOnly    bool
	RowLimit    int32
}

func (q *Queries) ListPrescriptionsForEncounter(ctx context.Context, arg ListPrescriptionsForEncounterParams) ([]MedicationPrescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsForEncounter,
		arg.TenantID,
		arg.EncounterID,
		arg.LiveOnly,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationPrescription{}
	for rows.Next() {
		var i MedicationPrescription
		if err := rows.Scan(
			&i.PrescriptionID,
			&i.TenantID,
			&i.OrderID,
			&i.OrderNumber,
			&i.PatientID,
			&i.EncounterID,
			&i.FacilityID,
			&i.PrescriberID,
			&i.EnteredByID,
			&i.IngredientSystem,
			&i.IngredientCode,
			&i.IngredientDisplay,
			&i.IngredientVersion,
			&i.ProductSystem,
			&i.ProductCode,
			&i.ProductDisplay,
			&i.Route,
			&i.StartsAt,
			&i.StopKind,
			&i.StopAt,
			&i.StopDoses,
			&i.StopText,
			&i.Indication,
			&i.IndicationSystem,
			&i.IndicationCode,
			&i.IndicationDisplay,
			&i.Instructions,
			&i.Prn,
			&i.PrnIndication,
			&i.PrnMinInterval,
			&i.PrnMaxDoses,
			&i.PrnMaxTotalValue,
			&i.PrnMaxTotalUnit,
			&i.PrnPeriod,
			&i.TherapyStatus,
			&i.EffectiveStop,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationNote,
			&i.FormularyStatus,
			&i.FormularyScope,
			&i.FormularyScopeID,
			&i.FormularyRestriction,
			&i.FormularyApprovalPath,
			&i.ScreenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationItems = `-- name: ListReconciliationItems :many
SELECT tenant_id, reconciliation_id, sequence, medication_system, medication_code, medication_display, dose_text, route, source, disposition, rationale, resulting_prescription_id, decided_by, decided_at FROM medication.reconciliation_item
WHERE tenant_id = $1 AND reconciliation_id = $2
ORDER BY sequence
`

type ListReconciliationItemsParams struct {
	TenantID         uuid.UUID
	ReconciliationID uuid.UUID
}

func (q *Queries) ListReconciliationItems(ctx context.Context, arg ListReconciliationItemsParams) ([]MedicationReconciliationItem, error) {
	rows, err := q.db.Query(ctx, listReconciliationItems, arg.TenantID, arg.ReconciliationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationReconciliationItem{}
	for rows.Next() {
		var i MedicationReconciliationItem
		if err := rows.Scan(
			&i.TenantID,
			&i.ReconciliationID,
			&i.Sequence,
			&i.MedicationSystem,
			&i.MedicationCode,
			&i.MedicationDisplay,
			&i.DoseText,
			&i.Route,
			&i.Source,
			&i.Disposition,
			&i.Rationale,
			&i.ResultingPrescriptionID,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationsForEncounter = `-- name: ListReconciliationsForEncounter :many
SELECT reconciliation_id, tenant_id, patient_id, encounter_id, event, started_by, started_at, completed_by, completed_at, updated_at, version FROM medication.reconciliation
WHERE tenant_id = $1 AND encounter_id = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListReconciliationsForEncounterParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	RowLimit    int32
}

func (q *Queries) ListReconciliationsForEncounter(ctx context.Context, arg ListReconciliationsForEncounterParams) ([]MedicationReconciliation, error) {
	rows, err := q.db.Query(ctx, listReconciliationsForEncounter, arg.TenantID, arg.EncounterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationReconciliation{}
	for rows.Next() {
		var i MedicationReconciliation
		if err := rows.Scan(
			&i.ReconciliationID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Event,
			&i.StartedBy,
			&i.StartedAt,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableDoseRules = `-- name: ListRunnableDoseRules :many
SELECT tenant_id, rule_id, version, scope, medication_system, medication_code, medication_display, max_creatinine_clearance, max_age_years, advice, validated, validated_by, validated_at, active, updated_by, updated_at FROM medication.dose_rule
WHERE tenant_id = $1 AND active AND validated
ORDER BY rule_id, version
`

// Active and validated only (SRS-MED-004). The filter is in the query rather
// than in the caller, so a caller that forgets gets no advice rather than
// unchecked advice.
func (q *Queries) ListRunnableDoseRules(ctx context.Context, tenantID uuid.UUID) ([]MedicationDoseRule, error) {
	rows, err := q.db.Query(ctx, listRunnableDoseRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationDoseRule{}
	for rows.Next() {
		var i MedicationDoseRule
		if err := rows.Scan(
			&i.TenantID,
			&i.RuleID,
			&i.Version,
			&i.Scope,
			&i.MedicationSystem,
			&i.MedicationCode,
			&i.MedicationDisplay,
			&i.MaxCreatinineClearance,
			&i.MaxAgeYears,
			&i.Advice,
			&i.Validated,
			&i.ValidatedBy,
			&i.ValidatedAt,
			&i.Active,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstitutions = `-- name: ListSubstitutions :many
SELECT substitution_id, tenant_id, prescription_id, prescribed_system, prescribed_code, prescribed_display, dispensed_system, dispensed_code, dispensed_display, kind, status, reason, proposed_by, proposed_at, authorized_by, authorized_at, dispensed_at FROM medication.substitution
WHERE tenant_id = $1 AND prescription_id = $2
ORDER BY proposed_at DESC
`

type ListSubstitutionsParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

func (q *Queries) ListSubstitutions(ctx context.Context, arg ListSubstitutionsParams) ([]MedicationSubstitution, error) {
	rows, err := q.db.Query(ctx, listSubstitutions, arg.TenantID, arg.PrescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationSubstitution{}
	for rows.Next() {
		var i MedicationSubstitution
		if err := rows.Scan(
			&i.SubstitutionID,
			&i.TenantID,
			&i.PrescriptionID,
			&i.PrescribedSystem,
			&i.PrescribedCode,
			&i.PrescribedDisplay,
			&i.DispensedSystem,
			&i.DispensedCode,
			&i.DispensedDisplay,
			&i.Kind,
			&i.Status,
			&i.Reason,
			&i.ProposedBy,
			&i.ProposedAt,
			&i.AuthorizedBy,
			&i.AuthorizedAt,
			&i.DispensedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTherapyChanges = `-- name: ListTherapyChanges :many
SELECT change_id, tenant_id, prescription_id, from_status, to_status, effective_at, recorded_at, changed_by, reason FROM medication.therapy_change
WHERE tenant_id = $1 AND prescription_id = $2
ORDER BY effective_at, recorded_at
`

type ListTherapyChangesParams struct {
	TenantID       uuid.UUID
	PrescriptionID uuid.UUID
}

func (q *Queries) ListTherapyChanges(ctx context.Context, arg ListTherapyChangesParams) ([]MedicationTherapyChange, error) {
	rows, err := q.db.Query(ctx, listTherapyChanges, arg.TenantID, arg.PrescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationTherapyChange{}
	for rows.Next() {
		var i MedicationTherapyChange
		if err := rows.Scan(
			&i.ChangeID,
			&i.TenantID,
			&i.PrescriptionID,
			&i.FromStatus,
			&i.ToStatus,
			&i.EffectiveAt,
			&i.RecordedAt,
			&i.ChangedBy,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSafetyOverride = `-- name: RecordSafetyOverride :execrows
UPDATE medication.safety_finding
SET override_by = $1,
    override_at = $2,
    override_reason = $3
WHERE tenant_id = $4
  AND finding_id = $5
  AND override_by = ''
`

type RecordSafetyOverrideParams struct {
	OverrideBy     string
	OverrideAt     pgtype.Timestamptz
	OverrideReason string
	TenantID       uuid.UUID
	FindingID      uuid.UUID
}

func (q *Queries) RecordSafetyOverride(ctx context.Context, arg RecordSafetyOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSafetyOverride,
		arg.OverrideBy,
		arg.OverrideAt,
		arg.OverrideReason,
		arg.TenantID,
		arg.FindingID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMedicationPolicy = `-- name: SetMedicationPolicy :exec
INSERT INTO medication.policy (
    tenant_id, max_overridable, verification_required, verification_classes,
    structured_dose_classes, updated_by, updated_at
) VALUES (
    $1, $2, $3,
    $4::text[], $5::text[],
    $6, $7
)
ON CONFLICT (tenant_id)
DO UPDATE SET
    max_overridable = EXCLUDED.max_overridable,
    verification_required = EXCLUDED.verification_required,
    verification_classes = EXCLUDED.verification_classes,
    structured_dose_classes = EXCLUDED.structured_dose_classes,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type SetMedicationPolicyParams struct {
	TenantID              uuid.UUID
	MaxOverridable        string
	VerificationRequired  bool
	VerificationClasses   []string
	StructuredDoseClasses []string
	UpdatedBy             string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) SetMedicationPolicy(ctx context.Context, arg SetMedicationPolicyParams) error {
	_, err := q.db.Exec(ctx, setMedicationPolicy,
		arg.TenantID,
		arg.MaxOverridable,
		arg.VerificationRequired,
		arg.VerificationClasses,
		arg.StructuredDoseClasses,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const touchReconciliation = `-- name: TouchReconciliation :execrows
UPDATE medication.reconciliation
SET updated_at = $1, version = $2
WHERE tenant_id = $3
  AND reconciliation_id = $4
  AND version = $5
  AND completed_at IS NULL
`

type TouchReconciliationParams struct {
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	TenantID         uuid.UUID
	ReconciliationID uuid.UUID
	ExpectedVersion  int64
}

func (q *Queries) TouchReconciliation(ctx context.Context, arg TouchReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchReconciliation,
		arg.UpdatedAt,
		arg.Version,
		arg.TenantID,
		arg.ReconciliationID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReconciliationItem = `-- name: UpdateReconciliationItem :execrows
UPDATE medication.reconciliation_item
SET disposition = $1,
    rationale = $2,
    resulting_prescription_id = $3::uuid,
    decided_by = $4,
    decided_at = $5
WHERE tenant_id = $6
  AND reconciliation_id = $7
  AND sequence = $8
`

type UpdateReconciliationItemParams struct {
	Disposition             string
	Rationale               string
	ResultingPrescriptionID pgtype.UUID
	DecidedBy               string
	DecidedAt               pgtype.Timestamptz
	TenantID                uuid.UUID
	ReconciliationID        uuid.UUID
	Sequence                int32
}

func (q *Queries) UpdateReconciliationItem(ctx context.Context, arg UpdateReconciliationItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReconciliationItem,
		arg.Disposition,
		arg.Rationale,
		arg.ResultingPrescriptionID,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.TenantID,
		arg.ReconciliationID,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSubstitution = `-- name: UpdateSubstitution :execrows
UPDATE medication.substitution
SET status = $1,
    reason = $2,
    authorized_by = $3,
    authorized_at = $4::timestamptz,
    dispensed_at = $5::timestamptz
WHERE tenant_id = $6
  AND substitution_id = $7
  AND status = $8
`

type UpdateSubstitutionParams struct {
	Status         string
	Reason         string
	AuthorizedBy   string
	AuthorizedAt   pgtype.Timestamptz
	DispensedAt    pgtype.Timestamptz
	TenantID       uuid.UUID
	SubstitutionID uuid.UUID
	ExpectedStatus string
}

func (q *Queries) UpdateSubstitution(ctx context.Context, arg UpdateSubstitutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSubstitution,
		arg.Status,
		arg.Reason,
		arg.AuthorizedBy,
		arg.AuthorizedAt,
		arg.DispensedAt,
		arg.TenantID,
		arg.SubstitutionID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTherapyStatus = `-- name: UpdateTherapyStatus :execrows
UPDATE medication.prescription
SET therapy_status = $1,
    effective_stop = $2::timestamptz,
    updated_at = $3,
    version = $4
WHERE tenant_id = $5
  AND prescription_id = $6
  AND version = $7
  AND therapy_status = $8
`

type UpdateTherapyStatusParams struct {
	TherapyStatus   string
	EffectiveStop   pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int64
	TenantID        uuid.UUID
	PrescriptionID  uuid.UUID
	ExpectedVersion int64
	ExpectedStatus  string
}

// Guarded on the version, so two clinicians holding the same drug at the same
// moment produce one ledger entry rather than two. The status precondition is
// part of the guard rather than a read-then-write, because the read and the
// write are not one act.
func (q *Queries) UpdateTherapyStatus(ctx context.Context, arg UpdateTherapyStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTherapyStatus,
		arg.TherapyStatus,
		arg.EffectiveStop,
		arg.UpdatedAt,
		arg.Version,
		arg.TenantID,
		arg.PrescriptionID,
		arg.ExpectedVersion,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDoseRule = `-- name: UpsertDoseRule :exec
INSERT INTO medication.dose_rule (
    tenant_id, rule_id, version, scope,
    medication_system, medication_code, medication_display,
    max_creatinine_clearance, max_age_years, advice,
    validated, validated_by, validated_at, active, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13::timestamptz,
    $14, $15, $16
)
ON CONFLICT (tenant_id, rule_id, version)
DO UPDATE SET
    scope = EXCLUDED.scope,
    max_creatinine_clearance = EXCLUDED.max_creatinine_clearance,
    max_age_years = EXCLUDED.max_age_years,
    advice = EXCLUDED.advice,
    validated = EXCLUDED.validated,
    validated_by = EXCLUDED.validated_by,
    validated_at = EXCLUDED.validated_at,
    active = EXCLUDED.active,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertDoseRuleParams struct {
	TenantID               uuid.UUID
	RuleID                 string
	Version                string
	Scope                  string
	MedicationSystem       string
	MedicationCode         string
	MedicationDisplay      string
	MaxCreatinineClearance pgtype.Numeric
	MaxAgeYears            pgtype.Numeric
	Advice                 string
	Validated              bool
	ValidatedBy            string
	ValidatedAt            pgtype.Timestamptz
	Active                 bool
	UpdatedBy              string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertDoseRule(ctx context.Context, arg UpsertDoseRuleParams) error {
	_, err := q.db.Exec(ctx, upsertDoseRule,
		arg.TenantID,
		arg.RuleID,
		arg.Version,
		arg.Scope,
		arg.MedicationSystem,
		arg.MedicationCode,
		arg.MedicationDisplay,
		arg.MaxCreatinineClearance,
		arg.MaxAgeYears,
		arg.Advice,
		arg.Validated,
		arg.ValidatedBy,
		arg.ValidatedAt,
		arg.Active,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const upsertFormularyEntry = `-- name: UpsertFormularyEntry :exec
INSERT INTO medication.formulary_entry (
    tenant_id, medication_system, medication_code, medication_display,
    scope, scope_id, status, restriction, approval_path, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (tenant_id, medication_system, medication_code, scope, scope_id)
DO UPDATE SET
    medication_display = EXCLUDED.medication_display,
    status = EXCLUDED.status,
    restriction = EXCLUDED.restriction,
    approval_path = EXCLUDED.approval_path,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertFormularyEntryParams struct {
	TenantID          uuid.UUID
	MedicationSystem  string
	MedicationCode    string
	MedicationDisplay string
	Scope             string
	ScopeID           string
	Status            string
	Restriction       string
	ApprovalPath      string
	UpdatedBy         string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpsertFormularyEntry(ctx context.Context, arg UpsertFormularyEntryParams) error {
	_, err := q.db.Exec(ctx, upsertFormularyEntry,
		arg.TenantID,
		arg.MedicationSystem,
		arg.MedicationCode,
		arg.MedicationDisplay,
		arg.Scope,
		arg.ScopeID,
		arg.Status,
		arg.Restriction,
		arg.ApprovalPath,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const upsertInteractionRule = `-- name: UpsertInteractionRule :exec
INSERT INTO medication.interaction_rule (
    tenant_id, rule_id, version,
    left_system, left_code, left_display,
    right_system, right_code, right_display,
    severity, advice, management, active, updated_by, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
ON CONFLICT (tenant_id, rule_id, version)
DO UPDATE SET
    severity = EXCLUDED.severity,
    advice = EXCLUDED.advice,
    management = EXCLUDED.management,
    active = EXCLUDED.active,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertInteractionRuleParams struct {
	TenantID     uuid.UUID
	RuleID       string
	Version      string
	LeftSystem   string
	LeftCode     string
	LeftDisplay  string
	RightSystem  string
	RightCode    string
	RightDisplay string
	Severity     string
	Advice       string
	Management   string
	Active       bool
	UpdatedBy    string
	UpdatedAt    pgtype.Timestamptz
}

// A new version inserts a new row rather than editing the old one: a finding
// recorded last March names a version, and a version edited in place is a
// finding nobody can explain.
func (q *Queries) UpsertInteractionRule(ctx context.Context, arg UpsertInteractionRuleParams) error {
	_, err := q.db.Exec(ctx, upsertInteractionRule,
		arg.TenantID,
		arg.RuleID,
		arg.Version,
		arg.LeftSystem,
		arg.LeftCode,
		arg.LeftDisplay,
		arg.RightSystem,
		arg.RightCode,
		arg.RightDisplay,
		arg.Severity,
		arg.Advice,
		arg.Management,
		arg.Active,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const upsertTerminologyMapping = `-- name: UpsertTerminologyMapping :exec
INSERT INTO medication.terminology_map (
    tenant_id, medication_system, medication_code, medication_display,
    ingredients, classes, moiety_system, moiety_code, moiety_display,
    map_version, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5::text[], $6::text[],
    $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (tenant_id, medication_system, medication_code)
DO UPDATE SET
    medication_display = EXCLUDED.medication_display,
    ingredients = EXCLUDED.ingredients,
    classes = EXCLUDED.classes,
    moiety_system = EXCLUDED.moiety_system,
    moiety_code = EXCLUDED.moiety_code,
    moiety_display = EXCLUDED.moiety_display,
    map_version = EXCLUDED.map_version,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertTerminologyMappingParams struct {
	TenantID          uuid.UUID
	MedicationSystem  string
	MedicationCode    string
	MedicationDisplay string
	Ingredients       []string
	Classes           []string
	MoietySystem      string
	MoietyCode        string
	MoietyDisplay     string
	MapVersion        string
	UpdatedBy         string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpsertTerminologyMapping(ctx context.Context, arg UpsertTerminologyMappingParams) error {
	_, err := q.db.Exec(ctx, upsertTerminologyMapping,
		arg.TenantID,
		arg.MedicationSystem,
		arg.MedicationCode,
		arg.MedicationDisplay,
		arg.Ingredients,
		arg.Classes,
		arg.MoietySystem,
		arg.MoietyCode,
		arg.MoietyDisplay,
		arg.MapVersion,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const verifyPrescription = `-- name: VerifyPrescription :execrows
UPDATE medication.prescription
SET verified_by = $1,
    verified_at = $2,
    verification_note = $3,
    updated_at = $4,
    version = $5
WHERE tenant_id = $6
  AND prescription_id = $7
  AND version = $8
  AND verified_by = ''
`

type VerifyPrescriptionParams struct {
	VerifiedBy       string
	VerifiedAt       pgtype.Timestamptz
	VerificationNote string
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	TenantID         uuid.UUID
	PrescriptionID   uuid.UUID
	ExpectedVersion  int64
}

// Guarded on the prescription still being unverified as well as on its version,
// so a second pharmacist arriving at the same moment does not move the
// timestamp that records when the check happened.
func (q *Queries) VerifyPrescription(ctx context.Context, arg VerifyPrescriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyPrescription,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.VerificationNote,
		arg.UpdatedAt,
		arg.Version,
		arg.TenantID,
		arg.PrescriptionID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
