// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationFacility struct {
	FacilityID  uuid.UUID
	TenantID    uuid.UUID
	Code        string
	DisplayName string
	Type        string
	Status      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
	Version     int64
}

// SRS-PLT-001. tenant_id is immutable; display_name is not a key.
type OrganizationTenant struct {
	TenantID          uuid.UUID
	DisplayName       string
	LegalJurisdiction string
	DefaultLocale     string
	TimeZone          string
	Status            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         string
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         string
	Version           int64
}

type PlatformDataAuditRecord struct {
	AuditID       uuid.UUID
	TenantID      uuid.UUID
	ActorID       string
	Action        string
	ResourceType  string
	ResourceID    string
	Outcome       string
	Reason        string
	PurposeOfUse  string
	BreakGlass    bool
	CorrelationID string
	RequestID     string
	OccurredAt    pgtype.Timestamptz
	Context       []byte
}

type PlatformDataInboxMessage struct {
	Consumer    string
	EventID     uuid.UUID
	TenantID    uuid.UUID
	ProcessedAt pgtype.Timestamptz
}

type PlatformDataOutboxEvent struct {
	EventID       uuid.UUID
	EventType     string
	SchemaVersion int32
	OccurredAt    pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	TenantID      uuid.UUID
	Source        string
	AggregateType string
	AggregateID   string
	CorrelationID string
	CausationID   string
	Actor         string
	Payload       []byte
	Attempts      int32
	LastError     *string
}

type PlatformEdgeEnrollmentToken struct {
	TokenHash  string
	NodeID     uuid.UUID
	TenantID   uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PlatformEdgeForwardedOperation struct {
	NodeID        uuid.UUID
	OperationID   uuid.UUID
	TenantID      uuid.UUID
	OperationType string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Outcome       string
	RejectReason  string
}

type PlatformEdgeNode struct {
	NodeID                uuid.UUID
	TenantID              uuid.UUID
	FacilityID            uuid.UUID
	DisplayName           string
	Status                string
	CredentialFingerprint string
	EnrolledAt            pgtype.Timestamptz
	LastSeenAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int64
}

type PlatformRulesDecisionLog struct {
	DecisionID     uuid.UUID
	TenantID       uuid.UUID
	RuleSetName    string
	RuleSetVersion int32
	MatchedRule    string
	Input          []byte
	Outcome        []byte
	Explanation    []byte
	CorrelationID  string
	OccurredAt     pgtype.Timestamptz
}

type PlatformRulesRuleSet struct {
	RuleSetID     uuid.UUID
	TenantID      pgtype.UUID
	Name          string
	Version       int32
	Status        string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
	Definition    []byte
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
	PublishedAt   pgtype.Timestamptz
	PublishedBy   string
}

type PlatformWorkflowHistory struct {
	HistoryID  int64
	InstanceID uuid.UUID
	TenantID   uuid.UUID
	Sequence   int32
	EventType  string
	Step       string
	Attempt    int32
	Detail     []byte
	OccurredAt pgtype.Timestamptz
}

type PlatformWorkflowHumanTask struct {
	TaskID       uuid.UUID
	InstanceID   uuid.UUID
	TenantID     uuid.UUID
	Step         string
	AssignedRole string
	Status       string
	DueAt        pgtype.Timestamptz
	CompletedBy  string
	Outcome      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PlatformWorkflowInstance struct {
	InstanceID        uuid.UUID
	TenantID          uuid.UUID
	DefinitionName    string
	DefinitionVersion int32
	CorrelationKey    string
	Status            string
	CurrentStep       string
	StepIndex         int32
	Attempts          int32
	State             []byte
	LastError         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
}

type PlatformWorkflowSignal struct {
	InstanceID uuid.UUID
	SignalKey  string
	TenantID   uuid.UUID
	SignalName string
	Payload    []byte
	ReceivedAt pgtype.Timestamptz
}

type PlatformWorkflowTimer struct {
	TimerID    uuid.UUID
	InstanceID uuid.UUID
	TenantID   uuid.UUID
	Step       string
	DueAt      pgtype.Timestamptz
	FiredAt    pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
