// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrganizationFacility struct {
	FacilityID  uuid.UUID
	TenantID    uuid.UUID
	Code        string
	DisplayName string
	Type        string
	Status      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
	Version     int64
}

// SRS-PLT-001. tenant_id is immutable; display_name is not a key.
type OrganizationTenant struct {
	TenantID          uuid.UUID
	DisplayName       string
	LegalJurisdiction string
	DefaultLocale     string
	TimeZone          string
	Status            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         string
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         string
	Version           int64
}

type PlatformDataAuditRecord struct {
	AuditID       uuid.UUID
	TenantID      uuid.UUID
	ActorID       string
	Action        string
	ResourceType  string
	ResourceID    string
	Outcome       string
	Reason        string
	PurposeOfUse  string
	BreakGlass    bool
	CorrelationID string
	RequestID     string
	OccurredAt    pgtype.Timestamptz
	Context       []byte
}

type PlatformDataInboxMessage struct {
	Consumer    string
	EventID     uuid.UUID
	TenantID    uuid.UUID
	ProcessedAt pgtype.Timestamptz
}

type PlatformDataOutboxEvent struct {
	EventID       uuid.UUID
	EventType     string
	SchemaVersion int32
	OccurredAt    pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
	TenantID      uuid.UUID
	Source        string
	AggregateType string
	AggregateID   string
	CorrelationID string
	CausationID   string
	Actor         string
	Payload       []byte
	Attempts      int32
	LastError     *string
}
