// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: nursing.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeHandover = `-- name: AcknowledgeHandover :execrows
UPDATE nursing.handover
SET acknowledged_at = $1::timestamptz, acknowledged_by = $2,
    questions = $3, version = version + 1
WHERE tenant_id = $4 AND handover_id = $5
  AND acknowledged_at IS NULL
`

type AcknowledgeHandoverParams struct {
	AcknowledgedAt pgtype.Timestamptz
	AcknowledgedBy string
	Questions      string
	TenantID       uuid.UUID
	HandoverID     uuid.UUID
}

// Guarded on the handover still being unacknowledged, so responsibility cannot
// be accepted twice and the record cannot be made to show a second transfer.
func (q *Queries) AcknowledgeHandover(ctx context.Context, arg AcknowledgeHandoverParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeHandover,
		arg.AcknowledgedAt,
		arg.AcknowledgedBy,
		arg.Questions,
		arg.TenantID,
		arg.HandoverID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeTask = `-- name: CloseTask :execrows
UPDATE nursing.task
SET status = $1, evidence = $2, completed_at = $3::timestamptz,
    completed_by = $4, not_done_reason = $5,
    version = version + 1
WHERE tenant_id = $6 AND task_id = $7
  AND status = 'pending' AND version = $8
`

type CloseTaskParams struct {
	Status          string
	Evidence        string
	CompletedAt     pgtype.Timestamptz
	CompletedBy     string
	NotDoneReason   string
	TenantID        uuid.UUID
	TaskID          uuid.UUID
	ExpectedVersion int64
}

// Guarded on the task still being pending as well as on its version, so a
// second nurse completing the same task does not overwrite the first one's
// evidence.
func (q *Queries) CloseTask(ctx context.Context, arg CloseTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTask,
		arg.Status,
		arg.Evidence,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.NotDoneReason,
		arg.TenantID,
		arg.TaskID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countNursesOnDuty = `-- name: CountNursesOnDuty :one
SELECT COUNT(DISTINCT nurse_id)
FROM nursing.assignment
WHERE tenant_id = $1 AND unit_id = $2
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to > $3)
`

type CountNursesOnDutyParams struct {
	TenantID uuid.UUID
	UnitID   string
	AsOf     pgtype.Timestamptz
}

// Counted from live assignments, not from a roster: a roster says who was meant
// to be there.
func (q *Queries) CountNursesOnDuty(ctx context.Context, arg CountNursesOnDutyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNursesOnDuty, arg.TenantID, arg.UnitID, arg.AsOf)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discontinueRestraint = `-- name: DiscontinueRestraint :execrows
UPDATE nursing.restraint
SET discontinued_at = $1::timestamptz, discontinued_by = $2,
    discontinued_reason = $3, version = version + 1
WHERE tenant_id = $4 AND restraint_id = $5
  AND discontinued_at IS NULL AND version = $6
`

type DiscontinueRestraintParams struct {
	DiscontinuedAt     pgtype.Timestamptz
	DiscontinuedBy     string
	DiscontinuedReason string
	TenantID           uuid.UUID
	RestraintID        uuid.UUID
	ExpectedVersion    int64
}

func (q *Queries) DiscontinueRestraint(ctx context.Context, arg DiscontinueRestraintParams) (int64, error) {
	result, err := q.db.Exec(ctx, discontinueRestraint,
		arg.DiscontinuedAt,
		arg.DiscontinuedBy,
		arg.DiscontinuedReason,
		arg.TenantID,
		arg.RestraintID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endAssignment = `-- name: EndAssignment :execrows
UPDATE nursing.assignment
SET effective_to = $1::timestamptz, ended_reason = $2,
    version = version + 1
WHERE tenant_id = $3 AND assignment_id = $4
  AND effective_to IS NULL
`

type EndAssignmentParams struct {
	EffectiveTo  pgtype.Timestamptz
	EndedReason  string
	TenantID     uuid.UUID
	AssignmentID uuid.UUID
}

// Closed rather than deleted, so the answer to "who held this patient last
// Tuesday night" survives the shift ending.
func (q *Queries) EndAssignment(ctx context.Context, arg EndAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, endAssignment,
		arg.EffectiveTo,
		arg.EndedReason,
		arg.TenantID,
		arg.AssignmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endNursingDowntime = `-- name: EndNursingDowntime :execrows
UPDATE nursing.downtime_episode
SET ended_at = $1::timestamptz, ended_by = $2, version = version + 1
WHERE tenant_id = $3 AND episode_id = $4
  AND ended_at IS NULL
`

type EndNursingDowntimeParams struct {
	EndedAt   pgtype.Timestamptz
	EndedBy   string
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) EndNursingDowntime(ctx context.Context, arg EndNursingDowntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, endNursingDowntime,
		arg.EndedAt,
		arg.EndedBy,
		arg.TenantID,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const escalateTask = `-- name: EscalateTask :execrows
UPDATE nursing.task
SET escalated_at = $1::timestamptz, escalated_to = $2,
    version = version + 1
WHERE tenant_id = $3 AND task_id = $4
  AND status = 'pending' AND escalated_at IS NULL
`

type EscalateTaskParams struct {
	EscalatedAt pgtype.Timestamptz
	EscalatedTo string
	TenantID    uuid.UUID
	TaskID      uuid.UUID
}

func (q *Queries) EscalateTask(ctx context.Context, arg EscalateTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, escalateTask,
		arg.EscalatedAt,
		arg.EscalatedTo,
		arg.TenantID,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAdministrationForDose = `-- name: FindAdministrationForDose :one
SELECT administration_id, tenant_id, patient_id, encounter_id, order_id,
       scheduled_at, given_at, outcome, administered_by, recorded_at
FROM nursing.administration
WHERE tenant_id = $1 AND order_id = $2
  AND scheduled_at = $3
`

type FindAdministrationForDoseParams struct {
	TenantID    uuid.UUID
	OrderID     uuid.UUID
	ScheduledAt pgtype.Timestamptz
}

type FindAdministrationForDoseRow struct {
	AdministrationID uuid.UUID
	TenantID         uuid.UUID
	PatientID        uuid.UUID
	EncounterID      uuid.UUID
	OrderID          uuid.UUID
	ScheduledAt      pgtype.Timestamptz
	GivenAt          pgtype.Timestamptz
	Outcome          string
	AdministeredBy   string
	RecordedAt       pgtype.Timestamptz
}

// What the duplicate refusal names, so a transcriber checks rather than retries
// with a changed time.
func (q *Queries) FindAdministrationForDose(ctx context.Context, arg FindAdministrationForDoseParams) (FindAdministrationForDoseRow, error) {
	row := q.db.QueryRow(ctx, findAdministrationForDose, arg.TenantID, arg.OrderID, arg.ScheduledAt)
	var i FindAdministrationForDoseRow
	err := row.Scan(
		&i.AdministrationID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.OrderID,
		&i.ScheduledAt,
		&i.GivenAt,
		&i.Outcome,
		&i.AdministeredBy,
		&i.RecordedAt,
	)
	return i, err
}

const getAcuityWeights = `-- name: GetAcuityWeights :one
SELECT tenant_id, unit_id, dependency, open_task, overdue_task, device,
       high_risk, isolation, updated_by, updated_at
FROM nursing.acuity_weights
WHERE tenant_id = $1 AND unit_id = $2
`

type GetAcuityWeightsParams struct {
	TenantID uuid.UUID
	UnitID   string
}

func (q *Queries) GetAcuityWeights(ctx context.Context, arg GetAcuityWeightsParams) (NursingAcuityWeight, error) {
	row := q.db.QueryRow(ctx, getAcuityWeights, arg.TenantID, arg.UnitID)
	var i NursingAcuityWeight
	err := row.Scan(
		&i.TenantID,
		&i.UnitID,
		&i.Dependency,
		&i.OpenTask,
		&i.OverdueTask,
		&i.Device,
		&i.HighRisk,
		&i.Isolation,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdministrationPolicy = `-- name: GetAdministrationPolicy :one
SELECT tenant_id, facility_id, barcode_required, override_allowed,
       late_after_seconds, updated_by, updated_at
FROM nursing.administration_policy
WHERE tenant_id = $1 AND facility_id = $2
`

type GetAdministrationPolicyParams struct {
	TenantID   uuid.UUID
	FacilityID uuid.UUID
}

func (q *Queries) GetAdministrationPolicy(ctx context.Context, arg GetAdministrationPolicyParams) (NursingAdministrationPolicy, error) {
	row := q.db.QueryRow(ctx, getAdministrationPolicy, arg.TenantID, arg.FacilityID)
	var i NursingAdministrationPolicy
	err := row.Scan(
		&i.TenantID,
		&i.FacilityID,
		&i.BarcodeRequired,
		&i.OverrideAllowed,
		&i.LateAfterSeconds,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessment = `-- name: GetAssessment :one
SELECT assessment_id, tenant_id, patient_id, encounter_id, kind, template_id,
       template_version, answers, assessed_at, recorded_at, assessed_by, version
FROM nursing.assessment
WHERE tenant_id = $1 AND assessment_id = $2
`

type GetAssessmentParams struct {
	TenantID     uuid.UUID
	AssessmentID uuid.UUID
}

func (q *Queries) GetAssessment(ctx context.Context, arg GetAssessmentParams) (NursingAssessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, arg.TenantID, arg.AssessmentID)
	var i NursingAssessment
	err := row.Scan(
		&i.AssessmentID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Kind,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.Answers,
		&i.AssessedAt,
		&i.RecordedAt,
		&i.AssessedBy,
		&i.Version,
	)
	return i, err
}

const getAssessmentTemplate = `-- name: GetAssessmentTemplate :one
SELECT template_id, tenant_id, version, name, min_age_years, max_age_years,
       service_code, sections, retired, created_by, created_at
FROM nursing.assessment_template
WHERE tenant_id = $1 AND template_id = $2
  AND version = $3
`

type GetAssessmentTemplateParams struct {
	TenantID   uuid.UUID
	TemplateID uuid.UUID
	Version    string
}

func (q *Queries) GetAssessmentTemplate(ctx context.Context, arg GetAssessmentTemplateParams) (NursingAssessmentTemplate, error) {
	row := q.db.QueryRow(ctx, getAssessmentTemplate, arg.TenantID, arg.TemplateID, arg.Version)
	var i NursingAssessmentTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.TenantID,
		&i.Version,
		&i.Name,
		&i.MinAgeYears,
		&i.MaxAgeYears,
		&i.ServiceCode,
		&i.Sections,
		&i.Retired,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT device_id, tenant_id, patient_id, encounter_id, kind, site, laterality,
       size, lot, inserted_at, inserted_by, removed_at, removed_by,
       removal_reason, version
FROM nursing.device
WHERE tenant_id = $1 AND device_id = $2
`

type GetDeviceParams struct {
	TenantID uuid.UUID
	DeviceID uuid.UUID
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (NursingDevice, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.TenantID, arg.DeviceID)
	var i NursingDevice
	err := row.Scan(
		&i.DeviceID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Kind,
		&i.Site,
		&i.Laterality,
		&i.Size,
		&i.Lot,
		&i.InsertedAt,
		&i.InsertedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.RemovalReason,
		&i.Version,
	)
	return i, err
}

const getFluidEntry = `-- name: GetFluidEntry :one
SELECT fluid_id, tenant_id, patient_id, encounter_id, direction, category,
       volume_ml, observed_at, recorded_at, recorded_by, superseded_by_id,
       supersedes_id, amendment_reason, voided_reason, version
FROM nursing.fluid_entry
WHERE tenant_id = $1 AND fluid_id = $2
`

type GetFluidEntryParams struct {
	TenantID uuid.UUID
	FluidID  uuid.UUID
}

func (q *Queries) GetFluidEntry(ctx context.Context, arg GetFluidEntryParams) (NursingFluidEntry, error) {
	row := q.db.QueryRow(ctx, getFluidEntry, arg.TenantID, arg.FluidID)
	var i NursingFluidEntry
	err := row.Scan(
		&i.FluidID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Direction,
		&i.Category,
		&i.VolumeMl,
		&i.ObservedAt,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.SupersededByID,
		&i.SupersedesID,
		&i.AmendmentReason,
		&i.VoidedReason,
		&i.Version,
	)
	return i, err
}

const getHandover = `-- name: GetHandover :one
SELECT handover_id, tenant_id, patient_id, encounter_id, unit_id,
       from_shift_code, from_shift_start, from_shift_end,
       to_shift_code, to_shift_start, to_shift_end,
       situation, background, assessment, recommendation, critical_risks,
       outstanding, devices, pending_tasks, composed_at, composed_by,
       acknowledged_at, acknowledged_by, questions, version
FROM nursing.handover
WHERE tenant_id = $1 AND handover_id = $2
`

type GetHandoverParams struct {
	TenantID   uuid.UUID
	HandoverID uuid.UUID
}

func (q *Queries) GetHandover(ctx context.Context, arg GetHandoverParams) (NursingHandover, error) {
	row := q.db.QueryRow(ctx, getHandover, arg.TenantID, arg.HandoverID)
	var i NursingHandover
	err := row.Scan(
		&i.HandoverID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.UnitID,
		&i.FromShiftCode,
		&i.FromShiftStart,
		&i.FromShiftEnd,
		&i.ToShiftCode,
		&i.ToShiftStart,
		&i.ToShiftEnd,
		&i.Situation,
		&i.Background,
		&i.Assessment,
		&i.Recommendation,
		&i.CriticalRisks,
		&i.Outstanding,
		&i.Devices,
		&i.PendingTasks,
		&i.ComposedAt,
		&i.ComposedBy,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.Questions,
		&i.Version,
	)
	return i, err
}

const getNursingCarePlan = `-- name: GetNursingCarePlan :one
SELECT plan_id, tenant_id, patient_id, encounter_id, title, problems, status,
       created_at, created_by, reviewed_at, reviewed_by, evaluation, version
FROM nursing.care_plan
WHERE tenant_id = $1 AND plan_id = $2
`

type GetNursingCarePlanParams struct {
	TenantID uuid.UUID
	PlanID   uuid.UUID
}

func (q *Queries) GetNursingCarePlan(ctx context.Context, arg GetNursingCarePlanParams) (NursingCarePlan, error) {
	row := q.db.QueryRow(ctx, getNursingCarePlan, arg.TenantID, arg.PlanID)
	var i NursingCarePlan
	err := row.Scan(
		&i.PlanID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Title,
		&i.Problems,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.Evaluation,
		&i.Version,
	)
	return i, err
}

const getNursingDowntime = `-- name: GetNursingDowntime :one
SELECT episode_id, tenant_id, unit_id, reason, started_at, started_by,
       ended_at, ended_by, reconciled_at, reconciled_by, version
FROM nursing.downtime_episode
WHERE tenant_id = $1 AND episode_id = $2
`

type GetNursingDowntimeParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) GetNursingDowntime(ctx context.Context, arg GetNursingDowntimeParams) (NursingDowntimeEpisode, error) {
	row := q.db.QueryRow(ctx, getNursingDowntime, arg.TenantID, arg.EpisodeID)
	var i NursingDowntimeEpisode
	err := row.Scan(
		&i.EpisodeID,
		&i.TenantID,
		&i.UnitID,
		&i.Reason,
		&i.StartedAt,
		&i.StartedBy,
		&i.EndedAt,
		&i.EndedBy,
		&i.ReconciledAt,
		&i.ReconciledBy,
		&i.Version,
	)
	return i, err
}

const getRestraint = `-- name: GetRestraint :one
SELECT restraint_id, tenant_id, patient_id, encounter_id, kind, description,
       authorized_by, authorized_at, expires_at, indication, renewals,
       started_at, started_by, monitor_every_seconds, discontinued_at,
       discontinued_by, discontinued_reason, version
FROM nursing.restraint
WHERE tenant_id = $1 AND restraint_id = $2
`

type GetRestraintParams struct {
	TenantID    uuid.UUID
	RestraintID uuid.UUID
}

func (q *Queries) GetRestraint(ctx context.Context, arg GetRestraintParams) (NursingRestraint, error) {
	row := q.db.QueryRow(ctx, getRestraint, arg.TenantID, arg.RestraintID)
	var i NursingRestraint
	err := row.Scan(
		&i.RestraintID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Kind,
		&i.Description,
		&i.AuthorizedBy,
		&i.AuthorizedAt,
		&i.ExpiresAt,
		&i.Indication,
		&i.Renewals,
		&i.StartedAt,
		&i.StartedBy,
		&i.MonitorEverySeconds,
		&i.DiscontinuedAt,
		&i.DiscontinuedBy,
		&i.DiscontinuedReason,
		&i.Version,
	)
	return i, err
}

const getRiskScale = `-- name: GetRiskScale :one
SELECT scale_id, tenant_id, version, name, risk_domain, inputs, bands,
       reassess_after_seconds, retired, created_by, created_at
FROM nursing.risk_scale
WHERE tenant_id = $1 AND scale_id = $2 AND version = $3
`

type GetRiskScaleParams struct {
	TenantID uuid.UUID
	ScaleID  uuid.UUID
	Version  string
}

func (q *Queries) GetRiskScale(ctx context.Context, arg GetRiskScaleParams) (NursingRiskScale, error) {
	row := q.db.QueryRow(ctx, getRiskScale, arg.TenantID, arg.ScaleID, arg.Version)
	var i NursingRiskScale
	err := row.Scan(
		&i.ScaleID,
		&i.TenantID,
		&i.Version,
		&i.Name,
		&i.RiskDomain,
		&i.Inputs,
		&i.Bands,
		&i.ReassessAfterSeconds,
		&i.Retired,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT task_id, tenant_id, patient_id, encounter_id, description, priority,
       due_at, source_kind, source_id, recur_every_seconds, recur_until,
       status, evidence, completed_at, completed_by, not_done_reason,
       assigned_to, escalated_at, escalated_to, created_at, created_by, version
FROM nursing.task
WHERE tenant_id = $1 AND task_id = $2
`

type GetTaskParams struct {
	TenantID uuid.UUID
	TaskID   uuid.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (NursingTask, error) {
	row := q.db.QueryRow(ctx, getTask, arg.TenantID, arg.TaskID)
	var i NursingTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.Description,
		&i.Priority,
		&i.DueAt,
		&i.SourceKind,
		&i.SourceID,
		&i.RecurEverySeconds,
		&i.RecurUntil,
		&i.Status,
		&i.Evidence,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.NotDoneReason,
		&i.AssignedTo,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getWoundAssessment = `-- name: GetWoundAssessment :one
SELECT wound_assessment_id, tenant_id, patient_id, encounter_id, wound_id,
       location, body_map_system, body_map_code, body_map_display, laterality,
       kind, stage, length_mm, width_mm, depth_mm, appearance, exudate,
       surrounding_skin, pain_score, assessed_at, recorded_at, assessed_by,
       version
FROM nursing.wound_assessment
WHERE tenant_id = $1 AND wound_assessment_id = $2
`

type GetWoundAssessmentParams struct {
	TenantID          uuid.UUID
	WoundAssessmentID uuid.UUID
}

func (q *Queries) GetWoundAssessment(ctx context.Context, arg GetWoundAssessmentParams) (NursingWoundAssessment, error) {
	row := q.db.QueryRow(ctx, getWoundAssessment, arg.TenantID, arg.WoundAssessmentID)
	var i NursingWoundAssessment
	err := row.Scan(
		&i.WoundAssessmentID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.WoundID,
		&i.Location,
		&i.BodyMapSystem,
		&i.BodyMapCode,
		&i.BodyMapDisplay,
		&i.Laterality,
		&i.Kind,
		&i.Stage,
		&i.LengthMm,
		&i.WidthMm,
		&i.DepthMm,
		&i.Appearance,
		&i.Exudate,
		&i.SurroundingSkin,
		&i.PainScore,
		&i.AssessedAt,
		&i.RecordedAt,
		&i.AssessedBy,
		&i.Version,
	)
	return i, err
}

const insertAdministration = `-- name: InsertAdministration :exec
INSERT INTO nursing.administration (
    administration_id, tenant_id, patient_id, encounter_id, order_id,
    medication_system, medication_version, medication_code, medication_display,
    scheduled_dose, scheduled_unit, scheduled_at, given_dose, given_unit,
    given_at, route, site, outcome, reason, scan_performed, scanned_patient,
    scanned_medication, scanned_at, override_reason, override_by, override_at,
    override_patient_mismatch, override_medication_mismatch,
    override_not_scanned, idempotency_key, recorded_offline, administered_by,
    witnessed_by, recorded_at, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12::timestamptz,
    $13, $14, $15::timestamptz, $16, $17, $18, $19,
    $20, $21, $22, $23::timestamptz,
    $24, $25, $26::timestamptz, $27,
    $28, $29, $30,
    $31, $32, $33, $34, 1
)
`

type InsertAdministrationParams struct {
	AdministrationID           uuid.UUID
	TenantID                   uuid.UUID
	PatientID                  uuid.UUID
	EncounterID                uuid.UUID
	OrderID                    uuid.UUID
	MedicationSystem           string
	MedicationVersion          string
	MedicationCode             string
	MedicationDisplay          string
	ScheduledDose              float64
	ScheduledUnit              string
	ScheduledAt                pgtype.Timestamptz
	GivenDose                  float64
	GivenUnit                  string
	GivenAt                    pgtype.Timestamptz
	Route                      string
	Site                       string
	Outcome                    string
	Reason                     string
	ScanPerformed              bool
	ScannedPatient             string
	ScannedMedication          string
	ScannedAt                  pgtype.Timestamptz
	OverrideReason             string
	OverrideBy                 string
	OverrideAt                 pgtype.Timestamptz
	OverridePatientMismatch    bool
	OverrideMedicationMismatch bool
	OverrideNotScanned         bool
	IdempotencyKey             string
	RecordedOffline            bool
	AdministeredBy             string
	WitnessedBy                string
	RecordedAt                 pgtype.Timestamptz
}

// SRS-NUR-018: the unique index on (tenant, order, scheduled_at) rejects a
// second transcription of the same paper entry. The refusal is a constraint
// violation the adapter maps, not a check this query performs, because the two
// transcriptions can be in flight at the same moment.
func (q *Queries) InsertAdministration(ctx context.Context, arg InsertAdministrationParams) error {
	_, err := q.db.Exec(ctx, insertAdministration,
		arg.AdministrationID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.OrderID,
		arg.MedicationSystem,
		arg.MedicationVersion,
		arg.MedicationCode,
		arg.MedicationDisplay,
		arg.ScheduledDose,
		arg.ScheduledUnit,
		arg.ScheduledAt,
		arg.GivenDose,
		arg.GivenUnit,
		arg.GivenAt,
		arg.Route,
		arg.Site,
		arg.Outcome,
		arg.Reason,
		arg.ScanPerformed,
		arg.ScannedPatient,
		arg.ScannedMedication,
		arg.ScannedAt,
		arg.OverrideReason,
		arg.OverrideBy,
		arg.OverrideAt,
		arg.OverridePatientMismatch,
		arg.OverrideMedicationMismatch,
		arg.OverrideNotScanned,
		arg.IdempotencyKey,
		arg.RecordedOffline,
		arg.AdministeredBy,
		arg.WitnessedBy,
		arg.RecordedAt,
	)
	return err
}

const insertAssessment = `-- name: InsertAssessment :exec
INSERT INTO nursing.assessment (
    assessment_id, tenant_id, patient_id, encounter_id, kind, template_id,
    template_version, answers, assessed_at, recorded_at, assessed_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, 1
)
`

type InsertAssessmentParams struct {
	AssessmentID    uuid.UUID
	TenantID        uuid.UUID
	PatientID       uuid.UUID
	EncounterID     uuid.UUID
	Kind            string
	TemplateID      uuid.UUID
	TemplateVersion string
	Answers         []byte
	AssessedAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	AssessedBy      string
}

func (q *Queries) InsertAssessment(ctx context.Context, arg InsertAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertAssessment,
		arg.AssessmentID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Kind,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.Answers,
		arg.AssessedAt,
		arg.RecordedAt,
		arg.AssessedBy,
	)
	return err
}

const insertAssessmentTemplate = `-- name: InsertAssessmentTemplate :exec

INSERT INTO nursing.assessment_template (
    template_id, tenant_id, version, name, min_age_years, max_age_years,
    service_code, sections, retired, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, false, $9, $10
)
`

type InsertAssessmentTemplateParams struct {
	TemplateID  uuid.UUID
	TenantID    uuid.UUID
	Version     string
	Name        string
	MinAgeYears int32
	MaxAgeYears int32
	ServiceCode string
	Sections    []byte
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
}

// Nursing (SRS-NUR).
func (q *Queries) InsertAssessmentTemplate(ctx context.Context, arg InsertAssessmentTemplateParams) error {
	_, err := q.db.Exec(ctx, insertAssessmentTemplate,
		arg.TemplateID,
		arg.TenantID,
		arg.Version,
		arg.Name,
		arg.MinAgeYears,
		arg.MaxAgeYears,
		arg.ServiceCode,
		arg.Sections,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertAssignment = `-- name: InsertAssignment :exec
INSERT INTO nursing.assignment (
    assignment_id, tenant_id, unit_id, bed_id, patient_id, nurse_id,
    relationship, effective_from, assigned_by, version
) VALUES (
    $1, $2, $3, $4, $5::uuid, $6,
    $7, $8, $9, 1
)
`

type InsertAssignmentParams struct {
	AssignmentID  uuid.UUID
	TenantID      uuid.UUID
	UnitID        string
	BedID         string
	PatientID     pgtype.UUID
	NurseID       string
	Relationship  string
	EffectiveFrom pgtype.Timestamptz
	AssignedBy    string
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertAssignment,
		arg.AssignmentID,
		arg.TenantID,
		arg.UnitID,
		arg.BedID,
		arg.PatientID,
		arg.NurseID,
		arg.Relationship,
		arg.EffectiveFrom,
		arg.AssignedBy,
	)
	return err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO nursing.device (
    device_id, tenant_id, patient_id, encounter_id, kind, site, laterality,
    size, lot, inserted_at, inserted_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, 1
)
`

type InsertDeviceParams struct {
	DeviceID    uuid.UUID
	TenantID    uuid.UUID
	PatientID   uuid.UUID
	EncounterID uuid.UUID
	Kind        string
	Site        string
	Laterality  string
	Size        string
	Lot         string
	InsertedAt  pgtype.Timestamptz
	InsertedBy  string
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.Exec(ctx, insertDevice,
		arg.DeviceID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Kind,
		arg.Site,
		arg.Laterality,
		arg.Size,
		arg.Lot,
		arg.InsertedAt,
		arg.InsertedBy,
	)
	return err
}

const insertDeviceCare = `-- name: InsertDeviceCare :exec
INSERT INTO nursing.device_care (
    care_id, tenant_id, device_id, kind, finding, output_ml, performed_at,
    performed_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
`

type InsertDeviceCareParams struct {
	CareID      uuid.UUID
	TenantID    uuid.UUID
	DeviceID    uuid.UUID
	Kind        string
	Finding     string
	OutputMl    float64
	PerformedAt pgtype.Timestamptz
	PerformedBy string
}

func (q *Queries) InsertDeviceCare(ctx context.Context, arg InsertDeviceCareParams) error {
	_, err := q.db.Exec(ctx, insertDeviceCare,
		arg.CareID,
		arg.TenantID,
		arg.DeviceID,
		arg.Kind,
		arg.Finding,
		arg.OutputMl,
		arg.PerformedAt,
		arg.PerformedBy,
	)
	return err
}

const insertEducation = `-- name: InsertEducation :exec
INSERT INTO nursing.education (
    education_id, tenant_id, patient_id, encounter_id, topic_system,
    topic_version, topic_code, topic_display, learner, learner_name, method,
    understanding, barriers, taught_at, taught_by, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, 1
)
`

type InsertEducationParams struct {
	EducationID   uuid.UUID
	TenantID      uuid.UUID
	PatientID     uuid.UUID
	EncounterID   uuid.UUID
	TopicSystem   string
	TopicVersion  string
	TopicCode     string
	TopicDisplay  string
	Learner       string
	LearnerName   string
	Method        string
	Understanding string
	Barriers      string
	TaughtAt      pgtype.Timestamptz
	TaughtBy      string
}

func (q *Queries) InsertEducation(ctx context.Context, arg InsertEducationParams) error {
	_, err := q.db.Exec(ctx, insertEducation,
		arg.EducationID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.TopicSystem,
		arg.TopicVersion,
		arg.TopicCode,
		arg.TopicDisplay,
		arg.Learner,
		arg.LearnerName,
		arg.Method,
		arg.Understanding,
		arg.Barriers,
		arg.TaughtAt,
		arg.TaughtBy,
	)
	return err
}

const insertFlowsheetEntry = `-- name: InsertFlowsheetEntry :exec
INSERT INTO nursing.flowsheet_entry (
    entry_id, tenant_id, patient_id, encounter_id, code_system, code_version,
    code, code_display, value_number, value_unit, value_text, coded_system,
    coded_code, coded_display, observed_at, recorded_at, source, device_id,
    recorded_by, late_entry_reason, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9::double precision, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, 1
)
`

type InsertFlowsheetEntryParams struct {
	EntryID         uuid.UUID
	TenantID        uuid.UUID
	PatientID       uuid.UUID
	EncounterID     uuid.UUID
	CodeSystem      string
	CodeVersion     string
	Code            string
	CodeDisplay     string
	ValueNumber     *float64
	ValueUnit       string
	ValueText       string
	CodedSystem     string
	CodedCode       string
	CodedDisplay    string
	ObservedAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	Source          string
	DeviceID        string
	RecordedBy      string
	LateEntryReason string
}

func (q *Queries) InsertFlowsheetEntry(ctx context.Context, arg InsertFlowsheetEntryParams) error {
	_, err := q.db.Exec(ctx, insertFlowsheetEntry,
		arg.EntryID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.CodeSystem,
		arg.CodeVersion,
		arg.Code,
		arg.CodeDisplay,
		arg.ValueNumber,
		arg.ValueUnit,
		arg.ValueText,
		arg.CodedSystem,
		arg.CodedCode,
		arg.CodedDisplay,
		arg.ObservedAt,
		arg.RecordedAt,
		arg.Source,
		arg.DeviceID,
		arg.RecordedBy,
		arg.LateEntryReason,
	)
	return err
}

const insertFluidEntry = `-- name: InsertFluidEntry :exec
INSERT INTO nursing.fluid_entry (
    fluid_id, tenant_id, patient_id, encounter_id, direction, category,
    volume_ml, observed_at, recorded_at, recorded_by, supersedes_id,
    amendment_reason, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11::uuid,
    $12, 1
)
`

type InsertFluidEntryParams struct {
	FluidID         uuid.UUID
	TenantID        uuid.UUID
	PatientID       uuid.UUID
	EncounterID     uuid.UUID
	Direction       string
	Category        string
	VolumeMl        float64
	ObservedAt      pgtype.Timestamptz
	RecordedAt      pgtype.Timestamptz
	RecordedBy      string
	SupersedesID    pgtype.UUID
	AmendmentReason string
}

func (q *Queries) InsertFluidEntry(ctx context.Context, arg InsertFluidEntryParams) error {
	_, err := q.db.Exec(ctx, insertFluidEntry,
		arg.FluidID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Direction,
		arg.Category,
		arg.VolumeMl,
		arg.ObservedAt,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.SupersedesID,
		arg.AmendmentReason,
	)
	return err
}

const insertHandover = `-- name: InsertHandover :exec
INSERT INTO nursing.handover (
    handover_id, tenant_id, patient_id, encounter_id, unit_id,
    from_shift_code, from_shift_start, from_shift_end,
    to_shift_code, to_shift_start, to_shift_end,
    situation, background, assessment, recommendation, critical_risks,
    outstanding, devices, pending_tasks, composed_at, composed_by, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7::timestamptz,
    $8::timestamptz,
    $9, $10::timestamptz,
    $11::timestamptz,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, 1
)
`

type InsertHandoverParams struct {
	HandoverID     uuid.UUID
	TenantID       uuid.UUID
	PatientID      uuid.UUID
	EncounterID    uuid.UUID
	UnitID         string
	FromShiftCode  string
	FromShiftStart pgtype.Timestamptz
	FromShiftEnd   pgtype.Timestamptz
	ToShiftCode    string
	ToShiftStart   pgtype.Timestamptz
	ToShiftEnd     pgtype.Timestamptz
	Situation      string
	Background     string
	Assessment     string
	Recommendation string
	CriticalRisks  []string
	Outstanding    []string
	Devices        []byte
	PendingTasks   []byte
	ComposedAt     pgtype.Timestamptz
	ComposedBy     string
}

func (q *Queries) InsertHandover(ctx context.Context, arg InsertHandoverParams) error {
	_, err := q.db.Exec(ctx, insertHandover,
		arg.HandoverID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.UnitID,
		arg.FromShiftCode,
		arg.FromShiftStart,
		arg.FromShiftEnd,
		arg.ToShiftCode,
		arg.ToShiftStart,
		arg.ToShiftEnd,
		arg.Situation,
		arg.Background,
		arg.Assessment,
		arg.Recommendation,
		arg.CriticalRisks,
		arg.Outstanding,
		arg.Devices,
		arg.PendingTasks,
		arg.ComposedAt,
		arg.ComposedBy,
	)
	return err
}

const insertNursingCarePlan = `-- name: InsertNursingCarePlan :exec
INSERT INTO nursing.care_plan (
    plan_id, tenant_id, patient_id, encounter_id, title, problems, status,
    created_at, created_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    'active', $7, $8, 1
)
`

type InsertNursingCarePlanParams struct {
	PlanID      uuid.UUID
	TenantID    uuid.UUID
	PatientID   uuid.UUID
	EncounterID uuid.UUID
	Title       string
	Problems    []byte
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
}

func (q *Queries) InsertNursingCarePlan(ctx context.Context, arg InsertNursingCarePlanParams) error {
	_, err := q.db.Exec(ctx, insertNursingCarePlan,
		arg.PlanID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Title,
		arg.Problems,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertNursingDowntime = `-- name: InsertNursingDowntime :exec
INSERT INTO nursing.downtime_episode (
    episode_id, tenant_id, unit_id, reason, started_at, started_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6, 1
)
`

type InsertNursingDowntimeParams struct {
	EpisodeID uuid.UUID
	TenantID  uuid.UUID
	UnitID    string
	Reason    string
	StartedAt pgtype.Timestamptz
	StartedBy string
}

func (q *Queries) InsertNursingDowntime(ctx context.Context, arg InsertNursingDowntimeParams) error {
	_, err := q.db.Exec(ctx, insertNursingDowntime,
		arg.EpisodeID,
		arg.TenantID,
		arg.UnitID,
		arg.Reason,
		arg.StartedAt,
		arg.StartedBy,
	)
	return err
}

const insertRestraint = `-- name: InsertRestraint :exec
INSERT INTO nursing.restraint (
    restraint_id, tenant_id, patient_id, encounter_id, kind, description,
    authorized_by, authorized_at, expires_at, indication, renewals,
    started_at, started_by, monitor_every_seconds, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, 1
)
`

type InsertRestraintParams struct {
	RestraintID         uuid.UUID
	TenantID            uuid.UUID
	PatientID           uuid.UUID
	EncounterID         uuid.UUID
	Kind                string
	Description         string
	AuthorizedBy        string
	AuthorizedAt        pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	Indication          string
	Renewals            []byte
	StartedAt           pgtype.Timestamptz
	StartedBy           string
	MonitorEverySeconds int64
}

func (q *Queries) InsertRestraint(ctx context.Context, arg InsertRestraintParams) error {
	_, err := q.db.Exec(ctx, insertRestraint,
		arg.RestraintID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Kind,
		arg.Description,
		arg.AuthorizedBy,
		arg.AuthorizedAt,
		arg.ExpiresAt,
		arg.Indication,
		arg.Renewals,
		arg.StartedAt,
		arg.StartedBy,
		arg.MonitorEverySeconds,
	)
	return err
}

const insertRestraintCheck = `-- name: InsertRestraintCheck :exec
INSERT INTO nursing.restraint_check (
    check_id, tenant_id, restraint_id, observed_at, observed_by, findings,
    continued_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
`

type InsertRestraintCheckParams struct {
	CheckID         uuid.UUID
	TenantID        uuid.UUID
	RestraintID     uuid.UUID
	ObservedAt      pgtype.Timestamptz
	ObservedBy      string
	Findings        string
	ContinuedReason string
}

func (q *Queries) InsertRestraintCheck(ctx context.Context, arg InsertRestraintCheckParams) error {
	_, err := q.db.Exec(ctx, insertRestraintCheck,
		arg.CheckID,
		arg.TenantID,
		arg.RestraintID,
		arg.ObservedAt,
		arg.ObservedBy,
		arg.Findings,
		arg.ContinuedReason,
	)
	return err
}

const insertRiskAssessment = `-- name: InsertRiskAssessment :exec
INSERT INTO nursing.risk_assessment (
    risk_id, tenant_id, patient_id, encounter_id, scale_id, scale_version,
    risk_domain, inputs, total, band, escalate, assessed_at, recorded_at,
    assessed_by, due_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, 1
)
`

type InsertRiskAssessmentParams struct {
	RiskID       uuid.UUID
	TenantID     uuid.UUID
	PatientID    uuid.UUID
	EncounterID  uuid.UUID
	ScaleID      uuid.UUID
	ScaleVersion string
	RiskDomain   string
	Inputs       []byte
	Total        int32
	Band         string
	Escalate     bool
	AssessedAt   pgtype.Timestamptz
	RecordedAt   pgtype.Timestamptz
	AssessedBy   string
	DueAt        pgtype.Timestamptz
}

func (q *Queries) InsertRiskAssessment(ctx context.Context, arg InsertRiskAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertRiskAssessment,
		arg.RiskID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.ScaleID,
		arg.ScaleVersion,
		arg.RiskDomain,
		arg.Inputs,
		arg.Total,
		arg.Band,
		arg.Escalate,
		arg.AssessedAt,
		arg.RecordedAt,
		arg.AssessedBy,
		arg.DueAt,
	)
	return err
}

const insertRiskScale = `-- name: InsertRiskScale :exec
INSERT INTO nursing.risk_scale (
    scale_id, tenant_id, version, name, risk_domain, inputs, bands,
    reassess_after_seconds, retired, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, false, $9, $10
)
`

type InsertRiskScaleParams struct {
	ScaleID              uuid.UUID
	TenantID             uuid.UUID
	Version              string
	Name                 string
	RiskDomain           string
	Inputs               []byte
	Bands                []byte
	ReassessAfterSeconds int64
	CreatedBy            string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertRiskScale(ctx context.Context, arg InsertRiskScaleParams) error {
	_, err := q.db.Exec(ctx, insertRiskScale,
		arg.ScaleID,
		arg.TenantID,
		arg.Version,
		arg.Name,
		arg.RiskDomain,
		arg.Inputs,
		arg.Bands,
		arg.ReassessAfterSeconds,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO nursing.task (
    task_id, tenant_id, patient_id, encounter_id, description, priority,
    due_at, source_kind, source_id, recur_every_seconds, recur_until, status,
    assigned_to, created_at, created_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11::timestamptz,
    'pending', $12, $13, $14, 1
)
`

type InsertTaskParams struct {
	TaskID            uuid.UUID
	TenantID          uuid.UUID
	PatientID         uuid.UUID
	EncounterID       uuid.UUID
	Description       string
	Priority          string
	DueAt             pgtype.Timestamptz
	SourceKind        string
	SourceID          string
	RecurEverySeconds int64
	RecurUntil        pgtype.Timestamptz
	AssignedTo        string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         string
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.TaskID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.Description,
		arg.Priority,
		arg.DueAt,
		arg.SourceKind,
		arg.SourceID,
		arg.RecurEverySeconds,
		arg.RecurUntil,
		arg.AssignedTo,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertWoundAssessment = `-- name: InsertWoundAssessment :exec
INSERT INTO nursing.wound_assessment (
    wound_assessment_id, tenant_id, patient_id, encounter_id, wound_id,
    location, body_map_system, body_map_code, body_map_display, laterality,
    kind, stage, length_mm, width_mm, depth_mm, appearance, exudate,
    surrounding_skin, pain_score, assessed_at, recorded_at, assessed_by, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19::integer, $20, $21, $22, 1
)
`

type InsertWoundAssessmentParams struct {
	WoundAssessmentID uuid.UUID
	TenantID          uuid.UUID
	PatientID         uuid.UUID
	EncounterID       uuid.UUID
	WoundID           string
	Location          string
	BodyMapSystem     string
	BodyMapCode       string
	BodyMapDisplay    string
	Laterality        string
	Kind              string
	Stage             string
	LengthMm          float64
	WidthMm           float64
	DepthMm           float64
	Appearance        string
	Exudate           string
	SurroundingSkin   string
	PainScore         *int32
	AssessedAt        pgtype.Timestamptz
	RecordedAt        pgtype.Timestamptz
	AssessedBy        string
}

func (q *Queries) InsertWoundAssessment(ctx context.Context, arg InsertWoundAssessmentParams) error {
	_, err := q.db.Exec(ctx, insertWoundAssessment,
		arg.WoundAssessmentID,
		arg.TenantID,
		arg.PatientID,
		arg.EncounterID,
		arg.WoundID,
		arg.Location,
		arg.BodyMapSystem,
		arg.BodyMapCode,
		arg.BodyMapDisplay,
		arg.Laterality,
		arg.Kind,
		arg.Stage,
		arg.LengthMm,
		arg.WidthMm,
		arg.DepthMm,
		arg.Appearance,
		arg.Exudate,
		arg.SurroundingSkin,
		arg.PainScore,
		arg.AssessedAt,
		arg.RecordedAt,
		arg.AssessedBy,
	)
	return err
}

const insertWoundImage = `-- name: InsertWoundImage :exec
INSERT INTO nursing.wound_image (
    image_id, tenant_id, wound_assessment_id, consent_id, storage_key,
    content_type, captured_at, captured_by, sequence
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertWoundImageParams struct {
	ImageID           uuid.UUID
	TenantID          uuid.UUID
	WoundAssessmentID uuid.UUID
	ConsentID         uuid.UUID
	StorageKey        string
	ContentType       string
	CapturedAt        pgtype.Timestamptz
	CapturedBy        string
	Sequence          int32
}

func (q *Queries) InsertWoundImage(ctx context.Context, arg InsertWoundImageParams) error {
	_, err := q.db.Exec(ctx, insertWoundImage,
		arg.ImageID,
		arg.TenantID,
		arg.WoundAssessmentID,
		arg.ConsentID,
		arg.StorageKey,
		arg.ContentType,
		arg.CapturedAt,
		arg.CapturedBy,
		arg.Sequence,
	)
	return err
}

const latestRiskAssessment = `-- name: LatestRiskAssessment :one
SELECT risk_id, tenant_id, patient_id, encounter_id, scale_id, scale_version,
       risk_domain, inputs, total, band, escalate, assessed_at, recorded_at,
       assessed_by, due_at, superseded_by_id, version
FROM nursing.risk_assessment
WHERE tenant_id = $1 AND patient_id = $2
  AND risk_domain = $3 AND superseded_by_id IS NULL
ORDER BY assessed_at DESC
LIMIT 1
`

type LatestRiskAssessmentParams struct {
	TenantID   uuid.UUID
	PatientID  uuid.UUID
	RiskDomain string
}

func (q *Queries) LatestRiskAssessment(ctx context.Context, arg LatestRiskAssessmentParams) (NursingRiskAssessment, error) {
	row := q.db.QueryRow(ctx, latestRiskAssessment, arg.TenantID, arg.PatientID, arg.RiskDomain)
	var i NursingRiskAssessment
	err := row.Scan(
		&i.RiskID,
		&i.TenantID,
		&i.PatientID,
		&i.EncounterID,
		&i.ScaleID,
		&i.ScaleVersion,
		&i.RiskDomain,
		&i.Inputs,
		&i.Total,
		&i.Band,
		&i.Escalate,
		&i.AssessedAt,
		&i.RecordedAt,
		&i.AssessedBy,
		&i.DueAt,
		&i.SupersededByID,
		&i.Version,
	)
	return i, err
}

const listAdministrations = `-- name: ListAdministrations :many
SELECT administration_id, tenant_id, patient_id, encounter_id, order_id,
       medication_system, medication_version, medication_code,
       medication_display, scheduled_dose, scheduled_unit, scheduled_at,
       given_dose, given_unit, given_at, route, site, outcome, reason,
       scan_performed, scanned_patient, scanned_medication, scanned_at,
       override_reason, override_by, override_at, override_patient_mismatch,
       override_medication_mismatch, override_not_scanned, idempotency_key,
       recorded_offline, administered_by, witnessed_by, recorded_at, version
FROM nursing.administration
WHERE tenant_id = $1
  AND encounter_id = $2
  AND ($3::uuid IS NULL
       OR order_id = $3::uuid)
ORDER BY COALESCE(scheduled_at, given_at, recorded_at) DESC
LIMIT $4
`

type ListAdministrationsParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	OrderFilter pgtype.UUID
	PageLimit   int32
}

func (q *Queries) ListAdministrations(ctx context.Context, arg ListAdministrationsParams) ([]NursingAdministration, error) {
	rows, err := q.db.Query(ctx, listAdministrations,
		arg.TenantID,
		arg.EncounterID,
		arg.OrderFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingAdministration{}
	for rows.Next() {
		var i NursingAdministration
		if err := rows.Scan(
			&i.AdministrationID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.OrderID,
			&i.MedicationSystem,
			&i.MedicationVersion,
			&i.MedicationCode,
			&i.MedicationDisplay,
			&i.ScheduledDose,
			&i.ScheduledUnit,
			&i.ScheduledAt,
			&i.GivenDose,
			&i.GivenUnit,
			&i.GivenAt,
			&i.Route,
			&i.Site,
			&i.Outcome,
			&i.Reason,
			&i.ScanPerformed,
			&i.ScannedPatient,
			&i.ScannedMedication,
			&i.ScannedAt,
			&i.OverrideReason,
			&i.OverrideBy,
			&i.OverrideAt,
			&i.OverridePatientMismatch,
			&i.OverrideMedicationMismatch,
			&i.OverrideNotScanned,
			&i.IdempotencyKey,
			&i.RecordedOffline,
			&i.AdministeredBy,
			&i.WitnessedBy,
			&i.RecordedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentTemplates = `-- name: ListAssessmentTemplates :many
SELECT template_id, tenant_id, version, name, min_age_years, max_age_years,
       service_code, sections, retired, created_by, created_at
FROM nursing.assessment_template
WHERE tenant_id = $1
  AND ($2::boolean = true OR retired = false)
  AND ($3::text = '' OR service_code = $3::text
       OR service_code = '')
ORDER BY name, version
LIMIT $4
`

type ListAssessmentTemplatesParams struct {
	TenantID       uuid.UUID
	IncludeRetired bool
	ServiceFilter  string
	PageLimit      int32
}

// Only the choosable ones by default: a retired template can be read on an old
// assessment but must not be picked for a new one.
func (q *Queries) ListAssessmentTemplates(ctx context.Context, arg ListAssessmentTemplatesParams) ([]NursingAssessmentTemplate, error) {
	rows, err := q.db.Query(ctx, listAssessmentTemplates,
		arg.TenantID,
		arg.IncludeRetired,
		arg.ServiceFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingAssessmentTemplate{}
	for rows.Next() {
		var i NursingAssessmentTemplate
		if err := rows.Scan(
			&i.TemplateID,
			&i.TenantID,
			&i.Version,
			&i.Name,
			&i.MinAgeYears,
			&i.MaxAgeYears,
			&i.ServiceCode,
			&i.Sections,
			&i.Retired,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessments = `-- name: ListAssessments :many
SELECT assessment_id, tenant_id, patient_id, encounter_id, kind, template_id,
       template_version, answers, assessed_at, recorded_at, assessed_by, version
FROM nursing.assessment
WHERE tenant_id = $1
  AND encounter_id = $2
  AND ($3::text = '' OR kind = $3::text)
ORDER BY assessed_at DESC
LIMIT $4
`

type ListAssessmentsParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	KindFilter  string
	PageLimit   int32
}

func (q *Queries) ListAssessments(ctx context.Context, arg ListAssessmentsParams) ([]NursingAssessment, error) {
	rows, err := q.db.Query(ctx, listAssessments,
		arg.TenantID,
		arg.EncounterID,
		arg.KindFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingAssessment{}
	for rows.Next() {
		var i NursingAssessment
		if err := rows.Scan(
			&i.AssessmentID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Kind,
			&i.TemplateID,
			&i.TemplateVersion,
			&i.Answers,
			&i.AssessedAt,
			&i.RecordedAt,
			&i.AssessedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignments = `-- name: ListAssignments :many
SELECT assignment_id, tenant_id, unit_id, bed_id, patient_id, nurse_id,
       relationship, effective_from, effective_to, assigned_by, ended_reason,
       version
FROM nursing.assignment
WHERE tenant_id = $1
  AND ($2::text = '' OR unit_id = $2::text)
  AND ($3::uuid IS NULL
       OR patient_id = $3::uuid)
  AND ($4::text = '' OR nurse_id = $4::text)
  AND effective_from <= $5
  AND (effective_to IS NULL OR effective_to > $5)
ORDER BY effective_from DESC
LIMIT $6
`

type ListAssignmentsParams struct {
	TenantID      uuid.UUID
	UnitFilter    string
	PatientFilter pgtype.UUID
	NurseFilter   string
	AsOf          pgtype.Timestamptz
	PageLimit     int32
}

// Answered as of a time, because the question an incident review asks is "who
// was looking after this patient at 03:40".
func (q *Queries) ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]NursingAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignments,
		arg.TenantID,
		arg.UnitFilter,
		arg.PatientFilter,
		arg.NurseFilter,
		arg.AsOf,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingAssignment{}
	for rows.Next() {
		var i NursingAssignment
		if err := rows.Scan(
			&i.AssignmentID,
			&i.TenantID,
			&i.UnitID,
			&i.BedID,
			&i.PatientID,
			&i.NurseID,
			&i.Relationship,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.AssignedBy,
			&i.EndedReason,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceCare = `-- name: ListDeviceCare :many
SELECT care_id, tenant_id, device_id, kind, finding, output_ml, performed_at,
       performed_by
FROM nursing.device_care
WHERE tenant_id = $1 AND device_id = $2
ORDER BY performed_at DESC
LIMIT $3
`

type ListDeviceCareParams struct {
	TenantID  uuid.UUID
	DeviceID  uuid.UUID
	PageLimit int32
}

func (q *Queries) ListDeviceCare(ctx context.Context, arg ListDeviceCareParams) ([]NursingDeviceCare, error) {
	rows, err := q.db.Query(ctx, listDeviceCare, arg.TenantID, arg.DeviceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingDeviceCare{}
	for rows.Next() {
		var i NursingDeviceCare
		if err := rows.Scan(
			&i.CareID,
			&i.TenantID,
			&i.DeviceID,
			&i.Kind,
			&i.Finding,
			&i.OutputMl,
			&i.PerformedAt,
			&i.PerformedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT device_id, tenant_id, patient_id, encounter_id, kind, site, laterality,
       size, lot, inserted_at, inserted_by, removed_at, removed_by,
       removal_reason, version
FROM nursing.device
WHERE tenant_id = $1
  AND encounter_id = $2
  AND ($3::boolean = false OR removed_at IS NULL)
ORDER BY inserted_at DESC
LIMIT $4
`

type ListDevicesParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	InPlaceOnly bool
	PageLimit   int32
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]NursingDevice, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.TenantID,
		arg.EncounterID,
		arg.InPlaceOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingDevice{}
	for rows.Next() {
		var i NursingDevice
		if err := rows.Scan(
			&i.DeviceID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Kind,
			&i.Site,
			&i.Laterality,
			&i.Size,
			&i.Lot,
			&i.InsertedAt,
			&i.InsertedBy,
			&i.RemovedAt,
			&i.RemovedBy,
			&i.RemovalReason,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueRiskAssessments = `-- name: ListDueRiskAssessments :many
SELECT risk_id, tenant_id, patient_id, encounter_id, scale_id, scale_version,
       risk_domain, inputs, total, band, escalate, assessed_at, recorded_at,
       assessed_by, due_at, superseded_by_id, version
FROM nursing.risk_assessment
WHERE tenant_id = $1
  AND superseded_by_id IS NULL
  AND due_at <= $2
  AND ($3::uuid IS NULL
       OR encounter_id = $3::uuid)
ORDER BY due_at
LIMIT $4
`

type ListDueRiskAssessmentsParams struct {
	TenantID        uuid.UUID
	AsOf            pgtype.Timestamptz
	EncounterFilter pgtype.UUID
	PageLimit       int32
}

// SRS-NUR-005: due reassessment appears as work.
func (q *Queries) ListDueRiskAssessments(ctx context.Context, arg ListDueRiskAssessmentsParams) ([]NursingRiskAssessment, error) {
	rows, err := q.db.Query(ctx, listDueRiskAssessments,
		arg.TenantID,
		arg.AsOf,
		arg.EncounterFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingRiskAssessment{}
	for rows.Next() {
		var i NursingRiskAssessment
		if err := rows.Scan(
			&i.RiskID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.ScaleID,
			&i.ScaleVersion,
			&i.RiskDomain,
			&i.Inputs,
			&i.Total,
			&i.Band,
			&i.Escalate,
			&i.AssessedAt,
			&i.RecordedAt,
			&i.AssessedBy,
			&i.DueAt,
			&i.SupersededByID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEducation = `-- name: ListEducation :many
SELECT education_id, tenant_id, patient_id, encounter_id, topic_system,
       topic_version, topic_code, topic_display, learner, learner_name, method,
       understanding, barriers, taught_at, taught_by, version
FROM nursing.education
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY taught_at DESC
LIMIT $3
`

type ListEducationParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	PageLimit int32
}

func (q *Queries) ListEducation(ctx context.Context, arg ListEducationParams) ([]NursingEducation, error) {
	rows, err := q.db.Query(ctx, listEducation, arg.TenantID, arg.PatientID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingEducation{}
	for rows.Next() {
		var i NursingEducation
		if err := rows.Scan(
			&i.EducationID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.TopicSystem,
			&i.TopicVersion,
			&i.TopicCode,
			&i.TopicDisplay,
			&i.Learner,
			&i.LearnerName,
			&i.Method,
			&i.Understanding,
			&i.Barriers,
			&i.TaughtAt,
			&i.TaughtBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRestraints = `-- name: ListExpiredRestraints :many
SELECT restraint_id, tenant_id, patient_id, encounter_id, kind, description,
       authorized_by, expires_at, indication, started_at, monitor_every_seconds,
       version
FROM nursing.restraint
WHERE tenant_id = $1
  AND discontinued_at IS NULL
  AND expires_at <= $2
ORDER BY expires_at
LIMIT $3
`

type ListExpiredRestraintsParams struct {
	TenantID  uuid.UUID
	AsOf      pgtype.Timestamptz
	PageLimit int32
}

type ListExpiredRestraintsRow struct {
	RestraintID         uuid.UUID
	TenantID            uuid.UUID
	PatientID           uuid.UUID
	EncounterID         uuid.UUID
	Kind                string
	Description         string
	AuthorizedBy        string
	ExpiresAt           pgtype.Timestamptz
	Indication          string
	StartedAt           pgtype.Timestamptz
	MonitorEverySeconds int64
	Version             int64
}

// SRS-NUR-013: an expired authorization raises an alert. It does not free the
// patient, so these rows are still active restraints.
func (q *Queries) ListExpiredRestraints(ctx context.Context, arg ListExpiredRestraintsParams) ([]ListExpiredRestraintsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredRestraints, arg.TenantID, arg.AsOf, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredRestraintsRow{}
	for rows.Next() {
		var i ListExpiredRestraintsRow
		if err := rows.Scan(
			&i.RestraintID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Kind,
			&i.Description,
			&i.AuthorizedBy,
			&i.ExpiresAt,
			&i.Indication,
			&i.StartedAt,
			&i.MonitorEverySeconds,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsheetEntries = `-- name: ListFlowsheetEntries :many
SELECT entry_id, tenant_id, patient_id, encounter_id, code_system, code_version,
       code, code_display, value_number, value_unit, value_text, coded_system,
       coded_code, coded_display, observed_at, recorded_at, source, device_id,
       recorded_by, late_entry_reason, superseded_by_id, version
FROM nursing.flowsheet_entry
WHERE tenant_id = $1
  AND encounter_id = $2
  AND ($3::text = '' OR code = $3::text)
  AND observed_at >= $4
  AND observed_at < $5
  AND superseded_by_id IS NULL
ORDER BY observed_at, recorded_at
LIMIT $6
`

type ListFlowsheetEntriesParams struct {
	TenantID     uuid.UUID
	EncounterID  uuid.UUID
	CodeFilter   string
	ObservedFrom pgtype.Timestamptz
	ObservedTo   pgtype.Timestamptz
	PageLimit    int32
}

// Ordered by observation time, because sorting by typing order puts a late
// 06:00 reading after the 08:00 one and draws a graph saying the patient
// improved and then deteriorated.
func (q *Queries) ListFlowsheetEntries(ctx context.Context, arg ListFlowsheetEntriesParams) ([]NursingFlowsheetEntry, error) {
	rows, err := q.db.Query(ctx, listFlowsheetEntries,
		arg.TenantID,
		arg.EncounterID,
		arg.CodeFilter,
		arg.ObservedFrom,
		arg.ObservedTo,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingFlowsheetEntry{}
	for rows.Next() {
		var i NursingFlowsheetEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.CodeSystem,
			&i.CodeVersion,
			&i.Code,
			&i.CodeDisplay,
			&i.ValueNumber,
			&i.ValueUnit,
			&i.ValueText,
			&i.CodedSystem,
			&i.CodedCode,
			&i.CodedDisplay,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.Source,
			&i.DeviceID,
			&i.RecordedBy,
			&i.LateEntryReason,
			&i.SupersededByID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFluidEntries = `-- name: ListFluidEntries :many
SELECT fluid_id, tenant_id, patient_id, encounter_id, direction, category,
       volume_ml, observed_at, recorded_at, recorded_by, superseded_by_id,
       supersedes_id, amendment_reason, voided_reason, version
FROM nursing.fluid_entry
WHERE tenant_id = $1
  AND encounter_id = $2
  AND observed_at >= $3
  AND observed_at < $4
  AND ($5::boolean = true
       OR (superseded_by_id IS NULL AND voided_reason = ''))
ORDER BY observed_at, recorded_at
LIMIT $6
`

type ListFluidEntriesParams struct {
	TenantID          uuid.UUID
	EncounterID       uuid.UUID
	ObservedFrom      pgtype.Timestamptz
	ObservedTo        pgtype.Timestamptz
	IncludeSuperseded bool
	PageLimit         int32
}

// Bounded by observation time, so a 06:00 reading charted at 08:40 falls in the
// night shift's balance where it belongs.
func (q *Queries) ListFluidEntries(ctx context.Context, arg ListFluidEntriesParams) ([]NursingFluidEntry, error) {
	rows, err := q.db.Query(ctx, listFluidEntries,
		arg.TenantID,
		arg.EncounterID,
		arg.ObservedFrom,
		arg.ObservedTo,
		arg.IncludeSuperseded,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingFluidEntry{}
	for rows.Next() {
		var i NursingFluidEntry
		if err := rows.Scan(
			&i.FluidID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Direction,
			&i.Category,
			&i.VolumeMl,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.SupersededByID,
			&i.SupersedesID,
			&i.AmendmentReason,
			&i.VoidedReason,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandovers = `-- name: ListHandovers :many
SELECT handover_id, tenant_id, patient_id, encounter_id, unit_id,
       from_shift_code, from_shift_start, from_shift_end,
       to_shift_code, to_shift_start, to_shift_end,
       situation, background, assessment, recommendation, critical_risks,
       outstanding, devices, pending_tasks, composed_at, composed_by,
       acknowledged_at, acknowledged_by, questions, version
FROM nursing.handover
WHERE tenant_id = $1
  AND ($2::uuid IS NULL
       OR encounter_id = $2::uuid)
  AND ($3::boolean = false OR acknowledged_at IS NULL)
ORDER BY composed_at DESC
LIMIT $4
`

type ListHandoversParams struct {
	TenantID           uuid.UUID
	EncounterFilter    pgtype.UUID
	UnacknowledgedOnly bool
	PageLimit          int32
}

func (q *Queries) ListHandovers(ctx context.Context, arg ListHandoversParams) ([]NursingHandover, error) {
	rows, err := q.db.Query(ctx, listHandovers,
		arg.TenantID,
		arg.EncounterFilter,
		arg.UnacknowledgedOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingHandover{}
	for rows.Next() {
		var i NursingHandover
		if err := rows.Scan(
			&i.HandoverID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.UnitID,
			&i.FromShiftCode,
			&i.FromShiftStart,
			&i.FromShiftEnd,
			&i.ToShiftCode,
			&i.ToShiftStart,
			&i.ToShiftEnd,
			&i.Situation,
			&i.Background,
			&i.Assessment,
			&i.Recommendation,
			&i.CriticalRisks,
			&i.Outstanding,
			&i.Devices,
			&i.PendingTasks,
			&i.ComposedAt,
			&i.ComposedBy,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.Questions,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNursingCarePlans = `-- name: ListNursingCarePlans :many
SELECT plan_id, tenant_id, patient_id, encounter_id, title, problems, status,
       created_at, created_by, reviewed_at, reviewed_by, evaluation, version
FROM nursing.care_plan
WHERE tenant_id = $1 AND encounter_id = $2
  AND ($3::boolean = false OR status = 'active')
ORDER BY created_at DESC
LIMIT $4
`

type ListNursingCarePlansParams struct {
	TenantID    uuid.UUID
	EncounterID uuid.UUID
	ActiveOnly  bool
	PageLimit   int32
}

func (q *Queries) ListNursingCarePlans(ctx context.Context, arg ListNursingCarePlansParams) ([]NursingCarePlan, error) {
	rows, err := q.db.Query(ctx, listNursingCarePlans,
		arg.TenantID,
		arg.EncounterID,
		arg.ActiveOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingCarePlan{}
	for rows.Next() {
		var i NursingCarePlan
		if err := rows.Scan(
			&i.PlanID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Title,
			&i.Problems,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.Evaluation,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNursingDowntime = `-- name: ListNursingDowntime :many
SELECT episode_id, tenant_id, unit_id, reason, started_at, started_by,
       ended_at, ended_by, reconciled_at, reconciled_by, version
FROM nursing.downtime_episode
WHERE tenant_id = $1
  AND ($2::text = '' OR unit_id = $2::text)
  AND ($3::boolean = false OR reconciled_at IS NULL)
ORDER BY started_at DESC
LIMIT $4
`

type ListNursingDowntimeParams struct {
	TenantID         uuid.UUID
	UnitFilter       string
	UnreconciledOnly bool
	PageLimit        int32
}

func (q *Queries) ListNursingDowntime(ctx context.Context, arg ListNursingDowntimeParams) ([]NursingDowntimeEpisode, error) {
	rows, err := q.db.Query(ctx, listNursingDowntime,
		arg.TenantID,
		arg.UnitFilter,
		arg.UnreconciledOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingDowntimeEpisode{}
	for rows.Next() {
		var i NursingDowntimeEpisode
		if err := rows.Scan(
			&i.EpisodeID,
			&i.TenantID,
			&i.UnitID,
			&i.Reason,
			&i.StartedAt,
			&i.StartedBy,
			&i.EndedAt,
			&i.EndedBy,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverrides = `-- name: ListOverrides :many
SELECT administration_id, tenant_id, patient_id, encounter_id, order_id,
       medication_display, override_reason, override_by, override_at,
       override_patient_mismatch, override_medication_mismatch,
       override_not_scanned, administered_by
FROM nursing.administration
WHERE tenant_id = $1
  AND override_reason <> ''
  AND override_at >= $2
  AND override_at < $3
ORDER BY override_at DESC
LIMIT $4
`

type ListOverridesParams struct {
	TenantID  uuid.UUID
	FromTime  pgtype.Timestamptz
	ToTime    pgtype.Timestamptz
	PageLimit int32
}

type ListOverridesRow struct {
	AdministrationID           uuid.UUID
	TenantID                   uuid.UUID
	PatientID                  uuid.UUID
	EncounterID                uuid.UUID
	OrderID                    uuid.UUID
	MedicationDisplay          string
	OverrideReason             string
	OverrideBy                 string
	OverrideAt                 pgtype.Timestamptz
	OverridePatientMismatch    bool
	OverrideMedicationMismatch bool
	OverrideNotScanned         bool
	AdministeredBy             string
}

// The report that gets a broken scanner replaced (SRS-NUR-008).
func (q *Queries) ListOverrides(ctx context.Context, arg ListOverridesParams) ([]ListOverridesRow, error) {
	rows, err := q.db.Query(ctx, listOverrides,
		arg.TenantID,
		arg.FromTime,
		arg.ToTime,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverridesRow{}
	for rows.Next() {
		var i ListOverridesRow
		if err := rows.Scan(
			&i.AdministrationID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.OrderID,
			&i.MedicationDisplay,
			&i.OverrideReason,
			&i.OverrideBy,
			&i.OverrideAt,
			&i.OverridePatientMismatch,
			&i.OverrideMedicationMismatch,
			&i.OverrideNotScanned,
			&i.AdministeredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestraintChecks = `-- name: ListRestraintChecks :many
SELECT check_id, tenant_id, restraint_id, observed_at, observed_by, findings,
       continued_reason
FROM nursing.restraint_check
WHERE tenant_id = $1 AND restraint_id = $2
ORDER BY observed_at
LIMIT $3
`

type ListRestraintChecksParams struct {
	TenantID    uuid.UUID
	RestraintID uuid.UUID
	PageLimit   int32
}

func (q *Queries) ListRestraintChecks(ctx context.Context, arg ListRestraintChecksParams) ([]NursingRestraintCheck, error) {
	rows, err := q.db.Query(ctx, listRestraintChecks, arg.TenantID, arg.RestraintID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingRestraintCheck{}
	for rows.Next() {
		var i NursingRestraintCheck
		if err := rows.Scan(
			&i.CheckID,
			&i.TenantID,
			&i.RestraintID,
			&i.ObservedAt,
			&i.ObservedBy,
			&i.Findings,
			&i.ContinuedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestraints = `-- name: ListRestraints :many
SELECT restraint_id, tenant_id, patient_id, encounter_id, kind, description,
       authorized_by, authorized_at, expires_at, indication, renewals,
       started_at, started_by, monitor_every_seconds, discontinued_at,
       discontinued_by, discontinued_reason, version
FROM nursing.restraint
WHERE tenant_id = $1
  AND ($2::uuid IS NULL
       OR encounter_id = $2::uuid)
  AND ($3::boolean = false OR discontinued_at IS NULL)
ORDER BY started_at DESC
LIMIT $4
`

type ListRestraintsParams struct {
	TenantID        uuid.UUID
	EncounterFilter pgtype.UUID
	ActiveOnly      bool
	PageLimit       int32
}

func (q *Queries) ListRestraints(ctx context.Context, arg ListRestraintsParams) ([]NursingRestraint, error) {
	rows, err := q.db.Query(ctx, listRestraints,
		arg.TenantID,
		arg.EncounterFilter,
		arg.ActiveOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingRestraint{}
	for rows.Next() {
		var i NursingRestraint
		if err := rows.Scan(
			&i.RestraintID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Kind,
			&i.Description,
			&i.AuthorizedBy,
			&i.AuthorizedAt,
			&i.ExpiresAt,
			&i.Indication,
			&i.Renewals,
			&i.StartedAt,
			&i.StartedBy,
			&i.MonitorEverySeconds,
			&i.DiscontinuedAt,
			&i.DiscontinuedBy,
			&i.DiscontinuedReason,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskAssessments = `-- name: ListRiskAssessments :many
SELECT risk_id, tenant_id, patient_id, encounter_id, scale_id, scale_version,
       risk_domain, inputs, total, band, escalate, assessed_at, recorded_at,
       assessed_by, due_at, superseded_by_id, version
FROM nursing.risk_assessment
WHERE tenant_id = $1 AND patient_id = $2
  AND ($3::text = '' OR risk_domain = $3::text)
ORDER BY assessed_at DESC
LIMIT $4
`

type ListRiskAssessmentsParams struct {
	TenantID     uuid.UUID
	PatientID    uuid.UUID
	DomainFilter string
	PageLimit    int32
}

func (q *Queries) ListRiskAssessments(ctx context.Context, arg ListRiskAssessmentsParams) ([]NursingRiskAssessment, error) {
	rows, err := q.db.Query(ctx, listRiskAssessments,
		arg.TenantID,
		arg.PatientID,
		arg.DomainFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingRiskAssessment{}
	for rows.Next() {
		var i NursingRiskAssessment
		if err := rows.Scan(
			&i.RiskID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.ScaleID,
			&i.ScaleVersion,
			&i.RiskDomain,
			&i.Inputs,
			&i.Total,
			&i.Band,
			&i.Escalate,
			&i.AssessedAt,
			&i.RecordedAt,
			&i.AssessedBy,
			&i.DueAt,
			&i.SupersededByID,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiskScales = `-- name: ListRiskScales :many
SELECT scale_id, tenant_id, version, name, risk_domain, inputs, bands,
       reassess_after_seconds, retired, created_by, created_at
FROM nursing.risk_scale
WHERE tenant_id = $1
  AND ($2::boolean = true OR retired = false)
  AND ($3::text = '' OR risk_domain = $3::text)
ORDER BY name, version
LIMIT $4
`

type ListRiskScalesParams struct {
	TenantID       uuid.UUID
	IncludeRetired bool
	DomainFilter   string
	PageLimit      int32
}

func (q *Queries) ListRiskScales(ctx context.Context, arg ListRiskScalesParams) ([]NursingRiskScale, error) {
	rows, err := q.db.Query(ctx, listRiskScales,
		arg.TenantID,
		arg.IncludeRetired,
		arg.DomainFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingRiskScale{}
	for rows.Next() {
		var i NursingRiskScale
		if err := rows.Scan(
			&i.ScaleID,
			&i.TenantID,
			&i.Version,
			&i.Name,
			&i.RiskDomain,
			&i.Inputs,
			&i.Bands,
			&i.ReassessAfterSeconds,
			&i.Retired,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksNeedingEscalation = `-- name: ListTasksNeedingEscalation :many
SELECT task_id, tenant_id, patient_id, encounter_id, description, priority,
       due_at, assigned_to, created_at, created_by, version
FROM nursing.task
WHERE tenant_id = $1
  AND status = 'pending'
  AND priority = 'critical'
  AND escalated_at IS NULL
  AND due_at < $2
ORDER BY due_at
LIMIT $3
`

type ListTasksNeedingEscalationParams struct {
	TenantID  uuid.UUID
	AsOf      pgtype.Timestamptz
	PageLimit int32
}

type ListTasksNeedingEscalationRow struct {
	TaskID      uuid.UUID
	TenantID    uuid.UUID
	PatientID   uuid.UUID
	EncounterID uuid.UUID
	Description string
	Priority    string
	DueAt       pgtype.Timestamptz
	AssignedTo  string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	Version     int64
}

// SRS-NUR-011: overdue critical work, and only critical. A stream nobody reads
// loses the critical one first.
func (q *Queries) ListTasksNeedingEscalation(ctx context.Context, arg ListTasksNeedingEscalationParams) ([]ListTasksNeedingEscalationRow, error) {
	rows, err := q.db.Query(ctx, listTasksNeedingEscalation, arg.TenantID, arg.AsOf, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksNeedingEscalationRow{}
	for rows.Next() {
		var i ListTasksNeedingEscalationRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Description,
			&i.Priority,
			&i.DueAt,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorklist = `-- name: ListWorklist :many
SELECT task_id, tenant_id, patient_id, encounter_id, description, priority,
       due_at, source_kind, source_id, recur_every_seconds, recur_until,
       status, evidence, completed_at, completed_by, not_done_reason,
       assigned_to, escalated_at, escalated_to, created_at, created_by, version
FROM nursing.task
WHERE tenant_id = $1
  AND ($2::uuid IS NULL
       OR encounter_id = $2::uuid)
  AND ($3::text = '' OR assigned_to = $3::text)
  AND ($4::boolean = false OR status = 'pending')
ORDER BY
    CASE priority WHEN 'critical' THEN 0 WHEN 'urgent' THEN 1 ELSE 2 END,
    due_at
LIMIT $5
`

type ListWorklistParams struct {
	TenantID        uuid.UUID
	EncounterFilter pgtype.UUID
	AssigneeFilter  string
	PendingOnly     bool
	PageLimit       int32
}

// Ordered the way a nurse works: most urgent first, then by how overdue.
func (q *Queries) ListWorklist(ctx context.Context, arg ListWorklistParams) ([]NursingTask, error) {
	rows, err := q.db.Query(ctx, listWorklist,
		arg.TenantID,
		arg.EncounterFilter,
		arg.AssigneeFilter,
		arg.PendingOnly,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingTask{}
	for rows.Next() {
		var i NursingTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.Description,
			&i.Priority,
			&i.DueAt,
			&i.SourceKind,
			&i.SourceID,
			&i.RecurEverySeconds,
			&i.RecurUntil,
			&i.Status,
			&i.Evidence,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.NotDoneReason,
			&i.AssignedTo,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWoundAssessments = `-- name: ListWoundAssessments :many
SELECT wound_assessment_id, tenant_id, patient_id, encounter_id, wound_id,
       location, body_map_system, body_map_code, body_map_display, laterality,
       kind, stage, length_mm, width_mm, depth_mm, appearance, exudate,
       surrounding_skin, pain_score, assessed_at, recorded_at, assessed_by,
       version
FROM nursing.wound_assessment
WHERE tenant_id = $1 AND patient_id = $2
  AND ($3::text = '' OR wound_id = $3::text)
ORDER BY assessed_at DESC
LIMIT $4
`

type ListWoundAssessmentsParams struct {
	TenantID    uuid.UUID
	PatientID   uuid.UUID
	WoundFilter string
	PageLimit   int32
}

func (q *Queries) ListWoundAssessments(ctx context.Context, arg ListWoundAssessmentsParams) ([]NursingWoundAssessment, error) {
	rows, err := q.db.Query(ctx, listWoundAssessments,
		arg.TenantID,
		arg.PatientID,
		arg.WoundFilter,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingWoundAssessment{}
	for rows.Next() {
		var i NursingWoundAssessment
		if err := rows.Scan(
			&i.WoundAssessmentID,
			&i.TenantID,
			&i.PatientID,
			&i.EncounterID,
			&i.WoundID,
			&i.Location,
			&i.BodyMapSystem,
			&i.BodyMapCode,
			&i.BodyMapDisplay,
			&i.Laterality,
			&i.Kind,
			&i.Stage,
			&i.LengthMm,
			&i.WidthMm,
			&i.DepthMm,
			&i.Appearance,
			&i.Exudate,
			&i.SurroundingSkin,
			&i.PainScore,
			&i.AssessedAt,
			&i.RecordedAt,
			&i.AssessedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWoundImages = `-- name: ListWoundImages :many
SELECT image_id, tenant_id, wound_assessment_id, consent_id, storage_key,
       content_type, captured_at, captured_by, sequence
FROM nursing.wound_image
WHERE tenant_id = $1 AND wound_assessment_id = $2
ORDER BY sequence
`

type ListWoundImagesParams struct {
	TenantID          uuid.UUID
	WoundAssessmentID uuid.UUID
}

func (q *Queries) ListWoundImages(ctx context.Context, arg ListWoundImagesParams) ([]NursingWoundImage, error) {
	rows, err := q.db.Query(ctx, listWoundImages, arg.TenantID, arg.WoundAssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NursingWoundImage{}
	for rows.Next() {
		var i NursingWoundImage
		if err := rows.Scan(
			&i.ImageID,
			&i.TenantID,
			&i.WoundAssessmentID,
			&i.ConsentID,
			&i.StorageKey,
			&i.ContentType,
			&i.CapturedAt,
			&i.CapturedBy,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileNursingDowntime = `-- name: ReconcileNursingDowntime :execrows
UPDATE nursing.downtime_episode
SET reconciled_at = $1::timestamptz, reconciled_by = $2,
    version = version + 1
WHERE tenant_id = $3 AND episode_id = $4
  AND ended_at IS NOT NULL AND reconciled_at IS NULL
`

type ReconcileNursingDowntimeParams struct {
	ReconciledAt pgtype.Timestamptz
	ReconciledBy string
	TenantID     uuid.UUID
	EpisodeID    uuid.UUID
}

// Guarded on the episode having ended and not yet been reconciled: reconciling
// an open episode claims the paper is fully entered while the ward is still
// writing on it.
func (q *Queries) ReconcileNursingDowntime(ctx context.Context, arg ReconcileNursingDowntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileNursingDowntime,
		arg.ReconciledAt,
		arg.ReconciledBy,
		arg.TenantID,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeDevice = `-- name: RemoveDevice :execrows
UPDATE nursing.device
SET removed_at = $1::timestamptz, removed_by = $2,
    removal_reason = $3, version = version + 1
WHERE tenant_id = $4 AND device_id = $5
  AND removed_at IS NULL AND version = $6
`

type RemoveDeviceParams struct {
	RemovedAt       pgtype.Timestamptz
	RemovedBy       string
	RemovalReason   string
	TenantID        uuid.UUID
	DeviceID        uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) RemoveDevice(ctx context.Context, arg RemoveDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDevice,
		arg.RemovedAt,
		arg.RemovedBy,
		arg.RemovalReason,
		arg.TenantID,
		arg.DeviceID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewRestraint = `-- name: RenewRestraint :execrows
UPDATE nursing.restraint
SET renewals = $1, version = version + 1
WHERE tenant_id = $2 AND restraint_id = $3
  AND discontinued_at IS NULL AND version = $4
`

type RenewRestraintParams struct {
	Renewals        []byte
	TenantID        uuid.UUID
	RestraintID     uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) RenewRestraint(ctx context.Context, arg RenewRestraintParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewRestraint,
		arg.Renewals,
		arg.TenantID,
		arg.RestraintID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireAssessmentTemplate = `-- name: RetireAssessmentTemplate :execrows
UPDATE nursing.assessment_template
SET retired = true
WHERE tenant_id = $1 AND template_id = $2
  AND version = $3
`

type RetireAssessmentTemplateParams struct {
	TenantID   uuid.UUID
	TemplateID uuid.UUID
	Version    string
}

func (q *Queries) RetireAssessmentTemplate(ctx context.Context, arg RetireAssessmentTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireAssessmentTemplate, arg.TenantID, arg.TemplateID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeFlowsheetEntry = `-- name: SupersedeFlowsheetEntry :execrows
UPDATE nursing.flowsheet_entry
SET superseded_by_id = $1::uuid, version = version + 1
WHERE tenant_id = $2 AND entry_id = $3
  AND superseded_by_id IS NULL
`

type SupersedeFlowsheetEntryParams struct {
	SupersededByID pgtype.UUID
	TenantID       uuid.UUID
	EntryID        uuid.UUID
}

func (q *Queries) SupersedeFlowsheetEntry(ctx context.Context, arg SupersedeFlowsheetEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeFlowsheetEntry, arg.SupersededByID, arg.TenantID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeFluidEntry = `-- name: SupersedeFluidEntry :execrows
UPDATE nursing.fluid_entry
SET superseded_by_id = $1::uuid, version = version + 1
WHERE tenant_id = $2 AND fluid_id = $3
  AND superseded_by_id IS NULL AND voided_reason = ''
`

type SupersedeFluidEntryParams struct {
	SupersededByID pgtype.UUID
	TenantID       uuid.UUID
	FluidID        uuid.UUID
}

// The original stays readable: the shift total that was handed over was
// computed from it.
func (q *Queries) SupersedeFluidEntry(ctx context.Context, arg SupersedeFluidEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeFluidEntry, arg.SupersededByID, arg.TenantID, arg.FluidID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeRiskAssessment = `-- name: SupersedeRiskAssessment :execrows
UPDATE nursing.risk_assessment
SET superseded_by_id = $1::uuid, version = version + 1
WHERE tenant_id = $2 AND risk_id = $3
  AND superseded_by_id IS NULL
`

type SupersedeRiskAssessmentParams struct {
	SupersededByID pgtype.UUID
	TenantID       uuid.UUID
	RiskID         uuid.UUID
}

// A recalculation never overwrites: the nurse acted on the old number.
func (q *Queries) SupersedeRiskAssessment(ctx context.Context, arg SupersedeRiskAssessmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeRiskAssessment, arg.SupersededByID, arg.TenantID, arg.RiskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNursingCarePlan = `-- name: UpdateNursingCarePlan :execrows
UPDATE nursing.care_plan
SET problems = $1, status = $2, reviewed_at = $3::timestamptz,
    reviewed_by = $4, evaluation = $5, version = version + 1
WHERE tenant_id = $6 AND plan_id = $7
  AND version = $8
`

type UpdateNursingCarePlanParams struct {
	Problems        []byte
	Status          string
	ReviewedAt      pgtype.Timestamptz
	ReviewedBy      string
	Evaluation      string
	TenantID        uuid.UUID
	PlanID          uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateNursingCarePlan(ctx context.Context, arg UpdateNursingCarePlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNursingCarePlan,
		arg.Problems,
		arg.Status,
		arg.ReviewedAt,
		arg.ReviewedBy,
		arg.Evaluation,
		arg.TenantID,
		arg.PlanID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAcuityWeights = `-- name: UpsertAcuityWeights :exec
INSERT INTO nursing.acuity_weights (
    tenant_id, unit_id, dependency, open_task, overdue_task, device,
    high_risk, isolation, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
ON CONFLICT (tenant_id, unit_id) DO UPDATE
SET dependency = EXCLUDED.dependency, open_task = EXCLUDED.open_task,
    overdue_task = EXCLUDED.overdue_task, device = EXCLUDED.device,
    high_risk = EXCLUDED.high_risk, isolation = EXCLUDED.isolation,
    updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
`

type UpsertAcuityWeightsParams struct {
	TenantID    uuid.UUID
	UnitID      string
	Dependency  int32
	OpenTask    int32
	OverdueTask int32
	Device      int32
	HighRisk    int32
	Isolation   int32
	UpdatedBy   string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertAcuityWeights(ctx context.Context, arg UpsertAcuityWeightsParams) error {
	_, err := q.db.Exec(ctx, upsertAcuityWeights,
		arg.TenantID,
		arg.UnitID,
		arg.Dependency,
		arg.OpenTask,
		arg.OverdueTask,
		arg.Device,
		arg.HighRisk,
		arg.Isolation,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const upsertAdministrationPolicy = `-- name: UpsertAdministrationPolicy :exec
INSERT INTO nursing.administration_policy (
    tenant_id, facility_id, barcode_required, override_allowed,
    late_after_seconds, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (tenant_id, facility_id) DO UPDATE
SET barcode_required = EXCLUDED.barcode_required,
    override_allowed = EXCLUDED.override_allowed,
    late_after_seconds = EXCLUDED.late_after_seconds,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at
`

type UpsertAdministrationPolicyParams struct {
	TenantID         uuid.UUID
	FacilityID       uuid.UUID
	BarcodeRequired  bool
	OverrideAllowed  bool
	LateAfterSeconds int64
	UpdatedBy        string
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpsertAdministrationPolicy(ctx context.Context, arg UpsertAdministrationPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertAdministrationPolicy,
		arg.TenantID,
		arg.FacilityID,
		arg.BarcodeRequired,
		arg.OverrideAllowed,
		arg.LateAfterSeconds,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const voidFluidEntry = `-- name: VoidFluidEntry :execrows
UPDATE nursing.fluid_entry
SET voided_reason = $1, recorded_at = $2,
    version = version + 1
WHERE tenant_id = $3 AND fluid_id = $4
  AND superseded_by_id IS NULL AND voided_reason = ''
`

type VoidFluidEntryParams struct {
	VoidedReason string
	RecordedAt   pgtype.Timestamptz
	TenantID     uuid.UUID
	FluidID      uuid.UUID
}

func (q *Queries) VoidFluidEntry(ctx context.Context, arg VoidFluidEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, voidFluidEntry,
		arg.VoidedReason,
		arg.RecordedAt,
		arg.TenantID,
		arg.FluidID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
