// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: organization.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const facilityCodeExists = `-- name: FacilityCodeExists :one
SELECT EXISTS (
    SELECT 1 FROM organization.facility
    WHERE tenant_id = $1 AND code = $2
)
`

type FacilityCodeExistsParams struct {
	TenantID uuid.UUID
	Code     string
}

func (q *Queries) FacilityCodeExists(ctx context.Context, arg FacilityCodeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, facilityCodeExists, arg.TenantID, arg.Code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFacilityByID = `-- name: GetFacilityByID :one
SELECT facility_id, tenant_id, code, display_name, type, status, time_zone,
       created_at, updated_at, version
FROM organization.facility
WHERE tenant_id = $1
  AND facility_id = $2
`

type GetFacilityByIDParams struct {
	TenantID   uuid.UUID
	FacilityID uuid.UUID
}

type GetFacilityByIDRow struct {
	FacilityID  uuid.UUID
	TenantID    uuid.UUID
	Code        string
	DisplayName string
	Type        string
	Status      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

// The tenant predicate is part of the lookup, not a post-filter: a facility ID
// belonging to another tenant returns no rows rather than a forbidden row.
func (q *Queries) GetFacilityByID(ctx context.Context, arg GetFacilityByIDParams) (GetFacilityByIDRow, error) {
	row := q.db.QueryRow(ctx, getFacilityByID, arg.TenantID, arg.FacilityID)
	var i GetFacilityByIDRow
	err := row.Scan(
		&i.FacilityID,
		&i.TenantID,
		&i.Code,
		&i.DisplayName,
		&i.Type,
		&i.Status,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, display_name, legal_jurisdiction, default_locale, time_zone,
       status, created_at, updated_at, version
FROM organization.tenant
WHERE tenant_id = $1
`

type GetTenantByIDRow struct {
	TenantID          uuid.UUID
	DisplayName       string
	LegalJurisdiction string
	DefaultLocale     string
	TimeZone          string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
}

func (q *Queries) GetTenantByID(ctx context.Context, tenantID uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.TenantID,
		&i.DisplayName,
		&i.LegalJurisdiction,
		&i.DefaultLocale,
		&i.TimeZone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertFacility = `-- name: InsertFacility :exec
INSERT INTO organization.facility (
    facility_id, tenant_id, code, display_name, type, status, time_zone,
    created_at, created_by, updated_at, updated_by, version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12
)
`

type InsertFacilityParams struct {
	FacilityID  uuid.UUID
	TenantID    uuid.UUID
	Code        string
	DisplayName string
	Type        string
	Status      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   string
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
	Version     int64
}

func (q *Queries) InsertFacility(ctx context.Context, arg InsertFacilityParams) error {
	_, err := q.db.Exec(ctx, insertFacility,
		arg.FacilityID,
		arg.TenantID,
		arg.Code,
		arg.DisplayName,
		arg.Type,
		arg.Status,
		arg.TimeZone,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.Version,
	)
	return err
}

const insertTenant = `-- name: InsertTenant :exec

INSERT INTO organization.tenant (
    tenant_id, display_name, legal_jurisdiction, default_locale, time_zone,
    status, created_at, created_by, updated_at, updated_by, version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type InsertTenantParams struct {
	TenantID          uuid.UUID
	DisplayName       string
	LegalJurisdiction string
	DefaultLocale     string
	TimeZone          string
	Status            string
	CreatedAt         pgtype.Timestamptz
	CreatedBy         string
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         string
	Version           int64
}

// Organization context queries.
//
// Every tenant-owned statement takes tenant_id explicitly; the repository layer
// can only supply it from an authctx.TenantScope (SRS-PLT-003, FIT-03).
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.TenantID,
		arg.DisplayName,
		arg.LegalJurisdiction,
		arg.DefaultLocale,
		arg.TimeZone,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.Version,
	)
	return err
}

const listFacilities = `-- name: ListFacilities :many
SELECT facility_id, tenant_id, code, display_name, type, status, time_zone,
       created_at, updated_at, version
FROM organization.facility
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND (
        $3::timestamptz IS NULL
        OR (created_at, facility_id) >
           ($3::timestamptz, $4::uuid)
      )
ORDER BY created_at, facility_id
LIMIT $5
`

type ListFacilitiesParams struct {
	TenantID        uuid.UUID
	Status          *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageLimit       int32
}

type ListFacilitiesRow struct {
	FacilityID  uuid.UUID
	TenantID    uuid.UUID
	Code        string
	DisplayName string
	Type        string
	Status      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

// Keyset pagination on (created_at, facility_id). Page numbers are avoided
// because concurrent inserts would shift rows across page boundaries.
func (q *Queries) ListFacilities(ctx context.Context, arg ListFacilitiesParams) ([]ListFacilitiesRow, error) {
	rows, err := q.db.Query(ctx, listFacilities,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilitiesRow{}
	for rows.Next() {
		var i ListFacilitiesRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.TenantID,
			&i.Code,
			&i.DisplayName,
			&i.Type,
			&i.Status,
			&i.TimeZone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
