// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: platform_edge.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :execrows
UPDATE platform_edge.enrollment_token
SET consumed_at = $1
WHERE token_hash = $2
  AND consumed_at IS NULL
  AND expires_at > $3
`

type ConsumeEnrollmentTokenParams struct {
	ConsumedAt pgtype.Timestamptz
	TokenHash  string
	Now        pgtype.Timestamptz
}

// Single-use and time-bounded, enforced in the predicate rather than in
// application code: two nodes racing the same token cannot both match.
func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEnrollmentToken, arg.ConsumedAt, arg.TokenHash, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enrollEdgeNode = `-- name: EnrollEdgeNode :one
UPDATE platform_edge.node
SET status = 'enrolled',
    credential_fingerprint = $1,
    enrolled_at = $2,
    updated_at = $3,
    version = version + 1
WHERE node_id = $4 AND tenant_id = $5 AND status = 'pending'
RETURNING node_id, tenant_id, facility_id, display_name, status,
          credential_fingerprint, enrolled_at, last_seen_at, created_at, updated_at, version
`

type EnrollEdgeNodeParams struct {
	CredentialFingerprint string
	EnrolledAt            pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	NodeID                uuid.UUID
	TenantID              uuid.UUID
}

func (q *Queries) EnrollEdgeNode(ctx context.Context, arg EnrollEdgeNodeParams) (PlatformEdgeNode, error) {
	row := q.db.QueryRow(ctx, enrollEdgeNode,
		arg.CredentialFingerprint,
		arg.EnrolledAt,
		arg.UpdatedAt,
		arg.NodeID,
		arg.TenantID,
	)
	var i PlatformEdgeNode
	err := row.Scan(
		&i.NodeID,
		&i.TenantID,
		&i.FacilityID,
		&i.DisplayName,
		&i.Status,
		&i.CredentialFingerprint,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getEdgeNode = `-- name: GetEdgeNode :one
SELECT node_id, tenant_id, facility_id, display_name, status,
       credential_fingerprint, enrolled_at, last_seen_at, created_at, updated_at, version
FROM platform_edge.node
WHERE tenant_id = $1 AND node_id = $2
`

type GetEdgeNodeParams struct {
	TenantID uuid.UUID
	NodeID   uuid.UUID
}

func (q *Queries) GetEdgeNode(ctx context.Context, arg GetEdgeNodeParams) (PlatformEdgeNode, error) {
	row := q.db.QueryRow(ctx, getEdgeNode, arg.TenantID, arg.NodeID)
	var i PlatformEdgeNode
	err := row.Scan(
		&i.NodeID,
		&i.TenantID,
		&i.FacilityID,
		&i.DisplayName,
		&i.Status,
		&i.CredentialFingerprint,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getEnrollmentTokenNode = `-- name: GetEnrollmentTokenNode :one
SELECT node_id, tenant_id FROM platform_edge.enrollment_token
WHERE token_hash = $1
`

type GetEnrollmentTokenNodeRow struct {
	NodeID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetEnrollmentTokenNode(ctx context.Context, tokenHash string) (GetEnrollmentTokenNodeRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenNode, tokenHash)
	var i GetEnrollmentTokenNodeRow
	err := row.Scan(&i.NodeID, &i.TenantID)
	return i, err
}

const insertEdgeNode = `-- name: InsertEdgeNode :exec

INSERT INTO platform_edge.node (
    node_id, tenant_id, facility_id, display_name, status, created_at, updated_at, version
) VALUES ($1, $2, $3, $4, $5, $6, $7, 1)
`

type InsertEdgeNodeParams struct {
	NodeID      uuid.UUID
	TenantID    uuid.UUID
	FacilityID  uuid.UUID
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Hospital edge registry queries (P0-13).
func (q *Queries) InsertEdgeNode(ctx context.Context, arg InsertEdgeNodeParams) error {
	_, err := q.db.Exec(ctx, insertEdgeNode,
		arg.NodeID,
		arg.TenantID,
		arg.FacilityID,
		arg.DisplayName,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertEnrollmentToken = `-- name: InsertEnrollmentToken :exec
INSERT INTO platform_edge.enrollment_token (token_hash, node_id, tenant_id, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEnrollmentTokenParams struct {
	TokenHash string
	NodeID    uuid.UUID
	TenantID  uuid.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, insertEnrollmentToken,
		arg.TokenHash,
		arg.NodeID,
		arg.TenantID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertForwardedOperation = `-- name: InsertForwardedOperation :exec
INSERT INTO platform_edge.forwarded_operation (
    node_id, operation_id, tenant_id, operation_type, payload, occurred_at,
    received_at, outcome, reject_reason
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (node_id, operation_id) DO NOTHING
`

type InsertForwardedOperationParams struct {
	NodeID        uuid.UUID
	OperationID   uuid.UUID
	TenantID      uuid.UUID
	OperationType string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Outcome       string
	RejectReason  string
}

func (q *Queries) InsertForwardedOperation(ctx context.Context, arg InsertForwardedOperationParams) error {
	_, err := q.db.Exec(ctx, insertForwardedOperation,
		arg.NodeID,
		arg.OperationID,
		arg.TenantID,
		arg.OperationType,
		arg.Payload,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Outcome,
		arg.RejectReason,
	)
	return err
}

const listForwardedOperations = `-- name: ListForwardedOperations :many
SELECT node_id, operation_id, tenant_id, operation_type, payload, occurred_at,
       received_at, outcome, reject_reason
FROM platform_edge.forwarded_operation
WHERE tenant_id = $1
ORDER BY occurred_at, operation_id
`

func (q *Queries) ListForwardedOperations(ctx context.Context, tenantID uuid.UUID) ([]PlatformEdgeForwardedOperation, error) {
	rows, err := q.db.Query(ctx, listForwardedOperations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformEdgeForwardedOperation{}
	for rows.Next() {
		var i PlatformEdgeForwardedOperation
		if err := rows.Scan(
			&i.NodeID,
			&i.OperationID,
			&i.TenantID,
			&i.OperationType,
			&i.Payload,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Outcome,
			&i.RejectReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEdgeNodeStatus = `-- name: SetEdgeNodeStatus :execrows
UPDATE platform_edge.node
SET status = $1, updated_at = $2, version = version + 1
WHERE node_id = $3 AND tenant_id = $4
`

type SetEdgeNodeStatusParams struct {
	Status    string
	UpdatedAt pgtype.Timestamptz
	NodeID    uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) SetEdgeNodeStatus(ctx context.Context, arg SetEdgeNodeStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEdgeNodeStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.NodeID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchEdgeNode = `-- name: TouchEdgeNode :exec
UPDATE platform_edge.node
SET last_seen_at = $1
WHERE node_id = $2 AND tenant_id = $3
`

type TouchEdgeNodeParams struct {
	LastSeenAt pgtype.Timestamptz
	NodeID     uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) TouchEdgeNode(ctx context.Context, arg TouchEdgeNodeParams) error {
	_, err := q.db.Exec(ctx, touchEdgeNode, arg.LastSeenAt, arg.NodeID, arg.TenantID)
	return err
}

const tryInsertForwardedOperation = `-- name: TryInsertForwardedOperation :execrows
INSERT INTO platform_edge.forwarded_operation (
    node_id, operation_id, tenant_id, operation_type, payload, occurred_at, received_at, outcome
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (node_id, operation_id) DO NOTHING
`

type TryInsertForwardedOperationParams struct {
	NodeID        uuid.UUID
	OperationID   uuid.UUID
	TenantID      uuid.UUID
	OperationType string
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	ReceivedAt    pgtype.Timestamptz
	Outcome       string
}

// Returns 1 for a new operation and 0 for a redelivery, which is what makes the
// edge's blind retry safe.
func (q *Queries) TryInsertForwardedOperation(ctx context.Context, arg TryInsertForwardedOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertForwardedOperation,
		arg.NodeID,
		arg.OperationID,
		arg.TenantID,
		arg.OperationType,
		arg.Payload,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Outcome,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
