// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: platform_rules.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDecisionLog = `-- name: GetDecisionLog :one
SELECT decision_id, tenant_id, rule_set_name, rule_set_version, matched_rule,
       input, outcome, explanation, correlation_id, occurred_at
FROM platform_rules.decision_log
WHERE tenant_id = $1 AND decision_id = $2
`

type GetDecisionLogParams struct {
	TenantID   uuid.UUID
	DecisionID uuid.UUID
}

func (q *Queries) GetDecisionLog(ctx context.Context, arg GetDecisionLogParams) (PlatformRulesDecisionLog, error) {
	row := q.db.QueryRow(ctx, getDecisionLog, arg.TenantID, arg.DecisionID)
	var i PlatformRulesDecisionLog
	err := row.Scan(
		&i.DecisionID,
		&i.TenantID,
		&i.RuleSetName,
		&i.RuleSetVersion,
		&i.MatchedRule,
		&i.Input,
		&i.Outcome,
		&i.Explanation,
		&i.CorrelationID,
		&i.OccurredAt,
	)
	return i, err
}

const getEffectiveRuleSet = `-- name: GetEffectiveRuleSet :one
SELECT rule_set_id, tenant_id, name, version, status, effective_from, effective_to,
       definition, created_at, created_by, published_at, published_by
FROM platform_rules.rule_set
WHERE name = $1
  AND status = 'published'
  AND tenant_id IS NOT DISTINCT FROM $2::uuid
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to > $3)
ORDER BY effective_from DESC, version DESC
LIMIT 1
`

type GetEffectiveRuleSetParams struct {
	Name     string
	TenantID pgtype.UUID
	At       pgtype.Timestamptz
}

// The version in force at a given instant. Effective dating is what lets a
// decision made last quarter be explained with last quarter's rules.
func (q *Queries) GetEffectiveRuleSet(ctx context.Context, arg GetEffectiveRuleSetParams) (PlatformRulesRuleSet, error) {
	row := q.db.QueryRow(ctx, getEffectiveRuleSet, arg.Name, arg.TenantID, arg.At)
	var i PlatformRulesRuleSet
	err := row.Scan(
		&i.RuleSetID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Definition,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const getRuleSetVersion = `-- name: GetRuleSetVersion :one
SELECT rule_set_id, tenant_id, name, version, status, effective_from, effective_to,
       definition, created_at, created_by, published_at, published_by
FROM platform_rules.rule_set
WHERE name = $1 AND version = $2
  AND tenant_id IS NOT DISTINCT FROM $3::uuid
`

type GetRuleSetVersionParams struct {
	Name     string
	Version  int32
	TenantID pgtype.UUID
}

func (q *Queries) GetRuleSetVersion(ctx context.Context, arg GetRuleSetVersionParams) (PlatformRulesRuleSet, error) {
	row := q.db.QueryRow(ctx, getRuleSetVersion, arg.Name, arg.Version, arg.TenantID)
	var i PlatformRulesRuleSet
	err := row.Scan(
		&i.RuleSetID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Definition,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const insertDecisionLog = `-- name: InsertDecisionLog :exec
INSERT INTO platform_rules.decision_log (
    decision_id, tenant_id, rule_set_name, rule_set_version, matched_rule,
    input, outcome, explanation, correlation_id, occurred_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
`

type InsertDecisionLogParams struct {
	DecisionID     uuid.UUID
	TenantID       uuid.UUID
	RuleSetName    string
	RuleSetVersion int32
	MatchedRule    string
	Input          []byte
	Outcome        []byte
	Explanation    []byte
	CorrelationID  string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) InsertDecisionLog(ctx context.Context, arg InsertDecisionLogParams) error {
	_, err := q.db.Exec(ctx, insertDecisionLog,
		arg.DecisionID,
		arg.TenantID,
		arg.RuleSetName,
		arg.RuleSetVersion,
		arg.MatchedRule,
		arg.Input,
		arg.Outcome,
		arg.Explanation,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const insertRuleSet = `-- name: InsertRuleSet :exec

INSERT INTO platform_rules.rule_set (
    rule_set_id, tenant_id, name, version, status, effective_from, effective_to,
    definition, created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
`

type InsertRuleSetParams struct {
	RuleSetID     uuid.UUID
	TenantID      pgtype.UUID
	Name          string
	Version       int32
	Status        string
	EffectiveFrom pgtype.Timestamptz
	EffectiveTo   pgtype.Timestamptz
	Definition    []byte
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
}

// Rules evaluation harness queries (P0-07).
func (q *Queries) InsertRuleSet(ctx context.Context, arg InsertRuleSetParams) error {
	_, err := q.db.Exec(ctx, insertRuleSet,
		arg.RuleSetID,
		arg.TenantID,
		arg.Name,
		arg.Version,
		arg.Status,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Definition,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const publishRuleSet = `-- name: PublishRuleSet :execrows
UPDATE platform_rules.rule_set
SET status = 'published', published_at = $1, published_by = $2
WHERE rule_set_id = $3 AND status = 'draft'
`

type PublishRuleSetParams struct {
	PublishedAt pgtype.Timestamptz
	PublishedBy string
	RuleSetID   uuid.UUID
}

// Only a draft may be published, and publication stamps who did it. A
// published set is never edited: a change is a new version.
func (q *Queries) PublishRuleSet(ctx context.Context, arg PublishRuleSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishRuleSet, arg.PublishedAt, arg.PublishedBy, arg.RuleSetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
