// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: scheduling.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSeries = `-- name: CancelSeries :execrows
UPDATE scheduling.appointment_series
SET cancelled = true
WHERE tenant_id = $1 AND series_id = $2 AND NOT cancelled
`

type CancelSeriesParams struct {
	TenantID uuid.UUID
	SeriesID uuid.UUID
}

func (q *Queries) CancelSeries(ctx context.Context, arg CancelSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSeries, arg.TenantID, arg.SeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimSlotCapacity = `-- name: ClaimSlotCapacity :one
UPDATE scheduling.slot
SET booked = booked + 1, updated_at = $1
WHERE tenant_id = $2
  AND resource_id = $3
  AND starts_at = $4
  AND visit_type = $5
  AND booked < capacity
RETURNING slot_id, capacity, booked
`

type ClaimSlotCapacityParams struct {
	UpdatedAt  pgtype.Timestamptz
	TenantID   uuid.UUID
	ResourceID uuid.UUID
	StartsAt   pgtype.Timestamptz
	VisitType  string
}

type ClaimSlotCapacityRow struct {
	SlotID   uuid.UUID
	Capacity int32
	Booked   int32
}

// Takes one unit of capacity, or reports that there is none (SRS-SCH-004).
//
// This single statement is the whole of "book atomically and prevent
// overbooking". UPDATE ... RETURNING takes a row lock, so concurrent claimants
// serialise and each either gets capacity or does not. Reading the count first
// and updating second is a race that two bookings both win, and the way it
// fails — two patients in one slot, under load, not under test — is the way
// nobody notices until both are in the waiting room.
func (q *Queries) ClaimSlotCapacity(ctx context.Context, arg ClaimSlotCapacityParams) (ClaimSlotCapacityRow, error) {
	row := q.db.QueryRow(ctx, claimSlotCapacity,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ResourceID,
		arg.StartsAt,
		arg.VisitType,
	)
	var i ClaimSlotCapacityRow
	err := row.Scan(&i.SlotID, &i.Capacity, &i.Booked)
	return i, err
}

const countBookedSlots = `-- name: CountBookedSlots :many
SELECT resource_id, starts_at, visit_type, capacity, booked
FROM scheduling.slot
WHERE tenant_id = $1
  AND resource_id = ANY($2::uuid[])
  AND starts_at >= $3::timestamptz
  AND starts_at < $4::timestamptz
`

type CountBookedSlotsParams struct {
	TenantID    uuid.UUID
	ResourceIds []uuid.UUID
	FromAt      pgtype.Timestamptz
	UntilAt     pgtype.Timestamptz
}

type CountBookedSlotsRow struct {
	ResourceID uuid.UUID
	StartsAt   pgtype.Timestamptz
	VisitType  string
	Capacity   int32
	Booked     int32
}

// How much capacity is consumed across a window, for the slot search.
//
// One query for the whole page rather than one per slot: a fortnight of a busy
// clinic is several hundred slots, and a round trip each would make the search
// endpoint the slow one.
func (q *Queries) CountBookedSlots(ctx context.Context, arg CountBookedSlotsParams) ([]CountBookedSlotsRow, error) {
	rows, err := q.db.Query(ctx, countBookedSlots,
		arg.TenantID,
		arg.ResourceIds,
		arg.FromAt,
		arg.UntilAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBookedSlotsRow{}
	for rows.Next() {
		var i CountBookedSlotsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.StartsAt,
			&i.VisitType,
			&i.Capacity,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteException = `-- name: DeleteException :execrows
DELETE FROM scheduling.schedule_exception
WHERE tenant_id = $1 AND exception_id = $2
`

type DeleteExceptionParams struct {
	TenantID    uuid.UUID
	ExceptionID uuid.UUID
}

func (q *Queries) DeleteException(ctx context.Context, arg DeleteExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteException, arg.TenantID, arg.ExceptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM scheduling.schedule
WHERE tenant_id = $1
  AND schedule_id = $2
  AND effective_from > $3::date
`

type DeleteScheduleParams struct {
	TenantID   uuid.UUID
	ScheduleID uuid.UUID
	Today      pgtype.Date
}

// Rosters are configuration, not history: a rule withdrawn before it ever took
// effect should leave nothing behind. A rule that HAS taken effect is ended by
// setting effective_until instead, which is why this is guarded.
func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, arg.TenantID, arg.ScheduleID, arg.Today)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endSchedule = `-- name: EndSchedule :execrows
UPDATE scheduling.schedule
SET effective_until = $1, updated_at = $2
WHERE tenant_id = $3 AND schedule_id = $4
`

type EndScheduleParams struct {
	EffectiveUntil pgtype.Date
	UpdatedAt      pgtype.Timestamptz
	TenantID       uuid.UUID
	ScheduleID     uuid.UUID
}

func (q *Queries) EndSchedule(ctx context.Context, arg EndScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, endSchedule,
		arg.EffectiveUntil,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ScheduleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSlot = `-- name: EnsureSlot :exec
INSERT INTO scheduling.slot (
    slot_id, tenant_id, resource_id, starts_at, ends_at, visit_type,
    capacity, booked, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, 0, $8, $9
)
ON CONFLICT (tenant_id, resource_id, starts_at, visit_type) DO NOTHING
`

type EnsureSlotParams struct {
	SlotID     uuid.UUID
	TenantID   uuid.UUID
	ResourceID uuid.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	VisitType  string
	Capacity   int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Materialises a slot the first time it is booked.
//
// ON CONFLICT DO NOTHING rather than an upsert: two concurrent first bookings
// both run this, and the loser must not reset the winner's counter to zero.
// Capacity is deliberately not refreshed from the roster here either — a
// roster edited between two bookings must not silently change how many patients
// the slot already half-full can take.
func (q *Queries) EnsureSlot(ctx context.Context, arg EnsureSlotParams) error {
	_, err := q.db.Exec(ctx, ensureSlot,
		arg.SlotID,
		arg.TenantID,
		arg.ResourceID,
		arg.StartsAt,
		arg.EndsAt,
		arg.VisitType,
		arg.Capacity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const expireStaleOffers = `-- name: ExpireStaleOffers :execrows
UPDATE scheduling.waitlist_entry
SET status = 'waiting', offered_slot_at = NULL, offer_expires_at = NULL,
    updated_at = $1
WHERE tenant_id = $2
  AND status = 'offered'
  AND offer_expires_at <= $3::timestamptz
`

type ExpireStaleOffersParams struct {
	UpdatedAt pgtype.Timestamptz
	TenantID  uuid.UUID
	Now       pgtype.Timestamptz
}

// Returns entries whose offer nobody answered to the waiting list.
//
// Back to waiting rather than to a terminal state: the patient did not answer
// one message, which is not the same as no longer wanting an appointment.
func (q *Queries) ExpireStaleOffers(ctx context.Context, arg ExpireStaleOffersParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleOffers, arg.UpdatedAt, arg.TenantID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppointment = `-- name: GetAppointment :one
SELECT appointment_id, tenant_id, facility_id, resource_id, org_unit_id,
       patient_id, slot_id, visit_type, visit_mode, starts_at, ends_at,
       status, booked_by, reason, rescheduled_from_id, created_at, updated_at, version,
       series_id, occurrence, reschedule_count, join_url
FROM scheduling.appointment
WHERE tenant_id = $1 AND appointment_id = $2
`

type GetAppointmentParams struct {
	TenantID      uuid.UUID
	AppointmentID uuid.UUID
}

func (q *Queries) GetAppointment(ctx context.Context, arg GetAppointmentParams) (SchedulingAppointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, arg.TenantID, arg.AppointmentID)
	var i SchedulingAppointment
	err := row.Scan(
		&i.AppointmentID,
		&i.TenantID,
		&i.FacilityID,
		&i.ResourceID,
		&i.OrgUnitID,
		&i.PatientID,
		&i.SlotID,
		&i.VisitType,
		&i.VisitMode,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.BookedBy,
		&i.Reason,
		&i.RescheduledFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SeriesID,
		&i.Occurrence,
		&i.RescheduleCount,
		&i.JoinUrl,
	)
	return i, err
}

const getCancellationPolicy = `-- name: GetCancellationPolicy :many
SELECT notice_hours, reschedule_notice_hours, max_reschedules,
       chargeable_when_late, teleconsult_enabled, teleconsult_visit_types,
       teleconsult_requires_confirmed_identity, facility_id
FROM scheduling.cancellation_policy
WHERE tenant_id = $1
  AND (facility_id IS NULL OR facility_id = $2::uuid)
ORDER BY (facility_id IS NULL)
`

type GetCancellationPolicyParams struct {
	TenantID   uuid.UUID
	FacilityID pgtype.UUID
}

type GetCancellationPolicyRow struct {
	NoticeHours                          int32
	RescheduleNoticeHours                int32
	MaxReschedules                       int32
	ChargeableWhenLate                   bool
	TeleconsultEnabled                   bool
	TeleconsultVisitTypes                []string
	TeleconsultRequiresConfirmedIdentity bool
	FacilityID                           pgtype.UUID
}

// Facility-specific rows first, so the resolver takes the first it sees.
func (q *Queries) GetCancellationPolicy(ctx context.Context, arg GetCancellationPolicyParams) ([]GetCancellationPolicyRow, error) {
	rows, err := q.db.Query(ctx, getCancellationPolicy, arg.TenantID, arg.FacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCancellationPolicyRow{}
	for rows.Next() {
		var i GetCancellationPolicyRow
		if err := rows.Scan(
			&i.NoticeHours,
			&i.RescheduleNoticeHours,
			&i.MaxReschedules,
			&i.ChargeableWhenLate,
			&i.TeleconsultEnabled,
			&i.TeleconsultVisitTypes,
			&i.TeleconsultRequiresConfirmedIdentity,
			&i.FacilityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT resource_id, tenant_id, facility_id, org_unit_id, resource_type,
       subject_id, display_name, status, time_zone, created_at, updated_at
FROM scheduling.resource
WHERE tenant_id = $1 AND resource_id = $2
`

type GetResourceParams struct {
	TenantID   uuid.UUID
	ResourceID uuid.UUID
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (SchedulingResource, error) {
	row := q.db.QueryRow(ctx, getResource, arg.TenantID, arg.ResourceID)
	var i SchedulingResource
	err := row.Scan(
		&i.ResourceID,
		&i.TenantID,
		&i.FacilityID,
		&i.OrgUnitID,
		&i.ResourceType,
		&i.SubjectID,
		&i.DisplayName,
		&i.Status,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT series_id, tenant_id, patient_id, resource_id, visit_type,
       interval_days, occurrences, starts_at, created_by, created_at, cancelled
FROM scheduling.appointment_series
WHERE tenant_id = $1 AND series_id = $2
`

type GetSeriesParams struct {
	TenantID uuid.UUID
	SeriesID uuid.UUID
}

func (q *Queries) GetSeries(ctx context.Context, arg GetSeriesParams) (SchedulingAppointmentSeries, error) {
	row := q.db.QueryRow(ctx, getSeries, arg.TenantID, arg.SeriesID)
	var i SchedulingAppointmentSeries
	err := row.Scan(
		&i.SeriesID,
		&i.TenantID,
		&i.PatientID,
		&i.ResourceID,
		&i.VisitType,
		&i.IntervalDays,
		&i.Occurrences,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Cancelled,
	)
	return i, err
}

const getSlot = `-- name: GetSlot :one
SELECT slot_id, tenant_id, resource_id, starts_at, ends_at, visit_type,
       capacity, booked, created_at, updated_at
FROM scheduling.slot
WHERE tenant_id = $1 AND slot_id = $2
`

type GetSlotParams struct {
	TenantID uuid.UUID
	SlotID   uuid.UUID
}

func (q *Queries) GetSlot(ctx context.Context, arg GetSlotParams) (SchedulingSlot, error) {
	row := q.db.QueryRow(ctx, getSlot, arg.TenantID, arg.SlotID)
	var i SchedulingSlot
	err := row.Scan(
		&i.SlotID,
		&i.TenantID,
		&i.ResourceID,
		&i.StartsAt,
		&i.EndsAt,
		&i.VisitType,
		&i.Capacity,
		&i.Booked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWaitlistEntry = `-- name: GetWaitlistEntry :one
SELECT waitlist_id, tenant_id, patient_id, resource_id, facility_id, org_unit_id,
       visit_type, not_before, not_after, appointment_id, status,
       offered_slot_at, offer_expires_at, created_by, created_at, updated_at
FROM scheduling.waitlist_entry
WHERE tenant_id = $1 AND waitlist_id = $2
`

type GetWaitlistEntryParams struct {
	TenantID   uuid.UUID
	WaitlistID uuid.UUID
}

func (q *Queries) GetWaitlistEntry(ctx context.Context, arg GetWaitlistEntryParams) (SchedulingWaitlistEntry, error) {
	row := q.db.QueryRow(ctx, getWaitlistEntry, arg.TenantID, arg.WaitlistID)
	var i SchedulingWaitlistEntry
	err := row.Scan(
		&i.WaitlistID,
		&i.TenantID,
		&i.PatientID,
		&i.ResourceID,
		&i.FacilityID,
		&i.OrgUnitID,
		&i.VisitType,
		&i.NotBefore,
		&i.NotAfter,
		&i.AppointmentID,
		&i.Status,
		&i.OfferedSlotAt,
		&i.OfferExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppointment = `-- name: InsertAppointment :exec
INSERT INTO scheduling.appointment (
    appointment_id, tenant_id, facility_id, resource_id, org_unit_id,
    patient_id, slot_id, visit_type, visit_mode, starts_at, ends_at,
    status, booked_by, reason, rescheduled_from_id, created_at, updated_at, version,
    series_id, occurrence, reschedule_count, join_url
) VALUES (
    $1, $2, $3, $4,
    $5::uuid, $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15::uuid, $16, $17, 1,
    $18::uuid, $19::integer,
    $20, $21
)
`

type InsertAppointmentParams struct {
	AppointmentID     uuid.UUID
	TenantID          uuid.UUID
	FacilityID        uuid.UUID
	ResourceID        uuid.UUID
	OrgUnitID         pgtype.UUID
	PatientID         uuid.UUID
	SlotID            uuid.UUID
	VisitType         string
	VisitMode         string
	StartsAt          pgtype.Timestamptz
	EndsAt            pgtype.Timestamptz
	Status            string
	BookedBy          string
	Reason            string
	RescheduledFromID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	SeriesID          pgtype.UUID
	Occurrence        *int32
	RescheduleCount   int32
	JoinUrl           string
}

func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) error {
	_, err := q.db.Exec(ctx, insertAppointment,
		arg.AppointmentID,
		arg.TenantID,
		arg.FacilityID,
		arg.ResourceID,
		arg.OrgUnitID,
		arg.PatientID,
		arg.SlotID,
		arg.VisitType,
		arg.VisitMode,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.BookedBy,
		arg.Reason,
		arg.RescheduledFromID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SeriesID,
		arg.Occurrence,
		arg.RescheduleCount,
		arg.JoinUrl,
	)
	return err
}

const insertException = `-- name: InsertException :exec
INSERT INTO scheduling.schedule_exception (
    exception_id, tenant_id, resource_id, kind, starts_at, ends_at,
    reason, overridable, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
`

type InsertExceptionParams struct {
	ExceptionID uuid.UUID
	TenantID    uuid.UUID
	ResourceID  uuid.UUID
	Kind        string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	Reason      string
	Overridable bool
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertException(ctx context.Context, arg InsertExceptionParams) error {
	_, err := q.db.Exec(ctx, insertException,
		arg.ExceptionID,
		arg.TenantID,
		arg.ResourceID,
		arg.Kind,
		arg.StartsAt,
		arg.EndsAt,
		arg.Reason,
		arg.Overridable,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertPolicyOutcome = `-- name: InsertPolicyOutcome :exec
INSERT INTO scheduling.appointment_policy_outcome (
    outcome_id, tenant_id, appointment_id, kind, timely,
    notice_given_minutes, notice_required_minutes, chargeable,
    decided_by, decided_at, reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
`

type InsertPolicyOutcomeParams struct {
	OutcomeID             uuid.UUID
	TenantID              uuid.UUID
	AppointmentID         uuid.UUID
	Kind                  string
	Timely                bool
	NoticeGivenMinutes    int32
	NoticeRequiredMinutes int32
	Chargeable            bool
	DecidedBy             string
	DecidedAt             pgtype.Timestamptz
	Reason                string
}

func (q *Queries) InsertPolicyOutcome(ctx context.Context, arg InsertPolicyOutcomeParams) error {
	_, err := q.db.Exec(ctx, insertPolicyOutcome,
		arg.OutcomeID,
		arg.TenantID,
		arg.AppointmentID,
		arg.Kind,
		arg.Timely,
		arg.NoticeGivenMinutes,
		arg.NoticeRequiredMinutes,
		arg.Chargeable,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Reason,
	)
	return err
}

const insertResource = `-- name: InsertResource :exec

INSERT INTO scheduling.resource (
    resource_id, tenant_id, facility_id, org_unit_id, resource_type,
    subject_id, display_name, status, time_zone, created_at, updated_at
) VALUES (
    $1, $2, $3, $4::uuid,
    $5, $6, $7, $8, $9,
    $10, $11
)
`

type InsertResourceParams struct {
	ResourceID   uuid.UUID
	TenantID     uuid.UUID
	FacilityID   uuid.UUID
	OrgUnitID    pgtype.UUID
	ResourceType string
	SubjectID    string
	DisplayName  string
	Status       string
	TimeZone     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Scheduling: resources, rosters, slots and appointments (SRS-SCH).
func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.Exec(ctx, insertResource,
		arg.ResourceID,
		arg.TenantID,
		arg.FacilityID,
		arg.OrgUnitID,
		arg.ResourceType,
		arg.SubjectID,
		arg.DisplayName,
		arg.Status,
		arg.TimeZone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSchedule = `-- name: InsertSchedule :exec
INSERT INTO scheduling.schedule (
    schedule_id, tenant_id, resource_id, facility_id, visit_type, visit_mode,
    weekday, start_minute, end_minute, slot_minutes, capacity,
    effective_from, effective_until, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13::date, $14, $15
)
`

type InsertScheduleParams struct {
	ScheduleID     uuid.UUID
	TenantID       uuid.UUID
	ResourceID     uuid.UUID
	FacilityID     uuid.UUID
	VisitType      string
	VisitMode      string
	Weekday        int16
	StartMinute    int32
	EndMinute      int32
	SlotMinutes    int32
	Capacity       int32
	EffectiveFrom  pgtype.Date
	EffectiveUntil pgtype.Date
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) error {
	_, err := q.db.Exec(ctx, insertSchedule,
		arg.ScheduleID,
		arg.TenantID,
		arg.ResourceID,
		arg.FacilityID,
		arg.VisitType,
		arg.VisitMode,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
		arg.SlotMinutes,
		arg.Capacity,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSeries = `-- name: InsertSeries :exec
INSERT INTO scheduling.appointment_series (
    series_id, tenant_id, patient_id, resource_id, visit_type,
    interval_days, occurrences, starts_at, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
`

type InsertSeriesParams struct {
	SeriesID     uuid.UUID
	TenantID     uuid.UUID
	PatientID    uuid.UUID
	ResourceID   uuid.UUID
	VisitType    string
	IntervalDays int32
	Occurrences  int32
	StartsAt     pgtype.Timestamptz
	CreatedBy    string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertSeries(ctx context.Context, arg InsertSeriesParams) error {
	_, err := q.db.Exec(ctx, insertSeries,
		arg.SeriesID,
		arg.TenantID,
		arg.PatientID,
		arg.ResourceID,
		arg.VisitType,
		arg.IntervalDays,
		arg.Occurrences,
		arg.StartsAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertStatusHistory = `-- name: InsertStatusHistory :exec
INSERT INTO scheduling.appointment_status_history (
    history_id, tenant_id, appointment_id, from_status, to_status,
    changed_at, changed_by, reason, corrected
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type InsertStatusHistoryParams struct {
	HistoryID     uuid.UUID
	TenantID      uuid.UUID
	AppointmentID uuid.UUID
	FromStatus    string
	ToStatus      string
	ChangedAt     pgtype.Timestamptz
	ChangedBy     string
	Reason        string
	Corrected     bool
}

func (q *Queries) InsertStatusHistory(ctx context.Context, arg InsertStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertStatusHistory,
		arg.HistoryID,
		arg.TenantID,
		arg.AppointmentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedAt,
		arg.ChangedBy,
		arg.Reason,
		arg.Corrected,
	)
	return err
}

const insertWaitlistEntry = `-- name: InsertWaitlistEntry :exec
INSERT INTO scheduling.waitlist_entry (
    waitlist_id, tenant_id, patient_id, resource_id, facility_id, org_unit_id,
    visit_type, not_before, not_after, appointment_id, status,
    created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4::uuid,
    $5::uuid, $6::uuid,
    $7, $8::timestamptz,
    $9::timestamptz, $10::uuid,
    $11, $12, $13, $14
)
`

type InsertWaitlistEntryParams struct {
	WaitlistID    uuid.UUID
	TenantID      uuid.UUID
	PatientID     uuid.UUID
	ResourceID    pgtype.UUID
	FacilityID    pgtype.UUID
	OrgUnitID     pgtype.UUID
	VisitType     string
	NotBefore     pgtype.Timestamptz
	NotAfter      pgtype.Timestamptz
	AppointmentID pgtype.UUID
	Status        string
	CreatedBy     string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertWaitlistEntry(ctx context.Context, arg InsertWaitlistEntryParams) error {
	_, err := q.db.Exec(ctx, insertWaitlistEntry,
		arg.WaitlistID,
		arg.TenantID,
		arg.PatientID,
		arg.ResourceID,
		arg.FacilityID,
		arg.OrgUnitID,
		arg.VisitType,
		arg.NotBefore,
		arg.NotAfter,
		arg.AppointmentID,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAppointmentsForDay = `-- name: ListAppointmentsForDay :many
SELECT appointment_id, tenant_id, facility_id, resource_id, org_unit_id,
       patient_id, slot_id, visit_type, visit_mode, starts_at, ends_at,
       status, booked_by, reason, rescheduled_from_id, created_at, updated_at, version,
       series_id, occurrence, reschedule_count, join_url
FROM scheduling.appointment
WHERE tenant_id = $1
  AND facility_id = $2
  AND starts_at >= $3::timestamptz
  AND starts_at < $4::timestamptz
  AND ($5::uuid IS NULL OR resource_id = $5::uuid)
ORDER BY starts_at, appointment_id
LIMIT $6
`

type ListAppointmentsForDayParams struct {
	TenantID   uuid.UUID
	FacilityID uuid.UUID
	FromAt     pgtype.Timestamptz
	UntilAt    pgtype.Timestamptz
	ResourceID pgtype.UUID
	PageLimit  int32
}

// The clinic list. Cancelled appointments are included: a clerk looking at
// today needs to see that the 10:15 was cancelled rather than find a gap and
// wonder whether the diary is wrong.
func (q *Queries) ListAppointmentsForDay(ctx context.Context, arg ListAppointmentsForDayParams) ([]SchedulingAppointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForDay,
		arg.TenantID,
		arg.FacilityID,
		arg.FromAt,
		arg.UntilAt,
		arg.ResourceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingAppointment{}
	for rows.Next() {
		var i SchedulingAppointment
		if err := rows.Scan(
			&i.AppointmentID,
			&i.TenantID,
			&i.FacilityID,
			&i.ResourceID,
			&i.OrgUnitID,
			&i.PatientID,
			&i.SlotID,
			&i.VisitType,
			&i.VisitMode,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.BookedBy,
			&i.Reason,
			&i.RescheduledFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SeriesID,
			&i.Occurrence,
			&i.RescheduleCount,
			&i.JoinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsForPatient = `-- name: ListAppointmentsForPatient :many
SELECT appointment_id, tenant_id, facility_id, resource_id, org_unit_id,
       patient_id, slot_id, visit_type, visit_mode, starts_at, ends_at,
       status, booked_by, reason, rescheduled_from_id, created_at, updated_at, version,
       series_id, occurrence, reschedule_count, join_url
FROM scheduling.appointment
WHERE tenant_id = $1 AND patient_id = $2
ORDER BY starts_at DESC, appointment_id
LIMIT $3
`

type ListAppointmentsForPatientParams struct {
	TenantID  uuid.UUID
	PatientID uuid.UUID
	PageLimit int32
}

func (q *Queries) ListAppointmentsForPatient(ctx context.Context, arg ListAppointmentsForPatientParams) ([]SchedulingAppointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForPatient, arg.TenantID, arg.PatientID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingAppointment{}
	for rows.Next() {
		var i SchedulingAppointment
		if err := rows.Scan(
			&i.AppointmentID,
			&i.TenantID,
			&i.FacilityID,
			&i.ResourceID,
			&i.OrgUnitID,
			&i.PatientID,
			&i.SlotID,
			&i.VisitType,
			&i.VisitMode,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.BookedBy,
			&i.Reason,
			&i.RescheduledFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SeriesID,
			&i.Occurrence,
			&i.RescheduleCount,
			&i.JoinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptionsForResources = `-- name: ListExceptionsForResources :many
SELECT exception_id, tenant_id, resource_id, kind, starts_at, ends_at,
       reason, overridable, created_by, created_at
FROM scheduling.schedule_exception
WHERE tenant_id = $1
  AND resource_id = ANY($2::uuid[])
  AND starts_at < $3::timestamptz
  AND ends_at > $4::timestamptz
ORDER BY resource_id, starts_at
`

type ListExceptionsForResourcesParams struct {
	TenantID    uuid.UUID
	ResourceIds []uuid.UUID
	UntilAt     pgtype.Timestamptz
	FromAt      pgtype.Timestamptz
}

func (q *Queries) ListExceptionsForResources(ctx context.Context, arg ListExceptionsForResourcesParams) ([]SchedulingScheduleException, error) {
	rows, err := q.db.Query(ctx, listExceptionsForResources,
		arg.TenantID,
		arg.ResourceIds,
		arg.UntilAt,
		arg.FromAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingScheduleException{}
	for rows.Next() {
		var i SchedulingScheduleException
		if err := rows.Scan(
			&i.ExceptionID,
			&i.TenantID,
			&i.ResourceID,
			&i.Kind,
			&i.StartsAt,
			&i.EndsAt,
			&i.Reason,
			&i.Overridable,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWaitlistEntries = `-- name: ListOpenWaitlistEntries :many
SELECT waitlist_id, tenant_id, patient_id, resource_id, facility_id, org_unit_id,
       visit_type, not_before, not_after, appointment_id, status,
       offered_slot_at, offer_expires_at, created_by, created_at, updated_at
FROM scheduling.waitlist_entry
WHERE tenant_id = $1
  AND status IN ('waiting', 'offered')
  AND ($2::uuid IS NULL OR resource_id = $2::uuid)
ORDER BY created_at, waitlist_id
LIMIT $3
`

type ListOpenWaitlistEntriesParams struct {
	TenantID   uuid.UUID
	ResourceID pgtype.UUID
	PageLimit  int32
}

// The list a scheduler works when a slot frees up. Oldest first: the person who
// has waited longest is offered first, which is the only ordering anybody can
// defend at the desk.
func (q *Queries) ListOpenWaitlistEntries(ctx context.Context, arg ListOpenWaitlistEntriesParams) ([]SchedulingWaitlistEntry, error) {
	rows, err := q.db.Query(ctx, listOpenWaitlistEntries, arg.TenantID, arg.ResourceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingWaitlistEntry{}
	for rows.Next() {
		var i SchedulingWaitlistEntry
		if err := rows.Scan(
			&i.WaitlistID,
			&i.TenantID,
			&i.PatientID,
			&i.ResourceID,
			&i.FacilityID,
			&i.OrgUnitID,
			&i.VisitType,
			&i.NotBefore,
			&i.NotAfter,
			&i.AppointmentID,
			&i.Status,
			&i.OfferedSlotAt,
			&i.OfferExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyOutcomes = `-- name: ListPolicyOutcomes :many
SELECT kind, timely, notice_given_minutes, notice_required_minutes,
       chargeable, decided_by, decided_at, reason
FROM scheduling.appointment_policy_outcome
WHERE tenant_id = $1 AND appointment_id = $2
ORDER BY decided_at, outcome_id
`

type ListPolicyOutcomesParams struct {
	TenantID      uuid.UUID
	AppointmentID uuid.UUID
}

type ListPolicyOutcomesRow struct {
	Kind                  string
	Timely                bool
	NoticeGivenMinutes    int32
	NoticeRequiredMinutes int32
	Chargeable            bool
	DecidedBy             string
	DecidedAt             pgtype.Timestamptz
	Reason                string
}

func (q *Queries) ListPolicyOutcomes(ctx context.Context, arg ListPolicyOutcomesParams) ([]ListPolicyOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listPolicyOutcomes, arg.TenantID, arg.AppointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyOutcomesRow{}
	for rows.Next() {
		var i ListPolicyOutcomesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Timely,
			&i.NoticeGivenMinutes,
			&i.NoticeRequiredMinutes,
			&i.Chargeable,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesForSearch = `-- name: ListResourcesForSearch :many
SELECT resource_id, tenant_id, facility_id, org_unit_id, resource_type,
       subject_id, display_name, status, time_zone, created_at, updated_at
FROM scheduling.resource
WHERE tenant_id = $1
  AND status = 'active'
  AND ($2::uuid IS NULL OR facility_id = $2::uuid)
  AND ($3::uuid IS NULL OR org_unit_id = $3::uuid)
  AND ($4::uuid IS NULL OR resource_id = $4::uuid)
ORDER BY display_name, resource_id
LIMIT $5
`

type ListResourcesForSearchParams struct {
	TenantID   uuid.UUID
	FacilityID pgtype.UUID
	OrgUnitID  pgtype.UUID
	ResourceID pgtype.UUID
	PageLimit  int32
}

// The candidate set a slot search generates from.
//
// Only active resources: SRS-SCH-014 requires an inactive one to be unbookable,
// and the cheapest way to guarantee that is for its slots never to exist.
func (q *Queries) ListResourcesForSearch(ctx context.Context, arg ListResourcesForSearchParams) ([]SchedulingResource, error) {
	rows, err := q.db.Query(ctx, listResourcesForSearch,
		arg.TenantID,
		arg.FacilityID,
		arg.OrgUnitID,
		arg.ResourceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingResource{}
	for rows.Next() {
		var i SchedulingResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.TenantID,
			&i.FacilityID,
			&i.OrgUnitID,
			&i.ResourceType,
			&i.SubjectID,
			&i.DisplayName,
			&i.Status,
			&i.TimeZone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForResources = `-- name: ListSchedulesForResources :many
SELECT schedule_id, tenant_id, resource_id, facility_id, visit_type, visit_mode,
       weekday, start_minute, end_minute, slot_minutes, capacity,
       effective_from, effective_until, created_at, updated_at
FROM scheduling.schedule
WHERE tenant_id = $1
  AND resource_id = ANY($2::uuid[])
  AND effective_from < $3::date
  AND (effective_until IS NULL OR effective_until > $4::date)
  AND ($5::text = '' OR visit_type = $5::text)
ORDER BY resource_id, weekday, start_minute
`

type ListSchedulesForResourcesParams struct {
	TenantID    uuid.UUID
	ResourceIds []uuid.UUID
	UntilDate   pgtype.Date
	FromDate    pgtype.Date
	VisitType   string
}

// Every rule that could be in force for these resources over a date range.
//
// Deliberately not filtered by weekday: the generator walks days and asks each
// rule whether it applies, and a SQL-side weekday filter would have to repeat
// that reasoning in a second place where it could drift.
func (q *Queries) ListSchedulesForResources(ctx context.Context, arg ListSchedulesForResourcesParams) ([]SchedulingSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesForResources,
		arg.TenantID,
		arg.ResourceIds,
		arg.UntilDate,
		arg.FromDate,
		arg.VisitType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingSchedule{}
	for rows.Next() {
		var i SchedulingSchedule
		if err := rows.Scan(
			&i.ScheduleID,
			&i.TenantID,
			&i.ResourceID,
			&i.FacilityID,
			&i.VisitType,
			&i.VisitMode,
			&i.Weekday,
			&i.StartMinute,
			&i.EndMinute,
			&i.SlotMinutes,
			&i.Capacity,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesAppointments = `-- name: ListSeriesAppointments :many
SELECT appointment_id, tenant_id, facility_id, resource_id, org_unit_id,
       patient_id, slot_id, visit_type, visit_mode, starts_at, ends_at,
       status, booked_by, reason, rescheduled_from_id, created_at, updated_at, version,
       series_id, occurrence, reschedule_count, join_url
FROM scheduling.appointment
WHERE tenant_id = $1 AND series_id = $2
ORDER BY starts_at, appointment_id
`

type ListSeriesAppointmentsParams struct {
	TenantID uuid.UUID
	SeriesID pgtype.UUID
}

// Every occurrence of a series, in order, so a bulk change can walk them.
func (q *Queries) ListSeriesAppointments(ctx context.Context, arg ListSeriesAppointmentsParams) ([]SchedulingAppointment, error) {
	rows, err := q.db.Query(ctx, listSeriesAppointments, arg.TenantID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulingAppointment{}
	for rows.Next() {
		var i SchedulingAppointment
		if err := rows.Scan(
			&i.AppointmentID,
			&i.TenantID,
			&i.FacilityID,
			&i.ResourceID,
			&i.OrgUnitID,
			&i.PatientID,
			&i.SlotID,
			&i.VisitType,
			&i.VisitMode,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.BookedBy,
			&i.Reason,
			&i.RescheduledFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SeriesID,
			&i.Occurrence,
			&i.RescheduleCount,
			&i.JoinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusHistory = `-- name: ListStatusHistory :many
SELECT from_status, to_status, changed_at, changed_by, reason, corrected
FROM scheduling.appointment_status_history
WHERE tenant_id = $1 AND appointment_id = $2
ORDER BY changed_at, history_id
`

type ListStatusHistoryParams struct {
	TenantID      uuid.UUID
	AppointmentID uuid.UUID
}

type ListStatusHistoryRow struct {
	FromStatus string
	ToStatus   string
	ChangedAt  pgtype.Timestamptz
	ChangedBy  string
	Reason     string
	Corrected  bool
}

func (q *Queries) ListStatusHistory(ctx context.Context, arg ListStatusHistoryParams) ([]ListStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listStatusHistory, arg.TenantID, arg.AppointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatusHistoryRow{}
	for rows.Next() {
		var i ListStatusHistoryRow
		if err := rows.Scan(
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.Reason,
			&i.Corrected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSlotCapacity = `-- name: ReleaseSlotCapacity :execrows
UPDATE scheduling.slot
SET booked = booked - 1, updated_at = $1
WHERE tenant_id = $2 AND slot_id = $3 AND booked > 0
`

type ReleaseSlotCapacityParams struct {
	UpdatedAt pgtype.Timestamptz
	TenantID  uuid.UUID
	SlotID    uuid.UUID
}

// Gives capacity back when an appointment is cancelled.
//
// Guarded on booked > 0 so a double cancellation cannot drive the counter
// negative and hand the clinic capacity it does not have.
func (q *Queries) ReleaseSlotCapacity(ctx context.Context, arg ReleaseSlotCapacityParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSlotCapacity, arg.UpdatedAt, arg.TenantID, arg.SlotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppointmentRescheduled = `-- name: SetAppointmentRescheduled :execrows
UPDATE scheduling.appointment
SET reschedule_count = $1, updated_at = $2,
    version = version + 1
WHERE tenant_id = $3
  AND appointment_id = $4
  AND version = $5
`

type SetAppointmentRescheduledParams struct {
	RescheduleCount int32
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	AppointmentID   uuid.UUID
	ExpectedVersion int64
}

// Records that a booking was moved, carrying the reschedule count forward.
func (q *Queries) SetAppointmentRescheduled(ctx context.Context, arg SetAppointmentRescheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentRescheduled,
		arg.RescheduleCount,
		arg.UpdatedAt,
		arg.TenantID,
		arg.AppointmentID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppointmentStatus = `-- name: SetAppointmentStatus :execrows
UPDATE scheduling.appointment
SET status = $1, updated_at = $2, version = version + 1
WHERE tenant_id = $3
  AND appointment_id = $4
  AND version = $5
`

type SetAppointmentStatusParams struct {
	Status          string
	UpdatedAt       pgtype.Timestamptz
	TenantID        uuid.UUID
	AppointmentID   uuid.UUID
	ExpectedVersion int64
}

// Optimistic concurrency on version: two clerks checking in the same patient
// at once would otherwise both write, and the second would overwrite a status
// it never saw.
func (q *Queries) SetAppointmentStatus(ctx context.Context, arg SetAppointmentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.AppointmentID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setResourceStatus = `-- name: SetResourceStatus :execrows
UPDATE scheduling.resource
SET status = $1, updated_at = $2
WHERE tenant_id = $3 AND resource_id = $4
`

type SetResourceStatusParams struct {
	Status     string
	UpdatedAt  pgtype.Timestamptz
	TenantID   uuid.UUID
	ResourceID uuid.UUID
}

func (q *Queries) SetResourceStatus(ctx context.Context, arg SetResourceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setResourceStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWaitlistEntry = `-- name: UpdateWaitlistEntry :execrows
UPDATE scheduling.waitlist_entry
SET status = $1,
    offered_slot_at = $2::timestamptz,
    offer_expires_at = $3::timestamptz,
    updated_at = $4
WHERE tenant_id = $5
  AND waitlist_id = $6
  AND status = $7
`

type UpdateWaitlistEntryParams struct {
	Status         string
	OfferedSlotAt  pgtype.Timestamptz
	OfferExpiresAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TenantID       uuid.UUID
	WaitlistID     uuid.UUID
	ExpectedStatus string
}

// Guarded on the status the caller read: two schedulers offering the same slot
// to the same patient would otherwise both write, and the second would replace
// the first one's offer with an expiry the patient never saw.
func (q *Queries) UpdateWaitlistEntry(ctx context.Context, arg UpdateWaitlistEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWaitlistEntry,
		arg.Status,
		arg.OfferedSlotAt,
		arg.OfferExpiresAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.WaitlistID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCancellationPolicy = `-- name: UpsertCancellationPolicy :exec
INSERT INTO scheduling.cancellation_policy (
    policy_id, tenant_id, facility_id, notice_hours, reschedule_notice_hours,
    max_reschedules, chargeable_when_late, teleconsult_enabled,
    teleconsult_visit_types, teleconsult_requires_confirmed_identity,
    created_at, updated_at
) VALUES (
    $1, $2, $3::uuid, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11, $12
)
ON CONFLICT (tenant_id, COALESCE(facility_id, '00000000-0000-0000-0000-000000000000'::uuid))
DO UPDATE SET notice_hours = EXCLUDED.notice_hours,
              reschedule_notice_hours = EXCLUDED.reschedule_notice_hours,
              max_reschedules = EXCLUDED.max_reschedules,
              chargeable_when_late = EXCLUDED.chargeable_when_late,
              teleconsult_enabled = EXCLUDED.teleconsult_enabled,
              teleconsult_visit_types = EXCLUDED.teleconsult_visit_types,
              teleconsult_requires_confirmed_identity =
                  EXCLUDED.teleconsult_requires_confirmed_identity,
              updated_at = EXCLUDED.updated_at
`

type UpsertCancellationPolicyParams struct {
	PolicyID                             uuid.UUID
	TenantID                             uuid.UUID
	FacilityID                           pgtype.UUID
	NoticeHours                          int32
	RescheduleNoticeHours                int32
	MaxReschedules                       int32
	ChargeableWhenLate                   bool
	TeleconsultEnabled                   bool
	TeleconsultVisitTypes                []string
	TeleconsultRequiresConfirmedIdentity bool
	CreatedAt                            pgtype.Timestamptz
	UpdatedAt                            pgtype.Timestamptz
}

func (q *Queries) UpsertCancellationPolicy(ctx context.Context, arg UpsertCancellationPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertCancellationPolicy,
		arg.PolicyID,
		arg.TenantID,
		arg.FacilityID,
		arg.NoticeHours,
		arg.RescheduleNoticeHours,
		arg.MaxReschedules,
		arg.ChargeableWhenLate,
		arg.TeleconsultEnabled,
		arg.TeleconsultVisitTypes,
		arg.TeleconsultRequiresConfirmedIdentity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
