// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: security_platform.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveExportRequest = `-- name: ApproveExportRequest :execrows
UPDATE security_platform.export_request
SET status = 'approved', approved_by = $1, approved_at = $2,
    updated_at = $2, version = version + 1
WHERE export_id = $3 AND tenant_id = $4
  AND status = 'pending_approval'
`

type ApproveExportRequestParams struct {
	ApprovedBy string
	ApprovedAt pgtype.Timestamptz
	ExportID   uuid.UUID
	TenantID   uuid.UUID
}

// Only a pending request may be approved, and the approver is recorded. The
// predicate is what stops a second approval from overwriting the first.
func (q *Queries) ApproveExportRequest(ctx context.Context, arg ApproveExportRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveExportRequest,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.ExportID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeDowntimeEpisode = `-- name: CloseDowntimeEpisode :execrows
UPDATE security_platform.downtime_episode e
SET status = 'reconciled', closed_by = $1, closed_at = $2
WHERE e.tenant_id = $3 AND e.episode_id = $4 AND e.status = 'recovering'
  AND NOT EXISTS (
      SELECT 1 FROM security_platform.downtime_action a
      WHERE a.episode_id = e.episode_id AND a.reconciled_at IS NULL
  )
`

type CloseDowntimeEpisodeParams struct {
	ClosedBy  string
	ClosedAt  pgtype.Timestamptz
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

// The NOT EXISTS clause is the control, not a convenience: an episode closed
// with unreconciled actions means paper that never reaches the chart. Putting
// it in the statement means a caller cannot close one by skipping the domain.
func (q *Queries) CloseDowntimeEpisode(ctx context.Context, arg CloseDowntimeEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeDowntimeEpisode,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.TenantID,
		arg.EpisodeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeEmergencyGrant = `-- name: CloseEmergencyGrant :execrows
UPDATE security_platform.emergency_grant
SET status = 'closed', closed_at = $1
WHERE tenant_id = $2 AND grant_id = $3 AND status = 'active'
`

type CloseEmergencyGrantParams struct {
	ClosedAt pgtype.Timestamptz
	TenantID uuid.UUID
	GrantID  uuid.UUID
}

func (q *Queries) CloseEmergencyGrant(ctx context.Context, arg CloseEmergencyGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeEmergencyGrant, arg.ClosedAt, arg.TenantID, arg.GrantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeExportRequest = `-- name: CompleteExportRequest :execrows
UPDATE security_platform.export_request
SET status = 'completed', object_key = $1, object_sha256 = $2,
    manifest = $3, row_count = $4, grant_expires_at = $5,
    updated_at = $6, version = version + 1
WHERE export_id = $7 AND tenant_id = $8 AND status = 'approved'
`

type CompleteExportRequestParams struct {
	ObjectKey      string
	ObjectSha256   string
	Manifest       []byte
	RowCount       int64
	GrantExpiresAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ExportID       uuid.UUID
	TenantID       uuid.UUID
}

func (q *Queries) CompleteExportRequest(ctx context.Context, arg CompleteExportRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeExportRequest,
		arg.ObjectKey,
		arg.ObjectSha256,
		arg.Manifest,
		arg.RowCount,
		arg.GrantExpiresAt,
		arg.UpdatedAt,
		arg.ExportID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countExportDownloads = `-- name: CountExportDownloads :one
SELECT count(*) FROM security_platform.export_download
WHERE tenant_id = $1 AND export_id = $2
`

type CountExportDownloadsParams struct {
	TenantID uuid.UUID
	ExportID uuid.UUID
}

func (q *Queries) CountExportDownloads(ctx context.Context, arg CountExportDownloadsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExportDownloads, arg.TenantID, arg.ExportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurposeGrants = `-- name: CountPurposeGrants :one
SELECT count(*) FROM security_platform.purpose_grant
WHERE tenant_id = $1 AND subject_ref = $2 AND purpose_code = $3
`

type CountPurposeGrantsParams struct {
	TenantID    uuid.UUID
	SubjectRef  string
	PurposeCode string
}

func (q *Queries) CountPurposeGrants(ctx context.Context, arg CountPurposeGrantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurposeGrants, arg.TenantID, arg.SubjectRef, arg.PurposeCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreconciledActions = `-- name: CountUnreconciledActions :one
SELECT count(*) FROM security_platform.downtime_action
WHERE tenant_id = $1 AND episode_id = $2 AND reconciled_at IS NULL
`

type CountUnreconciledActionsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) CountUnreconciledActions(ctx context.Context, arg CountUnreconciledActionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreconciledActions, arg.TenantID, arg.EpisodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideSubjectRequest = `-- name: DecideSubjectRequest :execrows
UPDATE security_platform.subject_request
SET status = $1, reviewer = $2, decision = $3,
    decision_basis = $4, evidence_ref = $5,
    closed_at = $6, updated_at = $7, version = version + 1
WHERE request_id = $8 AND tenant_id = $9
  AND status NOT IN ('fulfilled', 'refused')
`

type DecideSubjectRequestParams struct {
	Status        string
	Reviewer      string
	Decision      string
	DecisionBasis string
	EvidenceRef   string
	ClosedAt      pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RequestID     uuid.UUID
	TenantID      uuid.UUID
}

func (q *Queries) DecideSubjectRequest(ctx context.Context, arg DecideSubjectRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideSubjectRequest,
		arg.Status,
		arg.Reviewer,
		arg.Decision,
		arg.DecisionBasis,
		arg.EvidenceRef,
		arg.ClosedAt,
		arg.UpdatedAt,
		arg.RequestID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireEmergencyGrants = `-- name: ExpireEmergencyGrants :execrows
UPDATE security_platform.emergency_grant
SET status = 'expired', closed_at = expires_at
WHERE status = 'active' AND expires_at <= $1
`

// Idempotent by construction: only rows still 'active' are touched, so the
// at-least-once sweeper cannot move closed_at on a second pass.
func (q *Queries) ExpireEmergencyGrants(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireEmergencyGrants, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveEmergencyGrant = `-- name: GetActiveEmergencyGrant :one
SELECT grant_id, tenant_id, subject_id, facility_id, incident_ref, justification,
       permissions, status, activated_at, expires_at, closed_at,
       accessed_resources, reviewed_by, reviewed_at, review_note, correlation_id
FROM security_platform.emergency_grant
WHERE tenant_id = $1 AND subject_id = $2 AND status = 'active'
`

type GetActiveEmergencyGrantParams struct {
	TenantID  uuid.UUID
	SubjectID string
}

func (q *Queries) GetActiveEmergencyGrant(ctx context.Context, arg GetActiveEmergencyGrantParams) (SecurityPlatformEmergencyGrant, error) {
	row := q.db.QueryRow(ctx, getActiveEmergencyGrant, arg.TenantID, arg.SubjectID)
	var i SecurityPlatformEmergencyGrant
	err := row.Scan(
		&i.GrantID,
		&i.TenantID,
		&i.SubjectID,
		&i.FacilityID,
		&i.IncidentRef,
		&i.Justification,
		&i.Permissions,
		&i.Status,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.AccessedResources,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CorrelationID,
	)
	return i, err
}

const getCurrentPurposeGrant = `-- name: GetCurrentPurposeGrant :one
SELECT grant_id, tenant_id, subject_ref, purpose_code, notice_version, granted,
       recorded_by, occurred_at
FROM security_platform.purpose_grant
WHERE tenant_id = $1 AND subject_ref = $2 AND purpose_code = $3
ORDER BY occurred_at DESC, grant_id DESC
LIMIT 1
`

type GetCurrentPurposeGrantParams struct {
	TenantID    uuid.UUID
	SubjectRef  string
	PurposeCode string
}

// The latest row wins; earlier rows stay for the history of what was agreed.
func (q *Queries) GetCurrentPurposeGrant(ctx context.Context, arg GetCurrentPurposeGrantParams) (SecurityPlatformPurposeGrant, error) {
	row := q.db.QueryRow(ctx, getCurrentPurposeGrant, arg.TenantID, arg.SubjectRef, arg.PurposeCode)
	var i SecurityPlatformPurposeGrant
	err := row.Scan(
		&i.GrantID,
		&i.TenantID,
		&i.SubjectRef,
		&i.PurposeCode,
		&i.NoticeVersion,
		&i.Granted,
		&i.RecordedBy,
		&i.OccurredAt,
	)
	return i, err
}

const getDowntimeEpisode = `-- name: GetDowntimeEpisode :one
SELECT episode_id, tenant_id, facility_id, planned, declared_by, declared_at,
       reason, restored_at, status, closed_by, closed_at, correlation_id
FROM security_platform.downtime_episode
WHERE tenant_id = $1 AND episode_id = $2
`

type GetDowntimeEpisodeParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) GetDowntimeEpisode(ctx context.Context, arg GetDowntimeEpisodeParams) (SecurityPlatformDowntimeEpisode, error) {
	row := q.db.QueryRow(ctx, getDowntimeEpisode, arg.TenantID, arg.EpisodeID)
	var i SecurityPlatformDowntimeEpisode
	err := row.Scan(
		&i.EpisodeID,
		&i.TenantID,
		&i.FacilityID,
		&i.Planned,
		&i.DeclaredBy,
		&i.DeclaredAt,
		&i.Reason,
		&i.RestoredAt,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CorrelationID,
	)
	return i, err
}

const getEmergencyGrant = `-- name: GetEmergencyGrant :one
SELECT grant_id, tenant_id, subject_id, facility_id, incident_ref, justification,
       permissions, status, activated_at, expires_at, closed_at,
       accessed_resources, reviewed_by, reviewed_at, review_note, correlation_id
FROM security_platform.emergency_grant
WHERE tenant_id = $1 AND grant_id = $2
`

type GetEmergencyGrantParams struct {
	TenantID uuid.UUID
	GrantID  uuid.UUID
}

func (q *Queries) GetEmergencyGrant(ctx context.Context, arg GetEmergencyGrantParams) (SecurityPlatformEmergencyGrant, error) {
	row := q.db.QueryRow(ctx, getEmergencyGrant, arg.TenantID, arg.GrantID)
	var i SecurityPlatformEmergencyGrant
	err := row.Scan(
		&i.GrantID,
		&i.TenantID,
		&i.SubjectID,
		&i.FacilityID,
		&i.IncidentRef,
		&i.Justification,
		&i.Permissions,
		&i.Status,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.AccessedResources,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.CorrelationID,
	)
	return i, err
}

const getExportRequest = `-- name: GetExportRequest :one
SELECT export_id, tenant_id, requested_by, justification, data_class, scope,
       status, step_up_reference, approved_by, approved_at, object_key,
       object_sha256, manifest, row_count, watermark, grant_expires_at,
       created_at, updated_at, version
FROM security_platform.export_request
WHERE tenant_id = $1 AND export_id = $2
`

type GetExportRequestParams struct {
	TenantID uuid.UUID
	ExportID uuid.UUID
}

func (q *Queries) GetExportRequest(ctx context.Context, arg GetExportRequestParams) (SecurityPlatformExportRequest, error) {
	row := q.db.QueryRow(ctx, getExportRequest, arg.TenantID, arg.ExportID)
	var i SecurityPlatformExportRequest
	err := row.Scan(
		&i.ExportID,
		&i.TenantID,
		&i.RequestedBy,
		&i.Justification,
		&i.DataClass,
		&i.Scope,
		&i.Status,
		&i.StepUpReference,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ObjectKey,
		&i.ObjectSha256,
		&i.Manifest,
		&i.RowCount,
		&i.Watermark,
		&i.GrantExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getLastSecurityEventHash = `-- name: GetLastSecurityEventHash :one
SELECT entry_hash FROM security_platform.security_event
WHERE tenant_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLastSecurityEventHash(ctx context.Context, tenantID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastSecurityEventHash, tenantID)
	var entry_hash string
	err := row.Scan(&entry_hash)
	return entry_hash, err
}

const getProcessingPurpose = `-- name: GetProcessingPurpose :one
SELECT purpose_id, tenant_id, code, description, withdrawable, lawful_basis, created_at
FROM security_platform.processing_purpose
WHERE tenant_id = $1 AND code = $2
`

type GetProcessingPurposeParams struct {
	TenantID uuid.UUID
	Code     string
}

func (q *Queries) GetProcessingPurpose(ctx context.Context, arg GetProcessingPurposeParams) (SecurityPlatformProcessingPurpose, error) {
	row := q.db.QueryRow(ctx, getProcessingPurpose, arg.TenantID, arg.Code)
	var i SecurityPlatformProcessingPurpose
	err := row.Scan(
		&i.PurposeID,
		&i.TenantID,
		&i.Code,
		&i.Description,
		&i.Withdrawable,
		&i.LawfulBasis,
		&i.CreatedAt,
	)
	return i, err
}

const getRetentionClass = `-- name: GetRetentionClass :one
SELECT retention_class_id, tenant_id, name, data_class, retain_days,
       archive_after_days, created_at, updated_at
FROM security_platform.retention_class
WHERE tenant_id = $1 AND name = $2
`

type GetRetentionClassParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) GetRetentionClass(ctx context.Context, arg GetRetentionClassParams) (SecurityPlatformRetentionClass, error) {
	row := q.db.QueryRow(ctx, getRetentionClass, arg.TenantID, arg.Name)
	var i SecurityPlatformRetentionClass
	err := row.Scan(
		&i.RetentionClassID,
		&i.TenantID,
		&i.Name,
		&i.DataClass,
		&i.RetainDays,
		&i.ArchiveAfterDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectRequest = `-- name: GetSubjectRequest :one
SELECT request_id, tenant_id, subject_ref, request_type, status, received_at,
       due_at, reviewer, decision, decision_basis, evidence_ref, closed_at,
       created_at, updated_at, version
FROM security_platform.subject_request
WHERE tenant_id = $1 AND request_id = $2
`

type GetSubjectRequestParams struct {
	TenantID  uuid.UUID
	RequestID uuid.UUID
}

func (q *Queries) GetSubjectRequest(ctx context.Context, arg GetSubjectRequestParams) (SecurityPlatformSubjectRequest, error) {
	row := q.db.QueryRow(ctx, getSubjectRequest, arg.TenantID, arg.RequestID)
	var i SecurityPlatformSubjectRequest
	err := row.Scan(
		&i.RequestID,
		&i.TenantID,
		&i.SubjectRef,
		&i.RequestType,
		&i.Status,
		&i.ReceivedAt,
		&i.DueAt,
		&i.Reviewer,
		&i.Decision,
		&i.DecisionBasis,
		&i.EvidenceRef,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertDowntimeAction = `-- name: InsertDowntimeAction :execrows
INSERT INTO security_platform.downtime_action (
    action_id, episode_id, tenant_id, performed_by, performed_at, action_type,
    subject_ref, summary, paper_form_ref
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (action_id) DO NOTHING
`

type InsertDowntimeActionParams struct {
	ActionID     uuid.UUID
	EpisodeID    uuid.UUID
	TenantID     uuid.UUID
	PerformedBy  string
	PerformedAt  pgtype.Timestamptz
	ActionType   string
	SubjectRef   string
	Summary      string
	PaperFormRef string
}

// ON CONFLICT DO NOTHING: a ward terminal that loses its response retries, and
// duplicating a medication administration would be a clinical incident.
func (q *Queries) InsertDowntimeAction(ctx context.Context, arg InsertDowntimeActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDowntimeAction,
		arg.ActionID,
		arg.EpisodeID,
		arg.TenantID,
		arg.PerformedBy,
		arg.PerformedAt,
		arg.ActionType,
		arg.SubjectRef,
		arg.Summary,
		arg.PaperFormRef,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDowntimeEpisode = `-- name: InsertDowntimeEpisode :exec

INSERT INTO security_platform.downtime_episode (
    episode_id, tenant_id, facility_id, planned, declared_by, declared_at,
    reason, status, correlation_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
`

type InsertDowntimeEpisodeParams struct {
	EpisodeID     uuid.UUID
	TenantID      uuid.UUID
	FacilityID    string
	Planned       bool
	DeclaredBy    string
	DeclaredAt    pgtype.Timestamptz
	Reason        string
	Status        string
	CorrelationID string
}

// Downtime episodes (SRS-SEC-014).
func (q *Queries) InsertDowntimeEpisode(ctx context.Context, arg InsertDowntimeEpisodeParams) error {
	_, err := q.db.Exec(ctx, insertDowntimeEpisode,
		arg.EpisodeID,
		arg.TenantID,
		arg.FacilityID,
		arg.Planned,
		arg.DeclaredBy,
		arg.DeclaredAt,
		arg.Reason,
		arg.Status,
		arg.CorrelationID,
	)
	return err
}

const insertEmergencyGrant = `-- name: InsertEmergencyGrant :exec

INSERT INTO security_platform.emergency_grant (
    grant_id, tenant_id, subject_id, facility_id, incident_ref, justification,
    permissions, status, activated_at, expires_at, correlation_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertEmergencyGrantParams struct {
	GrantID       uuid.UUID
	TenantID      uuid.UUID
	SubjectID     string
	FacilityID    string
	IncidentRef   string
	Justification string
	Permissions   []string
	Status        string
	ActivatedAt   pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	CorrelationID string
}

// Emergency access (SRS-SEC-014).
// The partial unique index on (tenant_id, subject_id) WHERE status = 'active'
// is what refuses a second concurrent activation; this insert relies on it
// rather than on a prior SELECT, which would race.
func (q *Queries) InsertEmergencyGrant(ctx context.Context, arg InsertEmergencyGrantParams) error {
	_, err := q.db.Exec(ctx, insertEmergencyGrant,
		arg.GrantID,
		arg.TenantID,
		arg.SubjectID,
		arg.FacilityID,
		arg.IncidentRef,
		arg.Justification,
		arg.Permissions,
		arg.Status,
		arg.ActivatedAt,
		arg.ExpiresAt,
		arg.CorrelationID,
	)
	return err
}

const insertExportDownload = `-- name: InsertExportDownload :exec
INSERT INTO security_platform.export_download (
    download_id, export_id, tenant_id, downloaded_by, correlation_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertExportDownloadParams struct {
	DownloadID    uuid.UUID
	ExportID      uuid.UUID
	TenantID      uuid.UUID
	DownloadedBy  string
	CorrelationID string
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) InsertExportDownload(ctx context.Context, arg InsertExportDownloadParams) error {
	_, err := q.db.Exec(ctx, insertExportDownload,
		arg.DownloadID,
		arg.ExportID,
		arg.TenantID,
		arg.DownloadedBy,
		arg.CorrelationID,
		arg.OccurredAt,
	)
	return err
}

const insertExportRequest = `-- name: InsertExportRequest :exec
INSERT INTO security_platform.export_request (
    export_id, tenant_id, requested_by, justification, data_class, scope,
    status, step_up_reference, watermark, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, 1
)
`

type InsertExportRequestParams struct {
	ExportID        uuid.UUID
	TenantID        uuid.UUID
	RequestedBy     string
	Justification   string
	DataClass       string
	Scope           []byte
	Status          string
	StepUpReference string
	Watermark       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertExportRequest(ctx context.Context, arg InsertExportRequestParams) error {
	_, err := q.db.Exec(ctx, insertExportRequest,
		arg.ExportID,
		arg.TenantID,
		arg.RequestedBy,
		arg.Justification,
		arg.DataClass,
		arg.Scope,
		arg.Status,
		arg.StepUpReference,
		arg.Watermark,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPrivacyNotice = `-- name: InsertPrivacyNotice :exec
INSERT INTO security_platform.privacy_notice (
    notice_id, tenant_id, version, locale, body_uri, effective_from, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPrivacyNoticeParams struct {
	NoticeID      uuid.UUID
	TenantID      uuid.UUID
	Version       int32
	Locale        string
	BodyUri       string
	EffectiveFrom pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertPrivacyNotice(ctx context.Context, arg InsertPrivacyNoticeParams) error {
	_, err := q.db.Exec(ctx, insertPrivacyNotice,
		arg.NoticeID,
		arg.TenantID,
		arg.Version,
		arg.Locale,
		arg.BodyUri,
		arg.EffectiveFrom,
		arg.CreatedAt,
	)
	return err
}

const insertProcessingPurpose = `-- name: InsertProcessingPurpose :exec
INSERT INTO security_platform.processing_purpose (
    purpose_id, tenant_id, code, description, withdrawable, lawful_basis, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertProcessingPurposeParams struct {
	PurposeID    uuid.UUID
	TenantID     uuid.UUID
	Code         string
	Description  string
	Withdrawable bool
	LawfulBasis  string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertProcessingPurpose(ctx context.Context, arg InsertProcessingPurposeParams) error {
	_, err := q.db.Exec(ctx, insertProcessingPurpose,
		arg.PurposeID,
		arg.TenantID,
		arg.Code,
		arg.Description,
		arg.Withdrawable,
		arg.LawfulBasis,
		arg.CreatedAt,
	)
	return err
}

const insertPurposeGrant = `-- name: InsertPurposeGrant :exec
INSERT INTO security_platform.purpose_grant (
    grant_id, tenant_id, subject_ref, purpose_code, notice_version, granted,
    recorded_by, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8
)
`

type InsertPurposeGrantParams struct {
	GrantID       uuid.UUID
	TenantID      uuid.UUID
	SubjectRef    string
	PurposeCode   string
	NoticeVersion int32
	Granted       bool
	RecordedBy    string
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) InsertPurposeGrant(ctx context.Context, arg InsertPurposeGrantParams) error {
	_, err := q.db.Exec(ctx, insertPurposeGrant,
		arg.GrantID,
		arg.TenantID,
		arg.SubjectRef,
		arg.PurposeCode,
		arg.NoticeVersion,
		arg.Granted,
		arg.RecordedBy,
		arg.OccurredAt,
	)
	return err
}

const insertRetentionClass = `-- name: InsertRetentionClass :exec
INSERT INTO security_platform.retention_class (
    retention_class_id, tenant_id, name, data_class, retain_days,
    archive_after_days, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
`

type InsertRetentionClassParams struct {
	RetentionClassID uuid.UUID
	TenantID         uuid.UUID
	Name             string
	DataClass        string
	RetainDays       *int32
	ArchiveAfterDays *int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertRetentionClass(ctx context.Context, arg InsertRetentionClassParams) error {
	_, err := q.db.Exec(ctx, insertRetentionClass,
		arg.RetentionClassID,
		arg.TenantID,
		arg.Name,
		arg.DataClass,
		arg.RetainDays,
		arg.ArchiveAfterDays,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSecurityEvent = `-- name: InsertSecurityEvent :exec
INSERT INTO security_platform.security_event (
    event_id, tenant_id, sequence, event_class, severity, actor_id,
    resource_type, resource_id, outcome, detail, correlation_id, occurred_at,
    entry_hash, previous_hash
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14
)
`

type InsertSecurityEventParams struct {
	EventID       uuid.UUID
	TenantID      uuid.UUID
	Sequence      int64
	EventClass    string
	Severity      string
	ActorID       string
	ResourceType  string
	ResourceID    string
	Outcome       string
	Detail        []byte
	CorrelationID string
	OccurredAt    pgtype.Timestamptz
	EntryHash     string
	PreviousHash  string
}

func (q *Queries) InsertSecurityEvent(ctx context.Context, arg InsertSecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityEvent,
		arg.EventID,
		arg.TenantID,
		arg.Sequence,
		arg.EventClass,
		arg.Severity,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.Detail,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.EntryHash,
		arg.PreviousHash,
	)
	return err
}

const insertSubjectRequest = `-- name: InsertSubjectRequest :exec
INSERT INTO security_platform.subject_request (
    request_id, tenant_id, subject_ref, request_type, status, received_at,
    due_at, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, 1
)
`

type InsertSubjectRequestParams struct {
	RequestID   uuid.UUID
	TenantID    uuid.UUID
	SubjectRef  string
	RequestType string
	Status      string
	ReceivedAt  pgtype.Timestamptz
	DueAt       pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertSubjectRequest(ctx context.Context, arg InsertSubjectRequestParams) error {
	_, err := q.db.Exec(ctx, insertSubjectRequest,
		arg.RequestID,
		arg.TenantID,
		arg.SubjectRef,
		arg.RequestType,
		arg.Status,
		arg.ReceivedAt,
		arg.DueAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isUnderLegalHold = `-- name: IsUnderLegalHold :one
SELECT EXISTS (
    SELECT 1 FROM security_platform.legal_hold
    WHERE tenant_id = $1 AND resource_type = $2
      AND resource_id = $3 AND released_at IS NULL
)
`

type IsUnderLegalHoldParams struct {
	TenantID     uuid.UUID
	ResourceType string
	ResourceID   string
}

func (q *Queries) IsUnderLegalHold(ctx context.Context, arg IsUnderLegalHoldParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUnderLegalHold, arg.TenantID, arg.ResourceType, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDowntimeActions = `-- name: ListDowntimeActions :many
SELECT action_id, episode_id, tenant_id, performed_by, performed_at, action_type,
       subject_ref, summary, paper_form_ref, reconciled_by, reconciled_at, resource_ref
FROM security_platform.downtime_action
WHERE tenant_id = $1 AND episode_id = $2
ORDER BY performed_at ASC, action_id ASC
`

type ListDowntimeActionsParams struct {
	TenantID  uuid.UUID
	EpisodeID uuid.UUID
}

func (q *Queries) ListDowntimeActions(ctx context.Context, arg ListDowntimeActionsParams) ([]SecurityPlatformDowntimeAction, error) {
	rows, err := q.db.Query(ctx, listDowntimeActions, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPlatformDowntimeAction{}
	for rows.Next() {
		var i SecurityPlatformDowntimeAction
		if err := rows.Scan(
			&i.ActionID,
			&i.EpisodeID,
			&i.TenantID,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.ActionType,
			&i.SubjectRef,
			&i.Summary,
			&i.PaperFormRef,
			&i.ReconciledBy,
			&i.ReconciledAt,
			&i.ResourceRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsAwaitingReview = `-- name: ListGrantsAwaitingReview :many
SELECT grant_id, tenant_id, subject_id, facility_id, incident_ref, justification,
       permissions, status, activated_at, expires_at, closed_at,
       accessed_resources, reviewed_by, reviewed_at, review_note, correlation_id
FROM security_platform.emergency_grant
WHERE tenant_id = $1 AND status IN ('closed', 'expired')
ORDER BY closed_at ASC, grant_id ASC
LIMIT $2
`

type ListGrantsAwaitingReviewParams struct {
	TenantID uuid.UUID
	PageSize int32
}

func (q *Queries) ListGrantsAwaitingReview(ctx context.Context, arg ListGrantsAwaitingReviewParams) ([]SecurityPlatformEmergencyGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsAwaitingReview, arg.TenantID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPlatformEmergencyGrant{}
	for rows.Next() {
		var i SecurityPlatformEmergencyGrant
		if err := rows.Scan(
			&i.GrantID,
			&i.TenantID,
			&i.SubjectID,
			&i.FacilityID,
			&i.IncidentRef,
			&i.Justification,
			&i.Permissions,
			&i.Status,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.AccessedResources,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldResourceIDs = `-- name: ListHeldResourceIDs :many
SELECT resource_id FROM security_platform.legal_hold
WHERE tenant_id = $1 AND resource_type = $2 AND released_at IS NULL
`

type ListHeldResourceIDsParams struct {
	TenantID     uuid.UUID
	ResourceType string
}

func (q *Queries) ListHeldResourceIDs(ctx context.Context, arg ListHeldResourceIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listHeldResourceIDs, arg.TenantID, arg.ResourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityEvents = `-- name: ListSecurityEvents :many
SELECT event_id, tenant_id, sequence, event_class, severity, actor_id,
       resource_type, resource_id, outcome, detail, correlation_id, occurred_at,
       entry_hash, previous_hash
FROM security_platform.security_event
WHERE tenant_id = $1
ORDER BY sequence
`

func (q *Queries) ListSecurityEvents(ctx context.Context, tenantID uuid.UUID) ([]SecurityPlatformSecurityEvent, error) {
	rows, err := q.db.Query(ctx, listSecurityEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPlatformSecurityEvent{}
	for rows.Next() {
		var i SecurityPlatformSecurityEvent
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.Sequence,
			&i.EventClass,
			&i.Severity,
			&i.ActorID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.Detail,
			&i.CorrelationID,
			&i.OccurredAt,
			&i.EntryHash,
			&i.PreviousHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSecurityEventSequence = `-- name: NextSecurityEventSequence :one

SELECT COALESCE(MAX(sequence), 0) + 1 FROM security_platform.security_event
WHERE tenant_id = $1
`

// Security platform queries.
// The chain is per tenant, so one tenant's volume cannot renumber another's.
func (q *Queries) NextSecurityEventSequence(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSecurityEventSequence, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const placeLegalHold = `-- name: PlaceLegalHold :execrows
INSERT INTO security_platform.legal_hold (
    hold_id, tenant_id, resource_type, resource_id, reason, placed_by, placed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
`

type PlaceLegalHoldParams struct {
	HoldID       uuid.UUID
	TenantID     uuid.UUID
	ResourceType string
	ResourceID   string
	Reason       string
	PlacedBy     string
	PlacedAt     pgtype.Timestamptz
}

func (q *Queries) PlaceLegalHold(ctx context.Context, arg PlaceLegalHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, placeLegalHold,
		arg.HoldID,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Reason,
		arg.PlacedBy,
		arg.PlacedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reconcileDowntimeAction = `-- name: ReconcileDowntimeAction :execrows
UPDATE security_platform.downtime_action
SET reconciled_by = $1, reconciled_at = $2,
    resource_ref = $3
WHERE tenant_id = $4 AND episode_id = $5 AND action_id = $6
  AND reconciled_at IS NULL
`

type ReconcileDowntimeActionParams struct {
	ReconciledBy string
	ReconciledAt pgtype.Timestamptz
	ResourceRef  string
	TenantID     uuid.UUID
	EpisodeID    uuid.UUID
	ActionID     uuid.UUID
}

func (q *Queries) ReconcileDowntimeAction(ctx context.Context, arg ReconcileDowntimeActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileDowntimeAction,
		arg.ReconciledBy,
		arg.ReconciledAt,
		arg.ResourceRef,
		arg.TenantID,
		arg.EpisodeID,
		arg.ActionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordEmergencyAccess = `-- name: RecordEmergencyAccess :execrows
UPDATE security_platform.emergency_grant
SET accessed_resources = CASE
        WHEN $1::text = ANY (accessed_resources) THEN accessed_resources
        ELSE array_append(accessed_resources, $1::text)
    END
WHERE tenant_id = $2 AND grant_id = $3
  AND status = 'active' AND expires_at > $4
`

type RecordEmergencyAccessParams struct {
	ResourceRef string
	TenantID    uuid.UUID
	GrantID     uuid.UUID
	Now         pgtype.Timestamptz
}

// array_append only when absent, so a repeated read of the same record does not
// inflate the list the reviewer reads. The expires_at predicate means a grant
// past its window cannot record access even if the sweeper has not run.
func (q *Queries) RecordEmergencyAccess(ctx context.Context, arg RecordEmergencyAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordEmergencyAccess,
		arg.ResourceRef,
		arg.TenantID,
		arg.GrantID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectExportRequest = `-- name: RejectExportRequest :execrows
UPDATE security_platform.export_request
SET status = 'rejected', approved_by = $1, approved_at = $2,
    updated_at = $2, version = version + 1
WHERE export_id = $3 AND tenant_id = $4
  AND status = 'pending_approval'
`

type RejectExportRequestParams struct {
	ApprovedBy string
	ApprovedAt pgtype.Timestamptz
	ExportID   uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) RejectExportRequest(ctx context.Context, arg RejectExportRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectExportRequest,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.ExportID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseLegalHold = `-- name: ReleaseLegalHold :execrows
UPDATE security_platform.legal_hold
SET released_by = $1, released_at = $2
WHERE tenant_id = $3 AND resource_type = $4
  AND resource_id = $5 AND released_at IS NULL
`

type ReleaseLegalHoldParams struct {
	ReleasedBy   string
	ReleasedAt   pgtype.Timestamptz
	TenantID     uuid.UUID
	ResourceType string
	ResourceID   string
}

func (q *Queries) ReleaseLegalHold(ctx context.Context, arg ReleaseLegalHoldParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLegalHold,
		arg.ReleasedBy,
		arg.ReleasedAt,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreDowntimeEpisode = `-- name: RestoreDowntimeEpisode :execrows
UPDATE security_platform.downtime_episode
SET status = 'recovering', restored_at = $1
WHERE tenant_id = $2 AND episode_id = $3 AND status = 'open'
`

type RestoreDowntimeEpisodeParams struct {
	RestoredAt pgtype.Timestamptz
	TenantID   uuid.UUID
	EpisodeID  uuid.UUID
}

func (q *Queries) RestoreDowntimeEpisode(ctx context.Context, arg RestoreDowntimeEpisodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreDowntimeEpisode, arg.RestoredAt, arg.TenantID, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewEmergencyGrant = `-- name: ReviewEmergencyGrant :execrows
UPDATE security_platform.emergency_grant
SET status = $1, reviewed_by = $2, reviewed_at = $3,
    review_note = $4
WHERE tenant_id = $5 AND grant_id = $6
  AND (status IN ('closed', 'expired') OR (status = 'active' AND expires_at <= $7))
  AND subject_id <> $2
`

type ReviewEmergencyGrantParams struct {
	Status     string
	ReviewedBy string
	ReviewedAt pgtype.Timestamptz
	ReviewNote string
	TenantID   uuid.UUID
	GrantID    uuid.UUID
	Now        pgtype.Timestamptz
}

// "Ended" is a question about the clock, not about the sweeper: a grant whose
// window has passed is reviewable even while the row still reads 'active',
// so a reviewer working promptly after expiry is not told to come back later.
// Same rule as RecordEmergencyAccess, which refuses on the same predicate.
func (q *Queries) ReviewEmergencyGrant(ctx context.Context, arg ReviewEmergencyGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewEmergencyGrant,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.TenantID,
		arg.GrantID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
